### ISSUE TITLE
unable to use transitions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jliljebl/flowblade#100]
```
What steps will reproduce the problem?
1. select two successive clips on the timeline
2. right or left-click on transition/fade button
3. you can choose a transition and the number of frames, if available wipe 
pattern or dip color and encoding, but not the clip handles (wonder what it is 
?), validate
4. a warning box appears, complaining that "TO clip handle is too short"


What is the expected output? What do you see instead?
I would like to be advised of the way to set the parameters for "clip handles", 
but I don't see any.


What version of the product are you using? On what operating system?
0.16 on Ubuntu 14.04 64 bits

Please provide any additional information below.


```

Original issue reported on code.google.com by `erikmar...@hotmail.com` on 25 Dec 2014 at 8:40

Attachments:
- [Capture du 2014-12-25 23:36:01.png](https://storage.googleapis.com/google-code-attachments/flowblade/issue-100/comment-0/Capture du 2014-12-25 23:36:01.png)
- [Capture du 2014-12-25 23:36:09.png](https://storage.googleapis.com/google-code-attachments/flowblade/issue-100/comment-0/Capture du 2014-12-25 23:36:09.png)

**Comment by qubodup** [comment]
I would like to suggest that flowblade would provide the option to automatically do the minimum steps required for it to be possible to crossfade between two clips: cut the right clip and remove the left slice of it and then apply the transition.

This would require a check whether the clip has enough frames at all.

UI-wise it could be either made an option ("Do you want to automatically cut the right clip by N frames?") or automatic with a warning ("Please note that the right clip has been automatically cut by N frames for this crossfade to be made possible.").

**Comment by jliljebl** [comment]
I will consider this, users keep reporting on this issue. The term "handle" is in both used in both Avid and Premiere for material available outside of the part of clip used on the timeline, and I'm unwilling to change the nomenclature here, even though it is clear that it is not generally understood correctly by non-expert users.

It is necessary to shorten possibly both clips so a checkbox with label "Shorten clips if necessary and possible" would be used here. The fix is however non-trivial, and I do not prefer solutions that do edits that are not clearly defined by users (number of frames to be removed is not known before doing the edit), so I'm not committing to doing this yet.

**Comment by qubodup** [comment]
Absolutely.

If there was a tool that does "magic", it would be ideal if there was a warning explaining concisely what is going to happen.

possible message:

> To create this transition, clips will be manipulated
> Left clip will be cut by 9 frames
> Right clip will be cut by 4 frames
> Cancel         Okay

or if only one of the clips is problematic:

> To create this transition, clips will be manipulated
> Left clip will be cut by 6 frames
> Cancel         Okay

Ideally, the necessity to cut would be identified in the create-transition window already.

**Comment by jliljebl** [comment]
Yes, to do this the user will need to be informed precisely about the clip shortenings.

**Comment by reinout** [comment]
Replying on an old issue. (Yes, I also wondered how to get a transition into my movie and had to look up a youtube video to figure out how). 

I'm used to apple's imovie where you can "just" drag in a transition. It uses the end of the first clip and the start of the second clip to create the transition. So a piece of the clips (automatically) ends up in the transition.

So: I'm used to trimming the clips to just the part I want to have visible. I strip off the part where my finger wanders in front of the lens.

With flowblade's default transition handling, it seems like it implicitly re-adds my finger in the transition. Right?

Implicitly lengthening the clip seems to be what happens and seems to be ok. But using parts of the clip ("implicitly shortening them") for the transition seems to be bad and the user should be warned in quite technical terms about the implications. **My question**: why is the one bad and the other good?

It seems more logical the other way around, but that might be my "imovie/consumer" focus :-)
What I normally do is grab some 20-40 clips; trim some of them, leave some of them alone; add simple transitions; done. I don't really want to have to trim all clips manually on both ends before applying the transitions. (Though what I'm doing might not be flowblade's focus.)
