### ISSUE TITLE
black frame on fade in different aspect ratio

### ISSUE THREAD

**Issue by neurino** [jliljebl/flowblade#1001]
Thanks for such a great piece of software! I have one problem as follow:

1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): xubuntu 20.04
4) I have a picture in picture video where aspect ratio of the overlay video is 1:1 while main video is 16:9 if I do: select V2 > fade in I get a black frame the size of a 16:9 frame, see picture:

![flawblade_fade_in][1]

I'm going to render the video without fade in / outs and then later reprocess the flattened video with fade in / out. This is inefficient and reduces video quality. Any hint?

Also keeping the overlay video in 16:9 and adding a Crop filter leads to the same point — that was my first attempt.

[1]: https://user-images.githubusercontent.com/418283/113146890-81480b80-9230-11eb-85f6-f4a8da454874.png

**Comment by jliljebl** [comment]
I didn't have material to produce this exact issue at hand but adding filter *Alpha->Crop* on 1:1 video allows for cutting out the black bars on the side.

**Comment by jliljebl** [comment]
Closing as this is not actionable issue and we did offer some advise.
