### ISSUE TITLE
Feature request: zoom on mouse position instead of timeline caret

### ISSUE THREAD

**Issue by SemjonWilke** [jliljebl/flowblade#1004]
This is a feature request for an option to zoom on mouse position instead of timeline caret.

When scrolling the mouse wheel to zoom in or out, I expect the timeline to stay at the position where the mouse is. Instead Flowblade takes the position of the timeline caret to zoom in and out from, which means that I have to be aware of the caret position, which I mostly am not. So my workaround is zooming only after placing the caret to the desired position. But when I forget to place the caret and start zooming I will most definelty throw a tantrum, because the timeline jumps around and I don't know where I am anymore.

I didn't find a solution or open/closed issue so here it is.
Zooming on mouse position is normal behavior in other media-editors (e.g. gimp, audacity), I can't speak from experience with other video editing tools though.

(btw I use Arch, Flowblade v2.8, MLT v6.24)

**Comment by jliljebl** [comment]
I can make this behavior a user selectable option in *Editing Panel* in *Preferences*.

Did a quick web search on this behavior on video editors. For Da Vinci Resolve there was a comment: "That centers on the playhead, not the mouse cursor" in a thread with user asking the behavior you wish to have. So there are probably other users who want this, let's add it.

**Comment by SemjonKerner** [comment]
Thank you and thanks for that awesome software.

> I can make this behavior a user selectable option in Editing Panel in Preferences.

That is totally fine for me, you can put it to the mouse wheel settings, thats where I'd look for it.

> For Da Vinci Resolve there was a comment: [...]

I found the exact same comment when looking for a solution :D

**Comment by jliljebl** [comment]
Feature is now in repo, will be in 2.12 release.
