### ISSUE TITLE
problem with Pattern Producer & Color Clip

### ISSUE THREAD

**Issue by Brt-L** [jliljebl/flowblade#1006]
1) Flowblade version 2.8
2) MLT version 6.20.0
3) distribution: Mint (Flowblade installed from .deb)

Color Clips & Pattern Producers creation is ok, but when opening in the Clip Monitor or adding to the timeline (by menu or dragging), the original values of lenght, mark_in and mark_out don't come trough.

Trying to debug, I added into patternproducer.py > class  BinColorClip > def create_mlt_producer a command
   print("CHECK: params " + str(profile.length) + "  " + str(profile.mark_in) + "  " + str(profile.mark_out))
and now values are indeed present.
I then instead tried adding next lines at the start of the definition:
   xxx = profile.length
   xxx = profile.mark_in
   xxx = profile.mark_out
and again it worked ...

So these values don't seem to be propagated as long as they are not used ...  No idea why ...

**Comment by Brt-L** [comment]
Investigated a bit further ...

Adding previous mentioned lines (which generate an error: missing param) made Flowblade use the deprecated procedure for a Color Clip because of these code lines:
  try:
    clip = bin_clip.create_mlt_producer(profile)
  except:
    clip = _create_patten_producer_old_style(profile, bin_clip)
Thus avoiding the initial problem.

The real problem is that 'mlt.Producer(profile, write_file_path)' creates a clip with length 2147483647 (a bug ?), whereas with the old style producer, length by default is 15000. This also affects insertion of a patternproducer ColorBar or a .png file as they use the same type of producer.

I patched patternproducer.py by adding 2 lines after commands using mlt.Producer with a file
     producer = mlt.Producer(profile, <some file>)
     _producer.set("length", 15000)_
     _self.ttl = 15000_

I patched projectdata.py, def write_image
     length = producer.get_length()
     frame = length // 2
     _if length == 2147483647 or length == 0:_
         _producer.set("length", 15000)_
         _length = producer.get_length()_
         _frame = 0_

I patched projectdata.py, def add_media_file
     media_object.ttl = None
     _if media_type == appconsts.IMAGE:_
         _media_object.ttl = 15000_

I patched sequence.py, create_file_producer_clip
     producer = mlt.Producer(self.profile, str(path)) # this runs 0.5s+ on some clips
     try:
         check_length = producer.get_length()
         if check_length == 2147483647 or check_length == 0:
             producer.set("length", 15000)
     except:
         producer.set("length", 15000)

For now this allows me to insert color clips, colorbars and image files, but not all insert methods are giving a good result. I hope the patches above may just give some preliminary insight to where code might need to be adapted.

Bart.

**Comment by jliljebl** [comment]
Thanks, for looking into this. The behavior is confirmed, but patches as presented here would cause more problems then they solve but maybe something along those lines will do.

The problem has been solved in relation to Pattern Producers, those will be removed and replaced with new Media Plugins for next release.

I'll look into graphics and Color Clips issue next.

**Comment by jliljebl** [comment]
Ok, the Color Clip now respects Mark In and Mark Out from monitor, previous it was explicitly disabled.

Graphics files use default length preference.

    # Graphics files get added with their default lengths
    f_name, ext = os.path.splitext(media_file.name)
    if utils.file_extension_is_graphics_file(ext) and media_file.type != appconsts.IMAGE_SEQUENCE: # image sequences are graphics files but have own length
        in_fr, out_fr, l = editorpersistance.get_graphics_default_in_out_length()
        new_clip.mark_in = in_fr
        new_clip.mark_out = out_fr

I think I'll change this so that when *MediaFile* objects are created we set Mark In and Out to default length and later respect  Mark In and Mark Out if set, we'll. I'll close as fixed, some  additional patches coming later.
