### ISSUE TITLE
rendering stops but white frames are added to the end of clip

### ISSUE THREAD

**Issue by eszternagy** [jliljebl/flowblade#1009]
Hello! 

Im not good at computers at all, but i will try to explain my problem as much as possible. please keep in mind that although i love Flowblade and Ubuntu, i really have only a basic understanding of both.

i have seen a similar problem at others, but i have no idea how to fix mine. i want to "fade out" the end of my last clip, and although the rendering window pops up, it stops at some point of the process (depending on the length of fade i want do add; the longer the fade, the sooner the rendering process stops). 
then if i cancel the rendering, it still adds pure white frames to the end of my clip (where the fading effect should be). 
it removed this last clip and tried to fade out the new ending again, but nothing changed.
i successfully edited a video with flowblade in 2020 with a previous version of Ubuntu and Flowblade. this time i tried to reinstall Flowblade (today) hoping that it will fix the problem, but no luck :(

it is annoying, but I'm more afraid of having the same problem when i want to render my final video:/ i haven't tried it yet, because my video is not in its final version, and im afraid of messing it up :D 

sorry for my poor IT language or if i missed any infos you might need ...i hope you can help me somehow :) 

1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment):6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.):Ubuntu 20.04.2

**Comment by thennicke** [comment]
What encoding option are you using for your fades? Try FLV -- it should work. This was a known issue in 2.4. By the way you're running a really old version of Flowblade; a lot of these kinds of bugs have been fixed in newer versions. Cheers

**Comment by eszternagy** [comment]
thank you so much! i chose lossless ffv1/.mkv now instead of h.264/.mp4 (that i was using) and it's working :) I'll try to install the newest version, i didn't realize ive been using a very old one:/ i downloaded it from ubuntu software centre, and it was the only version i found there...but i will look into it. i much appreciate your reply! have a nice day:)

**Comment by thennicke** [comment]
No problem :) Try using the Flatpak version rather than the one through your software centre; that should be the latest version (2.8). It's easier for developers to maintain a single Flatpak than targeting all these different package managers, so it should usually be more up to date.

**Comment by eszternagy** [comment]
yeah finally i managed to install the Flatpak version, thank you so much! :)
