### ISSUE TITLE
Timeline Rendering settings not showing proper list of encodings

### ISSUE THREAD

**Issue by jcreigh** [jliljebl/flowblade#1010]
I compiled the current git head, d5ca2ee3f961b327838c6e3d7335f39860581eaa, in hopes of using NVENC, and  while I see it's now in `res/render/renderencoding.xml`, I don't believe it's possible to select. The encoding selector only shows the `proxyencodingoption`s from the xml file. Am I missing something?

https://github.com/jliljebl/flowblade/blob/d5ca2ee3f961b327838c6e3d7335f39860581eaa/flowblade-trunk/Flowblade/tlinerender.py#L930-L943

**Comment by jliljebl** [comment]
Yeah, this is coming in 2.10 later this year, code is already in repo.  *nvenc* needed some extra work to make it available. I'll do further checks that everything is working before release.
