### ISSUE TITLE
Build using Development Repository Version - Ubuntu 18.04

### ISSUE THREAD

**Issue by Termplexed** [jliljebl/flowblade#1013]
Sorry if this is noise, and close if in the way.

---

Only a short write on what I did to get [latest git](https://github.com/jliljebl/flowblade/tree/d5ca2ee3f961b327838c6e3d7335f39860581eaa) (d5ca2ee3f9) running on:

* OS: Ubuntu 18.04.5 LTS [linux version 4.15.0-147-generic]

Based on:

* [Installing using Development Repository Version](https://github.com/jliljebl/flowblade/blob/d5ca2ee3f961b327838c6e3d7335f39860581eaa/flowblade-trunk/docs/INSTALLING.md#installing-using-development-repository-version) and
* [Building Python 3 bindings to use with repo installation](https://github.com/jliljebl/flowblade/blob/d5ca2ee3f961b327838c6e3d7335f39860581eaa/flowblade-trunk/docs/creating_user_folder_bindings.md)

# Base of operations:
```sh
mkdir ~/soft/videoedit/flowblade
cd ~/soft/videoedit/flowblade
git clone https://github.com/jliljebl/flowblade.git
git clone git://github.com/mltframework/mlt.git
cd mlt # staying here for the duration of this post
```

# Build MLT (96ea8f3868)

* https://github.com/mltframework/mlt/tree/96ea8f386835cc9e3c3e135c2d9fca9f47e1315e

* See dependencies: https://www.mltframework.org/docs/install/

### Update ffmpeg to version 4 (to get `libavformat` for `mlt`)
```sh
sudo add-apt-repository ppa:jonathonf/ffmpeg-4
sudo apt update
sudo apt install ffmpeg
sudo apt install libavformat-dev
```

No `./configure` script, so editing `CMakeList.txt` directly to enable `SWIG_PYTHON`:

```sh
vim CMakeList.txt
# Set to ON
option(SWIG_PYTHON "Enable SWIG Python bindings" ON)
```

Remember to move or remove `CMakeCache.txt` after editing `CMakeList.txt`!

Then on to a repetitive dependency install:

```sh
cmake .
# Install dependencies etc. and re-run cmake .
```

This can be very different depending on what already is installed; for me:

```sh
libfftw3-dev libsox-dev libmovit-dev libebur128-dev libsamplerate0-dev libavformat-dev
```

Final run:

```
-- The following features have been enabled:

 * GPLv2
 * GPLv3
 * Module: avformat
 * Module: DeckLink
 * Module: Frei0r
 * Module: GDK
 * Module: JACKRack
 * Module: Kdenlive
 * Module: Normalize
 * Module: Oldfilm
 * Module: Movit
 * Module: Plus
 * Module: PlusGPL
 * Module: Qt
 * Module: Resample
 * Module: RtAudio
 * Module: Rubberband
 * Module: SDL1
 * Module: SDL2
 * Module: SoX
 * Module: Vorbis
 * Module: XINE
 * Module: XML
 * SWIG: Python

-- The following OPTIONAL packages have been found:

 * OpenGL
 * Freetype
 * Fontconfig
 * Qt5Core
 * Qt5Gui
 * Qt5Xml
 * Qt5Svg
 * Qt5Widgets
 * Qt5
 * SWIG

-- The following REQUIRED packages have been found:

 * Threads
 * PkgConfig
 * X11
 * Python3

-- The following features have been disabled:

 * Tests
 * Doxygen
 * Module: NDI
 * Module: OpenCV
 * Module: vid.stab
 * SWIG: C#
 * SWIG: Java
 * SWIG: Lua
 * SWIG: Node.js
 * SWIG: Perl
 * SWIG: PHP
 * SWIG: Ruby
 * SWIG: Tcl

-- The following OPTIONAL packages have not been found:

 * JACK
```

* Was not able to find any `vid.stab`. 
* JACK seems to depend on jack1 (`librtaudio-dev`) and wanted to remove `jackd2`, so I skipped that for now.
* OpenCV seems to depend on some features not in bundled version. Have to look at that later.

## Finally build:

```sh
cmake --build .
```

This gave an Qt error for me:

```
src/modules/qt/qimage_wrapper.cpp:287:60: error: ‘class QImage’ has no member named ‘sizeInBytes’
```

* Qt 5.9.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.4.0) on "xcb" 

Not sure if this will cause trouble, but build was OK after this: Change qt  `sizeInBytes()` to `byteCount()`.

```sh
vim src/modules/qt/qimage_wrapper.cpp +287

			memcpy( self->current_image, scaled.constBits(), scaled.sizeInBytes());

			memcpy( self->current_image, scaled.constBits(), scaled.byteCount());

```

# Post MLT build

Next copy files to `flowblade` (note that the `.so` file differs in name and location from the *“Installing using Development Repository Version”* linked at top of this post):

```sh
cp src/swig/python/mlt.py ../flowblade/flowblade-trunk/
cp out/lib/_mlt7.so ../flowblade/flowblade-trunk/
```

Create a shell start script. This is the `setenv` file in root of `mlt`. Only added execution line at end:

```sh
printf '#! /bin/sh -\n\n' >flowblade
cat setenv >>flowblade
printf '\n\n# Start flowblade:\n%s/flowblade/flowblade-trunk/flowblade\n'  "$(dirname "$PWD")">>flowblade
chmod +x flowblade
```

Resulting in somehting like:

```sh
#! /bin/sh -


# Environment variable settings to allow execution without install

export MLT_REPOSITORY="`pwd`/out/lib/mlt"
export MLT_DATA="`pwd`/out/share/mlt"
export MLT_PROFILES_PATH="`pwd`/out/share/mlt/profiles"
export MLT_PRESETS_PATH="`pwd`/out/share/mlt/presets"


if [ "$(uname -s)" = "Darwin" ]; then
    export DYLD_LIBRARY_PATH="`pwd`/out/lib:$DYLD_LIBRARY_PATH"
else
    export LD_LIBRARY_PATH="`pwd`/out/lib:$LD_LIBRARY_PATH"
fi

export PATH="`pwd`/out/bin:$PATH"


# Start flowblade:
/home/username/soft/videoedit/flowblade/flowblade-trunk/flowblade
```

Execute:

`./flowblade`

# Horray !!

Not tested extensivley, but have not had any trouble so far ;)

**Comment by Kchour** [comment]
I'm also using Ubuntu 18.04, and I followed all of your steps and was able to start flowblade (could see the gui). However, as soon as I added a video to a project, I got a segmentation fault error 

See attached 
[output.txt](https://github.com/jliljebl/flowblade/files/6865570/output.txt)

**Comment by jliljebl** [comment]
I'll close this Issue here but add it to Forum and link this from there.
