### ISSUE TITLE
Choose audio codec for output

### ISSUE THREAD

**Issue by PatrickKing** [jliljebl/flowblade#1014]
Flowblade 2.8

The default audio codec seems to be mp3 for H.264 video in an mp4 container. This isn't suitable for some uses, e.g. Twitter does not support mp3. It would be useful to have a choice of audio encoders.

**Comment by jliljebl** [comment]
The current workflow for doing this.

1. Select *Encoding Format* from left panel in *Render* panel.
2. Check *Render Using Args* checkbox.
3. Change value of line *acodec =mp3lame* or whatever is the arg defining audio codec to some other codec. 
4. In Flowblade see *Help->Runtime Environment->Audio codecs* for available options or check *ffmpeg* documentation for correct codec values.
