### ISSUE TITLE
PDF Help Doc

### ISSUE THREAD

**Issue by kvnsz** [jliljebl/flowblade#1017]
Please include the following information.
1) Flowblade version (Help->About): 0.14.0
2) MLT version (Help->Runtime Environment): vers. 6.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easiest way to understand what is happening.:
 I have decided to make a pdf version of the online help file, so it would be easier for people to read as they need help, instead of using a web browser which takes up too many resources as a person is working with FlowBlade.  Also good for off line reading. I will redo all hyperlinks in document to point to bookmarks in the same doc. I will also do a spell check for any misspelled words. Will also move text up or down a little, so it will fit better on a page. I hope this is permissible to admins and creator of FlowBlade. I personally find it easier to read a pdf than a web page.     my email: kvnsz11@gmail.com

**Comment by smolnp** [comment]
Alternatively, you can place pdf versions in different languages ​​here: http://jliljebl.github.io/flowblade/webhelp/help.html and make them available for download. As already done with the French manual: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/FLOWBLADE_manuel_fr.pdf.
Also (for a draft) you can use the wiki: https://github.com/jliljebl/flowblade/wiki. Or rewrite the help at https://en.wikibooks.org/wiki/Main_Page, wikibooks already has the ability to download the page in pdf format, and it's easier to track changes for translation into other languages. The latter option provides for the inclusion of a larger number of users who want to replenish the manual. Also, wikibooks has a small threshold of entry, a person is by nature lazy, most find it easier to edit in a graphics editor than in text mode.

**Comment by jliljebl** [comment]
@kvnsz Yes, if you make PDF that you believe is an improvement on current docs for some use cases, please do contribute it available with pull request, or you can send it to me at janne.liljeblad@gmail.com if you are not familiar with making pull requests and I'll add it here too.

**Comment by jliljebl** [comment]
This has not seen any developments lately, closing.
