### ISSUE TITLE
MLT not found, exiting...

### ISSUE THREAD

**Issue by erkanisik1** [jliljebl/flowblade#1020]
Please include the following information.
1) Flowblade version (Help->About): 2.8.0.3
2) MLT version (Help->Runtime Environment): 7.0.1
3) Your distribution (Ubuntu, Debian, Mint etc.): Pisi GNU/Linux

**Comment by mariodebian** [comment]
In Debian testing/unstable python3-mlt, the import module is **mlt7**:

```
# dpkg -L python3-mlt 
/.
/usr
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/_mlt7.cpython-39-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/mlt7.py
/usr/share
/usr/share/doc
/usr/share/doc/python3-mlt
/usr/share/doc/python3-mlt/changelog.Debian.gz
/usr/share/doc/python3-mlt/copyright
```

As quick fix I changed all files with:

```
sudo find /usr/share/flowblade/ -type f -name "*.py" -exec sed -i 's/import mlt$/import mlt7 as mlt/g' {} +
sudo sed -i 's/import mlt$/import mlt7 as mlt/g' /usr/bin/flowblade
```

**Comment by jliljebl** [comment]
Ok. I'll try to set up VM for Debian maybe next week to take look at this.

**Comment by alexmyczko** [comment]
@jliljebl I don't think this is your problem, unless upstream mlt really calls their mlt mlt7 from versino 7 on. if so you'll need to add the fix, otherwise i have to in just the packaging.

**Comment by erkanisik1** [comment]
> In Debian testing/unstable python3-mlt, the import module is **mlt7**:
> 
> ```
> # dpkg -L python3-mlt 
> /.
> /usr
> /usr/lib
> /usr/lib/python3
> /usr/lib/python3/dist-packages
> /usr/lib/python3/dist-packages/_mlt7.cpython-39-x86_64-linux-gnu.so
> /usr/lib/python3/dist-packages/mlt7.py
> /usr/share
> /usr/share/doc
> /usr/share/doc/python3-mlt
> /usr/share/doc/python3-mlt/changelog.Debian.gz
> /usr/share/doc/python3-mlt/copyright
> ```
> 
> As quick fix I changed all files with:
> 
> ```
> sudo find /usr/share/flowblade/ -type f -name "*.py" -exec sed -i 's/import mlt$/import mlt7 as mlt/g' {} +
> sudo sed -i 's/import mlt$/import mlt7 as mlt/g' /usr/bin/flowblade
> ```

Thank you, 
sudo find /usr/share/flowblade/ -type f -name "*.py" -exec sed -i 's/import mlt$/import mlt7 as mlt/g' {} +
sudo sed -i 's/import mlt$/import mlt7 as mlt/g' /usr/bin/flowblade
When we compiled the commands after making them suitable for our system, the problem was solved.

**Comment by jliljebl** [comment]
We need to get both 'import mlt' and 'import mlt7 as mlt' since we cannot know what is being presented to us.

**Comment by sergiomb2** [comment]
```
sed -i 's/import mlt$/import mlt7 as mlt/' flowblade
sed -i 's/import mlt$/import mlt7 as mlt/' Flowblade/*py
sed -i 's/import mlt$/import mlt7 as mlt/' Flowblade/tools/*py
```

Fixed the problem

**Comment by jliljebl** [comment]
Ok, this is the *mlt -> mlt7* related issue that has been fixed.

**Comment by sergiomb2** [comment]
Thank you I will update RPMFusion packages soon , add see if now is eligible for Fedora
