### ISSUE TITLE
Mark's initial time should be as soon as I mark, not when I enter the name

### ISSUE THREAD

**Issue by xsawyerx** [jliljebl/flowblade#1022]
If the video is playing and I mark, I need to provide a name. When I enter a name and press "enter," the mark is done from the moment I pressed "enter" instead of the moment I pressed "m" to mark.

This goes against the whole point of me press "m" to say "mark here." I think it's just the code assuming that the timestamp of the dialogue would be the same as when the "m" is pressed and the dialog is opened. This would be true when playback is paused, but not when it's playing.

1) Flowblade version (Help->About): 2.8.0. (flatpak)
2) MLT version (Help->Runtime Environment): 6.24.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 21.04
4) Step-by-step reproduce instructions:

* Open a video.
* Play the video.
* At some point (say, 5 seconds in), press "m" to mark. The name dialog will open.
* Wait a few more seconds, then enter a name and press "enter".
* The mark is not done at the 5 seconds mark but only when a name was provided.
* Submit GitHub ticket. :D

**Comment by jliljebl** [comment]
Fixed, see the other issue #1023.

**Comment by xsawyerx** [comment]
Saved two birds with one tree. :)

Thank you.
