### ISSUE TITLE
Cross fade appears to be ignored with MLT 7.0 or higher

### ISSUE THREAD

**Issue by tabfugnic** [jliljebl/flowblade#1024]
Please include the following information.
1) Flowblade version (Help->About): 2.8
2) MLT version (Help->Runtime Environment): 7.0.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Debian Testing(Bookworm)
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

I could be doing something wrong. After upgrading my environment recently and dealing with the mlt is now mlt7 issues. I noticed that crossfades on my projects stopped working. Simple steps to reproduce:

1. Add an image or a video to two tracks. 
2. Add fade out/in between the two
3. Notice that nothing happens as if no cross fade were there at all

I've tried to debug this, but don't see any explicit options to increase verbosity of the output I get when running from command line. The command line doesn't report any issues either.

I've provided both an image of the cross fade setup I have and what the output is. 

![2021-10-01-234655_567x359_scrot](https://user-images.githubusercontent.com/755201/135702704-46f91d4d-20fe-4667-9acb-56de40ccf6f7.png)

https://user-images.githubusercontent.com/755201/135702689-53817c31-d54e-4b0e-864f-d84b602a774e.mp4

**Comment by jliljebl** [comment]
Ok, 'Fade In' works here but 'Fade Out' does not, this somehow got broken.

**Comment by tabfugnic** [comment]
I tried flatpak, but it didn't work as expected. I will try again.

**Comment by sergiomb2** [comment]
```
sed -i 's/import mlt$/import mlt7 as mlt/' flowblade
sed -i 's/import mlt$/import mlt7 as mlt/' Flowblade/*py
sed -i 's/import mlt$/import mlt7 as mlt/' Flowblade/tools/*py
```

Fixed the problem

**Comment by jliljebl** [comment]
The fade compositors have been dropped because MLT dropped the "region" transition that was used by Flowblade to implement them.

Please use "Fade" filters instead.
