### ISSUE TITLE
Flowblade Gives no module named dbus

### ISSUE THREAD

**Issue by konsbn** [jliljebl/flowblade#1026]
Please include the following information.
1) Flowblade version (Help->About): 2.8
2) MLT version (Help->Runtime Environment): 6.24.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Fedora 33
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
ON running `$ flowblade` I get the following error:
```
$  flowblade
FLOWBLADE MOVIE EDITOR 2.8
--------------------------
Launch script dir: /usr/bin
Running from installation...
MLT found, version: 6.24.0
Failed to import module app.py to launch Flowblade!
ERROR: No module named 'dbus'
Installation was assumed to be at: /usr/lib/python3.9/site-packages/Flowblade

```
I tried `sudo pip install -U dbus-python` as well as `sudo dnf install python3-dbus` with no effect.

**Comment by konsbn** [comment]
> Unforunately beats me, those commands should solve the issue, but I did find this page with some maybe related information: https://nixx.co/no-module-named-dbus/

Tried everything, didn't work

**Comment by jliljebl** [comment]
This is not reproduced in upcoming version 2.10 or the Flatpak being tested for it, closing.
