### ISSUE TITLE
Problems with openCV dependency on Ubuntu 21.04

### ISSUE THREAD

**Issue by Levitanus** [jliljebl/flowblade#1027]
Please include the following information.
1) Flowblade version (Help->About): Any, actually
2) MLT version (Help->Runtime Environment): --
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 21.04
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: For the couple of weeks I can't use flowblade of any version because of broken dependencies of OpenCV (libOpenEXR exactly, which is locked at v30, but presents only as v29)

```
libopencv-imgcodecs4.5 : Depends libopenexr30 (>= 3.1.2)
```
I'm confused what to do as I can't do anything and, actually love and more than, need the package quite regularly. I've opened [issue](https://github.com/opencv/opencv/issues/20941) in OpenCV repo, but they said, that they are not in deal)

I hoped the broken dependency will be fixed quickly, but it still is broken... How can I fix it?

**Comment by jliljebl** [comment]
Release notes at https://www.mltframework.org/ has point for version *MLT v6.26.1*:
* Fixed building with OpenCV 4.5

Flowblade does not use any OpenCV filters currently so building MLT with  OpenCV should solve issues. I'll do build tests before next release and comment here more with the results I'm getting then. I'm still working on Python code so it will unfortunately probably be month+ before there is any additional info on this.

**Comment by Levitanus** [comment]
Thanks a lot, installing package python3-mlt solve the problem

**Comment by alexmyczko** [comment]
ubuntu still has the very old version, a solution would be to upgrade to jammy 22.04 LTS (unreleased), unfortunately 21.10 also is affected...

**Comment by jliljebl** [comment]
Closing as newer versions of MLT very likely fix this issue.
