### ISSUE TITLE
Please edit and add one line in ...

### ISSUE THREAD

**Issue by ohquait** [jliljebl/flowblade#1028]
Please include the following information.
1) Flowblade version (Help->About):  2.8.0.3 master branch
2) MLT version (Help->Runtime Environment): 7.0.1
3) Your distribution (Ubuntu, Debian, Mint etc.): PCLinuxOS  [ Qua it (extremly testings)]
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
file does not exist if build from master-branch

[flowblade-mediaplugins-path.patch.txt](https://github.com/jliljebl/flowblade/files/7490935/flowblade-mediaplugins-path.patch.txt)

**Comment by ohquait** [comment]
that's solving a nostartup problem

**Comment by jliljebl** [comment]
Thanks, added that.
