### ISSUE TITLE
UX: Save dialog box don't close after hit button [save]

### ISSUE THREAD

**Issue by thanhhocse96** [jliljebl/flowblade#1030]
Information:
1) Flowblade version (Help->About): 2.0.4
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 20.04
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: Make new project > File: Save > enter file name, eg: abc.flb > hit [save] button > Dialog box not close

In the simple UX: hit [save] button > Dialog box close > jump to project name: abc.flb

**Comment by jliljebl** [comment]
> Flowblade version (Help->About): 2.0.4

This issue does not reproduce on current version 2.8; 'Save' option is not available until 'Save As...' has been used. I'll close this, if this behavior is seen in latest version, please comment her and I'll reopen.
