### ISSUE TITLE
Request: Need custom preset profile in [Project > Change Project Profile...]

### ISSUE THREAD

**Issue by thanhhocse96** [jliljebl/flowblade#1031]
Information.
1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment):
3) Your distribution (Ubuntu, Debian, Mint etc.): 20.04
 I want to make some portrait video with ratio 9:16, but i couldn't find any custom preset in [Project > Change Project Profile...] for 9:16 ratio

**Comment by jliljebl** [comment]
Ok, there seems to a problem here.

**Comment by smolnp** [comment]
Can I take it from kdenlive?
...
description=Vertical HD 30 fps
frame_rate_num=30
frame_rate_den=1
width=1080
height=1920
progressive=1
sample_aspect_num=1
sample_aspect_den=1
display_aspect_num=9
display_aspect_den=16
colorspace=709
...
description=Vertical HD 60 fps
frame_rate_num=60
frame_rate_den=1
width=1080
height=1920
progressive=1
sample_aspect_num=1
sample_aspect_den=1
display_aspect_num=9
display_aspect_den=16
colorspace=709

**Comment by jliljebl** [comment]
Yes, you should be able to use these files if you place them in folder *$XDG DATA DIR + "/flowblade/userprofiles/"* or just set values in *Profiles Manager* that saves them there.

**Comment by jliljebl** [comment]
Ok, I've fixed issue in this rea of functionality on current code base for next release. Not sure what the described issue was since it is described on older version, but 2.10 will be working correctly in with user profiles.
