### ISSUE TITLE
Rendered Video contains static when utilizing V1 multiple times. 

### ISSUE THREAD

**Issue by Gamertoc** [jliljebl/flowblade#1032]
1) Flowblade version (Help->About): 2.8 (tested with both Flatpak and .deb release)
2) MLT version (Help->Runtime Environment): 6.24.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 21.10 (tested on Kubuntu 21.04 as well, same issue)
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
- Insert your first track/tracks on V1 (Let's call them T1)
- Transition to a track (T2) on V2 (or others) 
- Transition back to a track (T3) on V1
- Render the video (tested with both MPEG-4 and H.264)
In the rendered video, the audio part of T3 will be moved to the front and overlayed with T1. Instead, there will be something I can only describe as a really hard static.
The video will be completely removed, and it will only show a white screen. 

Attached you will find a screenshot of how my timeline looks. The marked video track is the one that is causing the issue. Note that it only happens on V1. If I move the marked track to V2 or above, everything works as it's supposed to.
![2021-12-01_14-33](https://user-images.githubusercontent.com/33159593/144243682-23389f79-c2b3-4f3e-a9c7-c3f470f8ce59.png)

I really hope we can find a solution to that as my own search hasn't resulted in anything, and I really like the flow and feeling of Flowblade so I'd like to continue using it.

**Comment by jliljebl** [comment]
I'm moving into bug fixes phase now so will be looking at this before January release.

**Comment by jliljebl** [comment]
Ok, didn't look carefully enough the provided screenshot. The Clips and Compositors do not overlap, so no successful composited image creation can be expected. The new default Timeline Compositing Mode since 2.10 does compositing automatically and we should get less problems with incorrectly used Compositors.
