### ISSUE TITLE
Number of characters in "Position Scale" filter settings

### ISSUE THREAD

**Issue by 15mael** [jliljebl/flowblade#1033]
Please include the following information.
1) Flowblade version 2.8
2) MLT version 6.24.0
3) Your distribution : Debian 11 (flatpak)
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Hi, I think there's a little issue when applying the "Position Scale" filter (add filter / Transform / Position Scale).
In the filter's settings, the "X" and "Y" boxes can only show 4 characters, including "-" for negatives values. Which means that the minimum value you can set manually is "-999".
You can use the mouse to go over this value, but the box shows a cropped value.
Thanks for your help.
Have a good day.

**Comment by jliljebl** [comment]
This was fixed already and 2.10 will work correctly.
