### ISSUE TITLE
GPU acceleration discovery and selection

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#1035]
Please include the following information.
1) Flowblade version (Help->About): 2.8
2) MLT version (Help->Runtime Environment): 2.26.1
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Please support GPU acceleration discovery and selection as is found in https://obsproject.com/ Implementation there is in C but can be used to implement similar functionality in Python for Flowblade.

![e1](https://user-images.githubusercontent.com/198964/147079439-d39076f8-7d16-4f4a-bd47-0c28ef3b8f89.png)

![e2](https://user-images.githubusercontent.com/198964/147079458-ee9ba205-8e88-4393-851b-de16a928e84c.png)

**Comment by jliljebl** [comment]
GPU encoding is coming in next release.

**Comment by jliljebl** [comment]
Feature is also already in repo, so I'll mark this as *feature added*.

**Comment by wolfgangr** [comment]
Great :+1: 

now then, how can I enable GPU acceleration?
Ist it somewhere in the settings?
I can't find any, neither in my experimental 2.8 on mint 21.1 nor in my 2.0.0 on debian 10
Both machines have nvidia cards and drivers, and I can address GPU with a custom build of `ffmpeg`.

So **do I have to perform a custom build of flowblade?**
**What's required to enable GPU accelereation?**
`nvidia cuda nvenc` would be preferred :-)
any pointers would be appreciated :-)

a quick glance on `lsof` reveals loads of interrelated libraries.... `python` ... `mlt` ....
... have spent a week's night on getting `nvenc` to work on `ffmpeg` ....

**Comment by wolfgangr** [comment]
first try: quick build on **debian 10**
**failed** - does not meet the required mlt 7 (6.12.0-1 available)

second try: **flatpack**
looks promising, it even appears to **recognize my GPU driver** version installed:
`org.freedesktop.Platform.GL.nvidia-470-141-03`

I can select **NVENC H.264 High Profile** as "Kodierungs-Format"
(aka "coding format", sorry - don't know how to switch to english locale....)

However, **performance test results are rather disappointing.**
It takes 32 min to render a 10.5 min clip
changing from 4k (project setting) to single HD even takes slightly longer

CPU usage is "down" from 400 % (4 cores) to about 300 %
GPU access ist displayed in` nvidia-smi` (...`python`), but GPU-usage is far below 10 % (0 ... 1% for HD render)

So, may I suspect that there is much **bottleneck in the pipe before final rendering?**
When I play the timeline, I don't see GPU access in nvidia-smi.

May it help to **build `MLT` to use GPU?**
Any hints / experience?

btw: For **rendering proxy** files, it seems **not to use GPU at all**, and I did not find a way to configure.

**Comment by wolfgangr** [comment]
adding **proxy rendering** on GPU  seems quite **straight forward:**
I just added a `<profile>` to the `<proxyencodingoption>` list:

```
--- a/flowblade-trunk/Flowblade/res/render/renderencoding.xml
+++ b/flowblade-trunk/Flowblade/res/render/renderencoding.xml
@@ -225,6 +225,14 @@
     <proxyencodingoption name="H.264 Preset Ultrafast" extension="mp4" type="av" audiodesc="mp3, 192kb/s, 48000Hz" resize="True" qgroup="qgroup2">
         <profile args="f=mp4 acodec=libmp3lame ac=2 ab=192k ar=48000 vcodec=libx264 preset=ultrafast tune=fastdecode g=30 crf=25"/>
     </proxyencodingoption>
+
+   <!-- [wr] 2023-10-03 ... try hardcoded gpu encoding   -->
+    <proxyencodingoption name="H.264 NVENC p2=Faster" extension="mp4" type="av" audiodesc="mp3, 192kb/s, 48000Hz" resize="True" qgroup="qgroup2">
+   <!-- see ffmpeg -h encoder=h264_nvenc  -->
+        <profile args="f=mp4 acodec=libmp3lame ac=2 ab=192k ar=48000 vcodec=h264_nvenc preset=p2 tune=ull g=30 crf=25"/>
+    </proxyencodingoption>
+
+
```

It immediadely shows on proxy format selection menue, and works.
Maybe in a distro, it might be a good idea to make this setting dependent on GPU render test, of course.
The settings may need some testing and tuning still.
