### ISSUE TITLE
Creation of new project deletes the old one

### ISSUE THREAD

**Issue by keremet** [jliljebl/flowblade#1036]
Flowblade version: 2.8 (b739099f1593cc8ac1bc3c01524e1c29ba6d23d2)
MLT version: 6.20.0
distribution: Ubuntu 20.04

Create a project. Add something on timeline and don't save the project. Press Ctrl+N, click OK button. A new project will be created and previous project will be lost. 

I suggest to open a new window for new project. The creation of new project should not have any impact to the previous project.

**Comment by jliljebl** [comment]
We wont do this. Very few applications are 'document based' like this and there reasons like dbus connections that  strongly favor running only one instance of the application at a time.

**Comment by keremet** [comment]
@jliljebl , Can you add dialog box which will remind user to save previous project if it is not saved yet?
