### ISSUE TITLE
is the Flowblade project dead?

### ISSUE THREAD

**Issue by welon68** [jliljebl/flowblade#1037]
there was no update for a long time :-(

**Comment by ccoenen** [comment]
Looking at the commit history or the "insights" tab here on github, I'd say there's a steady stream of commits to this project. There just are no releases right now.

**Comment by jliljebl** [comment]
@welon68 No releases for a while, but getting those out sometimes depends on many things. There will be release in q1/22. Next release cycle after that will be shorter.

Closing this as *resolved*, project is not dead, but there has been some delay on getting release out. But compared to something like Gimp we are coming up with releases like clockwork.
