### ISSUE TITLE
Install flowbalde in Ubuntu18.04 wrong 

### ISSUE THREAD

**Issue by sunflower-knight** [jliljebl/flowblade#1039]
i want to use it  , and my os is ubuntu 18.04   . i have seen your install introduce ;  sad ,    
is it in your workplan?

**Comment by alexmyczko** [comment]
would you mind upgrading to 20.04? or even 22.04 (to be released in 3 months)?

**Comment by jliljebl** [comment]
Closing this because I don't think issue is relevant anymore. Ubuntu 18.04 is too old to be officially supported by the project.
