### ISSUE TITLE
new version release plan?

### ISSUE THREAD

**Issue by alexmyczko** [jliljebl/flowblade#1041]
I saw the break message until February.

However, I would like to point you at this:
https://discourse.ubuntu.com/t/jammy-jellyfish-release-schedule/23906

February 24 is the last day a package update of flowblade into Ubuntu 22.04 can happen.
So if you wish to have Ubuntu 22.04 users to use a more recent flowblade, please tag a release before when possible.
Otherwise they will be stuck with the current version for two years...

Thank you,

**Comment by jliljebl** [comment]
Thank you for the info. I will be able to tag next release by 15th February the latest, I'll comment here the release is available.

**Comment by jliljebl** [comment]
I've decided to take a longer break from the project so there will not be release coming, sorry.

**Comment by alexmyczko** [comment]
@jliljebl no problem, relax and enjoy your break! you don't owe anyone a thing...
