### ISSUE TITLE
Feature Request: rejoin previously splitted clips

### ISSUE THREAD

**Issue by metux** [jliljebl/flowblade#1044]
When cutting clips into separate ones, there doesn't seem to undo this later (except for undoing the last operations).
If some cuts later turn out to be a mistake, it should be possible to rejoin the pieces, so we have a larger clip again,
just as the particular cut hadn't been done in the first place.

**Comment by Disaster2life** [comment]
Personally wouldn't want that, while sure you could get a cleaner timeline, it'll take away the consideration of making a cut, but yeah you can always just use container clips to join together already cut things, or you could lift the clip and reinsert it without the accidental cuts, But yeah I personally wouldn't want to see this

**Comment by jliljebl** [comment]
The suggested workflow to get this done is just to delete one of clips, and then making the other one as long as both of them were comibined. Have not seen this feature in any other video editor, and I believe that strongly indicates that the requested feature has not been found useful by anyone so far.
