### ISSUE TITLE
Better colours for the clips? (Feature Request)

### ISSUE THREAD

**Issue by Disaster2life** [jliljebl/flowblade#1045]
Wondered if before 2.9 releases, I could contribute to make the colours you can change clips to fit more into the normal purple and green colours because they don't seem to fit great next to each other, I don't really know where the colours for them are located (if they even exist as a file that is), I could start a pull request in a few days probably?

**Comment by jliljebl** [comment]
Check the clip colors in the upcoming 2.10.  If you still don't like them create anew issue and we will discuss more.
