### ISSUE TITLE
Rendered MP4 / H.264 has no sound on iOS / iPhone

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#1057]
Please include the following information.
1) Flowblade version (Help->About): 2.8
2) MLT version (Help->Runtime Environment): 6.26.1
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 21.10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: Render

The output file is video H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 and has audio MP3 (MPEG audio layer 3). Playing on iOS of iPhone does not provide sound, Probably the codes is not supported by iOS. What is a good workaround? I can provide many example renderings with default MP4 settings that have this issue on iOS.

**Comment by jliljebl** [comment]
You can try to check the "Render with Args" checkbox and then change the line "acodec=" to use some other audio codec.
