### ISSUE TITLE
[REQ] license set on git

### ISSUE THREAD

**Issue by forart** [jliljebl/flowblade#1058]
Hi there, Flowblade is awesome !

Since we've collected it in our [HyMPS project](https://github.com/forart/HyMPS) (under [Video Editors section](https://github.com/forart/HyMPS/blob/main/VideoEditors.md)), can you please set licensing terms in your git ?

Our "problem" is that the badge service generates this: 

![](https://flat.badgen.net/github/license/jliljebl/flowblade/?label=LICENSE)
(generating URL: https://flat.badgen.net/github/license/jliljebl/flowblade/?label=LICENSE)

Thanks in advance.

**Comment by jliljebl** [comment]
I'll try to do this for 2.10.

**Comment by forart** [comment]
Thanks, we've (renamed and) updated the [Video Editors section](https://github.com/forart/HyMPS/blob/main/VideoEditors.md) page.

Chack it out.

**Comment by jliljebl** [comment]
The license text has been added. That also updated the 'About' panel to show that the application is under GPL 3, which is good.

**Comment by forart** [comment]
Cool, as you can see now the badge is generated correctly: thanks !
