### ISSUE TITLE
MLT install issue

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#1059]
Flowblade developpment version
MLT version 7.6.0
Ubuntu studio 22.04

I tried to install a Flowblade development version from these pages.

_**Page 1 Flowblade:** https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md_

Flowblade is OK using the new way for github : 

- creation of a public key in github 
- git clone git@github.com/jliljebl/flowblade.git 

   ( ex git clone https://github.com/jliljebl/flowblade.git)

_**page 2 MLT :** https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/creating_user_folder_bindings.md_

git clone git@github.com/mltframework/mlt.git,  clones MLT in the choosen directory.

But, the continuation of the page is obsolete. No more configure file, use of cmake rather than make.
I'm not familiar with compilation.
I tried the cmake qt gui to configure and generate then cmake install but I did'nt find the  mlt.py and _mlt.so files needed in the section set up bindings of the page 2.

 So can somebody explain to me what to do ?
Thanks.

**Comment by jliljebl** [comment]
I'll retest and update on the MLT bindings install info later, closing this now as I try to get a controlled view on current state of bugs and other major issues. Ill comment here once I've tried creating new bindings myself.
