### ISSUE TITLE
Flowblade Multi Camera support 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jliljebl/flowblade#106]
```
flowblade needs Multi Camera support and Multi Camera  sync and Multi Camera 
recording.
```

Original issue reported on code.google.com by `sshe...@yahoo.com` on 25 Jan 2015 at 9:48

**Comment by jliljebl** [comment]
Should be noted that getting this done depends on multiple technical issues that have not been explored yet.

**Comment by jliljebl** [comment]
I'm marking this wontfix, doing this will require contributions.
