### ISSUE TITLE
Undo box move blocks the playback (solved)

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#1066]
Flowblade version 2.8
MLT version 7.4.0
Ubuntu 22.04

When you undo a move of a box selection with the middlebar button, you can no more playback the project.

In "/usr/share/flowblade/Flowblade/edit.py 
line 1212 :

`action_object = utils.EmptyClass`
needs ()

replace by :
`action_object = utils.EmptyClass()`

**Comment by jliljebl** [comment]
Yes, thanks, this is fixed in repo now,
