### ISSUE TITLE
[Question] Multi GPU rendering?

### ISSUE THREAD

**Issue by NXTler** [jliljebl/flowblade#1067]
Hey,
its just what the title says.
Will there be multi GPU rendering at some point?

**Comment by jliljebl** [comment]
Upcoming 2.10 will  have GPU rendering but anything beyond that depends on what happens in upstream porjects ffmpeg and MLT, and at this tome I'm not aware of any developments in this area.

So the answer is maybe, but not anytime soon, and not by any development activity from this project.
