### ISSUE TITLE
No way to resync all?

### ISSUE THREAD

**Issue by futon88** [jliljebl/flowblade#1068]
Please include the following information.
1) Flowblade 2.8
2) MLT version 6.24.0
3) Ubuntu 18
4) I'm unable to resync all audio clips.  I can select individual clips and resync, and I can ctrl+click to select multiple, then resync, but this doesn't work if I use Select -> All Clips After.  I'm just looking for a way to easily resync all my audio clips all at once, without having to click on them.  Am I overlooking something?

**Comment by jliljebl** [comment]
We replaced the "Resync selected" -button with "Resync Track" -button which resyncs in clips in audio track, I hope this is what you are looking for.  "Resync selected" function is not coming back, so now you can resyc clips one at a time, or all clips on a track at once.
