### ISSUE TITLE
the .deb binary is marked as having a "proprietary" license

### ISSUE THREAD

**Issue by symbolisch1234** [jliljebl/flowblade#1069]
**Steps to reproduce**
* Visit https://github.com/jliljebl/flowblade/releases
* Download  flowblade-2.8.0.2-1_all.deb 
* Open the deb with "Software Install" (aka GNOME Software)
* I am using Xubuntu 22.04.01 LTS, but i very much suspect this is true for all versions

**Expected Result**
* the install page shows that the software package is OSS with **GPL license** (as per https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/copyrights )

**Actual Observed Result**
* the install page shows that the software package has a **proprietary license**

![flowblade_proprietary](https://user-images.githubusercontent.com/16333258/202696093-b72c283f-6716-4181-92e6-4600844eba4e.png)

**Comment by alexmyczko** [comment]
So it's a bug in GNOME software, please report it there, not here?

**Comment by jliljebl** [comment]
Thanks, for the info. I'll look into this after 2.10 release coming in a few weeks, and maybe try to find out who to communicate about this, but this just some bad info provided by Gnome Software.

**Comment by alexmyczko** [comment]
@jliljebl you're not on irc or element by chance?
