### ISSUE TITLE
Get AttributeError Can't get attribute Playlist (mlt) when loading project files saved with previous version of flowblade

### ISSUE THREAD

**Issue by oorail** [jliljebl/flowblade#1074]
Please include the following information.
1) Flowblade version (Help->About): 2.8 (latest source from Dec 4th 2022)
2) MLT version (Help->Runtime Environment):7.40
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 22.04 LTS
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Take a project saved with any previous version (I tried both 2.8.0.3 from Flatpak and Ubuntu, as well as files saved with older releases prior to 2020). Attempt to load it. Flowblade will sit there "unpickling" forever. In the cli you see:

AttributeError: Can't get attribute 'Playlist' on <module 'mlt' from '/usr/local/lib/python3.10/dist-packages/mlt/__init__.py'>

**Comment by jliljebl** [comment]
This is fixed in repo.
