### ISSUE TITLE
App crash after adding 3+ audio tracks, also (sometimes) while editing 4 tracks (1 vid + 3 aud)

### ISSUE THREAD

**Issue by edwin-fox** [jliljebl/flowblade#1075]
Flowblade v2.8
MLT v6.24.0
GTK v3.24.35

Linux Mint 19 Tara / MATE v1.20.1

It seems that Flowblade here crashes after adding a 4th audio track to the project (1 vid track), returning to the desktop screen... is there any crash log available?

**Comment by alexmyczko** [comment]
@edwin-fox mlt6 is pretty old. can you check if it's still a problem with recent flowblade + mlt7?

**Comment by jliljebl** [comment]
This does not reproduce here. After 2.10 Flatpak comes out in couple of weeks, please test and reopen if problem persists.
