### ISSUE TITLE
commit 19836610110448fe83f7cf90ad3bb852e208cb95 application launch error

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#1076]
...
MLT detection succeeded, 174 formats, 107 video codecs and 80 audio codecs found.
632 MLT services found.
Loading render profiles...
proxy encoding MPEG-2 Transport Stream NOT AVAILABLE.
Loading filters...
Loading transitions...
MLT transition region not found.
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
create_pattern_producer
G'MIC found
Player initialized with profile:  HD 1080p 30 fps
Traceback (most recent call last):
  File "./flowblade", line 93, in <module>
    app.main(modules_path)
  File "/home/rosa/flowblade-19836610110448fe83f7cf90ad3bb852e208cb95/flowblade-trunk/Flowblade/app.py", line 316, in main
    create_gui()
  File "/home/rosa/flowblade-19836610110448fe83f7cf90ad3bb852e208cb95/flowblade-trunk/Flowblade/app.py", line 499, in create_gui
    editor_window = editorwindow.EditorWindow()
  File "/home/rosa/flowblade-19836610110448fe83f7cf90ad3bb852e208cb95/flowblade-trunk/Flowblade/editorwindow.py", line 151, in __init__
    self._init_app_menu(self.ui)
  File "/home/rosa/flowblade-19836610110448fe83f7cf90ad3bb852e208cb95/flowblade-trunk/Flowblade/editorwindow.py", line 1143, in _init_app_menu
    self.ui.get_widget('/MenuBar/ProjectMenu/ContainerClipsMenu/CreateBlenderContainerItem').set_sensitive(False)
AttributeError: 'NoneType' object has no attribute 'set_sensitive'

**Comment by darkshram** [comment]
My fix to this issue in a standard installation from source code (no flatpak):

```
diff -Naur flowblade.orig/flowblade-trunk/Flowblade/editorwindow.py flowblade/flowblade-trunk/Flowblade/editorwindow.py
--- flowblade.orig/flowblade-trunk/Flowblade/editorwindow.py    2023-01-26 03:40:00.000000000 -0600
+++ flowblade/flowblade-trunk/Flowblade/editorwindow.py 2023-02-03 16:15:55.559697601 -0600
@@ -322,8 +322,6 @@
 
     def _init_gui_components(self):        
         # Disable Blender and G'Mic container clip menu items if not available.
-        if containerclip.blender_available() == False:
-            self.ui.get_widget('/MenuBar/ProjectMenu/ContainerClipsMenu/CreateBlenderContainerItem').set_sensitive(False)
         if gmic.gmic_available() == False:
             self.ui.get_widget('/MenuBar/ProjectMenu/ContainerClipsMenu/CreateGMicContainerItem').set_sensitive(False)
             
@@ -1141,8 +1139,6 @@
         # Hide Blender menu item for Flatpaks or if not available.
         if editorstate.app_running_from == editorstate.RUNNING_FROM_FLATPAK:
             self.ui.get_widget('/MenuBar/ProjectMenu/ContainerClipsMenu/CreateBlenderContainerItem').set_visible(False)
-        elif containerclip.blender_available() == False:
-            self.ui.get_widget('/MenuBar/ProjectMenu/ContainerClipsMenu/CreateBlenderContainerItem').set_sensitive(False)
         # Hide G'Mic if not available.
         if gmic.gmic_available() == False:
             self.ui.get_widget('/MenuBar/ProjectMenu/ContainerClipsMenu/CreateGMicContainerItem').set_sensitive(False)
```

**Comment by smolnp** [comment]
As a workaround, I added this removed line.
![Screenshot_20230206_080436](https://user-images.githubusercontent.com/26217756/216888436-b96d9a72-a3cf-46cc-9a2a-6648157848f7.png)
