### ISSUE TITLE
Flowblade crashes when doing any fades

### ISSUE THREAD

**Issue by tazman-nz** [jliljebl/flowblade#1079]
Running version 2.8 and have never had issues but recently tried to do a cross fade and the application crashed.  Tried to just fade out a video and it crashed.  Tried launching from commandline and it runs but the UI doesn't appear.

MLT V7.4.0, Ubuntu

I tried opening old projects but it just says, "unpicking" and never opens them.

**Comment by bpetrikovics** [comment]
Same here, getting a Segmentation fault whenever trying to create a fadeout.

**Comment by dickinsondd** [comment]
Same.  Flowblade 2.8 on Ubuntu 22.04.1 LTS.  Fade in, fade out or disolve all cause a segfault in libmlt-7.so.7.12.0, per syslog.

**Comment by decryptedchaos** [comment]
Same.  

Debian Bookworm  
Flowblade 2.8
MLT 7.12.0

This is 100% preventing me from adopting flowblade currently.   I'm having t default back to kdenlive  because of this.

**Comment by jliljebl** [comment]
The "Fade" transitions were removed because MLT removed the "region" transition from MLT 7.0.

Use the "Fade" filters instead.
