### ISSUE TITLE
No video displayed Fedora 37

### ISSUE THREAD

**Issue by Blueking-prime** [jliljebl/flowblade#1081]
Please include the following information.
1) Flowblade version (Help->About): Version 2.8
2) MLT version (Help->Runtime Environment): MLT Version 7.12.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Fedora 37
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: 
I can add video clips to the bin but I can't see them in the monitor
I can hear sound though
I checked through the issues and I found a similar situation happening with elementaryOS users a while back

**Comment by jliljebl** [comment]
I'll try to reproduce after 2.10. Maybe you could Flatpak version and if not please try and see if the issue remains, info would be useful?

**Comment by jliljebl** [comment]
No further updates on this, closing. If problems exist on Fedora systems, please try the Flatpak version first.

**Comment by jimav** [comment]
Same symptom here (can hear audio, but Clip Monitor is black).

At first it worked (with the same clip), but later fooling with other videos (in different .flb projects!) with different "profile"s (resolution, frame rate, etc.) I can no longer see the original landscape video when loaded into a new project.

This makes me think some persistent state (per user, not per project) changed which prevents rendering.   NOTE: fb does _not_ ask me if I want to switch my profile to match the file (as it once did when I first loaded a vertical-orientation video).

Using Flowblade 2.12.0.2 on Ubuntu
