### ISSUE TITLE
How can I fadeout text to 100% transparent?

### ISSUE THREAD

**Issue by NoTitleGamesOfficial** [jliljebl/flowblade#1082]
How can I fadeout text to 100% transparent?

I tried adding a alpha modification effect, together with a blend compositor but it does not work.

**Comment by smolnp** [comment]
Alpha -> Opacity
![Screenshot_20230106_185437](https://user-images.githubusercontent.com/26217756/211157551-d01a6dc7-b3a5-4c0b-9f3b-755aec88dc4a.png)

**Comment by smolnp** [comment]
This question is more relevant here: https://github.com/jliljebl/flowblade-forum/issues. Although, in modern realities, it seems to me, it is easier to create a chat in a telegram. It is convenient when all users receive notifications and answer questions according to their competence.

**Comment by jliljebl** [comment]
Closing, not an actionable issue.
