### ISSUE TITLE
Cannot install from .deb: 

### ISSUE THREAD

**Issue by dpitch40** [jliljebl/flowblade#1083]
Please include the following information.
1) Flowblade version (Help->About): 2.8.0.2-1
2) MLT version (Help->Runtime Environment): python-mlt version 6.6.0-1build1 installed
3) Your distribution (Ubuntu, Debian, Mint etc.): Linux Mint 19.3 Tricia
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: As previously described in [issue 997](https://github.com/jliljebl/flowblade/issues/997), the .deb installation does not work because it depends on the package `python3-mlt`, but this package is called `python-mlt` in my version of Linux. When I try to install the .deb, I get this output:

```$ sudo apt install '/data/Downloads/flowblade-2.8.0.2-1_all.deb' 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'flowblade' instead of '/data/Downloads/flowblade-2.8.0.2-1_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 flowblade : Depends: python3-mlt but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I was able to install it via flatpak, though the url `https://flathub.org/repo/appstream/io.github.jliljebl.Flowblade.flatpakref` seems to be returning a 404 error, but the .deb installation process is broken on my distribution.

**Comment by alexmyczko** [comment]
It works for me on Debian as well as Ubuntu. `apt install flowblade`

I don't have Mint, sorry...

**Comment by jep-fa** [comment]
It seems you have python-mlt installed instead of python3-mlt.

**Comment by jliljebl** [comment]
We have dropped providing *.deb* packages in the future and will only provide Flatpaks by the project, so this issue will not be resolved with new releases, sorry, closing.
