### ISSUE TITLE
Small resolutions (125px, 180px) result in graphical glitches

### ISSUE THREAD

**Issue by coffeehabit** [jliljebl/flowblade#1086]
Please include the following information.
1) Flowblade version (Help->About): 2.6.0
2) MLT version (Help->Runtime Environment): 6.24.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Debian
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Create a profile like this:
![125x125 at 15 frames per second](https://i.imgur.com/DPyYMqG.png)

And you get a preview render like this:
![45 degree slant](https://i.imgur.com/ozMdIj7.png)

Granted, the final output is fine, but it's impossible to work with for making GIFs or anything small in size.

Also if you do something like 125px or 180px, you get some pixels at the bottom which are black and permanent like this:
![](https://i.imgur.com/w2uObiV.png)

**Comment by jliljebl** [comment]
Thanks for the report. I created the 125x125 15fps Profile in my system and it worked just fine. When 2.10 comes out in a few weeks, please try that on Flatpak and report again if problem persists.
