### ISSUE TITLE
 Multi live audio channel recording

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jliljebl/flowblade#109]
```
I don't know if flowblade all ready has this but, flowblade could use Multi 
live audio channel recording support in the mixer and Multiaudio channel mixing.
```

Original issue reported on code.google.com by `sshe...@yahoo.com` on 7 Feb 2015 at 5:47

**Comment by jliljebl** [comment]
This is going wontfix. Flowblade can at best look to improve multichannel audio import and handling, but recording multichannel audio will not be on the agenda.
