### ISSUE TITLE
Flowblade opens any images and photos as a white screen.

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#1092]
1) Flowblade version: flowblade/commit/228550f0e73483e3a031d06a15c84368e2284d97
2) MLT found, version: 7.14.0
3) OS: ROSA Fresh Desktop 12.4
![flowbladebag](https://github.com/jliljebl/flowblade/assets/26217756/0dd99b4b-5762-4c73-b158-52acf17b2e12)

user@rosa2021 ~/user/flowblade-trunk $ ./flowblade
FLOWBLADE MOVIE EDITOR 2.10 alpha
---------------------------------
Launch script dir: /home/user/flowblade-trunk
Running from filesystem...
MLT found, version: 7.14.0

(flowblade:46236): Gtk-WARNING **: 11:36:42.946: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(flowblade:46236): Gtk-WARNING **: 11:36:42.946: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
numpy version: 1.21.2
Application version: 2.10.0
OS: ROSA Fresh Desktop 12.4
Python 3.8.13 (default, Aug 23 2022, 13:02:17) 
[GCC 11.2.0 20210728 (ROSA)]
GTK+ version: 3.24.34
XDG Config /home/user/.config/flowblade
XDG Data /home/user/.local/share/flowblade
XDG Cache /home/user/.cache/flowblade
Locale: ru_RU
Found translations at /home/user/flowblade-trunk/Flowblade/locale/, using those.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml

(flowblade:46236): Gtk-WARNING **: 11:36:44.598: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(flowblade:46236): Gtk-WARNING **: 11:36:44.598: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
Gtk version is 3.24.34, Flowblade theme is available.

(flowblade:46236): Gtk-WARNING **: 11:36:44.703: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(flowblade:46236): Gtk-WARNING **: 11:36:44.703: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
Using Full Screen size for layout: 1366 x 768
Small height: True
Small width: True
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - amv
  - apng
  - asv1
  - asv2
  - avrp
  - avui
  - ayuv
  - bmp
  - cfhd
  - cinepak
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - exr
  - ffv1
  - ffvhuff
  - fits
  - flashsv
  - flashsv2
  - flv
  - gif
  - h261
  - h263
  - h263p
  - huffyuv
  - jpeg2000
  - jpegls
  - ljpeg
  - magicyuv
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - msvideo1
  - pam
  - pbm
  - pcx
  - pfm
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - prores_aw
  - prores_ks
  - qtrle
  - r10k
  - r210
  - rawvideo
  - roqvideo
  - rpza
  - rv10
  - rv20
  - sgi
  - snow
  - speedhq
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v308
  - v408
  - v410
  - vc2
  - wrapped_avframe
  - wmv1
  - wmv2
  - xbm
  - xface
  - xwd
  - y41p
  - yuv4
  - zlib
  - zmbv
  - libaom-av1
  - libopenjpeg
  - libtheora
  - libvpx
  - libvpx-vp9
  - libx264
  - libx264rgb
  - libx265
  - libxvid
  - h263_v4l2m2m
  - h264_nvenc
  - h264_v4l2m2m
  - h264_vaapi
  - nvenc
  - nvenc_h264
  - nvenc_hevc
  - hevc_nvenc
  - hevc_v4l2m2m
  - hevc_vaapi
  - mjpeg_vaapi
  - mpeg2_vaapi
  - mpeg4_v4l2m2m
  - vp8_v4l2m2m
  - vp8_vaapi
  - vp9_vaapi
...
---
audio_codecs:
  - comfortnoise
  - s302m
  - aac
  - ac3
  - ac3_fixed
  - alac
  - aptx
  - aptx_hd
  - dca
  - eac3
  - flac
  - g723_1
  - mlp
  - mp2
  - mp2fixed
  - nellymoser
  - opus
  - real_144
  - sbc
  - sonic
  - sonicls
  - truehd
  - tta
  - wavpack
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_dvd
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s8_planar
  - pcm_s16be
  - pcm_s16be_planar
  - pcm_s16le
  - pcm_s16le_planar
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s24le_planar
  - pcm_s32be
  - pcm_s32le
  - pcm_s32le_planar
  - pcm_s64be
  - pcm_s64le
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - pcm_vidc
  - roq_dpcm
  - adpcm_adx
  - adpcm_argo
  - g722
  - g726
  - g726le
  - adpcm_ima_amv
  - adpcm_ima_alp
  - adpcm_ima_apm
  - adpcm_ima_qt
  - adpcm_ima_ssi
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libfdk_aac
  - libgsm
  - libgsm_ms
  - libmp3lame
  - libopencore_amrnb
  - libopus
  - libspeex
  - libvo_amrwbenc
  - libvorbis
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - alp
  - amr
  - amv
  - apm
  - apng
  - aptx
  - aptx_hd
  - argo_asf
  - asf
  - ass
  - ast
  - asf_stream
  - au
  - avi
  - avm2
  - avs2
  - bit
  - caf
  - cavsvideo
  - codec2
  - codec2raw
  - crc
  - dash
  - data
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffmetadata
  - fifo
  - fifo_test
  - filmstrip
  - fits
  - flac
  - flv
  - framecrc
  - framehash
  - framemd5
  - g722
  - g723_1
  - g726
  - g726le
  - gif
  - gsm
  - gxf
  - h261
  - h263
  - h264
  - hash
  - hds
  - hevc
  - hls
  - ico
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ircam
  - ismv
  - ivf
  - jacosub
  - kvag
  - latm
  - lrc
  - m4v
  - md5
  - matroska
  - matroska
  - microdvd
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - mxf_opatom
  - null
  - nut
  - oga
  - ogg
  - ogv
  - oma
  - opus
  - alaw
  - mulaw
  - vidc
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtp_mpegts
  - rtsp
  - sap
  - sbc
  - scc
  - film_cpk
  - segment
  - stream_segment,ssegment
  - singlejpeg
  - smjpeg
  - smoothstreaming
  - sox
  - spx
  - spdif
  - srt
  - streamhash
  - sup
  - swf
  - tee
  - 3g2
  - 3gp
  - mkvtimestamp_v2
  - truehd
  - tta
  - ttml
  - uncodedframecrc
  - vc1
  - vc1test
  - voc
  - w64
  - wav
  - webm
  - webm_dash_manifest
  - webm_chunk
  - webp
  - webvtt
  - wtv
  - wv
  - yuv4mpegpipe
  - alsa
  - fbdev
  - oss
  - pulse
  - sdl,sdl2
  - video4linux2,v4l2
...
MLT detection succeeded, 175 formats, 107 video codecs and 80 audio codecs found.
631 MLT services found.
Loading render profiles...
ffmpeg version 4.4.3 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11.2.0 (GCC) 20210728 (ROSA)
configuration: --prefix=/usr --enable-shared --libdir=/usr/lib64 --shlibdir=/usr/lib64 --incdir=/usr/include --disable-stripping --enable-libaom --enable-postproc --enable-gpl --enable-pthreads --enable-ladspa --enable-libbluray --enable-libtheora --enable-libvorbis --disable-encoder=vorbis --enable-libvpx --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-libxcb-shape --enable-runtime-cpudetect --enable-libfdk-aac --enable-libdc1394 --enable-librtmp --enable-libspeex --enable-libfreetype --enable-libgsm --enable-libcelt --enable-avresample --enable-version3 --enable-nonfree --enable-nvdec --enable-nvenc --disable-libopencv --enable-libopenjpeg --enable-libopus --enable-libsoxr --disable-libxavs --enable-libmodplug --enable-libmp3lame --enable-libass --enable-gnutls --enable-libcdio --enable-libpulse --enable-libv4l2 --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-version3 --enable-libx264 --enable-libx265 --enable-libvo-amrwbenc --enable-libxvid
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
['ffmpeg', '-version']
return code: 0
ffmpeg available
Loading filters...
Loading transitions...
MLT transition region not found.
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
Adding full track compositors
restacking compositors!
Adding full track compositors DONE
G'MIC found
Player initialized with profile:  HD 1080p 30 fps
Panel positioning feature not available, too small screen.
Selected color NOT detected
BG color detected
Create SDL1 consumer...
restacking compositors!
window resized FAILED
restacking compositors!
Player initialized with profile:  HD 1080p 30 fps
Create SDL1 consumer...
restacking compositors!
Deleting /home/user/.cache/flowblade/autosave/autosave_80b3e3dbd2d3660af54d1bb94b7c7913
Autosave started...
Saving project...
autosave load
GPU test results {'NVENC H.264 High Profile / .mp4': -11, 'NVENC HEVC Main10 Profile / .mp4': -11, 'VAAPI H.264 / .mp4': -11}
[swscaler @ 0x7f2a60874700] Warning: data is not aligned! This can lead to a speed loss
Saving project...

**Comment by jliljebl** [comment]
Closing as *unreproduced* as explanation above is the only thing I can think of to produce the results described here.
