### ISSUE TITLE
Bindigs problem with "module 'mlt7' has no attribute 'mlt_image_rgb24a'"

### ISSUE THREAD

**Issue by lupatch** [jliljebl/flowblade#1094]
flowblade 2.8.0.3-3
MLT 7.4.0
GTK 3.24.33
Missing MLT Services: [empty]
Ubuntu 22.04.2

Video: *.mts from a Canon Legria HF 200

It's not the first time to use the Rotomask, with Filter Blur and Compositer Blend. In the past, it works very fine. Yet, it crashes every time. By click on the button "Launch RotoMask editor" the windows open + a crash report. The screen in the RotoMask editor is grey and the time-cursor is fixed / unmovable.

> flowblade crashed with AttributeError in seek_and_get_rgb_frame(): module 'mlt7' has no attribute 'mlt_image_rgb24a'

**Comment by jliljebl** [comment]
Yeah, this is  mlt 7 bindings issue. I fixed it for manually Flatpak 2.10  it won't have this issue once it comes out. I need to get patch into MLT, and I changed the title so I remember do that.

**Comment by jliljebl** [comment]
This is fixed in MLT >= 7.18. Update MLT to fix Issue.
