### ISSUE TITLE
Generators dialog enhancements.

### ISSUE THREAD

**Issue by Disaster2life** [jliljebl/flowblade#1096]
1) Flowblade version (Help->About): 2.10
2) MLT version (Help->Runtime Environment): 7.17
3) Your distribution (Ubuntu, Debian, Mint etc.): Debian (Sid/Unstable)
4) Open "Add generator menu', use one of the text based generators, write a sentence longer than the text box can show at once, black "artefacts" appear at the very edge of the text window.

I recreated this twice, but now trying to take screenshots, I cannot, thought to mention it if others can reproduce this.

Also have a few suggestions relating to the menu:

- Shouldn't the text box fit to the window size instead of being an arbitrary-sized box?
- I think from a design perspective, the text input box shouldn't be part of the larger settings scroll bar, I think it should be independent with a scroll bar for a "settings panel" below it.
- Responsive menu, currently it doesn't scale at all but because of how many settings there are, think it would be a good idea if one could expand the menu, because currently it doesn't do much except make it look wonky.
- If the "settings" panel is a good idea, probably should split it up into like three panels, one for general positioning, one for Animation and movement, and one for all the background option.

I would love to contribute code myself, but I still don't know my way around the code to actually be able to sadly.

**Comment by jliljebl** [comment]
> Open "Add generator menu', use one of the text based generators, write a sentence longer than the text box can show at once, black "artefacts" appear at the very edge of the text window.

Ok, I don't see this one, screenshot might help to understand the issue. 

> Shouldn't the text box fit to the window size instead of being an arbitrary-sized box?

I made it fixed size, but it might be possible to make it fill all available space, and that would probably be an improvement. I'll see if there is away to do this.

>  I think from a design perspective, the text input box shouldn't be part of the larger settings scroll bar, I think it should be independent with a scroll bar for a "settings panel" below it.

This I think cannot be changed. All editors are part of the same pipeline all the way from their definition in the generator script,  and editors are created in a loop and placed in panal vertically one after another to be available for editing. Trying to special case the text box somehow is certainly possible but quite tedious to do.  

> Responsive menu, currently it doesn't scale at all but because of how many settings there are, think it would be a good idea if one could expand the menu, because currently it doesn't do much except make it look wonky.

This one I don't understand, you mean this menu:

![dialog_menu](https://github.com/jliljebl/flowblade/assets/1823444/0274b6a6-a01c-4014-b7d3-5008319b1dfb)


> If the "settings" panel is a good idea, probably should split it up into like three panels, one for general positioning, one for Animation and movement, and one for all the background option.

Well, if I add a generic solution to enable editors to be grouped in tabbed panels, then that would make edit panels smaller vertically. The "Multiline Animation" is admittedly a bit unwieldy right now.

This is not a bad idea, and I may implement it in the future, but probably not for next release.

**Comment by Disaster2life** [comment]
For the actual bug report, I think I might have been wrong about it being a proper "bug", I can't seem to recreate it now, but I think what happened was my mouse cursor was right on the larger scroll bar without be realising, and that caused the "strange black bar" 
![image](https://github.com/jliljebl/flowblade/assets/19931889/30c00b83-0999-47db-aaa5-62da01122d9c)

For the UI improvement proposals, I think it's hard for me to get them across because I don't know the proper wording, so I spent ~~way too long~~ some time creating a mock-up of what I meant, I didn't bother putting all the settings in the mock-up, but I think it gets the idea across?
![flowblade-design-idea](https://github.com/jliljebl/flowblade/assets/19931889/66b94782-fdb7-48dc-b6e6-6fe030c9a50e)
Hopefully this is sort of possible at least, think it would be way more user accessible and less unwieldy. 

Unsure if I should open a separate issue for this, but shouldn't the "preview" button be just part of the generator? As in, it automatically generates and updates itself after every few seconds of inputs, I don't think it would be that computationally intensive, and seems like what is the general philosophy in similar programs.

**Comment by jliljebl** [comment]
> Hopefully this is sort of possible at least, think it would be way more user accessible and less unwieldy.

The 3 tabs to divide up the editable parameters is doable, and would be an improvement on current situation. I may actually prefer to add group labels first, as that is much easier to do, and maybe add the possibility to interpret group labels as tabbed panels later. The internal data representation is the same for both.

The separate text box is not practical given the internal structure of the implementation.

> Unsure if I should open a separate issue for this, but shouldn't the "preview" button be just part of the generator? As in, it automatically generates and updates itself after every few seconds of inputs, I don't think it would be that computationally intensive, and seems like what is the general philosophy in similar programs.

This is true and feature will be added. Not having to explicitly ask for updates is better UX here.

**Comment by Disaster2life** [comment]
Grouping thing sounds like a good stop gap solution, hopefully it at least reduces the amount of options displayed at once. Hopefully it'll also help with the migration to the tabbed panels.

And that makes sense, I hope with the grouping / tabbed panels, it becomes unnecessary as the bigger scroll bar goes away.

And that's good to hear, hopefully better UX will make it more accessible to everyone, thanks!

**Comment by jliljebl** [comment]
For this Issue the following changes were done:

> Shouldn't the text box fit to the window size instead of being an arbitrary-sized box?

This is now changed, text boxes now takes all available size.

>  I think from a design perspective, the text input box shouldn't be part of the larger settings scroll bar, I think it should be independent with a scroll bar for a "settings panel" below it.

This was not done, didn't really fit the design approach or codebase.

> Responsive menu, currently it doesn't scale at all but because of how many settings there are, think it would be a good idea if one could expand the menu, because currently it doesn't do much except make it look wonky.

Edit areas now take all available space and look fine I think.

> If the "settings" panel is a good idea, probably should split it up into like three panels, one for general positioning, one for Animation and movement, and one for all the background option.

We now have editors grouped in three tabs in 'Multiline Animations' Generator,  which I believe was a nice improvement over the previous very long single column of editors.

> As in, it automatically generates and updates itself after every few seconds of inputs, I don't think it would be that ...

I'll do this for 2.12 or maybe 2.14 together with auto updates on *Gmic* editor tool and *Generator Script Editor* tool as I believe all these need to auto update to make UX consistant. 

But for now I'll close this Issue as *Fixed* as all the improvements I that believe can be done right are done and will be 2.12.
