### ISSUE TITLE
Perhaps reflecting minor version changes in RELEASE_NOTES.md ?

### ISSUE THREAD

**Issue by luzpaz** [jliljebl/flowblade#1106]
2.10.0.x version changes are not included in [RELEASE_NOTES.md](https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/RELEASE_NOTES.md). Would it be a lot to ask in order to make this happen. It helps downstream packagers to conveniently present this data to users.

**Comment by jliljebl** [comment]
Ok, I'll add when doing next session.

**Comment by jliljebl** [comment]
I updated release notes with info on hotfix releases.
