### ISSUE TITLE
Does Flowblade fallback if gmic and swh-plugins not installed?

### ISSUE THREAD

**Issue by bkauler** [jliljebl/flowblade#1107]
Hi guys,
I'm running the latest release of Flowblade, 2.10.0.4, without gmic and swh-plugins installed, and it seems to be working OK.

My question is, does Flowblade check if these are available at startup, then fallback gracefully to not using them if not available?

If Flowblade expects them to be there, then crashes if try to do something that needs them, then not so good.

I'm asking this because I'm running Flowblade in EasyOS 5.4.9, which has all the deps except not those two in its package repository.

**Comment by bkauler** [comment]
Ah, I have the answer to half of the question. Just discovered, there is a "G'MIC Tools" menu entry; selecting that says that not available, need to install gmic. Good.

OK, what about swh-plugins? Is the lack of this also automatically detected?

**Comment by jliljebl** [comment]
> OK, what about swh-plugins? Is the lack of this also automatically detected?

I  don't think there is anything else then them not showing up at various filter menus, or at *Help->Runtime Environenment ->MLT Filters* section. if swh-plugins are not present in system, then they are not added to available filters at application start, and won't available to be used when editing.

**Comment by jliljebl** [comment]
We have *Help->Runtime Environenment ->Missing MLT Services* section that will show all *ladspa.x* filters if they are not installed, forgot about that.

**Comment by bkauler** [comment]
Thanks for the feedback. Closing this issue.

Note, I'm planning to have Flowblade builtin in the next release of EasyOS. Posted about it to my blog:

https://bkhome.org/news/202308/the-return-of-flowblade.html
