### ISSUE TITLE
Feature request: cloning sequences

### ISSUE THREAD

**Issue by intelfisz** [jliljebl/flowblade#1108]
1. Flowblade version 2.10
2. MLT version 7.17.0
3. Ubuntu
4. Feature request description:
When creating a new sequence it should be possible to copy/clone it from another selected sequence. By this means one can reuse the work put into creating a sequence when working with a new one. Currently a new project would need to be created to achieve a similar effect. However, it may be beneficial for some workflows to maintain several (similar) sequences with some tweaks within the same project and decide on demand which one to render.

**Comment by jliljebl** [comment]
I think menu action *Sequence->Import Another Sequence Into This Sequence...* does what you want, right?

**Comment by intelfisz** [comment]
> I think menu action _Sequence->Import Another Sequence Into This Sequence..._ does what you want, right?

yes, it does indeed - thanks for pointing this out. I'm closing this request.
