### ISSUE TITLE
Fix: clone filters default behavior

### ISSUE THREAD

**Issue by intelfisz** [jliljebl/flowblade#1109]
1. Flowblade version 2.10
2. MLT version 7.17.0
3. Ubuntu
4. Description:
When selecting "Clone filters -> From Prev. Clip" the filters are only cloned if the previous clip is adjacent, i.e. if there is an empty space between the clips, no filters are cloned. I suppose the default behavior should be to clone the settings from the previous clip even if there is an empty space between them.

**Comment by jliljebl** [comment]
Agreed, will change behavior.

**Comment by jliljebl** [comment]
Change is now in repo, will be in 2.12.
