### ISSUE TITLE
Unable to open project, error "window resized FAILED"

### ISSUE THREAD

**Issue by Surfoo** [jliljebl/flowblade#1110]
Hello,

I created a projet yesterday, and this morning I can't open it and I have this error (in loop) in the terminal: `window resized FAILED`

Here the log: [flowblade_2.10.log](https://github.com/jliljebl/flowblade/files/12268895/flowblade_2.10.log)

I really want to recover the project, tell me if you want more informations in order to help you, thank you!

Informations: 
1) Flowblade version: 2.10
2) MLT version: 7.16.0
3) Your distribution: Manjaro
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening: I don't know.

**Comment by Surfoo** [comment]
OK, I found the problem. A part of my medias was on a NFS share, and this morning, it was umounting because my server was unavailable..

I cleaned the cache, how to recreate the thumbnails for all images at once ? When I select all medias, it's unselect when I pick "Recreate Icon"?

**Comment by jliljebl** [comment]
This seems solved, closing.
