### ISSUE TITLE
X forward: Monitor does not play

### ISSUE THREAD

**Issue by wolfgangr** [jliljebl/flowblade#1114]
The idea is to run flowblade on a **headless remote development playground**, where I can play with hardware, OS, libraries etc. without screwing my workstation.

Looks like I might have to setup audio forward?
Is it worth the hassle? Will it work then?
Does sbd work with flowblade on x forwarding?

----
**steps to reproduce:**

- installed from mint repo
- start flowblade  on the remote machine (from an **ssh console with x forward enabled**), 
- it comes smoothly up, I can add media, perform timeline editing, access menues, change themes.....

- However, the **monitor window is not oparating.**
- Neither for media preview, nor from the timeline.
- Neither the start button in the monitor nor the space bar in the preview succeed to start play.
- the monitor window is there, other widgets not related to "play" seem to work OK

A look at the console reveals broken audio connection.
A quick web search reveals that audio bypass for x forwarding is possible but tricky.

Is the missing audio the cause for inoperable monitor?

Part of the console messeages:

```
Launching io.github.jliljebl.Flowblade dbus service
Autosave started...
Saving project...
No user folders actions needed.
[consumer sdl] SDL failed to open audio: No available audio device
window resized FAILED
Player initialized with profile:  HD 1080p 30 fps
Create SDL1 consumer...
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
io.github.jliljebl.Flowblade dbus service already exists
Autosave started...
Saving project...
[consumer sdl] SDL failed to open audio: No available audio device
Saving project...
Saving project...
```

1) Flowblade version  2.8
2) MLT version : 7.4.0, GTK 3.24.33
3) Your distribution: 
remote = x-client = floblade host: Linux Mint 21.1 = ubuntu jammy
local = x-server = workstation: debian 10 buster

4) If possible, try to provide step-by-step instructions on how to reproduce the issue. 
see above

---------------
edit:

just stumbled across
https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/FAQ.md#wayland

`GDK_BACKEND=x11 flowblade`

tried this, did not change behaviour

**Comment by jliljebl** [comment]
This one is probably not fixable:
```
[consumer sdl] SDL failed to open audio: No available audio device
...
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
...
[consumer sdl] SDL failed to open audio: No available audio device
```

> Is the missing audio the cause for inoperable monitor?

Yes, I think so. 

We would need to devote some serious development time on current MLT video consumer to get this working, or maybe hack on age old SDL 1.2 lib to get some improvement, with very low probability of success, so I'm closing this one as *wontfix*.
