### ISSUE TITLE
flowblade 0.18.0 crashes during start on Linux Mint 13 Maya (Ubuntu 12.04)

### ISSUE THREAD

**Issue by dominikx** [jliljebl/flowblade#112]
Flowblade 0.18.0 crashes during start on Linux Mint 13 Maya (Ubuntu 12.04).
python-mlt3 0.7.6+git20120204-2 and frei0r-plugins 1.1.22git20091109-1.1ubuntu1 are installed.
Are there any suggestions how to get flowblade running?

Output is here:
https://github.com/dominikx/tmp/blob/master/flowblade.stdout
Strace is here
https://github.com/dominikx/tmp/blob/master/flowblade.strace.gz

**Comment by jliljebl** [comment]
Yeah, it does not even load filters. Unfortunately I don't think I can help here, MLT 0.7.6 is basically ancient and I don't think I can justify using time on trying to make current version work with outdated library.

You can try if some of the earlier versions work, see here: https://code.google.com/p/flowblade/downloads/list 

I'm marking this wontfix.
