### ISSUE TITLE
reconsider range log for timeline / sequence

### ISSUE THREAD

**Issue by wolfgangr** [jliljebl/flowblade#1121]
Dear jiljebl, 

here you say:
https://github.com/jliljebl/flowblade/issues/239#issuecomment-227159898

> Actually in my my view logging timeline ranges is nonsensical 

May I please disagree in all due form?

I am planning to produce videos from social events, where different media sources (multiple cameras, sound recorders, mobile clips, still images, documents...) are combined. My first idea for the workflow was to first sync all media to a common timeline, e.g. along a sound record for the whole event. Then I'd like to mark the time slices of interest, regardless of the media source.
Only in the next step, I'd decide on the best media source and maybe filter option (zoom/crop beeing the most important one) at any given time to produce final video footage from that time slice.

So I think range logging in timeline view might have some sense, acutally .... 
Yes, and individual clips might skd of "inherit" the marks from a synced timeline, I'd suppose.

So may I please ask to reconsider the issue for some future release?

---------

Please include the following information.
1) Flowblade version (Help->About): any until now
.....
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

- set monitor to timeline view
- mark a range in the timeline
- hit "log current marked range"

**Comment by jliljebl** [comment]
> Actually in my my view logging timeline ranges is nonsensical

The thinking here is that *Range Log* is named area of interest in *source media* defined by Mark In/Mark Out timecodes, and as such is immutable once defined. Area of interest in timeline if defined by Mark In/Mark Out timecodes is subject to changes as user does more edits.

Anyway, I believe there already exists workflow that does what you want.

1.  ...first sync all media to a common timeline, e.g. along a sound record for the whole event....
2. From application menu *Project->Create Container Clip...->From current Sequence*. This creates an immutable MLT XML clip of current state of timeline.
3.  Now you can create *Range Log* items from that clip.

Alternatively:

1. Render timeline with Range set as "Marked Range" and make sure to use lossless rendering to not lose any quality. 

*Range Log* in Flowblade really is defined as log of In/Out ranges with interesting content in source media. The intention of the feature is to help user find and remember the useful stuff when the amount of material gets large.

**Comment by jliljebl** [comment]
I added an info dialog directing user to use *Timeline Markers* functionality when they try to log a range on Timeline, but otherwise I will keep the functionality as-is.
