### ISSUE TITLE
Clip stabilizing

### ISSUE THREAD

**Issue by jliljebl** [jliljebl/flowblade#1126]
There has been some developments in MLT regarding clip stabilizing and we might be able to get this in now, so I'll and this into feature queue.

**Comment by Disaster2life** [comment]
Could you link to these developments? Sounds really cool, would love to see how it works under the hood, cursory research got me nowhere.

**Comment by jliljebl** [comment]
They removed the old video stabilising module *videostab* and have a new one *vidstab*.

From 7.0 release notes:
```
Removed deprecated modules:

    dv
    gtk2 (not gdk)
    kino
    linsys
    lumas
    motion_est
    swfdec
    videostab  <- This one. 
```

Last time I tried a long time ago I used the  *videostab* that didn't work, maybe the new *vidstab* module works better.

**Comment by jliljebl** [comment]
This is now in and will be release 2.16.
