### ISSUE TITLE
Groups not showing

### ISSUE THREAD

**Issue by cassiel74** [jliljebl/flowblade#113]
I have this project with 9 sequences and a dozen clips, I have used ranges to create sub-clips and groups to keep them organized but now I can't see groups anymore.
They disappered from menù (which show always "All items") but the select doesn't work even if groups are there ("Move selected objects to group" menu item correctly shows up the group list).

Running Flowblade 0.18 on debian jessie (tried with Xfce and awesome DE)

**Comment by jliljebl** [comment]
Could you run flowblade in terminal and post the output here. Just open terminal and give command 'flowblade'.

**Comment by cassiel74** [comment]
Here follows.

rmorelli@debian:~$ flowblade 
FLOWBLADE MOVIE EDITOR 0.18
---------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 0.9.2
OS: Debian GNU/Linux 8 (jessie)
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2]
GTK+ version: (2, 24, 25)
Locale: en_US
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - amv
  - asv1
  - asv2
  - avrp
  - avui
  - ayuv
  - bmp
  - cinepak
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - flashsv
  - flashsv2
  - flv
  - gif
  - h261
  - h263
  - h263p
  - huffyuv
  - jpeg2000
  - jpegls
  - ljpeg
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - msvideo1
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - prores_aw
  - prores_ks
  - qtrle
  - r10k
  - r210
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - snow
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v308
  - v408
  - v410
  - wmv1
  - wmv2
  - xbm
  - xface
  - xwd
  - y41p
  - yuv4
  - zlib
  - zmbv
  - libopenjpeg
  - libtheora
  - libvpx
  - libvpx-vp9
  - libx264
  - libx264rgb
  - libx265
  - libxvid
...
---
audio_codecs:
  - comfortnoise
  - s302m
  - aac
  - ac3
  - ac3_fixed
  - alac
  - dca
  - eac3
  - flac
  - g723_1
  - mp2
  - mp2fixed
  - nellymoser
  - real_144
  - sonic
  - sonicls
  - tta
  - vorbis
  - wavpack
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s8_planar
  - pcm_s16be
  - pcm_s16be_planar
  - pcm_s16le
  - pcm_s16le_planar
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s24le_planar
  - pcm_s32be
  - pcm_s32le
  - pcm_s32le_planar
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libfaac
  - libfdk_aac
  - libgsm
  - libgsm_ms
  - libmp3lame
  - libopencore_amrnb
  - libopus
  - libspeex
  - libvo_aacenc
  - libvo_amrwbenc
  - libvorbis
  - libaacplus
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - asf
  - ass
  - ast
  - asf_stream
  - au
  - avi
  - avm2
  - bit
  - caf
  - cavsvideo
  - crc
  - data
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffm
  - ffmetadata
  - filmstrip
  - flac
  - flv
  - framecrc
  - framemd5
  - g722
  - g723_1
  - gif
  - gxf
  - h261
  - h263
  - h264
  - hds
  - hevc
  - hls
  - ico
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ircam
  - ismv
  - ivf
  - jacosub
  - latm
  - lrc
  - m4v
  - md5
  - matroska
  - matroska
  - microdvd
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - null
  - nut
  - oga
  - ogg
  - oma
  - opus
  - alaw
  - mulaw
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtsp
  - sap
  - segment
  - stream_segment,ssegment
  - smjpeg
  - smoothstreaming
  - sox
  - spx
  - spdif
  - srt
  - swf
  - tee
  - 3g2
  - 3gp
  - mkvtimestamp_v2
  - truehd
  - uncodedframecrc
  - vc1
  - vc1test
  - voc
  - w64
  - wav
  - webm
  - webm_dash_manifest
  - webvtt
  - wtv
  - wv
  - yuv4mpegpipe
...
MLT detection succeeded, 136 formats, 80 video codecs and 68 audio codecs found.
350 MLT services found.
Loading render profiles...
Proxy encoding MPEG-4 Preset Ultrafast ...available
Proxy encoding MPEG-2 Transport Stream ...available
Loading filters...
MLT service lumakey not found.
Brightness dropped, MLT version too low for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
Player initialized with profile:  DV/DVD PAL
maximize
Autosave started...
Save project autosave_04a9cf9fb9baded96f71d2b7b8b4b7ad

**Comment by jliljebl** [comment]
From the print out It seems that you only started the application, but didn't perform action that displays the bug. At least it seems that no project was loaded. I probably should have given more detailed instructions.

So what I want is:
1) start flowblade on terminal
2) load the project with missing groups
3) do the action that causes the bug to happen, which I think was trying to select the group
4) do some other actions too, try to create group and and move log items into it 
5) hopefully now the program prints some errors into terminal, and that is the interesting part that should help fix this

It is also useful information if nothing is printed, so please inform on that outcome too. Also, if you already did this and got nothing, please tell that too.

**Comment by cassiel74** [comment]
Ok, did it (load, click the dropdown, etc...) and groups show up when I create a new one, ie the select dropdown in populated but they did not if I try to move sub-clips to an existing one.

No relevant output is added though.

rmorelli@vaio:~$ flowblade 
FLOWBLADE MOVIE EDITOR 0.18
---------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT found, version: 0.9.2
OS: Debian GNU/Linux 8 (jessie)
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2]
GTK+ version: (2, 24, 25)
Locale: it_IT
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - asv1
  - asv2
  - bmp
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - flashsv
  - flv
  - gif
  - h261
  - h263
  - h263p
  - huffyuv
  - jpegls
  - ljpeg
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - qtrle
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v410
  - wmv1
  - wmv2
  - xbm
  - xwd
  - zlib
  - zmbv
  - libopenjpeg
  - libschroedinger
  - libtheora
  - libvpx
  - libvpx-vp9
  - libx264
  - libxvid
...
---
audio_codecs:
  - comfortnoise
  - aac
  - ac3
  - ac3_fixed
  - alac
  - eac3
  - flac
  - mp2
  - nellymoser
  - real_144
  - vorbis
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s16be
  - pcm_s16le
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s32be
  - pcm_s32le
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libgsm
  - libgsm_ms
  - libmp3lame
  - libopus
  - libspeex
  - libvorbis
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - asf
  - ass
  - asf_stream
  - au
  - avi
  - avm2
  - cavsvideo
  - crc
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffmetadata
  - filmstrip
  - flac
  - flv
  - framecrc
  - framemd5
  - g722
  - gif
  - gxf
  - h261
  - h263
  - h264
  - hds
  - hevc
  - hls
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ismv
  - ivf
  - latm
  - m4v
  - md5
  - matroska
  - matroska
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - null
  - nut
  - ogg
  - oma
  - alaw
  - mulaw
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtsp
  - sap
  - segment
  - smjpeg
  - smoothstreaming
  - sox
  - spdif
  - srt
  - swf
  - 3g2
  - 3gp
  - truehd
  - rcv
  - voc
  - wav
  - webm
  - wv
  - yuv4mpegpipe
  - alsa
  - oss
...
MLT detection succeeded, 115 formats, 61 video codecs and 49 audio codecs found.
338 MLT services found.
Loading render profiles...
Proxy encoding MPEG-4 Preset Ultrafast ...available
Proxy encoding MPEG-2 Transport Stream ...available
Loading filters...
MLT service lumakey not found.
Brightness dropped, MLT version too low for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
Player initialized with profile:  HD 720p 25 fps
maximize
Autosave started...
Save project autosave_aa3cd1ec9f895385bf02966eee9a8e5b
Loading corto.flb, SAVEFILE_VERSION: 5
[wav @ 0x7f71800fef40] max_analyze_duration 5000000 reached
[wav @ 0x7f71800ff880] max_analyze_duration 5000000 reached
Player initialized with profile:  DV/DVD PAL
Autosave started...
Save project autosave_aa3cd1ec9f895385bf02966eee9a8e5b
Save project autosave_aa3cd1ec9f895385bf02966eee9a8e5b
Save project corto.flb
Save project corto.flb
Exiting app...

**Comment by cassiel74** [comment]
Forgot to say that sub-clips are ~30 if it's worth knowing

**Comment by jliljebl** [comment]
Okay, thanks, I'll have to try to reproduce this manually.

**Comment by cassiel74** [comment]
I was creating ranges and the dropdown worked well, I "suspect" that the problem is somewhat related to the increasing number of groups (13 in my case)...
just my 0.02€

**Comment by jliljebl** [comment]
I fixed 4 bugs in the code and everything seems to be working.

You can see if this fixes your issues by testing the repository version, see here: https://github.com/jliljebl/flowblade#installing-using-development-repository-version

The repository version prints "FLOWBLADE MOVIE EDITOR rc1 for 1.0" as version on start-up

**Comment by cassiel74** [comment]
I'll give it a try ASAP and give you some feedback

**Comment by cassiel74** [comment]
bug fixed!

**Comment by jliljebl** [comment]
Commenting after close
