### ISSUE TITLE
Can not stretch graphics clips over 14999 frames, no reason to have a limit.

### ISSUE THREAD

**Issue by gegoxaren** [jliljebl/flowblade#1132]
Please include the following information.
1) Flowblade version (Help->About):
2.10

2) MLT version (Help->Runtime Environment):
7.17.0

3) Your distribution (Ubuntu, Debian, Mint etc.):
Flatpak.

4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easiest way to understand what is happening.:

     1) Add clip.
     2) try to stretch it to match an audio clip of set length
     3) can not cover full length

As the new 2.10 has changed how effects work, I can not use the old method of adding the graphics multiple times and have one effect over the all "clips", meaning I can't make it seamless easily, as I need to scroll the graphics over the whole time using the Position/Scale filter.

I do not see the reason for having a limit.

5) Workaround:
create sequence and use that as a clip.

**Comment by jliljebl** [comment]
Yeah, this has been an MLT restriction and every now and then I've   tested if it has been removed. I'll improve here if possible for 2.14, 2.12 is now in testing and feature lockdown mode.

**Comment by jliljebl** [comment]
Current MLT just required to set length property to get arbitrarily long graphics clips. This is now done and in repo.  

Users can now drag clips ends to make graphics clips as long as wished. Starts can only be dragged to frame 0, only about 7200 frames from when using default grphics clip length, but users will 98% drag clips ends to make them longer, so this should not cause much problems.
