### ISSUE TITLE
Packaging flowblade for pip

### ISSUE THREAD

**Issue by icedwater** [jliljebl/flowblade#1133]
Is there anyone who is able to package flowblade so that it can be installed using `pip install flowblade`? I'm not sure what is needed to do so, but I wouldn't mind exploring this. If someone already has experience in this regard, however, could we work together?

**Comment by jliljebl** [comment]
HI, this will be quite difficult and probably cannot be made to work on Windows or MacOS. You can look at Flatpak build file to get list of the required dependencies. https://github.com/flathub/io.github.jliljebl.Flowblade/blob/master/io.github.jliljebl.Flowblade.yaml

From the project side I'm currently only providing Flatpak as packaging. I also dropped the .deb packages lately and wont expand the release surface for the time being.

**Comment by jliljebl** [comment]
Closing this as 'wonfix'.  Flatpak packaging is currently the only I'm willing to do from the project side, and distros do their own packaging. I don't believe that pip would bring much additional value or increase availability for the application.
