### ISSUE TITLE
Generators not lasting the duration of the clip

### ISSUE THREAD

**Issue by brenton** [jliljebl/flowblade#1137]
Please include the following information.
1) Flowblade version (Help->About):
2.12

2) MLT version (Help->Runtime Environment):
7.20.0

3) Your distribution (Ubuntu, Debian, Mint etc.):
Fedora

4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easiest way to understand what is happening.:

This could easily be my own misunderstanding, but I'm having a problem where text animations in my generators are showing a "sliding in" transition multiple times.  For example, I have a 4 line text that should display over an image for about 10 seconds.  After 8 seconds or so the text slides out and slides back in.  Instead I want is to only slide in once and then slide out in 10 seconds.  What am I doing wrong?

The documentation mentions "Use Generator Length spin button to set generator maximum length."  This sounds like what I want, but I can't find the Generator Length spin button.

**Comment by jliljebl** [comment]
> After 8 seconds or so the text slides out and slides back in. Instead I want is to only slide in once and then slide out in 10 seconds. What am I doing wrong?

Nothing, there is a bug here. The Generator length button does affect text animation correctly.

For the time being you can fix this by using two generators, use start from one and end from another.

**Comment by brenton** [comment]
Thanks for your quick response, @jliljebl . In my case I might just use a static image for my text.  I like where the text animation functionality is going though.

**Comment by lfinston** [comment]
Another possibility would be to do the text animations separately and composite them with your images, either outside Flowblade or within it.  So far, I've always done it outside.  I use GNU 3DLDF together with MetaPost and TeX for text effects, but MetaPost alone or even TeX alone would work for effects that don't require 3D.  It should also be possible with other graphics programs, e.g., GIMP, but I don't have any experience doing that.

With MetaPost (with or without 3DLDF), you can either use PNG output, specify rgba as the color model and make the background transparent, or use a particular color for the background and change it to being transparent, e.g., with ImageMagick or GIMP.  You can then use either of these programs to composite the images with the text with the background images.

**Comment by lfinston** [comment]
In case this is of interest to you, these are two examples with a similar kind of effect:

This one actually has some "sliding".  The motion is meant to look a little jerky.  It could easily be made smoother by adding in-betweens: 
https://www.youtube.com/watch?v=w58wundSwp4

This one has a changing background:
https://www.youtube.com/watch?v=cnBXeot1Kbs

There are quite a few others.

**Comment by jliljebl** [comment]
Ok, this is fixed in repo now. I also created a new hotfix release 2.12.0.2 for the fix, and created a new Flatpak release 2.12.0.2 which will be available once Flathub updates with the new version.
