### ISSUE TITLE
RotoMaskEditor does not show a preview of the underlying video

### ISSUE THREAD

**Issue by SimonScholz** [jliljebl/flowblade#1138]
Please include the following information.
1) Flowblade version (Help->About): 2.12 (currently latest version)
2) MLT version (Help->Runtime Environment): 7.4.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 22.04.3 LTS
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

I tried to follow this tutorial https://www.youtube.com/watch?v=A5FUQh9vODg&t=143s on how to blur certain areas of a Video.

1. Add *.mkv video to media (formerly recorded using OBS Studio)
2. Copy Video to V1
3. Copy Video to V2
4. Add Blur Filter to V2
5. Change Composition from `Standard Full Track` to  `Compositors free move`
6. Right click V2 and select `Add Compositor > Blend`
7. Right click V2 and click `Add Filter > Alpha > Roto Mask`
8. Then press the `Launch RotoMask editor` button
9. `RotoMaskEditor` Dialog appears and is grayed out, as you can see in the Screenshot
10. I can still create a mask on the gray area an can see the change in the regular preview, but my expected behavior would be to see the preview in the dialog as well instead of the gray area.

![image](https://github.com/jliljebl/flowblade/assets/7559962/139ef3a6-3890-42c7-af19-8e551795c7f7)

**Comment by SimonScholz** [comment]
The same problem seems to be with version 2.8 of Flowblade.

But the funny thing is that, as I said earlier, the blur effect is actually being applied.
But it is kind of hard to guess where to put the mask onto that gray area. ;)

![image](https://github.com/jliljebl/flowblade/assets/7559962/bda4e0f6-d7c6-4172-b02b-1e0a385a3f9a)

**Comment by jliljebl** [comment]
> MLT version (Help->Runtime Environment): 7.4.0

This issue was fixed in MLT 7.14, from release notes:

> Fixed SWIG python shadow functions for mlt7.

You can use Flatpak version of 2.12 that has this issue fixed.

**Comment by SimonScholz** [comment]
Thanks @jliljebl ,
with Flatpak it works for me.
This means that the current Ubuntu apt package is kind of broken, at least in terms of the RotoMaskEditor.
