### ISSUE TITLE
Discussion: Make RELEASE_NOTES.md more parser friendly for downstream packagers/maintainers

### ISSUE THREAD

**Issue by luzpaz** [jliljebl/flowblade#1139]
Currently [RELEASE_NOTES.md](https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/RELEASE_NOTES.md) looks like this:
![Screenshot_20231230_093921](https://github.com/jliljebl/flowblade/assets/4140247/c8f09bd3-e2c7-491e-bfdf-8771bda26f93)

The order of minor releases are not listed as most recent first but under the major release. This makes it difficult to parse the file to get the latest version of flowblade. Would you consider restructuring the file ?

**Comment by jliljebl** [comment]
Ok, I did a change in the release notes doc. I believe it is now presented as wished, right?

**Comment by luzpaz** [comment]
Fixed in ebc7e24

**Comment by luzpaz** [comment]
Just one issue... from a parser approach we have 

```shell
/ ## FLOWBLADE ([\d.]+)/   # for major issues 
/ \*\*Flowblade ([\d.]+)/  # for minor issues
```

Would you consider just keeping one style for all releases ?

**Comment by jliljebl** [comment]
Changed all releases to use the same Markdown title, looks ok.

**Comment by luzpaz** [comment]
thank you!
