### ISSUE TITLE
re: Better Clip Colours

### ISSUE THREAD

**Issue by Disaster2life** [jliljebl/flowblade#1141]
This is regarding the previous issue I opened up regarding the clip colour options available, I sadly still don't like them, though I think more so it has to do with how all the colours are not shaded the same way? I am not sure if that makes sense, but I am attaching an example ![image showing two clips, a blue one atop a purple one](https://github.com/jliljebl/flowblade/assets/19931889/038af809-d0f2-41fe-a7b3-5e1bd4f70cea), I think olive and brown look nice, though the red is super bright, and all of them except the default purple has a different shading, I am sorry for pestering again about this.

**Comment by jliljebl** [comment]
> though I think more so it has to do with how all the colours are not shaded the same way

This is true, the user selectable colors don't have gradients like default colors.

> I think olive and brown look nice, though the red is super bright, and all of them except the default purple has a different shading, I am sorry for pestering again about this.

I want to keep some options for users to create super noticeable clips that really pop out, but I do think we have some opportunities for improvement here, like adding the gradients to selectable colors or changing some colors. I'll do a session on this towards the end of cycle, I'm just re-activating after a bit of a mid-winter lull.

**Comment by Disaster2life** [comment]
> This is true, the user selectable colors don't have gradients like default colors.
I see that makes sense why they looked off to me

> I want to keep some options for users to create super noticeable clips that really pop out, but I do think we have some opportunities for improvement here, like adding the gradients to selectable colors or changing some colors.
I agree with the sentiment, but I agree, hopefully this'll be easy enough, and hope you enjoyed your time off!

**Comment by jliljebl** [comment]
Pushed the fix for this and the clips look much nicer now. Not many features coming before next release, but we're still at least a few weeks off from 2.14 release.
