### ISSUE TITLE
Flathub? what?

### ISSUE THREAD

**Issue by vmajor** [jliljebl/flowblade#1148]
Instructions for installing flathub are all 404 so cannot even get to the starting line.

**Comment by vmajor** [comment]
For anyone searching on how to install Flowblade, do this instead:

```
git clone https://github.com/jliljebl/flowblade.git
cd flowblade/flowblade-trunk
python setup.py build
python setup.py install
```
then run it from the local directory with `./flowblade`

or start it with the suggested prefix `SDL12COMPAT_NO_QUIT_VIDEO=1 GDK_BACKEND=x11 SDL_VIDEODRIVER=x11 ./flowblade`

**Comment by jliljebl** [comment]
Which instructions are unavailable, links seems to be okay here: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md

**Comment by jliljebl** [comment]
I'll look at Flatpak related links and look for fixes. I can't recommend install using *setup.py*  as then I would on hook for making sure it works but I'll maybe add a mention that it has been observed to work.
