### ISSUE TITLE
Better Error Handling?

### ISSUE THREAD

**Issue by robog-two** [jliljebl/flowblade#1151]
Hi, I experienced a crash earlier, and I actually am not sure what caused it, but I was just noticing the relatively high number of crash reports. Given that this app is not security-critical and it's written in python, is it possible to handle errors nicer than crashing? For example, if there is an issue applying an effect, perhaps it should alert the user that it failed to apply with error details, or if there is an issue importing a file, it skips importing that file with an error dialog? I think sort of sectioning-off different pieces of the program with try-catch blocks would be a good idea for the stability of the application over all.

I would love to submit a PR for this but I really don't know where to start and my Python skills are mediocre at best. If this is a misunderstanding of how the program works or makes some false assumptions, feel free to reject and close.

Best,
        Sam

**Comment by jliljebl** [comment]
There isn't a way to make the application usefully recover from crashes using Python *try/except* method. 

Most crashes are on the C-side of the application and are unrecoverable segfaults, and if crashes are purely on the Python side, then the backtraces produced by crashes are extremely useful, and we very likely would not be able to continue running.

Closing as 'wontfix'.
