### ISSUE TITLE
"Large set of user configurable" [what] in README

### ISSUE THREAD

**Issue by dandv** [jliljebl/flowblade#1152]
Last item under Editing at https://github.com/jliljebl/flowblade?tab=readme-ov-file#features-overview

**Comment by Disaster2life** [comment]
Think a few things in the README needs to be updated actually, If I get time soon enough (highly likely), I'll hopefully open a merge request with the whole document a bit more stylied

**Comment by jliljebl** [comment]
Thanks, I'll fix the problem in README. @Disaster2life Ok, I'll certainly merge all improvements to README, it is quite simple and boring as is.
