### ISSUE TITLE
Possible missing python-libusb1 dependency 

### ISSUE THREAD

**Issue by xylphii** [jliljebl/flowblade#1157]
FLOWBLADE MOVIE EDITOR 2.14
---------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/lib/python3.11/site-packages/Flowblade
MLT found, version: 7.22.0
Failed to import module app.py to launch Flowblade!
ERROR: No module named 'usb1'
Installation was assumed to be at: /usr/lib/python3.11/site-packages/Flowblade

I'm using artix, X11, and no desktop environment.
When installing flowblade from pacman using archlinux mirrors,  python-libusb1 had to be installed manually otherwise I got the above error. Unsure if this was because of an issue with the installation process or missing dependencies in pacman, so I'm sorry if this isn't the correct place to report this

**Comment by jliljebl** [comment]
Yes, *python-libusb1* is needed now after support for USB shuttle devices was added. 

> Unsure if this was because of an issue with the installation process or missing dependencies in pacman, so I'm sorry if this isn't the correct place to report this

No problem, I think *missing dependencies in pacman* is exactly the right description of the issue, so to get this fixed a report to artix packagers would be thing to do. Closing as *distro issue*.
