### ISSUE TITLE
"Motion Tracking Create" not working

### ISSUE THREAD

**Issue by Disaster2life** [jliljebl/flowblade#1162]
Please include the following information.
1) Flowblade version (Help->About): 2.16
2) MLT version (Help->Runtime Environment): 7.23.0
3) Your distribution and desktop environment(Ubuntu/Unity, Debian/KDE, Mint/Cinnamon etc.): Debian Unstable/Gnome 44.9
4) X11 or Wayland: Wayland
5) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easiest way to understand what is happening.:
- Imported Media
- Applied "Motion Tracking Create"
- Kept all the settings at default
- Render job stuck at 0%
I recreated this from the terminal and got these error messages
```
Traceback (most recent call last):
  File "/app/share/flowblade/Flowblade/launch/flowbladetrackingheadless", line 43, in <module>
    trackingheadless.main(modules_path, session_id, parent_folder, profile_desc, clip_path, write_file, data_file_path, step, algo, rect)
  File "/app/share/flowblade/Flowblade/tools/trackingheadless.py", line 62, in main
    ccrutils.prints_to_log_file("/home/janne/trackinglog")
  File "/app/share/flowblade/Flowblade/tools/ccrutils.py", line 282, in prints_to_log_file
    so = se = open(log_file, 'w', buffering=1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/janne/trackinglog'
```

**Comment by jliljebl** [comment]
Oh, Jeesus Christ what a silly bug, fix coming shortly.

**Comment by jliljebl** [comment]
Thanks for reporting this quickly, that was such a dumb-ass bug.
