### ISSUE TITLE
Filter: Position Scale - Size & Width display not correct in edit fields

### ISSUE THREAD

**Issue by TheKilroy** [jliljebl/flowblade#1169]
1) Flowblade version (Help->About): 2.16.3
2) MLT version (Help->Runtime Environment): 7.4.0
3) Your distribution and desktop environment(Ubuntu/Unity, Debian/KDE, Mint/Cinnamon etc.): Ubuntu 22.04 LTS
4) X11 or Wayland: X11

The Size & Width display in the edit fields is not correct when changing key frames. The graphical representation works fine. So I assume it is only an update problem when selecting the corresponding key frame. 

![grafik](https://github.com/user-attachments/assets/e8285147-4ec2-4941-befe-d3a7d67eab62)
![grafik](https://github.com/user-attachments/assets/07ae1b72-570b-4f8a-81b4-6599dfded6fa)

**Comment by jliljebl** [comment]
Confirmed, thanks.

**Comment by jliljebl** [comment]
Fixed in repo, fix will be available in 2.18.
