### ISSUE TITLE
German translation insufficient

### ISSUE THREAD

**Issue by Bene81** [jliljebl/flowblade#119]
German translation partially "sucks".
Things like "Estimated left" are translated in a way, that would mean something like "estimated left side" rather than "estimated time remaining". There are a few other examples that behave the same way. And some items are not translated at all. It seems like the localization was done without any application context.
I will go over the translation and provide partial improvements (where I see need or assume I can contribute to a better translation).

**Comment by jliljebl** [comment]
Ok, all improvements to translations are accepted. I have a document on creating and updating translations available here: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/CREATING_TRANSLATION.md

**Comment by jliljebl** [comment]
A new translation update was applied already in November 2015 so hopefully this is at least somewhat fixed. New Issues against translations can always be opened.
