### ISSUE TITLE
on Linux the language .mo files should be in /usr/share/locale

### ISSUE THREAD

**Issue by martinkg** [jliljebl/flowblade#125]
on LInux the language files .mo files should be moved to the right place /usr/share/locale

and the file permissons should be corrected
# Fix script-without-shebang erros in fedora-review
# Remove permission to execute in all files except files that have sheban.
find . -type f -executable | xargs chmod a-x
find . -type f | xargs grep -El '\#!/usr/bin/env' | xargs chmod a+x

**Comment by jliljebl** [comment]
Both points are correct, I'll fix this after GTK3 port branch is merged.

**Comment by jliljebl** [comment]
The two issues have been fixed as follows;

**Issue:  > on LInux the language files .mo files should be moved to the right place /usr/share/locale**

1) Now the program tries to detect translations from _/usr/share/locale_ FIRST if it detected that launch script was at _/usr/bin_, which is assumed to mean that application is being run from  

2) If no translations are found at  _/usr/share/locale_  then the project folder _.../locale_ is tried

3) When running from arbitrary place in file system it assumed that this is a development version and the the look-up arder is reversed, first  project folder _.../locale_, then   _/usr/share/locale_ 

4) Anyone making an OS package from this needs to make sure that  a) .mo files are available in _/usr/share/locale_  b) launch script is _/usr/bin/flowblade_

5) .po and .mo files remain in their places in the repository and should not be installed by an OS package that wants to install .mo files in  _/usr/share/locale_ 

**Issue: Remove permission to execute in all files except files that have shebang.**

find . -type f -executable now returns:

./flowblade-trunk/flowblade
./flowblade-trunk/setup.py
./flowblade-trunk/Flowblade/locale/create_pot
./flowblade-trunk/Flowblade/locale/add_language
./flowblade-trunk/Flowblade/locale/copy_to_usr
./flowblade-trunk/Flowblade/locale/compile_language
./flowblade-trunk/Flowblade/locale/upgrade_all
./flowblade-trunk/Flowblade/locale/update_language
./flowblade-trunk/Flowblade/launch/flowblademedialinker
./flowblade-trunk/Flowblade/launch/flowbladebatch
