### ISSUE TITLE
[Question] Timeline paradigm

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#126]
hi

first of all congrats on this great app, seems really fantastic. 

do you plan on changing how the timeline behaves, i am used to a workflow where i can place/move freely the clips in he timeline kind of like in kdenlive/shotcut/pitivi i thik the paradigm you are using is avid's right? do you have plans to change the behavior somewhere down the roadmap?  

thanks and cheers

**Comment by denjello** [comment]
This is possible.
![overwrite](https://cloud.githubusercontent.com/assets/6129121/8337125/65b56552-1aa9-11e5-963f-86e183ac8ada.png)

To the right of the timecode is a dropdown menu. (with the downward pointing triangle). Choose overwrite and then you can drag as you like!!!

**Comment by faridosc** [comment]
get out!!! 

thanks so much. i am going to try it for my next project. 

cheers
