### ISSUE TITLE
Where can we post the videos we have made with flowblade?

### ISSUE THREAD

**Issue by denjello** [jliljebl/flowblade#127]
This isn't really a programming issue, but it is still relevant - I think.

I just finished a short film and was wondering if there is something like a showcase for films made with flowblade.

**Comment by jliljebl** [comment]
Send a link to YouTube/vimeo for the film and i'll add a page to github
after next release. I could put some of my test edits too. I still need to
set up an actual website for flowblade but github move postponed it.
25.6.2015 12.34 "denjell" <notifications@github.com> kirjoitti:

**Comment by faridosc** [comment]
there is also a community in google plus called linux video:
https://plus.google.com/u/0/communities/111055643146614621084

@denjello please share your work and experience with flowblade since i am thinking of using it for a side project.

cheers

**Comment by denjello** [comment]
If you've ever used an NLE, you'll understand flowblade, because that is what it is. It uses the excellent MLT Framework, which is how I stumbled upon it. I enjoy producing video entirely from the command-line (ffmpeg + data-moshing + mlt + homegrown tools), but for complex visual effects and grading using a GUI is obviously pretty important. The interface is clean and pretty usable.

I think one thing that it does right that other softwares don't is the autosave feature: Once a minute flowblade autosaves a recovery file in case it crashes. Very nice.

One tip: Make sure to set your final render size when you create the project. Otherwise any scaling or positioning that you do will be borked should you decide later to give it a different scale or aspect.

**Comment by faridosc** [comment]
cheers
