### ISSUE TITLE
adding VideoJack support to flowblade

### ISSUE THREAD

**Issue by Reaper10** [jliljebl/flowblade#128]
Could you adding VideoJack support to flowblade? http://www.piksel.org/videojack
About VideoJack 
video extensions for the Jack audio server

VideoJack is a mechanism to route video signals betweenapplications running on the same computer. It enables users of "jackified" video processingsoftware to publish and receive video livestreams. The current proposal is based on an extended version of the Jack audio server. In the GNU/Linux audio developer community, the Jack server is kind of an informal standard for realtime audio data exchange. An improved Jack system with videowires tries to be the same in the videoworld.

Get involved

There is a mailing list for VideoJack issues.

Download

The current VideoJack source can bedownloaded from the subversion repository:
http://videojack.svn.sourceforge.net/viewvc/videojack/ 

 Checkout with the following command:
svn co https://videojack.svn.sourceforge.net/svnroot/videojack videojack 

 Older tarballs and some patched client applications are available here. 

Hosts

The following video applications support VideoJack.

LiVES - (Howto use videoJack with LiVES)

UniCap

Wiki info

VideoJack

VjackDev

Credits

The original VideoJack was designed by Martin Bayer at the Piksel05 meeting in Bergen, and has been further developed by Salsaman and others in an ongoing effort to bring it to a usable state 

Gisle Frøysland from BEK organised the Piksel meeting in Bergen and is now sponsoring the virtual home of the VideoJack project.

**Comment by denjello** [comment]
Is there some other repository than sourceforge? I don't trust them anymore. Furthermore, the source code at SF appears to have been last updated in 2008...

**Comment by denjello** [comment]
Additionally, I am not exactly sure how you would videojack into **flowblade** and why that would make sense. Can you explain your workflow?

**Comment by Reaper10** [comment]
better idea Addig Gstreem framework #129
