### ISSUE TITLE
Addig Gstreem framework

### ISSUE THREAD

**Issue by Reaper10** [jliljebl/flowblade#129]
Adding Gstreem framework would great for sending video to a DAW software for scoring or voice over.
http://gstreamer.freedesktop.org/

**Comment by denjello** [comment]
Again, nice idea, but I think a clear explanation of your workflow would help us understand exactly what you want. Can you provide examples of other software that has this functionality?

**Comment by Reaper10** [comment]
I'll work on it

**Comment by jliljebl** [comment]
This not in the scope of Flowblade project. It might be possible to create a MLT consumer that acts as a GStreamer source but it is highly unlikely that anyone is willing to work on this.
