### ISSUE TITLE
Could porting flowblade  qt some day help with more OS support?

### ISSUE THREAD

**Issue by Reaper10** [jliljebl/flowblade#133]
This is just  a question could flowblade being ported over to qt some day help with supporting windows and mac OSX? Sorry about bugging you guys about this OS support thing but I have tried video editors like yours that will work on windows and 	I didn't like them and yours looked like the easiest to learn how to use and it's going to have the features I want.

**Comment by denjello** [comment]
@Reaper10 > Why don't you just install linux? It would be faster than bugging people to rewrite software for your OS. Seriously. (And you'll have fewer viruses.)

Or you could use a live-cd version of something like Ubuntu that won't change your hard drive but still let you test it. Then you could install flowblade on the live system.

Or, you could just install VirtualBox and then install Linux and then installl Flowblade.

**Comment by Reaper10** [comment]
I like windows and understand it more

**Comment by denjello** [comment]
I totally understand - and hope you don't think I was being rude - but this project is Linux right now - I can't speak for @jliljebl but if you visit https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md you will see that there are no instructions for non-linux OS.

Indeed, you opened a different issue https://github.com/jliljebl/flowblade/issues/130 that @jliljebl closed because there are no plans to do this.

**Comment by Reaper10** [comment]
This is just  a question I was asking if it would help I know that @jliljebl closed  #130

**Comment by denjello** [comment]
Sorry, I think that this issue is the same as #130 and as @jliljebl  wrote, there seem to be no plans in the foreseeable future to either switch from GTK & python to QT & c++ or support other OS's. Sorry. You should probably close this issue.

**Comment by Reaper10** [comment]
https://www.youtube.com/watch?v=hFyszYbAJnM

**Comment by faridosc** [comment]
@Reaper10 , i can't speak for @jliljebl, but i can tell you one thing, if you want a qt based mlt video editor use shotcut. i personally think it is great that it is using gtk like many other great programs (gimp, inkscape, gnome, etc...) and mind you they work on osx and windows as well... maybe you could hire (or help find) a dev willing to build flowblade for windows/osx.

cheers

**Comment by faridosc** [comment]
This is what darktable devs have to say about providing windows builds which i think could apply to flowblade:

http://www.darktable.org/2015/07/why-dont-you-provide-a-windows-build/

**Comment by Reaper10** [comment]
I  did try shotcut and I didn't  like it, yours looked like the easiest to learn how to use and it's going to have the features I want. I know all this I've said I would love to help with a windows build but I don't know how to code at all I'm so sorry about that.  This app can stay with GTK & python just asking if QT would make the windows & mac ports easier.

**Comment by denjello** [comment]
@faridosc Awesome article.

**Comment by faridosc** [comment]
@Reaper10 don't give up... you can dual boot to gnu+linux by installing to linuxmint, these days besides gaming you can have a descent alternative to windows.

**Comment by denjello** [comment]
I learned back in the [1980's](https://youtu.be/JzjldPdpT7Q?t=34) that one chooses an operating system based upon the software that is needed to be run and then builds the hardware around that environment. Today this is still true. If you @Reaper10 like how flowblade appears, and agree with the rest of us that it is really great then you should install linux and try it out.

**Comment by jliljebl** [comment]
The Qt port is not going to happen, for the following reasons:

1) Flowblade is such a GUI code heavy application that porting to another toolkit would essentially mean rewriting and re-debugging the the whole application, and would take more than a year with current resources.

2) Porting is _both_ difficult and boring. Usually programming tasks are either one or the other.

3) MLT Qt applications already exist (Shotcut, KDEnlive), whereas Flowblade is the only active MLT GTK project (Openshot is either dead or in the middle or being ported to qt and different media framework, take your pick) 

4) The focus of the project is to create a great Linux video editor, porting to Windows is a secondary and will not be allowed to hinder the achievement of primary goal.
