### ISSUE TITLE
Easier translations!

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#134]
Let us make translations easier by using [Weblate](https://hosted.weblate.org/about/ ), a web based translation with tight git integration supporting wide range of file formats and makes it easy for translators to contribute.  I am willing to set it up and start translating a brazilian portuguese. 

What do you think? 

Cheers

**Comment by jliljebl** [comment]
I don't think that I'm willing to change the way translations are handled.

**Comment by faridosc** [comment]
too bad, the thing is i didn't manage to translate flowblade since the method explained doesn't work for me running archlinux. i do ask to rethink this and maybe give a look at transifex as well. (shotcut has been there for a little while and already has 17 languages added with 6 at 100%.) 

i believe the easier we make it for people to participate the bigger the community gets... but i guess that in the end it is your choice. 

cheers!

**Comment by jliljebl** [comment]
I looked at both transifex and Weblate and both seemed big, professional ...and complex. I'm only willing to add complex external dependencies for clear functionality gains.

BTW. more info on why the scripts didn't work on archlinux would be helpful. Did you install gettext utilities, those may not be installed by default on archlinux? After omething like "pacman -S gettext" they might work. Terminal output from a failed attempt to run my helper scripts would be useful.

**Comment by faridosc** [comment]
> I looked at both transifex and Weblate and both seemed big, professional ...and complex. I'm only willing to add complex external dependencies for clear functionality gains.

Big and professional yes, complex not really. Maybe other translators could help us out with this discussion. Some functionality gains is that it makes it possible for more people to collaborate to translations as well as for more people to collaborate and correct translations of the same language.

> BTW. more info on why the scripts didn't work on archlinux would be helpful. Did you install gettext utilities, those may not be installed by default on archlinux? After omething like "pacman -S gettext" they might work. Terminal output from a failed attempt to run my helper scripts would be useful.

my bad, actually after a second try i did manage to get it working, so no problem here. 

cheers

**Comment by Miniellipse** [comment]
I mus admit, there are for me as a german native speaker two groups of programs that are better held in english language. That are 3D-programs like blender and the video-editing-programs. There might be more examples but these two groups use much english words that are always used in publications and tutorials and make it hard to choose a menue-point in a translated version.

**Comment by faridosc** [comment]
@Miniellipse although i agree with you, we must understand that we are privileged to speak more than one language. i have worked in projects to break the digital divide and having a program (flowblade, blender, gimp, inkscape, etc...) in a local makes a big difference.

**Comment by ovari** [comment]
> i do ask to rethink this and maybe give a look at transifex as well

Please prefer [Hosted Weblate](https://hosted.weblate.org/).

> I looked at both transifex and Weblate and both seemed big, professional ...and complex.

Has Weblate's complexity reduces since 2015?

There are simple programs, like [Plots](https://flathub.org/apps/details/com.github.alexhuntley.Plots) that use [Hosted Weblate](https://hosted.weblate.org/projects/plots/plots/en/).

> I'm only willing to add complex external dependencies for clear functionality gains.

Hosting on Weblate will help people discover your program as well as translate it.

Is enabling more people to use your program in their native language a functionality gain?

Is enabling web-browser translations is a functionality gain for translators too?

Can this issue please be re-opened?

Thank you
