### ISSUE TITLE
Flowblade crashes when using two blends at a time

### ISSUE THREAD

**Issue by Miniellipse** [jliljebl/flowblade#135]
Put one png-file with alpha-channel to V3, one png to V2 and a color-clip to V1. Add a blend to PNG in V3 to blend with V2, add a blend to PNG in V2 to blend with the color clip in V1.
Wierd preview appears, sometimes direct crash.
. Save this file, restart flowblade. Flowblade crashes each time these blends should show up in preview. When the blends are at the start, loading the file crashes flowblade instantly.
Picture before adding second blend.
![flowbladeblend](https://cloud.githubusercontent.com/assets/13347618/8695998/281f32e0-2ae9-11e5-801b-21ffa57fde1f.jpg)

**Comment by Miniellipse** [comment]
This happens in the old version, too.

**Comment by Miniellipse** [comment]
Update: The program crashes when using a Compositor-blend  where a color-clip is involved. No need to use two compositors as mentioned.

**Comment by denjello** [comment]
I think I have seen this too, what I did is I just created a .png and used that instead of color-clip. My solution was actually a mere work-around - so thanks for reporting it!

**Comment by jliljebl** [comment]
Haven't confirmed this yet, but this is probably too complex to fix while doing the GTK3 port which is the only thing being done for 1.2, so this was added for 1.4.

It would be useful to have information on: 1) Which version of Flowblade is used? 2) Which distro is used? 3) Which version of MLT is used? (Select "Help -> Runtime Environment" from menu for this info)

**Comment by Miniellipse** [comment]
It happens with both flowblade 0.14.0 and 1.0.0. On both versions, MLT is 0.9.6, i am using Arch-linux (evo-lution)

**Comment by Miniellipse** [comment]
There is a way to work around that error by using color-images, so zjere is a way... :)

**Comment by jliljebl** [comment]
The issue here was that compositing on top of a "Color Clip" crashed. This has now been fixed by making "Color Clips" use hidden png's (in folder <home>/.flowblade/rendered_clips)
