### ISSUE TITLE
Flowblade blends png-files with alpha-information with a white border

### ISSUE THREAD

**Issue by Miniellipse** [jliljebl/flowblade#136]
When blending two files (i used pictures and pictures as image-sequence with alpha-channel out of blender)with the blend-compositor, it creates a small white border around the object.

![flowbladealpha001](https://cloud.githubusercontent.com/assets/13347618/8710178/3754e570-2b48-11e5-8621-f0b0a57bf0c1.jpg)
Image created in flowblade

![flowbladealpha002](https://cloud.githubusercontent.com/assets/13347618/8710190/495401ac-2b48-11e5-9dd7-699de94ed647.jpg)
Image created in open shot for comparison, thats how it should look

**Comment by Miniellipse** [comment]
It is possible that the alpha-channel is shiftet by one pixel, as in the picture, the border is to the left.

**Comment by jliljebl** [comment]
Would be possible to get a few frames that display this problem as linked downloads, because if they're attached here some essential properties might be altered?

Openshot does not have "Blend" compositor available, so do other compositors like "Dissolve" in Flowblade give the desired result?

**Comment by denjello** [comment]
Here is a command line I use to make a video screencapure (no audio).

`sleep 5; ffmpeg -f alsa -ar 48000 -ac 2 -f s16le -i /dev/zero  -f x11grab  -s $(xdpyinfo | grep    'dimensions:'|awk '{print $2}') -r 25 -i :0.0 -c:v libx264 -pix_fmt yuv420p  -f mp4 -y -an screencap.mp4`

**Comment by Miniellipse** [comment]
Whow, used "dissolve" in stead of "blend" and it works! Many thanks! Solved!

**Comment by Miniellipse** [comment]
Must have a look what the german translation in 1.0.0 is using for "dissolve" ... tried it in 0.14.0 in english yet.

**Comment by Miniellipse** [comment]
In german language, the "dissolve" ist called "auflösen" ... I really would appreciate my 1.0.0-version to run in english language, too. How to start it in english? Thanks a lot ... :)

**Comment by jliljebl** [comment]
I will need to add a preference option for doing that, currently you'll get the system language forced on you. I'll add an Issue for that later.

**Comment by jliljebl** [comment]
Both issues mentioned here have been solved, closing.
