### ISSUE TITLE
Adding an image-sequence does not use the directory from the last import [enhancment]

### ISSUE THREAD

**Issue by Miniellipse** [jliljebl/flowblade#137]
When adding media, the file-chooser shows the path of the last import so you can look for additional files there to put into your bins. But the function for adding images-sequence does not use that path, so it may be a hard job to navigate to the folder containing the sequence-images for each sequ4ence over and over again.
![addmedia](https://cloud.githubusercontent.com/assets/13347618/8718748/f4c8b5f6-2ba6-11e5-8be6-57904957af43.jpg)
The media-import uses that file-chooser that has the last path choosen, thats perfect
![addimagesequence](https://cloud.githubusercontent.com/assets/13347618/8718760/0f58552a-2ba7-11e5-9b7a-211815757404.jpg)
The sequence-import uses that file-chooser, in my case, i have to click nine directory-names to navigate to the correct location. When adding more image-sequences, its needed over and over again.

**Comment by jliljebl** [comment]
Agreed, will fix.

**Comment by jliljebl** [comment]
Fixed in  repository, will be in next release.
