### ISSUE TITLE
[Enhancement] GPU rendering 

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#140]
Would it be possible to add GPU rendering to the roadmap? Or should this be a feature for MLT or ffmpeg?

**Comment by jliljebl** [comment]
I added the following text to roadmap to clear-up the situation a bit.

"""
GPU Rendering 
MLT already contains support for GPU rendering and it has been used by Shotcut for a while, but my experience has been that it is quite unstable. It may work well with some combinations of Qt version, graphics card and drivers but other combinations may be unusably crashy.

The Wayland transition should probably be completed too before this is attempted. Currently the earliest date that this will be looked at looks to be early 2017.
"""
