### ISSUE TITLE
Show waveform for audio tracks.

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#141]
It is very handy to have the audio waveform shown in the audio tracks in the timeline.

**Comment by jliljebl** [comment]
On demand Audio Level display already exists:

1) Right click on a timeline clip with audio
2) Select "Display Audio Level"
3) Audio Level data will be rendered and displayed

What does not currently exist is automatically background rendered data that is always diplayed on all clips if so asked by user.

This will be added some time in the future, but making this work will require creating a d-bus controlled background renderer for audio data and will take a bit of effort. Current ETA for this feature hitting the repo is sripng 2016, but might happen earlier.

**Comment by jliljebl** [comment]
Fixed in repository. Audio levels are now by default always displayed and they're rendered in a background process.
