### ISSUE TITLE
community.

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#145]
i feel the need to offer a place where a community (devs and users) can interact... this doesn't have to be something that gives work to imlplement and maintain (at least for now since all is new). we could use g+, mailing list or reddit for that. 

i offer myself to set this up and give you administrative rights. 

let's have a community and grow healthy and strong :)

**Comment by jliljebl** [comment]
Hi, I think I'll give this a bit more thought and get back on this next week. Reddit presence is probably not useful and mailing list is i think unnecessary with the "Issues" abd "Pull request" features here, but some google+ thing might be useful, I'll look up some other groups and see how they work.

**Comment by faridosc** [comment]
shotcut uses g+; 
kdenlive has forums, a mailing list, there is a g+ community as well;
pitivi uses twitter, g+ and irc

maybe a g+ community for starters is a good choice.

**Comment by jliljebl** [comment]
So Shotcut has this:

https://plus.google.com/communities/111984976401772983232

it is actually surprisingly high traffic which is both good and bad. I would not comment on everything there on that level of traffic, and participation by other users would very much be wanted.

But I think we can set something like this up. Do you know how this is done and how should we proceed?

**Comment by faridosc** [comment]
I created the community and sent you an invitation to make you admin. Could you send me the logo so that i can put it as the communities icon.

**Comment by jliljebl** [comment]
![flowbladeappicon](https://cloud.githubusercontent.com/assets/1823444/9185917/d49c41a4-3fc8-11e5-8525-380af387d392.png)

Okay, here's the icon, I'll still try to answer your invite, from the net GUI it is not completely clear how to do that, I'll try my phone

**Comment by jliljebl** [comment]
So I was able to join and post, now I'll need some admin rights and we can post a link a here to the group. I have so far _never_ used any sosial media so using this may not be that smoot...

**Comment by faridosc** [comment]
It worked and added you as admin. 

The minimum size to upload is 960 x  540. Do you have this logo in svg or bigger size?

**Comment by jliljebl** [comment]
No, the image was made as a bitmap from bitmap/vector images so no svg ever existed. I'll make something tomorrow night, maybe create a more reasonable post and then add the link on github page.

**Comment by faridosc** [comment]
Ok, great. I created two categories discussion and showcase, you can add some more or change if you think relevant. 

Let me know when it is ready so i can share the community and invite some people. 

I sent you a while back an email with a logo prototype if you like to use it as an inspiration if you see fit. ;)

Cheers

**Comment by denjello** [comment]
I can make the finished svg / pngquanted png.

**Comment by jliljebl** [comment]
![google_group_logo](https://cloud.githubusercontent.com/assets/1823444/9194938/c394424e-4027-11e5-807e-d1c3c5b73ec1.png)

Okay, so here's the design using some of my existing work and faridosc's logo idea. denjello, at 11K this is so small that it won't need further compression.

**Comment by denjello** [comment]
do you have a working file (psd / xcf / svg)?
anyway here is the crushed version: ![flowblade-crushd](https://cloud.githubusercontent.com/assets/6129121/9197364/e01e4a98-4033-11e5-9c25-d960bc785393.png) > 9.7kb

**Comment by faridosc** [comment]
hi @jliljebl and @denjello what you sent isn't doesn't work, what we need is just the logo  (https://cloud.githubusercontent.com/assets/1823444/9185917/d49c41a4-3fc8-11e5-8525-380af387d392.png) in a bigger size. 

if you have an xcf vesion i can try to do that.

cheers

ps
@denjello if you have a g+ account join the community ;)

**Comment by faridosc** [comment]
just to make it clearer maybe, check out how the logo of the communities is:

https://plus.google.com/u/0/communities/111984976401772983232
https://plus.google.com/u/0/communities/116548935195599437911
https://plus.google.com/u/0/communities/112463424693691728362
https://plus.google.com/u/0/communities/106356141458688249708

ours is like this at the moment:
https://plus.google.com/u/0/communities/103860400113389238474

**Comment by jliljebl** [comment]
![google_group_logo_2](https://cloud.githubusercontent.com/assets/1823444/9207539/f0753904-4076-11e5-9cd1-50a3d08a2713.png)

Ok, it's a portrait image. Let's slap this on and see how it looks. The upscaled pixmap for KDEnlive is quite bad. BTW I'll upload later the resource files I have to have them available in the future.

**Comment by faridosc** [comment]
updated the profile photo... gonna start sharing the community.

**Comment by jliljebl** [comment]
![google_group_logo_3](https://cloud.githubusercontent.com/assets/1823444/9208136/8715c484-407a-11e5-9589-e29dbcc49cd3.png)

Could you try if this orientation works better? Tomorrow I'll post a screenshot of the new dark theme work to have some content, and add the link to forum front page. I'll also try the moderation thing and remove the test posts.

**Comment by jliljebl** [comment]
I updated the front page and posted on the dark theme. Let's how this goes. Thanks for the work on this.

**Comment by faridosc** [comment]
cheers!
