### ISSUE TITLE
switch in and out icons?

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#149]
not that it makes a big difference, but just a question, why is the in icon this ] and the out one this [, wouldn't it make more sense for the in to be [ and the out ]?

**Comment by jliljebl** [comment]
Avid has had it like this 20+ years and it is not a good idea to use similar icons with reversed meanings compared to an industry mainstay program.

http://www.creativeobserver.com/img/1454_avid_media_composer_7_screenshot_lg.jpg

The icons admittedly remind square brackets a bit, but this is the first time I've heard someone make the connection and I don't think this is a problem.
