### ISSUE TITLE
Any chance to get more filters keyed?

### ISSUE THREAD

**Issue by Miniellipse** [jliljebl/flowblade#153]
It would be nice when the filters for tranlation, perhaps rotation and scaling, too, get keypoints to generate animated movement.

Would be nice if scaling is implemented as a a standallone-filter like translation and rotation and is not only available in affine-filter.

Any chances? :)

Thanks for this interesting software...

**Comment by jliljebl** [comment]
Yes, there are two solutions that I have been considering:

1. Adding new filter providing affine transformations to MLT using Cairo.
2. Add a complete node based compositor tool for the more complex animations and composites.

I'm actually working on 2. right now, but it will take a few more months to be complete, but it is starting to look good for 1.4 around November.

Its reusing an old project but it works quite well, here some clips that can be done with it
https://code.google.com/p/phantom2d/wiki/PhantomClips

Screenshot of current code:
![screenshot _phantom](https://cloud.githubusercontent.com/assets/1823444/9568542/3125b23e-4f55-11e5-885c-8ab2cd63d200.png)

Solution 1. will be done eventually but it may take a while.

**Comment by Miniellipse** [comment]
This really looks amazing. Its not that long till november... :) Would be nice if svg-files are possible and that transparent parts in files are possible... :)

**Comment by jliljebl** [comment]
This can be closed as an Issue here, the node editor is being worked on.
