### ISSUE TITLE
Audio-Output may be corrupted when first vid/pic is not at complete beginning

### ISSUE THREAD

**Issue by Miniellipse** [jliljebl/flowblade#154]
I have reconized that the output of audio (especially when using H.264 /mp4-codec and mp3 for audio) may be unusable when there is a (small) gap at the direct beginning of video. The sound then is like chopped. After moving the first files to the first frame and trimming them this is done correctly.

I only have a large project that shows this behaviour, will try to produce something smaller.

**Comment by jliljebl** [comment]
Confirmed. This is almost guaranteed to be MLT/codec issue and as such cannot be fixed within Flowblade. I'm not sure how to pursue this. I'll probably at some point try to reproduce this using MLT XML and melt, and then maybe file a bug report on MLT, but for now I'll mark this as known issue.

**Comment by jliljebl** [comment]
I'm closing this as a known issue. I also added a 'help wanted' to indicate that if this is shown to be Flowblade bug I will accept patches to fix this.
