### ISSUE TITLE
crashes when adding affine of png over a video

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#155]
1 add a video clip
2 add a png with alpha
3 add compositor affine of image over video
4 crash

**Comment by jliljebl** [comment]
Is this the setup?

![screenshot from 2015-09-07 19 59 19](https://cloud.githubusercontent.com/assets/1823444/9720853/29d1c6de-559b-11e5-9ebf-e593da2ed210.png)

It seems that it is working here.

**Comment by jliljebl** [comment]
Is possible that the crash depends on a property of the .png file, so if you make it downloadable somewhere, we can see if this is the case. An other possibility is that the compilation of some of the MLT/Frei0r/other libs is faulty in some way in your OS. It is quite difficult to determine the cause of this without reproducibility.

**Comment by faridosc** [comment]
here an example image... i also see that it doesn't happen with all png images.

![teste](https://cloud.githubusercontent.com/assets/373726/9721557/cb403d76-5572-11e5-97ce-6e1edb09d898.png)

**Comment by jliljebl** [comment]
Ok, that one did crash. Which is quite surprising. This will require an MLT side fix and will probably take quite a while.

**Comment by faridosc** [comment]
cheers

**Comment by jliljebl** [comment]
So it is only "Affine" compositor that does this on my system. The suggested workaround is to use some other Compositor.

**Comment by jliljebl** [comment]
Creating new "Affine" compositors is no longer possible. It is considered that stable and predictable functionality is more important than the additional functionality (non-planar rotations and shears) that "Affine gives". 

Existing projects with "Affine" compositors will continue to function as before.

No further action on any "Affine" related issues will be taken.
