### ISSUE TITLE
Cannot run from master

### ISSUE THREAD

**Issue by techwiz24** [jliljebl/flowblade#157]
```bash
[nathan@nathan-arch flowblade-trunk]$ python2 ./flowblade 
FLOWBLADE MOVIE EDITOR 1.2
--------------------------
Launch script dir: /home/nathan/projects/flowblade/flowblade-trunk
Running from filesystem...
MLT not found, exiting...
ERROR: 'module' object has no attribute 'PATH_MAX'
```

I have also tried from within pycharm and from the directory above (`python2 flowblade-trunk/flowblade`). I can confirm that flowblade does indeed run correctly on my system when installed via the package manager. I stepped through it in a debugger and it seems to be the `swig` helper file is returning a `module` object instead of the actual module itself, as the `mlt` ***and*** `_mlt` modules do indeed have a `PATH_MAX` attribute:

```python
[nathan@nathan-arch ~]$ python2
Python 2.7.10 (default, May 26 2015, 04:16:29) 
[GCC 5.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mlt,_mlt
>>> mlt.PATH_MAX
4096
>>> _mlt.PATH_MAX
4096
```

**Comment by jliljebl** [comment]
In the repository(master) .../flowblade-trunk directory the is a file mlt.py. Does deleting that help?

**Comment by techwiz24** [comment]
@jliljebl Sorry for the delay. Yes, deleting `mlt.py` allows me to run flowblade from source.

**Comment by jliljebl** [comment]
Thanks, good to know. mlt.py has been removed from repository, it should not have been there in the first place. It slipped in at some point because I run latest mlt and keep the bindings lib in same directory as the launch script. .gitignore was updated too.

Fixed in repository.
