### ISSUE TITLE
Run command after render completion

### ISSUE THREAD

**Issue by jmcudd** [jliljebl/flowblade#159]
It would be nice to be able to automatically upload to youtube or vimeo after the render is complete.

**Comment by jliljebl** [comment]
Yeah, this could be done. Youtube seems to have API for direct uploads: https://developers.google.com/youtube/2.0/developers_guide_protocol_direct_uploading#Direct_uploading . 

However, I haven't ever written code that communicates with remote servers over the internet, so if mcudd or anyone else has examples of command line commands that do this, that would help.

**Comment by jmcudd** [comment]
I've used youtube-upload recently, It works great. https://github.com/tokland/youtube-upload

**Comment by jliljebl** [comment]
Thanks for the tip.

**Comment by jliljebl** [comment]
This is not happening unless a pull request is provided.
