### ISSUE TITLE
Use cformat() or python3 style parameterized strings in the source code

### ISSUE THREAD

**Issue by ptrg** [jliljebl/flowblade#160]
I am working on the Hungarian translation of Flowblade and it is 75% ready at this moment, but I have an issue. There are single sentences written in two or more strings. This way the translation is very difficult if the word order (or the whole grammar) is different in the target language and sometimes it may be hard to find out the relation between msgids. Here is a not too hard example:

> msgid "Project was saved "
> msgstr ""
> msgid " minutes ago."
> msgstr ""

"Project was saved 10 minutes ago."  ==> "A projekt 10 perce volt mentve."
Project = A project
was = volt
saved = mentve
minutes ago = perce

As you can see the word order and the place of the number is different.

If the translator assumes them as separate senmtences:
"Project was saved " ==> "A projekt mentve"
" minutes ago." ==> " percekkel ez előtt"
The  concatenated result become to bad grammar for the target language:
"Project was saved "+ "10" + " minutes ago." ==> "A projekt mentve 10 percekkel ez előtt"

If formatted strings will be used the .pot file will be less in size and more translation friendly:

> msgid "Project was saved %d minutes ago."
> msgstr "A projekt %d perce volt mentve"

or:

> msgid "Project was saved {0} minutes ago."
> msgstr "A projekt {0} perce volt mentve"

See also: https://docs.python.org/2/library/string.html#string-formatting

Please, use strings with parameters (eg. the format() function that is built in python) instead of multiple strings for single sentences in the source code.

Thanks!

**Comment by jliljebl** [comment]
Ok, I will use formatted strings in the future. I probably will not change existing instances to cformat(), or at least not in the near future as changing those would require fixing all the existing translations too. 

I will accept patches that fix the source code translation string instances to cformat() style if those patches fix all translations too.

**Comment by ptrg** [comment]
Fixing the source code will force the .po files to be regenerated, so the segmented sentences will be lost at first (also the source references will change). The only way to "keep" the sentences is the manual re-copying (and concatenating) from a backup. But if the translations are not made with care about the segmentation of sentences this new translations can be very bad.

In my opinion they would be better to leave empty, or at least mark them as fuzzy (after re-copying from backup) because they need hard review or maybe totally new translations. 

Fuzzy translations do not show up on the GUI if you are using standard gettext implementation, but the English source texts are displayed. This is the same look of GUI as it would be without translations.

**Comment by ptrg** [comment]
Today I tried to update the translation and I saw a bug in preferenceswindow.py that leads to generating invalid po msgid string:

    row14.set_tooltip_text(_("Speed of Forward / Reverse will be multiplied by this value if Shift Key is held (Only using KEYS).\n" \
        "Enabling multiple modifier keys will multiply the set values.\n" \
        "E.g. if Shift is set to " + str(prefs.ffwd_rev_shift) + " and Ctrl to " + str(prefs.ffwd_rev_ctrl) + \
        ", holding Shift + Ctrl will result in up to " + str(prefs.ffwd_rev_shift * prefs.ffwd_rev_ctrl) + "x speed.\n" \
        "(Effective maximum speed depends on underlying software and/or hardware limitations)"))

which is written to the pot and po files as following:

#: preferenceswindow.py:257
msgid ""
"Speed of Forward / Reverse will be multiplied by this value if Shift Key is "
"held (Only using KEYS).\n"
"Enabling multiple modifier keys will multiply the set values.\n"
"E.g. if Shift is set to "
msgstr ""

The parser generates false results for the parameter(s) of _(). This is not what we want. 

Using fragmented messages (e.g. this one fragmented into separate sentences) may break the logic relation between them. So using cformat() is the only good solution.

**Comment by dvdlvr** [comment]
Thanks for that Peter.
This was my doing. I didn't know it would cause a problem - I'll review 
all my strings (old and new) and adapt them accordingly.

Regards,
Steven.

**Comment by jliljebl** [comment]
This is clearly not happening.
