### ISSUE TITLE
User-changeable preferences directory for  XDG support

### ISSUE THREAD

**Issue by pzl** [jliljebl/flowblade#161]
Opening this to see how the author(s) feel about allowing the `.flowblade` preferences directory to be moved by the user.

One thing that comes to mind is the [Freedesktop.org XDG Base Directory](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) spec. Basically, if the environment variable `$XDG_CONFIG_HOME` is present, it will be pointing to where the user wants their configuration files to go, and then it could be placed at `$XDG_CONFIG_HOME/flowblade`. 

And if that environment variable does _not_ exist, the spec says to use `$HOME/.config/<your directory>` as the fallback. That is generally the default location of `XDG_CONFIG_HOME` anyway. But since there is/would be the legacy location of `~/.flowbade` I can see arguments for that to be the fallback if `XDG_CONFIG_HOME` is not set. Or, to just additionally look there if the previous two come up with no existing folder.

That much, would make me more than happy. If the XDG spec does not seem like something you agree with, maybe compromises could be made a-la some other environment variable (like `$FLOWBLADE_DIR`?) to override the default location. Or make it a command-line switch: 

`flowblade --home=/var/prefs/.flowbade`. Or something along those lines.

If this is something the author(s) agree with, I would be more than happy to do the work, and issue a pull request with the consensus on the behavior here. 

Fortunately, everything in the code seems to reference `get_hidden_user_dir_path` for this path, so changes would be minimal, and likely restricted to just this function.

Friendlier explanation of the XDG Dir spec here: https://ploum.net/207-modify-your-application-to-use-xdg-folders/

**Comment by pzl** [comment]
Also, for what it's worth, if you're really excited/into the XDG spec, there is an existing python module [pyxdg](http://www.freedesktop.org/wiki/Software/pyxdg/) that will take care of it all, but it seems like overkill at the moment?

**Comment by jliljebl** [comment]
This is the first time that I've heard of the XDG spec. My initial thought on this is that I would rather accept a patch that makes a Flowblade comply to XDG spec if started with a command line switch and later perhaps make XDG behaviour default, but at this this time I'm probably not willing to make XDG  behaviour the default. So something like:

1. User starts Flowblade with command "flowblade -xdg" 
2. app.main() detects command line switch and sets flag in editorstate.py.
3. utils.get_hidden_user_dir() returns value based on value in editorstate.py

The flag would have to be set before line 125 in app.main().

**Comment by jliljebl** [comment]
We have some work on this, but this has not been completed, see pull request, setting milestone Future

**Comment by jliljebl** [comment]
Any flatpack support will be provided with zero further source code modifications.
