### ISSUE TITLE
Snapping clips in the timeline

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#166]
please add snapping as a feature somewhere down the line, would be great for 1.4 ;P

**Comment by jliljebl** [comment]
I will give this a go for 1.6. 

I've always known that some users would like this, but this has never been a high priority for me. Now that drag'n'drop to non-V1 tracks will do an overwrite when clip is dropped on empty space on track, this will be much more useful.

The main issue here is that for technical reasons getting this done may turn into a major undertaking (or not, I'm not quite sure without actually trying), and therefore I'm not willing to promise this even for 1.6. For 1.8 I'll make this a priority.

**Comment by faridosc** [comment]
cheers

**Comment by jliljebl** [comment]
Feature added in repository, will be in release 1.8.
