### ISSUE TITLE
Add G'MIC effects

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#172]
just saw these posts and thought that this would be really cool to add (especially since g'mic is a great free software project):

https://pixls.us/feed.xml#g-mic-for-adobe-after-effects-and-premier-pro
https://discuss.pixls.us/t/gmic-for-adobe-after-effects-and-premiere-pro/452

What do you think?

**Comment by jliljebl** [comment]
Thanks for bringing this to my attention, this seems very interesting. Its like ImageMagik, but more useful. Best of all, it is already on Ubuntu/Debian repos so any functionality will be immediately available to users.

It seems that this is not suitable for being used as an MLT service - there is no way we can get anything interesting from this in anywhere near real time - but as a stand-alone effect tool we can use MLT as input and the available CLI program do the output. This will also enable users to develop their own scripts.

I'm going to create a tool using this, maybe even for 1.6, but 1.8 seems very likely.

**Comment by faridosc** [comment]
nice, we should definitely write a post about this at the g+ community, what do you have in mind?

**Comment by jliljebl** [comment]
I posted a comment on the project Google+ group.

**Comment by jliljebl** [comment]
This is done
