### ISSUE TITLE
Spanish translation missprint

### ISSUE THREAD

**Issue by lEgeol** [jliljebl/flowblade#174]
In the actual 1.2 translation the follow lines are worng:
#: panels.py:405 mlttransitions.py:166
msgid "Fade In"
msgstr "Desaparecer"

The correct form are:
#: panels.py:405 mlttransitions.py:166
msgid "Fade In"
msgstr "**Aparecer**"

**Comment by jliljebl** [comment]
Fixed in repository, will be 1.6.
