### ISSUE TITLE
1.4 screenshots

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#176]
i took some screenshots for 1.4 version in case interested in using somewhere. i saw some requesting them. 

![captura de tela de 2015-11-24 14-15-12](https://cloud.githubusercontent.com/assets/373726/11372869/d6f4c962-92b6-11e5-9f65-710db7a1bdf7.png)
![captura de tela de 2015-11-24 14-15-01](https://cloud.githubusercontent.com/assets/373726/11372871/d70fe74c-92b6-11e5-979b-f56a887e4525.png)
![captura de tela de 2015-11-24 14-14-47](https://cloud.githubusercontent.com/assets/373726/11372870/d709d0d2-92b6-11e5-8dd2-8292430ac20b.png)

**Comment by jliljebl** [comment]
Thanks, I'll add the last one in to the repository, it looks real nice.
