### ISSUE TITLE
different errors when compiling flowblade-1.4 on Fedora 23

### ISSUE THREAD

**Issue by martinkg** [jliljebl/flowblade#177]
this are the messages when compiling with a rpm spec file on Fedora 23

byte-compiling /home/martin/rpmbuild/BUILDROOT/flowblade-1.4.0-1.gitf8032ea.fc23.x86_64/usr/lib/python2.7/site-packages/Flowblade/tools/gmicplayer.py to gmicplayer.pyc
  File "/usr/lib/python2.7/site-packages/Flowblade/tools/gmicplayer.py", line 46
    profile = get_default_profile():
                                   ^
SyntaxError: invalid syntax

.....
/usr/lib/python2.7/site-packages/Flowblade/compositormodes.py:156: SyntaxWarning: name 'sub_mode' is used prior to global declaration

.....
Bytecompiling .py files below /home/martin/rpmbuild/BUILDROOT/flowblade-1.4.0-1.gitf8032ea.fc23.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
/usr/lib/python2.7/site-packages/Flowblade/compositormodes.py:156: SyntaxWarning: name 'sub_mode' is used prior to global declaration
Compiling /home/martin/rpmbuild/BUILDROOT/flowblade-1.4.0-1.gitf8032ea.fc23.x86_64/usr/lib/python2.7/site-packages/Flowblade/tools/gmicplayer.py ...
  File "/usr/lib/python2.7/site-packages/Flowblade/tools/gmicplayer.py", line 46
    profile = get_default_profile():
                                   ^
SyntaxError: invalid syntax

do you need the complete compiling messages

**Comment by jliljebl** [comment]
This invalid because it is against the repository development version which can at any time contain errors.

If you are attempting to install Flowblade 1.4 or create a repository package version of it, please checkout the release version 1.4 which is indicated by tag "v1.4" in the "master" branch.
