### ISSUE TITLE
Make possible to display Audio Meter with small screen heights

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#179]
in the latest builds the audio meter is missing.

**Comment by jliljebl** [comment]
I may have pushed a version that did this, but current repository should not do this, is this still happening? When you launch program in terminal do you get "Small height: True"?  If this is the case then Audio Meter should not be displayed as it takes too much vertical space. Is there something that looks like an error in terminal print out?

**Comment by faridosc** [comment]
Yep, i get this:

Small height: True
Small width: False

It doesn't work even when fullscreen mode is activated.

**Comment by jliljebl** [comment]
Yeah, 768px height is not enough to display the Audio Meter as it is and it's automatically dropped for small screen heights. I'll change this to be an issue about making Audio Meter work small screen heights.

**Comment by jliljebl** [comment]
The get this fixed a pull request will be needed.

**Comment by jliljebl** [comment]
Ok, this now fixed in repository, will be in release 1.10. Turned out be doable anyway.
