### ISSUE TITLE
DEL key and Delete caption of buttons

### ISSUE THREAD

**Issue by ptrg** [jliljebl/flowblade#184]
Please use two separate strings for DEL key (Help/Quick keys) and for "Delete" caption of buttons.
Do the same in other similar cases. Some possibilities can be: INSERT, HOME, END, PLUS, MINUS, etc...
This will ease the creating of more user friendly translations, because non-english keyboard layouts (eg. HU) contains these keys with english names, and that names may not be translated.

Thanks!

**Comment by jliljebl** [comment]
I'll look into this and see what I can do about it.

**Comment by jliljebl** [comment]
Fixed by patch from ptrg.
