### ISSUE TITLE
Clips disapear in timeline when zooming in (v. 1.4.0)

### ISSUE THREAD

**Issue by cestomano** [jliljebl/flowblade#185]
Editing a video, clips don't appear if I zoom in (about viewing 1:30 minutes or less in timeline). Only in V1 track and from 2:00 minute to end.

Flowblade version 1.4.0
Ubuntu 14.04 64-bit

**Comment by cestomano** [comment]
I think the problem was with a clip. I deleted last three clips and put them again in timeline and now are all visible.

**Comment by jliljebl** [comment]
If you can reproduce this it would be useful information. This typically happens when there is a Python error when drawing timeline that does not terminate the application.

**Comment by cestomano** [comment]
Yes, I but it never happens again, only once. If it will happen again, I'll notify.

Thanks

**Comment by jliljebl** [comment]
Closing this  for now, if further reports emerge I will investigate more.
