### ISSUE TITLE
Possibility to add 1080p 60fps profile

### ISSUE THREAD

**Issue by cestomano** [jliljebl/flowblade#186]
I'm working with flowblade (1.4.0) and there are only 1080p 50fps maximum but it would be fantastic can work at 1080p 60fps.

Regards

(very useful and powerfull application, by the way!)

**Comment by jliljebl** [comment]
If this profile works on my system without crashing I'll add it to next version.

**Comment by cestomano** [comment]
Great!

**Comment by jliljebl** [comment]
Fixed in repository, will be 1.6.
