### ISSUE TITLE
Official website?

### ISSUE THREAD

**Issue by brylie** [jliljebl/flowblade#189]
Is there an official website for this project? Having a website can help new users learn about the project. Even a simple Github pages static website would be nice :-)

**Comment by jliljebl** [comment]
Yes, this will have to be done. I just keep postponing it in favour of other more "urgent" needs of the project, but now the web page is becoming a top item, and something will surely be released by September.

**Comment by Jevans101** [comment]
I really like this editor. I'm practicing web design at the moment. If there are any things I can help with web-wise, let me know.

**Comment by brylie** [comment]
:+1:  I can help set up a simple website CMS or Github page in collaboration with @Jevans101

**Comment by jliljebl** [comment]
Ok, I need to basically budget time in a release cycle to be able to commit to making this happen, so I'll make this part of the next release cycle. After next release in March I'll comment here and on Google+ to announce that we're doing this and this will be done as a Github project page which allows developing the site by accepting pull requests into the "gh-pages" branch which will be created at that time. How the site will develop will then depend on ideas and contributions from then on.

**Comment by brylie** [comment]
Great! Thanks :+1:

**Comment by jliljebl** [comment]
Fixed, this has now been up a while: http://jliljebl.github.io/flowblade/
