### ISSUE TITLE
Render using args inaccessible with small screens

### ISSUE THREAD

**Issue by snilek** [jliljebl/flowblade#190]
When flowblade starts with `Small height: True` the "Render using args" feature becomes inaccessible, i.e. unusable.

Or maybe I am just missing something.

Thanks,
Jan Jansky

**Comment by jliljebl** [comment]
Yes, I was completely unable to create a layout that worked when  "Render using args" feature was available with screen height 768px. 

In principle it would be possible to add back the functionality using a modal window, and I'm willing to accept patch that does this, but I'm currently not planning to work this myself.

**Comment by jliljebl** [comment]
Fixed in 1.10.
