### ISSUE TITLE
An ything new to animated moving of clips and pics

### ISSUE THREAD

**Issue by Miniellipse** [jliljebl/flowblade#193]
I still had the 1.0-version,m updated to 1.4 some minutes ago. There was light at the end of the tunnel that animation of translation and perhaps rotation is in work, perhaps with a new animation system. Anything at work or perhaps ready and i did not see it? :)

**Comment by jliljebl** [comment]
Not for 1.6, I hope to get something for 1.8, although the plan to create a webpage for the project in 1.8 development cycle may interfere with the plans here. I will also favour bug fixes to existing functionality and features that help beginner/casual users for the time being, so there could be a delay in further action on this area.

Closed as duplicate.
