### ISSUE TITLE
Crash when switching from proxy to original media.

### ISSUE THREAD

**Issue by bergamote** [jliljebl/flowblade#195]
I've been editing a video using proxies, and now I want to switch back to the original media for rendering. Whenever I click on "Use Original Media", Flowblade freezes and I get this error message in the terminal:

    Save project proxy_conv.flb
    Loading edit2.flb, SAVEFILE_VERSION: 5
    Exception in thread Thread-7:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner self.run()
      File "/home/herberts/apps/flowblade/flowblade-trunk/Flowblade/proxyediting.py", line 703, in run project = persistance.load_project(self.proxy_project_path)
      File "/home/herberts/apps/flowblade/flowblade-trunk/Flowblade/persistance.py", line 339, in load_project raise ProjectProfileNotFoundError(project.profile_desc)
    ProjectProfileNotFoundError: 'HD 1080p 23.98 fps'

Also, "HD 1080p 23.98 fps" is the profile I'm using.

**Comment by jliljebl** [comment]
Thanks for the terminal printout. I'm not yet sure how this is even possible as the profiles are installed with the program and should under no circumstance just disappear, but I'll look into this.

**Comment by bergamote** [comment]
Okay, the crash might well have been caused by my setup.
I have Flowblade installed from the repo and also an up-to-date clone from github (which is the version I use). Looking for the "HD 1080p 23.98fps" aka `atsc_1080p_2398`, which is the default profile in both installation, it turned up in those locations:

    /home/username/apps/flowblade/flowblade-trunk/Flowblade/res/profiles/atsc_1080p_2398
    /usr/lib/pymodules/python2.7/Flowblade/res/profiles/atsc_1080p_2398
    /usr/share/mlt/presets/consumer/avformat/atsc_1080p_2398
    /usr/share/mlt/presets/consumer/avformat/atsc_1080p_2398/DNxHD
    /usr/share/mlt/profiles/atsc_1080p_2398
    /usr/share/pyshared/Flowblade/res/profiles/atsc_1080p_2398

I was only able to switch back to the original media without crash once I copied the profile file here:

     /home/username/.flowblade/user_profiles/atsc_1080p_2398

I'll close this since it only happened with one file and I wasn't able to reproduce the crash.
