### ISSUE TITLE
Editing a pasted 'Color Grading' filter resets it to the default settings

### ISSUE THREAD

**Issue by bergamote** [jliljebl/flowblade#196]
Once the 'Color Grading' filter is copied from a clip and pasted onto another clip, it isn't possible to make small adjustment to it. As soon as you open the second clip in the Filters Editor, the filter gets reset to its default settings.

**Comment by jliljebl** [comment]
Confirmed.

**Comment by jliljebl** [comment]
Fixed in repository, will be in 1.6
