### ISSUE TITLE
Integrate shenidam

### ISSUE THREAD

**Issue by deedos** [jliljebl/flowblade#199]
Shenidam http://www.shenidam.org is a great syncer for DSLR footage with audio recorded externally as well as other common situations when editing. Would be great to have it inside flowblade. Thanks

**Comment by jliljebl** [comment]
Ok thanks, I'll look into this for 1.8.

**Comment by jliljebl** [comment]
This seems quite a lot work and I'm not currently willing to do the work to integrate this. Patches will be accepted.

**Comment by jliljebl** [comment]
I'm merging this with https://github.com/jliljebl/flowblade/issues/344.

We clearly should offer audio syncing functionality at some point, but it is not clear how yet. shenidam is one way to do this, but there are others too.
