### ISSUE TITLE
Independent clip monitor and program windows

### ISSUE THREAD

**Issue by massimostella** [jliljebl/flowblade#200]
Why is it not yet possible to have two independent clip monitor and program windows if you need them?
Sometimes they are very useful.
When you are editing fiction it's indispensable to watch the out point frame of the previous edit cut for matching the best in point of the next clip. As everybody knows fiction angles are shooted in different times so the editor has to find the best way to put pieces together. I guess he needs references. So a fixed image while he's searching (unstead of switch contiunesly from one window to the other) it's very important. :)﻿

**Comment by jliljebl** [comment]
The main reason is a technical. SDL library used to display the video can only display one overlay per process. Once I run the following line:

        os.putenv('SDL_WINDOWID', str(widget.get_window().get_xid())) 

that's it! I now have one video overlay on top of my monitor widget, but as you can see I'm setting an environment variable, which obviously can have only have one value. It may be possible to have a different value for this environment variable on another process, but I cannot run my clip monitor in another process and integrative it with a GUI application running in different process.

There may be a solution. Flowblade could be ported to use OpenGL consumer to display video which would probably enable multiple video displays and thus making possible to do this. But this will not be attempted in 2016, and I cannot make any predictions when I will try this.

As always, quality patches will be accepted. I'm in no way against doing this, I just do not have the resources to do it any time soon.

**Comment by jliljebl** [comment]
This will not be done.

Version 1.10 provided "Trim View" feature and two different types of "Match Frame" functionalities, that work even better in a dual monitor setup with the new 2 window layout provided. Additional value from separate clip monitor is quite small after these enhancements.

it is also clear that it is very difficult to do this with MLT without significant performance and/or responsiveness penalty.
