### ISSUE TITLE
Add option to add current frame as new media

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#206]
Please add this feature as it is very handy. In Openshot you can press Ctrl-D to add current frame displayed in preview window as new image media. This frame can then be used to extend a stationary clip if it is too short or create a frame freeze effect.

**Comment by jliljebl** [comment]
This could be done.

**Comment by jliljebl** [comment]
I can't bring myself to spend time on this because "Export"->"Current Frame" exists as a work around. Any further gains in efficiency brought by offering some quicker way to do this are in view not worth the development time. Quality patches will be accepted.
