### ISSUE TITLE
Enable adding custom render formats in GUI

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#207]
Now, the only way to do this is to edit _renderencoding.xml_.

**Comment by jliljebl** [comment]
There is a way to save render selection: 

1) Check Render Using Args -checkbox
2) Define your render as usual
3) Press "Load Selection" button
4) Possibly edit args on the text area
5) Press the button with save icon next to Render Using Args -checkbox

Creating a workflow "render GUI -> renderencoding.xml" would require a complex machinery using hundreds of lines of code and investment in development time that could be better spend elsewhere. Closing as _wontfix_.

**Comment by apienk** [comment]
Could you please point me to where I can find the _Render Using Args_ checkbox?

**Comment by jliljebl** [comment]
Maybe you have a translated version, but anyway here's a visual aid.
![render_args](https://cloud.githubusercontent.com/assets/1823444/13091277/0fe365e2-d503-11e5-9431-ebea31976139.png)

**Comment by apienk** [comment]
Thank you. Unfortunately, I can't see this dialog due to this issue: [Render using args inaccessible with small screens #190](https://github.com/jliljebl/flowblade/issues/190).

**Comment by jliljebl** [comment]
Ah, ok. I'll have to eventually figure that out, the 768 screens still seem quite common.
