### ISSUE TITLE
Transform>Affine filter's Width setting doesn't work as expected

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#208]
**Steps to reproduce:**

1. Add Affine filter (from Transform category) to a video clip.
2. Try changing the Width setting.
3. Instead of modifying the size of the original video it duplicates the X setting.

**Comment by jliljebl** [comment]
I'm just going to mark this filter deprecated and work on alternative solutions.

The problems with this are: 

1) Its implementation in MLT is very hacky. It uses code from compositors as the only filter that does so, and its initialization code is very messy. Anything related to this would needed to fix in MLT and I'm not going to touch it.

2) The programming interface to it very bad and makes me angry

3) As a solution to achieve any motion graphics a transform filter is very rudimentary, and there are alternative approaches available that will be pursued in the next release
