### ISSUE TITLE
Changing render profile doesn't work

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#210]
**Steps to reproduce:**

1. Create project as DV/DVD PAL (4:3).
2. In Render settings window uncheck _Use project profile_ and set profile to _HD 720p 25 fps_ (16:9).
3. Render the project.
4. Rendered video is 4:3 instead of 16:9.

**Comment by jliljebl** [comment]
Confirmed.

**Comment by jliljebl** [comment]
Fixed in repository, will be in 1.6. See: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/KNOWN_ISSUES.md for still existing restrictions in this functionality.
