### ISSUE TITLE
Recreate media icons doesn't work

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#211]
**Steps to reproduce:**

1. Add a PNG image to Flowblade.
2. Save as new project and close.
3. Modify PNG image in external program.
4. Reopen the project.
5. Media icons (thumbnails) have not updated.
6. Select *Recreate Media Icons* from menu.
7. Media icons (thumbnails) have not updated.

**Comment by jliljebl** [comment]
Confirmed and fixed, will be in 1.6.
