### ISSUE TITLE
Add localization instructions

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#213]
I'm a professional translator and I'd like to translate Flowblade into Polish but I don't really know how to do it. I've located _flowblade.pot_ file and I assumed that bash scripts in the locale folder are there to generate a new locale and then compile it. However, they don't seem to work on my system. Please add a short instruction how it should be done.

**Comment by jliljebl** [comment]
Hi,

There are translation instructions already. The link is in the project front page **Docs** section: 

https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/CREATING_TRANSLATION.md

The bash scripts should work, I use them my self all the time. Note that you cant run the bash scripts in the installed version unless you are *root* and it generally not a good idea to do work in any other place then your home folder.

I just updated the instructions to be easier to follow, but if you have problems, comment here and I can add clarifications.

**Comment by jliljebl** [comment]
There has been no further comments, closing as *not active*
