### ISSUE TITLE
Pixel aspect ratio is different than original

### ISSUE THREAD

**Issue by karlyeurl** [jliljebl/flowblade#215]
Hello,

I am under the impression that Flowblade uses a wrong pixel aspect when decoding (the encoding has the correct settings, I made sure of that using `ffprobe -v quiet video.mp4 -show_streams`).

Attached is a picture of the problem, and here is the [output](https://github.com/jliljebl/flowblade/files/160084/output.txt) of `ffprobe` on a video that creates this problem.

I am using the profile HD 720p 25 fps on flowblade 1.6.0.

It is also worth noting that when generating transitions, the video is shrunk in all four directions, only in the rendered version (the preview version in flowblade is fine). I believe these two may be related.

![flowblade_pixel_aspect](https://cloud.githubusercontent.com/assets/3105484/13551056/e6da3bac-e32c-11e5-90f7-8063720c56ff.png)

**Comment by jliljebl** [comment]
There is no clear way to proceed or activity with this, closing as *wontfix*.  Anyway this clearly MLT issue, and needs to handled there, and my MLt activity will not be focusing on this.
