### ISSUE TITLE
flowblade_icon_simple.svg contains unused bitmap

### ISSUE THREAD

**Issue by jonassmedegaard** [jliljebl/flowblade#216]
It seems the embedded JPEG "image9" (derived from the sand filter) is unused in flowblade_icon_simple.svg, and that SVG can be optimized.

Hint: The tool scour (in Debian package python-scour) is great for automating the task of optimizing SVG images.

**Comment by jliljebl** [comment]
You are correct. It took me 15 minutes to find it and remove it, so good catch. Fixed in repository.
