### ISSUE TITLE
changing profile framerate results in shifting beginning and end of clips

### ISSUE THREAD

**Issue by juliencarnot** [jliljebl/flowblade#219]
I wrongly imported clips as  24fps but the source is 30fps. I did my editing, mostly trimming clips and inserting them. I then figured out the problem and changed the profile to 30fps, and saved the project in a new file.

The trimmed clips are not kept as they were, and start earlier in the original media. It looks like the frames I selected as entry and exit points were not recomputed accordingly to the framerate change.

**Comment by jliljebl** [comment]
This has been declared a Known Issue: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/KNOWN_ISSUES.md

This issue will be addressed in the next 1.8 release by making the application inform the user of the potential difficulties when they import material that does not match the project profile

**Comment by mikeconnell** [comment]
I have had a problem with Flowblade and flv files coming out of OBS.  The early version of Flowblade 1.12 just tells me that there is a non-valid media problem, and won't let me edit the file.  1.14 and 1.16 will allow the file to be edited, but I get an option that tells me that the frame rate of the media doesn't match the project rate, and I need to change either the rate of the project or leave it alone.  If I change the frame rate to 23.97, the audio is off,  If I leave it at 30, the audio is ok,  but it takes longer to render the file.  When I look at the frame rate of the media in VLC the FPS is 30.
