### ISSUE TITLE
rendering with a profile with higher framerate leaves audio at the same length and appears to speed up the video compared to original playback

### ISSUE THREAD

**Issue by juliencarnot** [jliljebl/flowblade#220]
I wrongly imported clips as 24fps but the source is 30fps. I did my editing, mostly trimming clips and inserting them on the timeline. As I couldn't keep my editing as it was by changing the profile (see #219), I thought I would just render my editing at 30fps in the render tab.

My 4'14 timeline results in a 4'14 video file, but the video finishes at 3,23, which is in line with the 24 to 30 fps change. The audio keeps on to 4'14 and is out of sync.

The video appears to speed up a lot: the rendered 30fps movie in VLC plays much faster than the source/original 30fps file in VLC.

**Comment by jliljebl** [comment]
I added a F.A.Q item for, this cannot be fixed.

https://github.com/jliljebl/flowblade/edit/master/flowblade-trunk/docs/FAQ.md

**Comment by PanderMusubi** [comment]
I think this is a better URL https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/FAQ.md#rendering-with-a-profile-with-different-framerate-changes-video-playback-speed-and-loses-audio-sync

Perhaps a workaround can be provided, some `ffmpeg` example commands to run before importing adding video media.

**Comment by PanderMusubi** [comment]
To for example transcode to 24 fps, use:

    ffmpeg -i input.mp4 -filter:v fps=fps=24 output.mp4
