### ISSUE TITLE
Rearrange filters in the filters stack

### ISSUE THREAD

**Issue by massimostella** [jliljebl/flowblade#221]
I can't find a way to move up and down the filters which are inside the stack.
Sometimes it's a very useful action to perform if, for eg, you decide later to insert a filter you have to put on top of the pile.

**Comment by jliljebl** [comment]
Ok, I'm adding this in the new features queue.

**Comment by jliljebl** [comment]
I have to move this 1.10 to concentrate on getting node compositor out for 1.8.

**Comment by jliljebl** [comment]
This feature is now in repository and will be in release 1.10.

Rearranging filters by both using drag'n'drop and context menu "Move Up" and "Move Down" items is now available.
