### ISSUE TITLE
Regression: Rendered fades are corrupted

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#222]
**Steps to reproduce:**
1. Import a video clip.
2. Render fade-in.
3. The first frame of the fade is corrupted (contains just two color strips -- see attached image).

_This is a regression: this bug was not present in 1.4._

![test0001](https://cloud.githubusercontent.com/assets/9961826/13882652/b994be66-ed26-11e5-8293-d284434418fc.png)

**Comment by jliljebl** [comment]
Hi, I'm not reproducing this here, which encoding settings you are using to render the Fade In?

**Comment by apienk** [comment]
Indeed, it is more complicated than I though. I use Flowblade 1.6 on three laptops with the same version of Ubuntu (15.10). On one of my laptops rendering works for fades and SOME transitions -- Dissolve and Color Dip but not Wipes which produce color glitches similar to those generated by fades on the other two laptops: see the linked video.

Result is the same regardless of encoding settings. I tried most of them.

[https://www.dropbox.com/s/dv0c77d3nhmue0j/movie.mp4?dl=0](https://www.dropbox.com/s/dv0c77d3nhmue0j/movie.mp4?dl=0)

**Comment by jliljebl** [comment]
Okay, that glitch in your video file I have seen before maybe a bit more then a year ago, but it went away after I reinstalled some libraries. I'll look into this, it is not trivial, and will very likely require fixes on MLT once the problems are adequately identified.

**Comment by apienk** [comment]
Thank you. Let me know if I can be of any help.

**Comment by jliljebl** [comment]
There has been no further info on this, closing as unreproduced.
