### ISSUE TITLE
Feature: Look for missing files in current directory

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#226]
Could you please add an option to look for missing files also in current directory, not only in subfolders of the current directory where they are searched for now. I need to have all my project files in one dir.

**Comment by jliljebl** [comment]
Ok, this should be possible, but to keep application behaviour for existing projects as same as possible the current directory will look searched last.

**Comment by apienk** [comment]
Please just add it as an option in settings which is not turned on by default.

**Comment by jliljebl** [comment]
So, if understood correctly you would like the project file ("current") directory scanned for files first? It sort of makes sense as this would allow keeping projects in sub folders relative to other projects. To make that happen then there would really need to be a preference option that is by default off.

**Comment by apienk** [comment]
Yes, that's exactly what I meant.

**Comment by apienk** [comment]
It turns out that Flowblade actually looks for files in the current dir unasked. Please see the new issue: [Problem with saving a project](https://github.com/jliljebl/flowblade/issues/227).

**Comment by jliljebl** [comment]
Closing this as the other Issue is about the same functionality.
