### ISSUE TITLE
Problem with saving a project

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#227]
When I open a project created on a different system, paths to resources are automatically resolved (all files reside in current project directory where the .flb is) but such a project is not saved properly and I have to _Save As_ in order to be able to exit the program.

**Steps to reproduce:**
1. Create a project on another system, with all resources in the current directory.
2. Open the project on your system.
3. Media icons need to be recreated -- this is expected and works OK.
4. Try to save and exit Flowblade.

**Current result:** Clicking "Save" in the exit dialog does not close the program. Project is not saved.
**Expected result:** Clicking "Save" in the exit dialog saves the project and closes the program.

I'll post output from terminal in a few days when I have a new project.

**Comment by jliljebl** [comment]
Hi, does "Save Backup Snapshot..." functionality enable you to move the project from system A to system B?

1. Create project in system A
2. Save it using "Save Backup Snapshot..." functionality
3. Copy created folder to system B
4. Open project in system B

Does this work for you?

**Comment by jliljebl** [comment]
"Save Backup Snapshot..." is proposed as a way to move projects between systems.
