### ISSUE TITLE
had to install gir1.2-gtk-3.0

### ISSUE THREAD

**Issue by MarkoSchuetz** [jliljebl/flowblade#229]
on Ubuntu 14.04 I had to apt-get install gir1.2-gtk-3.0 in order to get flowblade 1.6 to load. Without I kept getting ERROR: cannot load name Gtk

**Comment by jliljebl** [comment]
Thanks, I updated the install instructions. Other dependencies that are missing from **.deb** are given here: https://github.com/jliljebl/flowblade/issues/217

This problem didn't arise on my install tests, so those were obviously not done correctly.

Leaving this open for the time being to provide info.

**Comment by jliljebl** [comment]
Closing, install instructions have been updated, and next provided .deb will contain updated instructions.
