### ISSUE TITLE
Difficultly installing on ubuntu 16.4

### ISSUE THREAD

**Issue by explodingword** [jliljebl/flowblade#230]
I have been using flowblade 1.4 orginally on ubuntu 14.4 but have just updated my OS to the new long term support verison Ubuntu 16.4 and decided to upgrade flowblade to the 1.6 version as well.
I had to do a clean install of the software, therefore updated manually all of the dependencies you highlighted on your site.
My problem is that when flowblade is installed it says it is 1.4 not 1.6 and some of the filters such as Chroma Key have disappeared along with the recently added 1080p 50fps profile.
I am at a lose as to what is happening.  I tried to revert to the orginal 1.4 version which I had previously used successfully but the same problems present themselves. At this stage I feel that I may have to revert to Ubuntu 14.4 to get it back to working order.
Aany suggestion would be most welcome.

**Comment by jliljebl** [comment]
Could you provide the terminal output from when you run the bad installation of 1.6 on 16.04? Open terminal and give command "flowblade" and copy paste output text here.

I will update myself to 16.04 once that is released, but currently I'm not able to test on 16.04.

**Comment by explodingword** [comment]
Hopefully this is what you are asking for.  

Thank you

william@william-System-Product-Name:~$ flowblade
FLOWBLADE MOVIE EDITOR 0.14rc
---------------------------
Launch script dir: /usr/bin
Running from installation...
MLT found, version: 6.0.0
OS: Ubuntu 16.04
Python 2.7.11+ (default, Mar 30 2016, 21:00:42) 
[GCC 5.3.1 20160330]
GTK+ version: (2, 24, 30)
Locale: en_GB
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - amv
  - apng
  - asv1
  - asv2
  - avrp
  - avui
  - ayuv
  - bmp
  - cinepak
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - flashsv
  - flashsv2
  - flv
  - gif
  - h261
  - h263
  - h263p
  - hap
  - huffyuv
  - jpeg2000
  - jpegls
  - ljpeg
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - msvideo1
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - prores_aw
  - prores_ks
  - qtrle
  - r10k
  - r210
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - snow
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v308
  - v408
  - v410
  - wmv1
  - wmv2
  - xbm
  - xface
  - xwd
  - y41p
  - yuv4
  - zlib
  - zmbv
  - libopenjpeg
  - libschroedinger
  - libtheora
  - libvpx
  - libvpx-vp9
  - libwebp
  - libx264
  - libx264rgb
  - libx265
  - libxvid
...
---
audio_codecs:
  - comfortnoise
  - s302m
  - aac
  - ac3
  - ac3_fixed
  - alac
  - dca
  - eac3
  - flac
  - g723_1
  - mp2
  - mp2fixed
  - nellymoser
  - real_144
  - sonic
  - sonicls
  - tta
  - vorbis
  - wavpack
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s8_planar
  - pcm_s16be
  - pcm_s16be_planar
  - pcm_s16le
  - pcm_s16le_planar
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s24le_planar
  - pcm_s32be
  - pcm_s32le
  - pcm_s32le_planar
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libgsm
  - libgsm_ms
  - libmp3lame
  - libopus
  - libshine
  - libspeex
  - libtwolame
  - libvorbis
  - libwavpack
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - apng
  - asf
  - ass
  - ast
  - asf_stream
  - au
  - avi
  - avm2
  - bit
  - caf
  - cavsvideo
  - crc
  - dash
  - data
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffm
  - ffmetadata
  - filmstrip
  - flac
  - flv
  - framecrc
  - framemd5
  - g722
  - g723_1
  - gif
  - gxf
  - h261
  - h263
  - h264
  - hds
  - hevc
  - hls
  - ico
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ircam
  - ismv
  - ivf
  - jacosub
  - latm
  - lrc
  - m4v
  - md5
  - matroska
  - matroska
  - microdvd
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - mxf_opatom
  - null
  - nut
  - oga
  - ogg
  - oma
  - opus
  - alaw
  - mulaw
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtp_mpegts
  - rtsp
  - sap
  - segment
  - stream_segment,ssegment
  - singlejpeg
  - smjpeg
  - smoothstreaming
  - sox
  - spx
  - spdif
  - srt
  - swf
  - tee
  - 3g2
  - 3gp
  - mkvtimestamp_v2
  - truehd
  - uncodedframecrc
  - vc1
  - vc1test
  - voc
  - w64
  - wav
  - webm
  - webm_dash_manifest
  - webm_chunk
  - webp
  - webvtt
  - wtv
  - wv
  - yuv4mpegpipe
  - alsa
  - caca
  - fbdev
  - opengl
  - oss
  - pulse
  - sdl
  - v4l2
  - xv
...
MLT detection succeeded, 152 formats, 84 video codecs and 65 audio codecs found.
341 MLT services found.
Loading render profiles...
Proxy encoding MPEG-4 Preset Ultrafast ...available
Proxy encoding MPEG-2 Transport Stream ...available
Loading filters...
MLT service ladspa.1210 not found.
Brightness dropped, MLT version too low for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
Player initialized with profile:  DV/DVD PAL
Autosave started...
Save project autosave_905c4bb2f5b15a618e8f95911b3b6d28
Exiting app...
william@william-System-Product-Name

**Comment by jliljebl** [comment]
You are running Flowblade from 16.04 repositories, not from deb provided here, you are running 0.14, which is from June 18, 2014.

First, elete your current flowblade version with:

sudo apt-get remove flowblade
sudo apt-get autoremove 

...and then follow instructions here: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md

I'm closing this as invalid.

**Comment by explodingword** [comment]
Hi   jliljebl

Just to update you.   the problem was resolved when I changed the OS to
15.10.

I guess 16.4 has a bug or something, because no matter what i did it would
only install flowblade 0.14.

Thank you for being back to me.

William Andrews

**Comment by jliljebl** [comment]
I was so wrong here. They have indeed gone and changed the functionality so that double clicking the .deb file installs the very old version 0.14.

It is possible to install 1.6 from .deb, but you need to use terminal to do it, see updated install instructions here: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md

I don't believe they have gone and done this...

**Comment by jliljebl** [comment]
Closing, as I do not know any possible fix here.
