### ISSUE TITLE
Add "Range Delete" edit action

### ISSUE THREAD

**Issue by velusip** [jliljebl/flowblade#231]
It would be nice to be able to cut into clips across all tracks, including spacers.  Unless I'm doing something wrong, the current alternative is to overwrite a specific length of clip into all the spaced tracks for cutting.  This is sort of a hack and only works well if the clip is resized first, then overwritten into the track.

Background: I'm spacing out many overlayed segments of transparent animations, but trying to cut the base film, and the void between the animations to remain synchronized.

**Comment by jliljebl** [comment]
If I understood correctly your description, I've run into this issue a few times myself which has forced a manual resync between material on different tracks.

The solution I thought of, but have not implemented yet would be a new "Range Delete" edit action which would work as follows:

1. Select a range on Timeline you wish to remove by setting Mark In and Mark Out points
2. Set all tracks from which wish the frame range to be removed.
3. Press "Range Delete" button
4. All material and spacer in the selected range is removed, leaving cuts if Mark In is on material and shortened spacer if Mark In is on top of spacer

Would this work for your use case?

Cutting spacer clip is from internal code point of view very hard to do in a satisfactory way, and is logically wrong too in my view.

Note that using "Spacer"-tool (keyshortcut 6) with CTRL pressed down moves all the material in a **single track** to the right from the pressed clip which can make fixing sync easier in the situation you describe.

**Comment by jliljebl** [comment]
I'm going to add the "Range Delete" functionality to help with this issue.

**Comment by velusip** [comment]
The ability to cut a length of the sequence across multiple tracks, regardless of clips or spacers, would be an ideal feature/solution for the problem I'm having.

I feel like I made a huge mistake by using spacers so often.  For now I calculate the length of a spacer by frames, close the program, edit the configuration file and change the default length of a clip to the exact length of the spacer, drop a transparent clip in, remove the spacer, add dissolve to the transparent clip and use that as my spacer.  I imagine there's a way to edit the project save file directly and replace all spacers with transparent clips, but I was more motivated to complain about it here than just do it. :)

**Comment by velusip** [comment]
I just realized there is an easy way to replace spacers with clips.

- Right click on the spacer and stretch the previous or next clip to cover the spacer.
- Cut the stretched clip where it originally ended/began to retain it's placement.
- Add cuts across all sequencer tracks and prepare to delete a range as intended.
- Apply effects to the remaining bits of stretched clips to hide them.

It's still a roundabout method, but much quicker than my original idea.

**Comment by jliljebl** [comment]
I have to move this 1.10 to concentrate on getting node compositor out for 1.8.

**Comment by jliljebl** [comment]
This now in repository and range delete edit action will be in release 1.10.
