### ISSUE TITLE
Too many audio tracks muted

### ISSUE THREAD

**Issue by ClaudioRomeo** [jliljebl/flowblade#234]
If I work with many audio tracks (e.g. A1, A2 and A3) and I want A2 to be muted, A1 goes mute as well.
In other words, muting an audio track mutes also all upper tracks.

Floblade 1.6.0
Ubuntu 15.10
See my environment in the attached image.
![05_informazioni di sistema_](https://cloud.githubusercontent.com/assets/18627955/14760478/6eb5bc02-0945-11e6-95d9-a1ff5e239c58.png)

**Comment by jliljebl** [comment]
This not happening on system, I'm closing this as invalid.
