### ISSUE TITLE
High memory usage for long renders

### ISSUE THREAD

**Issue by jliljebl** [jliljebl/flowblade#235]
Seem that there are reports of high memory usage when rendering long files. 

https://sourceforge.net/p/mlt/bugs/242/
https://plus.google.com/u/0/+PeterZemlyanukha/posts/QUzBDbj1nbK

**Comment by out-of-order** [comment]
I unfortunately also have problems with high RAM usage.
I'm using debian stretch and MLT 1:6.4.1-dmo1 from the multimaedia repos.
I have 6 GB RAM and a 4GB swap file.
The desktop takes about 0,25GB
After 2 minutes of rendered film material the RAM is full and tha swap file to the half so the system is not responsive anymore.
ffmpeg is 10:3.2.2-dmo3

**Comment by out-of-order** [comment]
setting the same fps for render doesn't raise the memory in my case.

**Comment by jliljebl** [comment]
This has been merged with #327
