### ISSUE TITLE
Copy sequences to another sequences

### ISSUE THREAD

**Issue by jliljebl** [jliljebl/flowblade#237]
This could be useful if user e.g. were to edit a fiction film by splitting scenes into separate sequences.

**Comment by crisisinaptica** [comment]
Hello,
It would be great if Flowblade could let you open a sequence in the _clip_ monitor, select ranges of that sequence, and insert those in another sequence.
That's a feature I used constantly when working with Lightworks.
It's useful for so many things.
As you say, a sequence could be a full scene, but it could also be a clip that needs some audios synchronized.
This is great workflow when managing complex projects.

Best,
-Sergio

**Comment by jliljebl** [comment]
The workflow you suggest is probably doable, but is quite hard to achieve.

There are few possible approaches here:

Approach 1
- make possible to create a compound clip of a sequence by exporting it as a .mlt file and making clip from that file. This will be done any way.
- obviously you can then view that file in clip monitor as it is just a media clip like any other from Flowblade/MLT point of view
- then we would need to to write a lot of special code to deserialize MLT XML into timeline objects. This is doable, but requires *a lot* of effort because Flowlblade does not use MLT XML as save file format

Approach 2
- user opens the source sequence and selects the range that the user wishes to copy to another sequence
- user opens the target sequence, selects the source sequence and does an "Import Range" action from it
- no deserialization code is needed because data is internal Flowblade data

Approach 3
- this is like Approach 2 but with an additional tool that would enable viewing and setting range on source sequence without exiting target sequence

We will probably go for something like Approach 2, but getting there will take some time.

**Comment by jliljebl** [comment]
Combining sequences and creating compound clips features will both be available for 1.14. There probably will not be additional improvement on this area after that release for the time being.
