### ISSUE TITLE
Adding a subtitle file (.srt) crashes flowblade

### ISSUE THREAD

**Issue by denjello** [jliljebl/flowblade#241]
flowblade 1.6, Ubuntu Mint 16.04

I tried importing an .srt file into the media explorer and flowblade crashed.

I guess it crashed because srt is not strictly a media-type and is not really expected behavior, but I thought I would try to import .srt because I needed to quickly burn the external file into the pixel data of the film. The following command is what I ended up using, because I couldn't get it to work with MELT...

`ffmpeg -i NeedSubs.mp4 -vf subtitles=NeedSubs.srt -strict -2 HasSubs.mp4`

So I guess I would mark this more as a feature request.

**Comment by jliljebl** [comment]
This would need to be added in MLT and I do not plan to work on this myself, so I'm closing this as wontfix. If the feature comes available in MLT I can consider sdding support to it.
