### ISSUE TITLE
saving project with new profile changes time range of clipped video

### ISSUE THREAD

**Issue by protonenfalter** [jliljebl/flowblade#242]
environment:
- flowblade 1.6 run as script (no installation)
- Ubuntu Gnome 14.04

steps to reproduce:
- open new project with DVD-profile
- import video to media (here .mp4, HD1080i)
- add video to track V1
- cut off some footage at beginning and end, so that roughly 20 sec out of the middle remain
- save project
- change project profile (-> project -> change project profile) to "HD 1080i 30fps" and save project with new name
- close project
- open project with changed profile

expected result:
- video clip in V1 shows the same time range but in new video format

actual result:
- time range of clip in V1 has changed to a different range (same length but other starting point in original video file)

**Comment by jliljebl** [comment]
This is known issue. Some attempts may be made to improve the situation, but mostly improving here will depend on future contributions.

https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/KNOWN_ISSUES.md

**Comment by jliljebl** [comment]
This was fixed for 1.6 and should work now.
