### ISSUE TITLE
crashing when using transition

### ISSUE THREAD

**Issue by sh2515** [jliljebl/flowblade#245]
ubuntu 16.04
flowblade 1.6

it keeps crashing when I have a few transitions in the video track.
 `segfault at 7f8153e48560 ip 00007f81d584ce1e sp 00007f818100f838 error 4 in libc-2.23.so[7f81d57ae000+1c0000]`

**Comment by jliljebl** [comment]
I'm closing this as invalid as there is too little information to reproduce. If problem persists please create new Issue with detailed preferably step-by-step instructions on how to reproduce.
