### ISSUE TITLE
Fast forward / reverse button

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#247]
[Edited original to refer to button, rather than FastFwd/FastRewind speed option]

Hi,

I would like to see a fast forward/reverse button. Preferably multi-speed (i.e. tap it twice and it goes even faster).

[Edit 03-Jul]
I have seen the jkl implementation and I have started development to piggy-back off that.
That works fine, but there are a couple of questions I have:
1) Is this a feature that should be implemented globally or also as part of user preferences? In the latter case I need to add some code.
2) The space allocated is not big enough to add 2 more buttons. In glassbuttons.py the value of MB_BUTTONS_WIDTH needs to be 400 rather than 317. Is this going to cause a problem elsewhere?
3) In several places there are arrays that depend on the exact button layout (glassbuttons.py: PlayerButtons -> icons, image_x, sensitive, editorwindow.py: connect_player -> pressed_callback_funcs). Would it be a good solution to place the different button definitions in the same file and all these items in a array of a class? This could be populated based on the several options selected and where needed we can just iterate through the array to get all the elements.

I'ld be happy to do the coding. 

Thanks,
Steven.

**Comment by jliljebl** [comment]
I'm going won't fix on this one:

1) I already had them and decided to remove them for cleaner appearance and better small screen support
2) Neither Final Cut X or Adobe Premiere has them, so major commercial apps do not consider them necessary
3) I think both jkl and ctrl+left/right arrow keys seeking are superior solutions to GUI buttons

You are right that there are hard coded indexes for buttons in code, but this can changed when necessery.
