### ISSUE TITLE
Contour Shuttle support

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#248]
Hi,

It would be great to have support for the Contour Shuttle Pro. And/or maybe other jog shuttles, but that's the one I have.

[edit] I can't find any python code to treat the USB events with a callback function. Are there any?
If not it looks like this needs to be done using a timer. I will have a play with it. 

Thanks,
Steven.

**Comment by jliljebl** [comment]
Hi, Flowblade currently has no USB event handling. This will probably need a pull request provided to add the functionality as i do not have hardware.

**Comment by panzth** [comment]
There is a way to use the Shuttle Pro on linux. 
Using this https://github.com/nanosyzygy/ShuttlePRO
There is also a workaround for shuttleXpress. 
It's not very user friendly but it's doable!

**Comment by jliljebl** [comment]
It is unfortunately unlikely that I will work on this.
