### ISSUE TITLE
Play / Pause on the play button?

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#249]
Hi,

Not sure if there is a specific reason to have a Play and a Stop button, but Play / Pause on the same button would be really practical.
If that's not everyone's opinion it could be made an option in user preferences.

**[Edit] Ok, I figured this one out. I have done the changes and issued a pull request so you can review.**

Thanks,
Steven.

**Comment by jliljebl** [comment]
Okay, I'll look at the pull request next week. If it works, I'll apply.

**Comment by jliljebl** [comment]
Fixed by patch from dvdlvr, will be in release 1.8.

**Comment by duanev** [comment]
I'm on 2.4 and a mouse click on play doesn't toggle play/pause.  I guess everyone is using the space bar?

**Comment by dvdlvr** [comment]
You need to enable the single play/pause button in Preferences and restart the application. There is a tickbox. Sent from my Huawei tablet-------- Original message --------From: Duane Voth <notifications@github.com>Date: Mon, 27 Apr 2020, 22:26To: jliljebl/flowblade <flowblade@noreply.github.com>Cc: dvdlvr <dvdlvrdb@gmail.com>, Author <author@noreply.github.com>Subject: Re: [jliljebl/flowblade] Play / Pause on the play button? (#249)
I'm on 2.4 and a mouse click on play doesn't toggle play/pause.  I guess everyone is using the space bar?
