### ISSUE TITLE
Segfault from conflicting GTK versions

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#255]
When I try to open one of my projects I get:

`(flowblade:21451): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported`
`Debugger/breakpoint trap (core dumped)`

The project was created on another system.

**Comment by jliljebl** [comment]
I'm unable to reproduce this.

If you could make the file that causes this available for download, testing it on development system could help solve the issue.

**Comment by apienk** [comment]
Never mind, this was just a single project that was problematic. I can't send it with media files, it is too big. We should have been using snapshots for moving projects across systems.

**Comment by jliljebl** [comment]
Okay, this has probably been some unexplained glitch, these happen.  Closing this wontfix because there probably isn't anything that can be done.
