### ISSUE TITLE
Add feature support to Wikipedia

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#260]
Please, add feature support to Wikipedia, see https://en.wikipedia.org/wiki/Comparison_of_video_editing_software Where possible, add a reference for each feature that is supported.

**Comment by jliljebl** [comment]
I tried to create a wikipedia page bug didn't have enough referenecs I think, page is here https://en.wikipedia.org/wiki/Draft:Flowblade

**Comment by PanderMusubi** [comment]
Try adding references to objective or independent articles and comparisons which have reviewed flowblade.

**Comment by rredesigns** [comment]
@jliljebl I edited the Wikipedia page, and resubmitted it. It was rejected (the guy who does the verification for publishing knows nothing about software, apparently, or anything related. So I wrote him back to clarify some things, and moments ago I received a notification that it has been approved as "start article", so I assume it can be read now like a normal entry. It still needs more polish, but the entry is there now.

Cheers. :)

**Comment by jliljebl** [comment]
@rredesigns Great, thanks. I didn't feel I could have "notability" arguments with Wikipedia on my own behalf, even more so that I did an anonymous submission when creating the article.

**Comment by PanderMusubi** [comment]
I have added it to the article with comparisons. Please add all details and add Flowblade to tables where it can be added too. After this has been done, this issue can be closed as fas as I am concerned.

**Comment by rredesigns** [comment]
Good, we are almost there. I think the only one who can provide that technical detail is @jliljebl, hope he has an account in Wikipedia as editor.

**Comment by jliljebl** [comment]
I'll try make time next week to move forward with this.

**Comment by jliljebl** [comment]
I'll try make time next week to move forward with this. -2017. This is not useful here, maybe there could be discussion on this subject in the forum.
