### ISSUE TITLE
Crash for a special mp4 file

### ISSUE THREAD

**Issue by xstable** [jliljebl/flowblade#265]
If I add a file named : rico_monitorarm.mp4, flowblade crash.

The Video-File could be downloded here: [WeTransfer-File](https://www.wetransfer.com/downloads/9cedf91a30d22de62ec89a51ebf8b0a920161010070256/80551e716fb0f9c632def48b8261dcbe20161010070256/a941bf)

Other Files in the same Directory works well.
Here are the output on the cli, if I add the file **rico_monitorarm.mp4** :

> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc0a400eda0] moov atom not found
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc0a400eda0] moov atom not found
> '/run/media/suther/theBase/suther/MedienDatenbank/Videos/Kleinanzeigen_Amazon/rico_monitorarm.mp4'
> [xcb] Unknown sequence number while processing queue
> [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
> [xcb] Aborting, sorry about that.
> python2: xcb_io.c:274: poll_for_event: Zusicherung »!xcb_xlib_threads_sequence_lost« nicht erfüllt.
> Abgebrochen (Speicherabzug geschrieben)
> 

And here the Full Log, since startup of Floblade:
>FLOWBLADE MOVIE EDITOR repository 1.6

> -------------------------------------
> Launch script dir: /usr/bin
> Running from installation...
> modules path: /usr/share/pyshared/Flowblade
> MLT found, version: 6.2.0
> /usr/share/pyshared/Flowblade/app.py:30: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>   from gi.repository import Gtk
> /usr/share/pyshared/Flowblade/audiomonitoring.py:31: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
>   from gi.repository import PangoCairo
> OS: Manjaro Linux
> Python 2.7.12 (default, Jun 28 2016, 08:31:05) 
> [GCC 6.1.1 20160602]
> GTK+ version: 3.20.9
> User dir: /home/suther/.flowblade/
> Locale: de_DE
> Translations at /usr/share/locale were not found, using program root directory translations.
> Use OS locale language.
> Small height: False
> Small width: False
> mlt_repository_init: failed to dlopen /usr/lib/mlt/libmltopengl.so
>   (libmovit.so.4: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden)
> Detecting environment...
> ---
> video_codecs:
>   - a64multi
>   - a64multi5
>   - alias_pix
>   - amv
>   - apng
>   - asv1
>   - asv2
>   - avrp
>   - avui
>   - ayuv
>   - bmp
>   - cinepak
>   - cljr
>   - dnxhd
>   - dpx
>   - dvvideo
>   - ffv1
>   - ffvhuff
>   - flashsv
>   - flashsv2
>   - flv
>   - gif
>   - h261
>   - h263
>   - h263p
>   - huffyuv
>   - jpeg2000
>   - jpegls
>   - ljpeg
>   - mjpeg
>   - mpeg1video
>   - mpeg2video
>   - mpeg4
>   - msmpeg4v2
>   - msmpeg4
>   - msvideo1
>   - pam
>   - pbm
>   - pcx
>   - pgm
>   - pgmyuv
>   - png
>   - ppm
>   - prores
>   - prores_aw
>   - prores_ks
>   - qtrle
>   - r10k
>   - r210
>   - rawvideo
>   - roqvideo
>   - rv10
>   - rv20
>   - sgi
>   - snow
>   - sunrast
>   - svq1
>   - targa
>   - tiff
>   - utvideo
>   - v210
>   - v308
>   - v408
>   - v410
>   - vc2
>   - wrapped_avframe
>   - wmv1
>   - wmv2
>   - xbm
>   - xface
>   - xwd
>   - y41p
>   - yuv4
>   - zlib
>   - zmbv
>   - libopenjpeg
>   - libschroedinger
>   - libtheora
>   - libvpx
>   - libvpx-vp9
>   - libwebp_anim
>   - libwebp
>   - libx264
>   - libx264rgb
>   - libx265
>   - libxvid
>   - h264_vaapi
>   - hevc_vaapi
>   - mjpeg_vaapi
> ...
> ---
> audio_codecs:
>   - comfortnoise
>   - s302m
>   - aac
>   - ac3
>   - ac3_fixed
>   - alac
>   - dca
>   - eac3
>   - flac
>   - g723_1
>   - mp2
>   - mp2fixed
>   - nellymoser
>   - real_144
>   - sonic
>   - sonicls
>   - tta
>   - vorbis
>   - wavpack
>   - wmav1
>   - wmav2
>   - pcm_alaw
>   - pcm_f32be
>   - pcm_f32le
>   - pcm_f64be
>   - pcm_f64le
>   - pcm_mulaw
>   - pcm_s8
>   - pcm_s8_planar
>   - pcm_s16be
>   - pcm_s16be_planar
>   - pcm_s16le
>   - pcm_s16le_planar
>   - pcm_s24be
>   - pcm_s24daud
>   - pcm_s24le
>   - pcm_s24le_planar
>   - pcm_s32be
>   - pcm_s32le
>   - pcm_s32le_planar
>   - pcm_u8
>   - pcm_u16be
>   - pcm_u16le
>   - pcm_u24be
>   - pcm_u24le
>   - pcm_u32be
>   - pcm_u32le
>   - roq_dpcm
>   - adpcm_adx
>   - g722
>   - g726
>   - adpcm_ima_qt
>   - adpcm_ima_wav
>   - adpcm_ms
>   - adpcm_swf
>   - adpcm_yamaha
>   - libgsm
>   - libgsm_ms
>   - libmp3lame
>   - libopencore_amrnb
>   - libopus
>   - libspeex
>   - libvorbis
> ...
> ---
> formats:
>   - a64
>   - ac3
>   - adts
>   - adx
>   - aiff
>   - amr
>   - apng
>   - asf
>   - ass
>   - ast
>   - asf_stream
>   - au
>   - avi
>   - avm2
>   - bit
>   - caf
>   - cavsvideo
>   - crc
>   - dash
>   - data
>   - daud
>   - dirac
>   - dnxhd
>   - dts
>   - dv
>   - eac3
>   - f4v
>   - ffm
>   - ffmetadata
>   - filmstrip
>   - flac
>   - flv
>   - framecrc
>   - framehash
>   - framemd5
>   - g722
>   - g723_1
>   - gif
>   - gsm
>   - gxf
>   - h261
>   - h263
>   - h264
>   - hash
>   - hds
>   - hevc
>   - hls
>   - ico
>   - ilbc
>   - image2
>   - image2pipe
>   - ipod
>   - ircam
>   - ismv
>   - ivf
>   - jacosub
>   - latm
>   - lrc
>   - m4v
>   - md5
>   - matroska
>   - matroska
>   - microdvd
>   - mjpeg
>   - mlp
>   - mmf
>   - mov
>   - mp2
>   - mp3
>   - mp4
>   - mpeg
>   - vcd
>   - mpeg1video
>   - dvd
>   - svcd
>   - mpeg2video
>   - vob
>   - mpegts
>   - mpjpeg
>   - mxf
>   - mxf_d10
>   - mxf_opatom
>   - null
>   - nut
>   - oga
>   - ogg
>   - oma
>   - opus
>   - alaw
>   - mulaw
>   - f64be
>   - f64le
>   - f32be
>   - f32le
>   - s32be
>   - s32le
>   - s24be
>   - s24le
>   - s16be
>   - s16le
>   - s8
>   - u32be
>   - u32le
>   - u24be
>   - u24le
>   - u16be
>   - u16le
>   - u8
>   - psp
>   - rawvideo
>   - rm
>   - roq
>   - rso
>   - rtp
>   - rtp_mpegts
>   - rtsp
>   - sap
>   - segment
>   - stream_segment,ssegment
>   - singlejpeg
>   - smjpeg
>   - smoothstreaming
>   - sox
>   - spx
>   - spdif
>   - srt
>   - swf
>   - tee
>   - 3g2
>   - 3gp
>   - mkvtimestamp_v2
>   - truehd
>   - uncodedframecrc
>   - vc1
>   - vc1test
>   - voc
>   - w64
>   - wav
>   - webm
>   - webm_dash_manifest
>   - webm_chunk
>   - webp
>   - webvtt
>   - wtv
>   - wv
>   - yuv4mpegpipe
>   - alsa
>   - fbdev
>   - oss
>   - pulse
>   - sdl
>   - v4l2
> ...
> MLT detection succeeded, 152 formats, 89 video codecs and 63 audio codecs found.
> 383 MLT services found.
> Loading render profiles...
> Proxy encoding MPEG-4 Preset Ultrafast ...available
> Proxy encoding MPEG-2 Transport Stream ...available
> Loading filters...
> MLT service ladspa.1406 not found.
> MLT service ladspa.1433 not found.
> MLT service ladspa.1408 not found.
> MLT service ladspa.1431 not found.
> MLT service ladspa.1901 not found.
> MLT service ladspa.1438 not found.
> MLT service ladspa.1195 not found.
> MLT service ladspa.1402 not found.
> MLT service ladspa.1185 not found.
> MLT service ladspa.1213 not found.
> MLT service ladspa.1904 not found.
> MLT service ladspa.1903 not found.
> MLT service ladspa.1215 not found.
> MLT service ladspa.1216 not found.
> MLT service ladspa.1410 not found.
> MLT service ladspa.1892 not found.
> MLT service ladspa.1194 not found.
> MLT service ladspa.1197 not found.
> MLT service ladspa.1423 not found.
> MLT service ladspa.1910 not found.
> MLT service ladspa.1417 not found.
> MLT service ladspa.1210 not found.
> MLT service ladspa.1198 not found.
> MLT service ladspa.1905 not found.
> MLT service ladspa.1201 not found.
> Brightness dropped, MLT version too high for this filter.
> Brightness Keyframed dropped, MLT version too high for this filter.
> Loading transitions...
> RGB Adjustment dropped for Color Adjustment
> Hue dropped for Color Adjustment
> Gamma dropped for Lift Gain Gamma
> G'MIC NOT found
> Player initialized with profile:  DV/DVD PAL
> Selected color NOT detected
> BG color detected
> [swscaler @ 0x7f903423f840] Warning: data is not aligned! This can lead to a speedloss
> Loading unbenannt.flb, SAVEFILE_VERSION: 5
> Player initialized with profile:  HD 720p 23.98 fps
> Deleting /home/suther/.flowblade/autosave/autosave_0740013d06a6e8410b277def40c563ff
> Autosave started...
> Save project autosave_826c3ed4fba922f2ec51b9ab4ad9d573
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f9044013aa0] moov atom not found
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f9044013aa0] moov atom not found
> '/run/media/suther/theBase/suther/MedienDatenbank/Videos/Kleinanzeigen_Amazon/rico_monitorarm.mp4'
> [xcb] Unknown request in queue while dequeuing
> [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
> [xcb] Aborting, sorry about that.
> python2: xcb_io.c:179: dequeue_pending_request: Zusicherung »!xcb_xlib_unknown_req_in_deq« nicht erfüllt.
> 
> (flowblade:9427): Gdk-WARNING **: flowblade: Fatal IO error 11 (Die Ressource ist zur Zeit nicht verfügbar) on X server :0.
>

**Comment by xstable** [comment]
Even if the Video seems to be broken, flowblade shouldn't crash, but give a notice for this.

**Comment by jliljebl** [comment]
Video file is indeed broken, neither Gnome Video or VLC open it.

Flowblade does not crash on my system however, I get the "Can't open non-valid media" dialog just like I should here for broken video.

I'm closing this as *invalid* since the described behavior is not observed on development system, and the reasons for it occurring on other systems are very likely not related to Flowblade source code.

**Comment by Celelibi** [comment]
For what it's worth, I get the very same crash with a file flowblade doesn't want to read (althought it should be perfectly valid).
And I found the reason why it crash.

The following line should be surrounded by `Gdk.thread_enter()` and `Gdk.thread_leave()`. 
https://github.com/jliljebl/flowblade/blob/71d72ac9c3b23796b33176dc3c66e1b2121c64d5/flowblade-trunk/Flowblade/projectaction.py#L224

Since it's related to thread synchronization, having fewer CPU cores might hide the bug by forcing some actions to be serialized.
