### ISSUE TITLE
Watermark - Block file choosing dialog

### ISSUE THREAD

**Issue by xstable** [jliljebl/flowblade#266]
**Flowblade 1.6.0**
 
if you try to set Watermark (on Manjaro-Linux), it opens the File dialog. 
Before you can choose a file, you have to close the "watermark" dialoge. Only if this dialoge is closed, you be able to select files in the File-Dialoge.﻿

**Comment by jliljebl** [comment]
Fixed in repository, will be in 1.10 release.

The behavior of GTK modal dialogs had changed at some point.
