### ISSUE TITLE
Filenames in Media-List

### ISSUE THREAD

**Issue by xstable** [jliljebl/flowblade#267]
**Flowblade 1.6.0**

I can't really read the filenames in the media-list. There is no way to show a list (minimum is 2 columns). And on mouseover, the filename is not shown.

Please add the option to show a filelist (maybe without thumbs in front of the Filename

![auswahl_030](https://cloud.githubusercontent.com/assets/1778068/19392940/1c5f1562-9233-11e6-906d-e41728241083.jpg)

**Comment by jliljebl** [comment]
I just pushed a patch that shows file name as tooltip for mouse over.

I'm leaving this open with *Help Wanted* label, which effectively means that this i not happening unless a pull request is provided,  there are many other improvements that I consider more important.

**Comment by jliljebl** [comment]
This was fixed by contribution, will be in 1.12.
