### ISSUE TITLE
Feature request : support for more image formats

### ISSUE THREAD

**Issue by ChameleonScales** [jliljebl/flowblade#268]
I think it would be very useful to have support for more image formats such as exr, iff or others. Currently we have to convert images, sometimes destructively, which means we have to keep the originals.  This can waste a lot of storage and time.
Could this idea be considered ?

**Comment by jliljebl** [comment]
This can only be fixed in MLT and I'm not currently planning on working on this, so I will close this as *wontfix*. If any new for mats become available via MLT, Flowblade will naturally support them.
