### ISSUE TITLE
Sequence Move Tool

### ISSUE THREAD

**Issue by jliljebl** [jliljebl/flowblade#270]
The purpose of this is to be able to move multi track compositions in a single edit
- User selects a range of clips on track _V1_ and **only** on track V1
- This selection defines a group of clips consisting of all clips and compositors fully contained in the timeline range defined by clips in track _V1_.
- This group will then be inserted in any edit point on track _V1_ and only on track _V1'.  Additional restriction is that no clips on other tracks may go ever the frame of insert frame on track *V1_.

**Comment by jliljebl** [comment]
This will be 1.12 as new Overwrite Box tool.

**Comment by montagist** [comment]
jesus christ moving things around in this program is arbitrarily difficult
