### ISSUE TITLE
How can I make "Render Timeline" export to /home/username/Downloads?

### ISSUE THREAD

**Issue by orschiro** [jliljebl/flowblade#271]
This preference did not change the behaviour:

![image](https://cloud.githubusercontent.com/assets/170947/19677679/b70c3210-9a9a-11e6-93e5-878816607d55.png)

**Comment by jliljebl** [comment]
Press file select button after "Folder" label in "Render" panel.

Closing as invalid as there is no fixable issue here.

**Comment by orschiro** [comment]
![image](https://cloud.githubusercontent.com/assets/170947/19755301/168c03c0-9c15-11e6-940f-cebe61289c6a.png)

**Comment by orschiro** [comment]
Thank you very much!

Apologies if this was the wrong place to ask.

Should I ask questions like these on Google+?

Regarding the question, I found it!

Can I make this a default for all new projects or do I have to set this for
each project individually?
