### ISSUE TITLE
Use GitHub releases for downloadable .deb packages instead of DropBox

### ISSUE THREAD

**Issue by JonasCz** [jliljebl/flowblade#273]
I think it would be a nice to use this repository to host the [downloadable .deb](https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md).

If you use [GitHub releases](https://help.github.com/articles/creating-releases/) to host the downloads, you won't have the limitations / issues of DropBox (such as the nag to create a DB account or bandwidth limits).

**Comment by jliljebl** [comment]
Thanks, good pointer, I didn't know this existed. It allows adding binary files too, so this might be the way to go in the future. I'll look more throughly at this when I do the next release.

**Comment by probonopd** [comment]
I also generated an x86_64 [AppImage](http://appimage.org/) for testing using the provided deb as an ingredient:
https://github.com/probonopd/AppImages/blob/master/recipes/meta/Flowblade.yml

It can be downloaded for testing here:
https://bintray.com/probono/AppImages/Flowblade_Movie_Editor/_latestVersion#files

Just download the AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run. No installation necessary, no root needed, no system libraries changed.

It is expected that some fine-tuning might be needed, so please test it on as many distributions (2014ish and newer) as you can. Usually some fine-tuning from upstream authors is required to make a polished AppImage.

Providing an AppImage would have, among others, these advantages:
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed
- No root needed
- One app = one file = super simple for users
- Optional(!) desktop integration with `appimaged`
- Binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can GPG2-sign your AppImages (inside the file)

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by JonasCz** [comment]
This is awesome ! 

Is MLT bundled in the AppImage, so it doesn't depend on the system MLT, thus avoiding incompatibilities with the Kdenlive one ?

Any chance of a 32bit one ?

**Comment by probonopd** [comment]
Yes, MLT is bundled. I personally don't do 32bit ones, but mine is just an example anyway.

**Comment by jliljebl** [comment]
Ok, great, I downloaded the Appimage file and will do tests with it sometime next week.

 I'll also try understand a bit better how this works, and try to create an Appimage myself. I'll comment here when I have more results and understanding of this. 

I might choose Appimage as the universal package format to distribute Flowblade over Snap and Flatpack because I don't need sandboxing.

**Comment by probonopd** [comment]
@jliljebl did you have a chance to look at it yet?

**Comment by jliljebl** [comment]
I successfully installed and ran on the AppImage on Ubuntu and elementaryOS. Most of the delay here was trying to get Fedora with Guest Additions working here to test, but no joy, so I couldn't test on Fedora 24.

But I assume that works there too. 

Next I'm going to try to make my own version of AppImage to have one available for next release.

@probonopd Are you doing these AppImages of all releases of the quite large collection of software you had made available? And if so, how fast do you update your releases? For Flowblade it seemed that you needed the .deb available to make the AppImage, right?

**Comment by probonopd** [comment]
@jliljebl I am doing mine mostly as examples for upstream projects to pick them up and provide official ones (continuous ones even, in the best case). My recipes are largely automated, so that if a newer version of the upstream software is available, it's a matter of triggering the AppImage generation to push a new version out.

**Comment by jliljebl** [comment]
This was done for 1.10 and will done for all further releases.

**Comment by probonopd** [comment]
Updated https://github.com/probonopd/AppImages/blob/master/recipes/meta/Flowblade.yml accordingly.

**Comment by sieger707** [comment]
I dont see app image file as yet in any of the links. I running into bunch o errors trying to install  the deb on  puppy linux . I want to do away with regular install - can someone pl point me to an app image  or how can I make one myself
