### ISSUE TITLE
Video with 240 fps

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#274]
Hello,

imported an video with 240 fps, recorded with iphone 6. But flowblade recognize it as 23,98 fps. Not 25, not 30, 50 or 60 fps. Exactly 23,98 fps. Can you fix this please?

Creating a slow motion video with a part of the 240 fps video, the file is not synchron with the normal speed rest.
But i think this is a effect of the not supported 240 fps!?

Thx in advance!

Regards, Oluja!

**Comment by jliljebl** [comment]
HI, would be possible to a get sample of the type of file in question here, if you could make one available to download somewhere? Testing with a file would be the best approach here.

**Comment by oluja1973** [comment]
Of course: Here is the link to 240 fps video todownload:
https://cloud.gmx.net/ngcloud/external?guestToken=f_rA20W9SJiXNYk94Z0VHA&loginName=oluja@gmx.at

**Comment by oluja1973** [comment]
Hello Jane,

have you take a look on this issue? flowblade still tells me that the video have 23.98 fps which is wrong. Also slow motion video are not synchrone with this 240 fps videos. And 240 fps videos are ideal for slow motion parts.

Can you check this if you have time?

Thx Mario!

**Comment by jliljebl** [comment]
Yeah, it really says that it is 240fps video. I created a user profile with240fps and loaded the file in it and it seemed to have multiple frames of same image. 

I don't think MLT works with this video and I'm not willing to spend time to get it done, so I'm closing this as *wonfix*. If someone is willing to work on MLT to make this video work I will revisit the issue.
