### ISSUE TITLE
Popup by changing project

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#277]
When closing flowblade, a popup appear to remind the user if he wanna save the project. Good thing because of possibility to loose the work if not saving.

But when chnaging the project inside flowblade, via the "open recent" point, flowblade load the other project without asking to save the actually project.

So it can be, if the project was not saved before, that your work is lost.

Not a bad point for me, because always saving my project more times then neccessary, but for other user maybe.

**Comment by jliljebl** [comment]
Confirmed, will be fixed.

**Comment by jliljebl** [comment]
Fixed in repository, will be in 1.10.
