### ISSUE TITLE
flowblade can create appimage?

### ISSUE THREAD

**Issue by manuelsongokuh** [jliljebl/flowblade#282]
hi appimage is full comfortable! So flowblade can to use in appimage?

(64bit and 32bit, stable,unstable..)

**Comment by jliljebl** [comment]
This is discussed in issue #273, I'm trying to do one yes, but I'll probably only do a 64-bit one.

**Comment by jliljebl** [comment]
This should be available for 1.12.

**Comment by manuelsongokuh** [comment]
thank you!!!!!!

**Comment by jliljebl** [comment]
Well, I just spend 3 hours on this and was very frustrated. I'm changing this to undecided. I will do one of these (Appimage, snap, Flatpack) , the one I do will be the one I successfully complete.

**Comment by jliljebl** [comment]
Merged with #453, closing.
