### ISSUE TITLE
Spacer tool bug

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#285]
Hello,

i found out how i can reproduce very easy the bug with the spacer tool and uploaded a video. I also tested it with the newest github version and the bug also exists there.
But see:

https://youtu.be/aXi6zd-ff7M

Regards, Mario!

**Comment by jliljebl** [comment]
Confirmed.

**Comment by jliljebl** [comment]
Fixed in repository, will be in 1.10. Good catch, for some reason this case has been missed completely.
