### ISSUE TITLE
Overwriting file

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#286]
Hello,

it would be fine when theres a popup which warns that a file already exists. When rendering a project flowblade is rendering it without checking if the file already exists.
So flowblade overwrites the old file. Data may be lost.

Regards, Mario!

**Comment by jliljebl** [comment]
I'll add a preference for this.

**Comment by jliljebl** [comment]
This is now new default behavior and there is no preference for it. Will be in 1.14
