### ISSUE TITLE
Portrait mode wrong

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#287]
As we discuss in the Google group, there is a bug with the portrait mode. But see the video.

https://www.youtube.com/watch?v=B4FjScNpBbk

**Comment by oluja1973** [comment]
Original file to test, can be downloaded here:
https://cloud.gmx.net/ngcloud/external?guestToken=f_rA20W9SJiXNYk94Z0VHA&loginName=oluja@gmx.at

Its the video namend "Rosi".

Regards, Mario!

**Comment by oluja1973** [comment]
The name from the video is "IMG_1208.MOV" not Rosi. Sorry for this!

**Comment by jliljebl** [comment]
Confirmed and Shotcut seems to do it right automatically, so this is possible to fix in Flowblade.

**Comment by oluja1973** [comment]
But in shotcut you cant rotate it or zoom it to fit it to page. Please don't make it in this way. This is horrible. Then ist better to live with the flowblade mode. Much more better.

**Comment by dvdlvr** [comment]
On Flowblade 1.10 and Ubuntu 16.10 this doesn't happen. I loaded the clip, opened it in Clip monitor and dragged it to the timeline. Always upright and showing the full video.
Interestingly, the video shows sideways in mplayer and xine and starts off sideways in Totem, but it is then rotated to show upright.
![fb-screen-1](https://cloud.githubusercontent.com/assets/7942463/22550090/b81edc36-e94e-11e6-97d9-760e11971af0.png)
![fb-screen-2](https://cloud.githubusercontent.com/assets/7942463/22550098/be5a448c-e94e-11e6-83b8-b09e473b294a.png)

**Comment by oluja1973** [comment]
I just tested it with flowblade 1.10 under ubuntu 16.04 LTS. Also with the actually github version. But still the same problem (se screenshot). Can it be that it depends on the MLT version? If i remember it right, you have version 6.2. Im still working on 6.0 which is default on my system.

![rosi](https://cloud.githubusercontent.com/assets/23220631/22552979/5544a87c-e95b-11e6-9be5-855aa9e83bf7.png)

**Comment by jliljebl** [comment]
Works here now too. I'm 99% sure that MLT 6.2.0 fixes this (I haven't written a single line of code to address this) and I'm closing this as *fixed upstream".

![screenshot from 2017-02-02 16-26-28](https://cloud.githubusercontent.com/assets/1823444/22553219/9c033c2a-e964-11e6-81b9-114f0a250783.png)
