### ISSUE TITLE
Wipe clip lenght bug

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#292]
Found a bug in the wipe clip lenght transition. Please see the video.

Regards, Mario!

https://www.youtube.com/watch?v=JonSUEaYFhw

**Comment by jliljebl** [comment]
Maybe I'm not understanding something but seemed to work.

Video only bug reports are not very useful (and force very high work load on developer), please add textual description of the perceived problem.

**Comment by jliljebl** [comment]
I'm closing as *unresolved* because I do not understand the problem. I can reopen if further clarification is provided.
