### ISSUE TITLE
Lintian warnings about non standard perm on files and dirs.

### ISSUE THREAD

**Issue by eumesmamente** [jliljebl/flowblade#298]
I found this on 1.10.0-1 deb package:
[flowblade_lintian_output.txt](https://github.com/jliljebl/flowblade/files/661958/flowblade_lintian_output.txt)

**Comment by jliljebl** [comment]
Ok, this will be fixed.

**Comment by jliljebl** [comment]
This was fixed to only 2 warnings for 1.14. The remaining 2 are not worth much work.
