### ISSUE TITLE
Version 1.10 with syntax error

### ISSUE THREAD

**Issue by orschiro** [jliljebl/flowblade#299]
On Ubuntu 16.10 when performing an apt installation of any software: 

/usr/share/menu/flowblade: 1: /usr/share/menu/flowblade: Syntax error: word unexpected (expecting ")")

**Comment by pleabargain** [comment]
confirmed
Processing triggers for menu (2.1.47ubuntu1) ...
/usr/share/menu/flowblade: 1: /usr/share/menu/flowblade: Syntax error: word unexpected (expecting ")")

4.4.0-57-generic GNU/Linux

**Comment by gregorydk** [comment]
It's because `/usr/share/menu/flowblade` is executable.

To fix it do: `sudo chmod 644 /usr/share/menu/flowblade`

**Comment by orschiro** [comment]
Thank you! :-)

**Comment by gregorydk** [comment]
@orschiro That's a manual fix, but it's still an issue that needs fixing by the devs.

**Comment by jliljebl** [comment]
@gregorydk Yeah, I'll do a new package next week, thanks pointing out the exact cause. The bloody thing both installed and ran on the three VM OSses I tested it on, but not on 16.10 then.

 It would be good if it failed on all systems, not just on some. Also the *dpkg-deb --build* refused to run on some other file permissions, but agreed to do the package with these permissions causing this issue. Fixing the lintian bug #298 will fix this too I think.

**Comment by jliljebl** [comment]
Doing a new 1.0 .deb seems unlikely now this be fixed for 1.12 .deb package.

**Comment by jliljebl** [comment]
This is fixed in 1.12 package.

**Comment by aitoehigie** [comment]
This issue is back
