### ISSUE TITLE
Add Fade In/Out filters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jliljebl/flowblade#30]
```
Make possible to do Fade ins and outs with dedicated filters.


```

Original issue reported on code.google.com by `janne.li...@gmail.com` on 30 Dec 2012 at 7:36

**Comment by jliljebl** [comment]
After cover-on-delete functionality for fade-ins and -outs it is considered that this use case is adequately covered, and the required MLT side contributions for the desired way to do this are not forthcoming.
