### ISSUE TITLE
prolonged use (over 1hour) python eats up 50% of Ram and memory

### ISSUE THREAD

**Issue by pleabargain** [jliljebl/flowblade#300]
OS: 4.4.0-57-generic GNU/Linux

Flowblade starts fast... 
I have been rendering between markers (application seemed more responsive/faster to do that rather than moving parts of the movie around)

but I noticed it got steadily slower with each render

I checked $top
and 3 instances of python were using a total of 50% of RAM and memory on my machine
workaround(?):
shutdown flowblade between renders/edits. 

desired:
mem is kept clean/empty after a render or edit to keep flowblade speedy

**Comment by jliljebl** [comment]
This has been merged with #327.
