### ISSUE TITLE
Feature request: timeline following key jumps

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#303]
Hi Janne,

the git version include now the end key feature. Great! :-) As you know, ist possible in this version to jump with pos 1 to the beginning of the project and with the end key to the end of the project.

Also its possible to jump to the cuts with the keys arrow up and arrow down.

But, when the whole project dosnt fill the timeline, the timeline cursor jumps out of the picture. Is it possible to add the feature that the timeline is following the jumps? It would be fine that the cursor is centered in the project middle when jumping with the keys.

Thanks and regads, Mario!

**Comment by jliljebl** [comment]
Yes,I think there are a few instances where timeline display could made to follow jumping frame pointer, I'll look into this before next release.

**Comment by jliljebl** [comment]
Fixed in repository, will be in 1.12.
