### ISSUE TITLE
Feature request: save dialogue

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#305]
Hello,

flowblade is always askin, when closing the project, if the user wanna save the project. Also if nothing have been changed.
Also this save dialogue appears if you open empty flowblade and close it.

It would be fine if this save dialougue only opens when a change have been made.

Regards, Mario!

**Comment by jliljebl** [comment]
Computing this reliably is going to be too tricky, I'm just going to go *wonfix* with this, even though having this would be marginally useful.
