### ISSUE TITLE
Magnetize Trimming

### ISSUE THREAD

**Issue by benrob0329** [jliljebl/flowblade#310]
It would be extraordinarily helpfully to have cutting/trimming "snap" to other tracks.

**Comment by jliljebl** [comment]
Yeah, this could be offered optionally.

**Comment by jliljebl** [comment]
Magnetizing cutting would require making dragging frame pointer magnetized.There already is functionality with up and down arrows that move the frame pointer to next cut and this is a better way to to create a cut on same frame as a cut that exists on another track.

Magnetizing trimming however will be done.

**Comment by jliljebl** [comment]
This is in repository and will be on 1.12.
