### ISSUE TITLE
Allow Clip Length To Be Manually Entered

### ISSUE THREAD

**Issue by benrob0329** [jliljebl/flowblade#311]
Handy for pictures & outros.

**Comment by jliljebl** [comment]
Are you proposing something like the following workflow?

1. User opens the clip context menu by right clicking on clip on timeline.
2. An options such as "Set clip length" is displayed on context menu.
3. A dialog opens, user enters length and after clicking OK the clip length changes.

**Comment by benrob0329** [comment]
That would work, I was thinking about just changing the label in clip properties to a numbox and adding a cancel button to it.

**Comment by oluja1973** [comment]
Very good idea benrob. This really would help in a few situations.

**Comment by jliljebl** [comment]
I will combine this with some other edit actions and create a "Edit" sub menu for clip context popup menu.

**Comment by Efenstor** [comment]
Manually entering a transition (compositor) length would be great as well. And an indicator of clip shift is needed. I mean, when creating a transition, you need first to create an overlap, but without such an indicator you cannot create an overlap of precise length.

**Comment by jliljebl** [comment]
The feature for entering clip length is now in repo and will be in 1.14. Closing this as "feature added"

Giving compositor length using keyboard can be done when GUI design is decided on, the question is do we access the feature from a pop-up menu or text enter box in "Compositors" panel or both.

On the last idea "... indicator of clip shift", @Efensor do you mean  a delta number displayed as timeline overlay when clip is moved with Overwrite tool?

**Comment by Efenstor** [comment]
Yeah, it is. Now it's the part of https://github.com/jliljebl/flowblade/issues/397

**Comment by jliljebl** [comment]
This is now in repo.
