### ISSUE TITLE
Add Option To Keep Aspect Ratio In Affine Blend

### ISSUE THREAD

**Issue by benrob0329** [jliljebl/flowblade#313]
It would be handy to have an option to keep the aspect ratio when scaling in Affine Blend etc. Something like a diagonal arrow in the corner or a checkbox.

**Comment by oluja1973** [comment]
Theres a Workaround in the affine blend. I use this often. Rescale the Video and the click on the option button and choose to set the correct aspect ratio.
But resizing with aspect ratio would be fine.

**Comment by jliljebl** [comment]
Yes, adding option to maintain aspect ration while dragging could be useful, but like oluja said  you can get aspect ration back using action.

I'll do this eventually not sure if it makes the next release.

**Comment by jliljebl** [comment]
This is now resolved by making modifier key CONTROL keep aspect ratio when dragging Affine Blend  scale handles.  Will be in 1.12.
