### ISSUE TITLE
feature request: affine blend move with arrow keys

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#314]
When adding affine blend and move the Picture from left to right or something in this way, and doing this with the arrow keys, ist very slow.
Is it possible to speed it up?

**Comment by jliljebl** [comment]
Well, I think we could add Control key move image 10px at a time. The default action has to be 1px so that all positions are reachable by keys.

**Comment by jliljebl** [comment]
This is fixed by making image move 10px for every arrow keys press if Control modifier key is held down, will be in 1.12.
