### ISSUE TITLE
Add ZOOM to filters

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#316]
Please add the Zoom / Pan option to the filters.
Below is something that works.

Please note the av.d entry is mandatory and, as far as I can see, it needs to be 1 to apply it to every frame - I can't figure out how to use a fixed value without displaying it.
There are other values that can be implemented, but these are a good start. Obviously the 0,500 / 0,5 range in the zoom is quite arbitrary, but it allows a 5x zoom on the picture. That should be sufficient for most people, I guess.

Implementing this allows you to zoom in on the picture and then move the zoomed picture around to get the part you want into the center.

    <filter id="avfilter.zoompan">
        <name>Zoom Pan</name>
        <group>Transform</group>
        <property name="av.zoom" args="range_in=0,500 range_out=0,5 displayname=Zoom">1</property>
        <property name="av.x" args="range_in=0,SCREENSIZE_WIDTH range_out=0,SCREENSIZE_WIDTH displayname=x">0</property>
        <property name="av.y" args="range_in=0,SCREENSIZE_HEIGHT range_out=0,SCREENSIZE_HEIGHT displayname=y">0</property>
        <property name="av.d" args="range_in=0,1 range_out=0,1 displayname=Duration!(Should!be!1)">1</property>

Thanks.

**Comment by jliljebl** [comment]
Ah, this from the libavfilter that was added to MLT 6.2.0. I will 100% do this. maybe even for next release, 

This kind of Zoom/Pan thing has been on of the most requested features but previous previous MLT solutions were not satisfactory. If libavfilter offers a better solution this is a very good thing.

I've sort only used MLT features available in latest Ubuntu, but I'm actually still in 16.04. If 16.10 has MLT 6.2.0 this will be in next release, otherwise it comes in the one after that.

**Comment by dvdlvr** [comment]
Yep, from libavfilter.And yes, I'm on 16.10. This filter is listed as available in the startup of flowblade on 16.10 (visible on the command line) that's why I took a closer look at it.Performance is pretty good. It's about 3x faster than doing the same thing in kdenlive (30m on my test file of 50m vs 100m in kdenlive).


Sent from Samsung tablet

-------- Original message --------

**Comment by jliljebl** [comment]
Excellent, I'll add this next release.

**Comment by dvdlvr** [comment]
Great, thanks.

**Comment by oluja1973** [comment]
Hello,

can somebody tells me how this pan and zoom effect will work? At the Moment ist possible with the affine or pip effect to pan and zoom. Whats the difference between the new pan and zoom.

Thanks Mario

**Comment by dvdlvr** [comment]
I don't see how to zoom in with the 'affine' effect. It seems to only move the clip around using the x and y sliders. The width slider doesn't seem to zoom in on the clip.
And I can't find the 'pip' effect.
Anyway, the Zoom / Pan effect works as follows:
1) Drag the effect over the clip in the timeline you want it to apply to.
2) Drag the Zoom slider so that the size of the output is what you want it to be
3) Drag the x and y sliders to position the output where you want it

Final implementation may be different from my test setup.

![flowblade-orig](https://cloud.githubusercontent.com/assets/7942463/22210853/79e85034-e18b-11e6-8b50-7bdcd6b0229a.png)
![flowblade-zoom](https://cloud.githubusercontent.com/assets/7942463/22210854/79f2d36a-e18b-11e6-8880-dde1e6d6923c.png)
![flowblade-zoom-pan](https://cloud.githubusercontent.com/assets/7942463/22210855/79fec472-e18b-11e6-9db3-790cc0437124.png)

**Comment by jliljebl** [comment]
The current Compositors "Affine Blend" and "Picture-in-picture" work fine for Zoom/Pan functionality.

The current "Transform->Affine" Filter however does actually often respect the "Width" parameter so you can not zoom with it. Its basically garbage.

This is a Filter would allow zooming image without using a Compositor, a use case that seems to be desired as many users do not discover that the use case can be satisfied using Compositors.

**Comment by jliljebl** [comment]
I updated to 16.10 and MLT 6.2.0 and avfilter.zoompan seems to be working. I'll do some tests before I push.

**Comment by oluja1973** [comment]
Hello dvdlvr,

in the first screenshot you can see the beginning of a picture. Added the affine blend and set a keyframe. At the keyframe position i zoomed in. So its a nice zoom effect with the affine blend.

Whats exactly the difference to the zoom/pann effect? Im sorry but im still not understand it (shame on me).

Regards, Mario!

![a1](https://cloud.githubusercontent.com/assets/23220631/22324501/fd3040a8-e3a9-11e6-93a8-0443804db504.png)
![a2](https://cloud.githubusercontent.com/assets/23220631/22324502/01f70edc-e3aa-11e6-81d4-6ecc934520b9.png)

**Comment by jliljebl** [comment]
@oluja1973 You are using a *Compositor* to achieve this.

Zoom/Pan is a *Filter*.

They different ways of doing the same thing.

**Comment by oluja1973** [comment]
Yes i have seen this. But both are doing the same things? Correct? Is this not active in the github version because i have seen in the log that you added this.

**Comment by jliljebl** [comment]
Compositors do compositing also, Filter just transforms the image, but from Zoom/pan point view they do the same thing.  Well, "Affine Blend" does rotation too.

**Comment by jliljebl** [comment]
This is in repository will be in 1.12
