### ISSUE TITLE
Feature request - real_time parameter

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#319]
Hi,

The real_time parameter for mlt allows to split handling of data over several cores on a multi-core system.
In theory you should, if I remember right, set it to the amount of real cores (i.e. not software cores).
On my i7 with 4 cores (8 virtual) a setting of -2 instead of the standard -1 increases the rendering performance significantly (From 1h10m to 35m for my test file). -3 will make it yet another 2-3m faster. From -4 to -8 it actually increases the render time again.

It would be great if we could have a preference setting where the user can fine tune the real_time value in order to optimize render time on our particular system.

If you don't have an objection to this I'll happily do the coding.

Test setting used:
renderconsumer.py - get_img_seq_render_consumer + get_mlt_render_consumer
...
consumer.set("real_time", -2)
instead of -1

**Comment by jliljebl** [comment]
I have no objection to adding this. If you get it working, I will happily apply the pull request.

If you add the selection GUI for this to "Render" panel, make sure to test with 768px height screen size as "Render" panel is the first GUI component to break on small screen sizes.

Other possibility is to add a preference option to "Preferences" window.

These kind of performance increases are very good for the application but they have not  been much of a focus area for me so far.

**Comment by dvdlvr** [comment]
Ok, thanks, I'll work on that next week.

**Comment by dvdlvr** [comment]
Pull request issued. Tested on my system (i7 CPU with 4 physical cores).
Test Settings on my system with the same test file.

Threads = Time without Drop Frames (With Drop Frames)
1 (Default, as is now) = 86m (59m)
2 = 56m (120m !!!)
3 = 50m (125m !!!)
4 = 55m (125m !!!)

So, interestingly, allowing drop frames will increase render time when using multiple threads, but decrease it when using a single threads.
In order to find the best performance you will need to do some testing on your own system. Adding threads will not necessarily increase performance, but, as you can see, setting it to 3 threads instead of 1, on my system, is over 40% faster than using a single thread, without frame dropping.

**Comment by jliljebl** [comment]
This is in repository now, will be in 1.12.
