### ISSUE TITLE
Delete items from Range Log All Items not possible.

### ISSUE THREAD

**Issue by svenn71** [jliljebl/flowblade#321]
Experimenting a bit with the punch-in and punch-out in the clip monitor reveals that I cannot remove lines from the Range Log All Items page by selecting an unwanted log item and pressing the Delete Selected Ranges button. Flowblade 1.10

If I create a new user group and move some items from All Items to the new user group, I can delete selected items in the user group with the button. The items moved to user group still remains in the All items list.

**Comment by jliljebl** [comment]
I'm unable to reproduce this. Could you post a step-by-step way to reproduce this, starting from application start, like this:

1. Start application and add some media items.
2. Open media item in monitor, select range and press "Log current marked range" button.
...
X. Now pressing "Delete Selected Ranges" button does nothing

**Comment by svenn71** [comment]
Hi,
I suspect the artifact I saw was based on update of libraries without restarting the computer.
After a clean reboot, Range Log works as expected.
