### ISSUE TITLE
Feature request: Select any one (or more) of multiple audio tracks

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#325]
Files with multiple audio tracks only use 'the first' one and there is no way to select an alternate audio track.
There should be a way to select the required audio track for editing.

Split audio only splits the 'first' audio track - a solution may be to split all tracks on separate audio lines.

The MLT XML export shows all audio tracks in the XML file, so they are detected correctly at some point, but there is no way to select one.

**Comment by jliljebl** [comment]
This seems useful. I'm adding it to feature queue, but I'm probably not planning on working this in the near future.

**Comment by dausruddin** [comment]
Any news regarding this? Sorry if this is an unnecessary bump.

**Comment by dvdlvr** [comment]
This is a lot of work since the MLT framework part used in Flowblade doesn't natively support it at the moment. The melt command line does support it, though. There is a shell script that can render using an alternate audio track using the MLT XML file that has been exported. I'm waiting for the underlying mlt framework parts to allow selection of the audio channel for now. Steven.

**Comment by dausruddin** [comment]
Ahh okay. Thanks for the detailed reply :)
