### ISSUE TITLE
Image sequence length

### ISSUE THREAD

**Issue by synk-a-dynka** [jliljebl/flowblade#333]
Dropping an image sequence clip from bin to timeline only the first 10 seconds is used.
Appending from clip monitor gives a 10 minute clip with the sequence looped.

A workaround is to add in/out points in clip monitor and then insert/append.

**Comment by jliljebl** [comment]
Confirmed.

**Comment by jliljebl** [comment]
Fixed in repository, will be in 1.12.

NOTE: Problem occurs when image sequence is added to project, so this will not fix image sequences added to projects with versions of code prior to fixing commit.
