### ISSUE TITLE
Add support for syncing audio to reference.

### ISSUE THREAD

**Issue by benrob0329** [jliljebl/flowblade#344]
For use with eg multiple cameras.

**Comment by jliljebl** [comment]
Yes, there was a bit of discussion on this and I found a Python file that may be useful called clapperless.py. I found it and saved it on my disk. Original target was to do this for 1.10, but now we can try to make it for 1.14.

clapperless:
http://users.mur.at/ms/projects/clapperless/clapperless
https://www.lwks.com/index.php?option=com_kunena&func=view&catid=6&id=40678&Itemid=81#40713

**Comment by jliljebl** [comment]
shenidam is one other possible way to do this.

**Comment by jliljebl** [comment]
A feature for creating a audio synced  combined clip is in repo, will be in 1.14.

We will add one more feature for finding audio sync offset between timeline clips and syncing them.

**Comment by jliljebl** [comment]
This is now in repo will be in 1.14.
