### ISSUE TITLE
Trasladate the flowblade documentation in spanish

### ISSUE THREAD

**Issue by detectivejd** [jliljebl/flowblade#345]
Hi, I really liked flowblade and wanted to know
What types of editions can be made with the program?
I also wanted to know
Will they translate the site documentation into Spanish?
Thank you.﻿

**Comment by dvdlvr** [comment]
"What types of editions".... what do you mean by that?
Put it in spanish if you like.
Personally I cannot translate any documentation to spanish, so hopefully someone out there can.

**Comment by detectivejd** [comment]
Types of editions as:

* create videos for intro and outro for youtube.
* videos for presentations.
* videos for advertisements
* and other editions more.

I wait that some translate the flowblade documentation in spanish.
Regards.

**Comment by jliljebl** [comment]
This Issue does not in my view preset any actionable plan so I'm closing it.

**Comment by lalegion** [comment]
If there is a plan to translate the manual into Spanish, I would be glad to help.

**Comment by jliljebl** [comment]
If you provide pull requests i will accept them. The files in question are in res/help, files like "basic_editing.html". If you do pull requests for creating Spanish version of these "basic_editing_es.html" I will accept these.

**Comment by lalegion** [comment]
I tried to create a new pull request and it gives me this message "Choose different branches or forks above to discuss and review changes."
Need some directions here, how do I do to pull a new request? Is it because I'm a new user or something?

**Comment by dvdlvr** [comment]
You need to upload the file to your own fork of the project.
Easiest is to upload the file to a separate 'patch'.
Then you click on the original project name from jliljebl and from that page create a new Pull Request.
Once you have that, click on the link above the frame saying something like 'compare with all forks' - make sure the original is on the left and select your fork + your patch on the right hand side.
Once selected you should see the changes made in the screen and you can submit the request.

Let me know if you still have problems after this.

**Comment by dvdlvr** [comment]
When you upload the file to your fork, make sure you go to the right directory before adding the files. I always get caught out by that. Just click on the flowblade-trunk link and then to the res/help directories.

**Comment by lalegion** [comment]
Ok I will take a look as you said.
Will keep in touch. Something tells me I am going to need it...
Thanks for your help!

**Comment by detectivejd** [comment]
Ok, thanks for the atention.
I will wait to see the trasladation of flowblade documentation with the
tutorials of types of editions
for create videos for intro and outro  in youtube, videos for presentations
and advertisements,
and more things because flowblade is worth it.

Regards.

**Comment by detectivejd** [comment]
Tren We will not have the spanish documentation?

Grettings

**Comment by detectivejd** [comment]
What need for the trasladation?

**Comment by jliljebl** [comment]
Hi, I re-opened the Issue and I'll keep open foe 6 months or so to if someone delivers Spanish documentation.

If someone provides it,  I will make it available in application and webpage.

**Comment by lalegion** [comment]
Ok, sorry for the delay. I've been quite busy but I have some time now.
I already started and I hope that it will go fast, but I don't know exactly how much, as this is the first time I'm doing it.
So please, have a little patience ;-)
Lalegion.

**Comment by lalegion** [comment]
By the way, I have a couple of questions about the workflow, but I will ask you later about that. For the moment I'm translating the help files and renaming them with a sufix "_sp" in order not to touch the original ones.

**Comment by jliljebl** [comment]
@lalegion  Ok, no hurry, I'll keep this open and apply when you're ready.

**Comment by detectivejd** [comment]
@lalegion Well, I'll be anxiously waiting for the translation into Spanish.
Greetings.

**Comment by detectivejd** [comment]
Is there news about the Spanish translation? Thank you.

**Comment by jliljebl** [comment]
No. This is a volunteer project, if we get it we get it, if not then not. I do not feel comfortable or justified in pushing or hurrying up any possible contributions/contributors.

**Comment by jliljebl** [comment]
This seems to not be happening.

**Comment by detectivejd** [comment]
Then, this was for nothing?
