### ISSUE TITLE
Thumbnail icon for flb project files?

### ISSUE THREAD

**Issue by orschiro** [jliljebl/flowblade#346]
Dear all, 

Is it possible to provide a thumbnail icon for flb project files instead of a generic icon?

This is how it looks on my Ubuntu 16.10 installation. 

![image](https://cloud.githubusercontent.com/assets/170947/23343069/a60fbbe4-fc65-11e6-94ed-5681d7cbe408.png)

**Comment by jliljebl** [comment]
I merged the pull request by dvdlvr addressing this issue by updating the .desktop file. haven't tested but if turns out that the fix was not sufficient, I 'll reopen.

**Comment by orschiro** [comment]
Thanks guys!
