### ISSUE TITLE
Can't shrink the timeline area vertically

### ISSUE THREAD

**Issue by emveeoh** [jliljebl/flowblade#347]
![flowblade-timeline-cantshrink](https://cloud.githubusercontent.com/assets/16849690/23346169/c03a4f34-fc65-11e6-8136-6c94cdf78dee.png)

Unable to shrink the timeline area vertically when only 2 VIDEO/1 AUDIO tracks are selected. Notice the whitespace above and below the tracks.

This is a serious problem on a laptop or other small screen where the video preview is unneccesarily small because that timeline area won't collapse to save space. It makes the video preview almost too small to work with.

**Comment by jliljebl** [comment]
I added check menu item "Vertical Shrink Timeline" into tracks menu on the left. When checked  timeline area can be shrunk vertically if fewer than max. tracks are used in sequence.

Fixed in repo, will be in 1.14.
