### ISSUE TITLE
Feature request: Add button for pop-out floating video preview window

### ISSUE THREAD

**Issue by emveeoh** [jliljebl/flowblade#348]
Feature request: 
Add a button or menu option to pop-out floating video preview window. I finally found the 2-window option. However, I think most users would expect to find this option by right-clicking on the video preview window itself or by clicking an expansion button on the bottom-right corner of the video preview window.

Thank you! 
:)

**Comment by jliljebl** [comment]
There are two slightly different points in this Feature request:
a) Discoverability problem, Feature exists, but is reported to be hard to find to activate,
b) A wish to be able to change the window mode at runtime, post application GUI init.

I pushed a patch to fix a) by adding a "Window Mode" menu item with options "Single Window" and "Two Windows" in the "View" menu. This will be in 1.14.

Point b) is impossible/very hard with the current code base and is going *wontfix*.
