### ISSUE TITLE
Feature: Freeze frame

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#353]
Could you please add a new tool that would allow extending clips beyond their physical length by repeating the last frame at the clip's end (freeze frame effect). Alternatively, a function generating a new still clip from a single frame. The _Export > Current frame_ function doesn't satisfy this need because it generates RGB bitmaps which differ visibly from YUV originals due to inherent color space conversion.

Suggested method: MLT's _repeat_ function with avformat consumer set to lossless and the original color space, e.g., _vcodec=libx264 pix_fmt=yuv444p g=1 qp=0 an=1_

**Comment by jliljebl** [comment]
Ok, will investigate. This is not going in menu "Edit->Export", some new "Project" menu item or a function in clip pop-up menu seem more appropriate. At first glance seems doable for 1.14.

**Comment by jliljebl** [comment]
I looked into this. The 'repeat' thing is a playlist method that force loops a range of frames on playback. This can't used we need 1:1 correspondence with producer and timeline frames. 

There is a also 'hold' producer but that is a wrapper for another producer. Using this would break proxy editing.

Unfortunately there does not seems to be any additional ways to provide freeze frames so we will have to do with current frame export and "Freeze" filter features.

**Comment by apienk** [comment]
The way we worked around this issue is to generate a still-frame video clip externally, using melt. This lets us avoid the problematic colorspace conversion. Possibly, a similar _create still clip from frame_ feature could be implemented in Flowblade (similarly to proxies).

`melt <infile> in=<frame_number> out=<frame_number> -repeat <clip_duration_in_frames> -consumer avformat:<outfile> vcodec=libx264 pix_fmt=yuv444p qp=0 an=1`

**Comment by jliljebl** [comment]
@apienk  So, if we just provide a convenient way to create a clip with freeze frame, that would be helpful for that use case because then there would be no RGB/YUV differences?

**Comment by apienk** [comment]
@jliljebl Yes.

**Comment by jliljebl** [comment]
I think we can get something done here eventually, I reopened this.

**Comment by jliljebl** [comment]
This could maybe be done by creating a MLT XML file similar to compound clips and betting this 'repeat' property in somehow, but I have to admit that I probably wont be working on this in next year at least.

**Comment by jliljebl** [comment]
I tried an MLT XML file from sequence with freeze filter attached to tractor but that failed. I'll keep this open, maybe we find a way.

**Comment by jliljebl** [comment]
Yeah, the existing Freeze Filter does not work with MLT XML files from multitrack objects, it just displays the bottom video track.

**Comment by jliljebl** [comment]
I looked quite carefully the MLT code and KDEnlive + Shotcut, and I'm convinced that this cannot be done without MLT patches. The melt -repeat thing is in melt code and not available for Flowblade as such.

I'm not marking *wontfix* because if it becomes possible to do this, we'll add this feature, but for now this is not really an active issue and is closed.

**Comment by apienk** [comment]
Thank you so much for devoting your time to this feature request.

**Comment by apienk** [comment]
What about _Export current frame to YUV_ option in the _File_ menu? That would be a useful workaround.

**Comment by pmjdebruijn** [comment]
That would indeed be rather nice... Ideally it could even be integrated further...

As a special cutting tool or mode, where the "cut" automatically inserts the "freeze frame" in de cut itself. With the except that of course you get a dialog where to save the freeze frame.

**Comment by pmjdebruijn** [comment]
The big advantage of using an image, as opposed to a generated video fragment, is that the "freeze frame" is easy to make shorter/longer in the Flowblade UI.

**Comment by pmjdebruijn** [comment]
It seems by setting a Mark In/Mark Out and then rendering a slowmotion video, doing a range delete, and then inserting that slow motion video, effectively provides a freeze frame features.

At least if #855 is resolved.
