### ISSUE TITLE
import image sequence error ubuntu

### ISSUE THREAD

**Issue by Shonanqn** [jliljebl/flowblade#360]
Bug importing sequences of images, I was working on the software 4d cinema and when exporting a sequence of images flowblade does not open all the frames, the video starts in 30 frames after .. that is to say the 30 frames of the beginning of the video are lost.
I tried with blender and there was not that problem ... just happen with cinema 4d .. used from wine in ubuntu.

**Comment by jliljebl** [comment]
Could you post a screenshot(s) of first 40-ish frames in folder as displayed by Files program just before you try to open image sequence?

**Comment by jliljebl** [comment]
This needs more info to proceed, closing as *not active* until more information provided.
