### ISSUE TITLE
Default Rendered Fade/Transition Bitrate To Match Clip

### ISSUE THREAD

**Issue by benrob0329** [jliljebl/flowblade#374]
Currently it defaults to lowest settings, which afaik serves no purpose as it would look out of place. It also resets to it when you change codec, so you have to remember to change it back. (Perhaps codec should default to project setting?)

**Comment by jliljebl** [comment]
The planned development was to make fade render settings persinstent after being set by the user.

I think this can be combined with your idea of making the initial settings something other than lower settings, so I'm adding this to feature queue.

**Comment by jliljebl** [comment]
I did the following changes that will be 1n 1.14:

1) Made encoding selections persistent across dialog invocations and even project loads
2) Upped rate value for transitions 3000kb -> 8000kb

I don't think there is much else to do atm. so I'm closing this as *featurees added*
