### ISSUE TITLE
Render tab does not remember previously used settings

### ISSUE THREAD

**Issue by KopiasCsaba** [jliljebl/flowblade#379]
Hello folks!

The render tab does not remember the prevously used settings, and i think it would be good if it would do that:)

I mean the Folder, name, render type, render profile, encoding format and render range.

Thanks!

**Comment by jliljebl** [comment]
This is planned and will be in 1.14.

**Comment by jliljebl** [comment]
Feature is in repository, will be in 1.14.

**Comment by KopiasCsaba** [comment]
You are awesome, thanks!
