### ISSUE TITLE
Add auto fade Compositors

### ISSUE THREAD

**Issue by KopiasCsaba** [jliljebl/flowblade#380]
Hi folks!

I think the fade thing should not require rendering, i'm sure mlt can do it somehow, kdenlive has it as an effect.
Rendering an effect(in this case fade) is cumbersome every time you need to deal with it.

So once if you could, please fix it:)

Thanks!

**Comment by benrob0329** [comment]
You can use the dissolve compositor to avoid prerendering.

**Comment by jliljebl** [comment]
I just tested KDEnlive 16.12 Appimage.

When adding "Dissolve" compositor it tries to guess if it is near the start or end of clip and then makes it a "Fade in" or "Fade out" by adding hidden keyframes in the start and end of clip and automatically updates those keyframes when the length of the Compositor is changed.

However it does a bad job at guessing the desired lengths and positions of Compositors when they are added.

It is possible to create special Compositors that act as "Fade In" and "Fade out" dissolves by making them auto update keyframes on length changes. They would also need to have a  different GUI to current "Dissolve" and different behavior when asked to resync with parent.

Unlike KDEnlive  I really do not want to use heuristics and try to guess if user wants Fade in or Fade out. I also find the behaviour of having a "Dissolve" being "Fade In" or "Fade out" based on heuristic quite confusing.

This would be done by adding a sub menu "Add Fade" to clip pop up menu with items "Fade In" and "Fade Out". These would also only be available for video tracks V2 and higher. They would not be called "Dissolve" but "Fade in" and "Fade Out" on timeline and "Auto Fade" in "Compositors" panel with selection for acting wither as "Fade In" or "Fade Out"

This is doable for 1.14 but I'm not sure if it comes for that.

**Comment by jliljebl** [comment]
Just pushed the feature (mostly) as described above, will be in 1.14.

**Comment by KopiasCsaba** [comment]
Great, thank you:) I'll check it out!
