### ISSUE TITLE
how to disable ripple editing

### ISSUE THREAD

**Issue by ftrotter** [jliljebl/flowblade#384]
Working on ubuntu the alt key is captured by the windowing system. so it does not work to solve the problem here:

http://nch.invisionzone.com/index.php?/topic/21992-why-cant-i-drag-clips-further-right-of-track-all-clips-just-go-back-to-beginning/

There are no "chevrons at the RH end of the toolbar." either. 

If there is a "secret" way to get this done, it should be added to the documentation. 

The documentation does not actually list "click and drag" as a method for moving clips. That is pretty strange, since that has to be how it is done 99% of the time.

-FT

**Comment by jliljebl** [comment]
There is absolutely no way to disable "ripple editing" here.

Flowblade works silmilar to Avid and Final Cut X. The concept is called "film editing" "insert editing" or "magnetic timeline" and is faster when used appropriately.

Use "Overwrite" tool to move 1-n clips freely in the timeline.
