### ISSUE TITLE
Sort out your mouse over documentation

### ISSUE THREAD

**Issue by ftrotter** [jliljebl/flowblade#385]
Most of the interface components do not have mouseover documentation. 
Many of those that do have two icons with more than one thing in the mouseover documentation. Each mouseover should reveal what only and only button does. It is very confusing to sort out which mouseover text goes with which icon.

This especially critical when you have one button that does two different things in different contexts. Then there is a mouseover hint that has three items for two buttons... confusing confusing. 

This is especially confusing with the right column with the moveable down arrow on the track labels to the bottom left of the screen. It is obvious that it is doing something important. But there is no way to discover A. What they do B. What they are called C. Where to read more about them. 
![what_the_hell_is_the_right_column](https://cloud.githubusercontent.com/assets/83133/26519348/56f8ad16-4285-11e7-8037-6b2e3a078a72.png)

When the icon is a status icon, like the greyed out speakers, or the lock icon or the very small checkbox... the mouseover should say something like "this track is locked" or something useful like that.

**Comment by jliljebl** [comment]
This is going *wontfix*. The slightly increased discoverability and clarity is not worth the development effort.

In case of the midbar buttons, those are implemented as a single GTK widget and *cannot technically* be made to have different tooltip for every button.
