### ISSUE TITLE
the cut icon should change the icon to a cutter and work on any track

### ISSUE THREAD

**Issue by ftrotter** [jliljebl/flowblade#387]
this is the way every editor that i have seen works. It makes much more intuitive sense.

**Comment by jliljebl** [comment]
No, were cutting movies here not sausages.

When cutting we are *always* interest in the actual in and out frames. The current "cut-at-play-head" action provides that information, and is superior to the "blind-cut-anywhere" cutting tool you are proposing.

Use the activity switches on the left to select track that are affected by the cut action.
