### ISSUE TITLE
Propose a basic usability review

### ISSUE THREAD

**Issue by ftrotter** [jliljebl/flowblade#389]
I propose that a developer with this project follow the famous "hallway usability testing" with someone who understands how to do amateur video editing with any other consumer grade or professional grade tool. Or even better, someone who does not know how to edit a video, but wants to know. 

Make a list of the like 5 tasks that are typical video editing tasks. You could use the "tutorials" that youtubers have done on the various FOSS video editing tools to make the list. 

As it stands, flowblade is obviously a powerful tool, but its design is heavily influenced by the developers own use cases. 

https://www.joelonsoftware.com/2000/08/09/the-joel-test-12-steps-to-better-code/
https://www.nngroup.com/articles/why-you-only-need-to-test-with-5-users/

I hope these issue submissions are useful, I can see that you have put a lot of work into this project. And I am giving you the kinds of detailed feedback that I wish my users gave me on the software that I develop.

HTH,
-FT

**Comment by jliljebl** [comment]
I do appreciate you taking time to give feedback, but I'm not convinced of your criticisms.

Here is a differing point of view on editing with Flowblade from another user: *"I have said before how much I admire this project. I consider it the only professional oriented alternative on linux. It has been clearly inspired (in a perfect way) by Avid."* found here: https://github.com/jliljebl/flowblade/issues/342

The comment sort of points out the people we are looking to build a tool for: users that are *both willing and capable* to learn to edit with a program that is at a complexity level similar to Avid.

It just may be that you are not part of this target user base.

A useful usability review would require that the participants are actually part of the target use base. Rounding up 4 grandmas and a niece would not provide any actionable information.

I'm closing this without a label, but feel free to add further comments.
