### ISSUE TITLE
Keyframe cannot be moved to the last frame

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#395]
Here is how it looks: https://youtu.be/wk3GLZUxRA8. Once a keyframe created on the last frame was moved out of its place, it cannot be returned back to the last frame.

**Comment by Efenstor** [comment]
I've noticed that when I resize the compositor and rely on the "magnet" action to adjust it's length, the resulting length is exactly one frame longer than it should be, as it is visible when I zoom in the timeline. May be that is the reason of the keyframe movement issue?

**Comment by jliljebl** [comment]
Fixed in repository, will be in 1.14. Fixing one bug caused another to appear, both causing same symptoms, so that was a bit confusing.

**Comment by Efenstor** [comment]
Is it really fixed in master? I still cannot move the last keyframe to the last frame.
