### ISSUE TITLE
Batch render all rendered transitions on request

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#398]
I am not completely sure yet but it really looks like the final render is being done from proxy files, if "Use Proxy Media" is chosen in the Proxy Manager. It is absolutely logical to expect it to be done from the original files.

**Comment by Efenstor** [comment]
The same problem is with the rendered transitions. By the way, may be it's time to remove those completely, as there are compositors doing the same thing?

**Comment by jliljebl** [comment]
Select "Use Original Medai" before doing final render, You are right on rendered transitions, those will currently need to be redone, rendered transitions are done from material on the timeline

Use Compositors to side step this problem or recreate transitions after going back to Original mdia.

The way proxys are done in Flowblade is that the media on timeline is replaced with proxy files and then again with original media on request, please read: https://jliljebl.github.io/flowblade/webhelp/proxy.html

BTW you have created such an large amount of Issues that it will take week+ to get to these, I'm doing other things atm.

**Comment by Efenstor** [comment]
> BTW you have created such an large amount of Issues that it will take week+ to get to these, I'm doing other things atm.

Even a year is not a problem. What matters is to eventually fix all these. I just thought: why not to make at least one Linux video editor good, instead of a bunch of buggy ones? And started to create issues about every single problem I stumbled upon when started using it practically.

**Comment by jliljebl** [comment]
With this careful consideration is needed.

We could:
1) Auto re-render all transitions on switching to "Use Original Media".
2) Re-render all transitions on request. this clocks in at 200+ lines of code and another out-of process laucher but we keep doing these kinds of additions as need.
3) Remove rendered transitions all completely. This is such a desired feature for beginner users that I'm unwilling to do it.
4) Render transitions from original media even when doing proxy editing, but that would defeat the original purpose of proxy editing.

Atm. I think only 2) is worth considering, maybe giving user option for 1) when after transitioning  "Use Original Media", they need 05% same code.

**Comment by Efenstor** [comment]
I also think the variant 2 is the best solution, at least for now. Variant 4 has some reason in it, but only like this:

- When using proxy editing render transitions from the sources using proxy settings (i.e. ultra-fast). Thus the quality will be consistent with the other clips and rendering will be quite fast, which is also good.

- When rendering the final file, re-render all transitions using the final quality settings.

**Comment by Efenstor** [comment]
> Select "Use Original Media" before doing final render
I think there must be a warning message. Otherwise there's a big risk to waste a lot of time on rendering final output from proxy files.

**Comment by jliljebl** [comment]
Yeah, this is a *user-is-always-right* kind of thing in a sense that once it proven that it *can* be misunderstood that rendering will use original media even when in "Proxy Mode" something  needs to be  done to inform user that this is not the case. Saying RTFM is not a solution.

I think there are to possible places to display info message:
* when user presses "Use Proxy Media"
* or when in presses render while in "Proxy Mode"

I think I will go for option one.

**Comment by Efenstor** [comment]
Go for option two, please! I personally will never remember whether I am in proxy mode or not. Just imagine, I've just completed a very complex editing and can't wait to click "Render". Do you think I'll remember I was in the proxy mode? :)

**Comment by jliljebl** [comment]
Ok, I can do option two based on your recommendation, it is possible to just forget the state you are in.

Users are indeed users, everyone's mental models on how software should work are a bit different, so this kind of info that better communicates the particular model of proxy editing in Flowblade *does* improve the user experience.

**Comment by jliljebl** [comment]
I added dialog to get confirmation when rendering is attempted in proxy mode. I'll edit the title to "Batch render all rendered transitions on request" so that this issues can solved by doing the change described in title.

**Comment by Efenstor** [comment]
Great! Thanks for all your efforts!

**Comment by jliljebl** [comment]
This has been in repo for a while, will be in 1.16.
