### ISSUE TITLE
Switching from proxy to original media resets settings

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#399]
Switching from proxy to original media or back resets render settings to default and clears the timeline in and out (marked range) points.

**Comment by Efenstor** [comment]
The render settings are also set to default every time I restart Flowblade. I think those must be saved in the project file, it's logical to expect it.

**Comment by jliljebl** [comment]
First comment is a bug, second is feature that has been already added: https://github.com/jliljebl/flowblade/issues/379

**Comment by jliljebl** [comment]
Fixed in repo, will be in 1.14

NOTE: Render settings are only saved *when project is rendered*, just changing values does make those values to be saved.
