### ISSUE TITLE
"Render threads" setting is redundant?

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#400]
It seems like the "Render threads" setting in Preferences is not needed. I have it currently set to 1 and nevertheless all the 6 cores of my CPU are utilized up to 100% when rendering is performed.

**Comment by jliljebl** [comment]
Did you set it at "2" or "3" and get different results? Is there any way in your system to get fewer then all cores rendering?

The related documentation is here, looking at my code I think we are doing what MLT says applications should do.

https://www.mltframework.org/plugins/ConsumerAvformat/#realtime

**Comment by Efenstor** [comment]
Somehow I got all the cores always heavily used no matter the setting. May be there are some differences but those are unsubstantial to notice. That's why I presumed it's redundant.

**Comment by jliljebl** [comment]
I won't remove any features before 2.0 so this stays in for now. I might do some tests on what is going on here but for now this is going wontfix.
