### ISSUE TITLE
Frames dropped in final render

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#401]
The "Allow Frame Dropping" option in Preferences affects the render output whereas it should not. Or should it? It is not completely clear what this option is needed for.

**Comment by jliljebl** [comment]
I'm not getting any frames dropped if it is turned off. if it is turned on dropping frames is allowed.

Does "affects the render output whereas it should not" mean that you are getting frames dropped always or frames dropped never or do you disagree with the  existence of this option or something else? The meaning is not clear enough here for me, can you represent the issue in step by step format.

**Comment by Efenstor** [comment]
No, the frames are dropped only if it's on. I just don't understand who would need that in the _final_ output?

**Comment by jliljebl** [comment]
Maybe someone wants to force capped render time for some placeholder clips in a hurry.

Anyway we won't be doing any feature removal until we go  1.x -> 2.0 as I consider feature removal breaking change.
