### ISSUE TITLE
Feature request: Better filter copy mechanism needed

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#402]
I see unfortunately there is no way to transfer filter settings between the tracks, or just to copy from one clip and paste to multiple clips at once. Ideally there also should exist a way to apply filters to tracks (e.g. for the movie-long color correction) and to some clips separately. There is no such thing as filter presets, while those are very useful, especially to save curve settings (e.g. for different types of film-like tinting styles).

**Comment by jliljebl** [comment]
1) It is absolutely possible to copy effects to multiple clips at once. Select one clip, do CTRL + C to copy filters, select multiple clips, do CTRL + ALT + V to copy filters into multiple clips at the same time.

2) No track filters exist in Avid, Premiere or Final Cut X, this is not a feature commonly considered useful. I think only Sony Vegas has these. I'm not looking for adding additional complexity into sequence.Sequence data structure, thisis wontfix unless a good quality patch is presented.

3) I added a hamburger menu into "Filters" panel edit area with menu items "Save Effect Values", "Load Effect Values" and "Reset Effect Values". Now you can create your own presets by saving effect values with appropriate names.

With addition of save/load functionality I feel that maximum has been done for this and will close. Added features will be in 1.16.
