### ISSUE TITLE
Problems with scrolling the timeline to the left

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#405]
Oftentimes it is impossible to scroll the timeline to the left using the scrollbar at the bottom of the program's window.

Steps to reproduce:
1. Load a clip and drag it into the track V1
2. Zoom out to see the whole clip and a couple of steps furthermore
3. Drag the timeline position (blue marker) to the end of the clip
4. Place the mouse cursor in the grey timeline area about 10 pixels to the left of of the area's edge
5. Zoom in until it's impossible to zoom further
6. Without moving the mouse cursor, zoom out
7. The scrollbar now occupies the whole width, yet there's a great piece of timeline to the left which you now cannot get to

**Workaround**: If you're stuck in this situation, just zoom out using the "Zoom Length" button in the timeline toolbar (or click the middle mouse button).

**Comment by jliljebl** [comment]
Confirmed, this needs fixing. I use  "Zoom Length" constantly so I don't hit this enough to make strong mental notes on this issue.

**Comment by jliljebl** [comment]
Fixed, will be in 1.14. The (bit surprising) correct answer was to set timeline position differently when doing zoom in and zoom out.
