### ISSUE TITLE
Filters/Audio Volume

### ISSUE THREAD

**Issue by bigalgeorge** [jliljebl/flowblade#409]
+ - volume setting and enter numeric (without Enter) does not stick; only if slider used volume sticks. Some users will want to be able to increase volume eg 200% when recording is low or normalize; currently not possible; I had to normalize by using avidemux; or am I missing something?

**Comment by jliljebl** [comment]
Confirmed.

**Comment by jliljebl** [comment]
Fixed in repository, will be in 1.14.

**Comment by arnolde** [comment]
I added a Volume filter to a .wav audio track but I can't find any way to edit the filter? I have the Filters tab open, I can see at the top that the track is selected and Volume is listed in the upper white box, and checked, but nothing that I try makes anything appear in the grey area next to it, so I can edit the volume value.
