### ISSUE TITLE
Feature requests: Codec prompt default recall & Tiler

### ISSUE THREAD

**Issue by bigalgeorge** [jliljebl/flowblade#410]
At start of project there is a prompt video keep or change which is brilliant. Is a way of reverting back to original video/audio codec for render if user changes mind later? EG source video codec setting reset.
Tiler: additional feature click on Tile, adjust Text and close Tiler and text remains in place as per Tiler for a selected region without having to go back to the tile graphic, insert and set?

**Comment by Efenstor** [comment]
You mean profile by 'codec'? You can always save the currently opened project with any other profile using Project > Change Project Profile. Actually it's quite hard to understand what you really mean.

**Comment by jliljebl** [comment]
The requested feature is not clear so I will close this as "wontfix". Use "Project > Change Project Profile" to change project profile as suggested by @Efenstor .
