### ISSUE TITLE
Audio Filter on Music won't change

### ISSUE THREAD

**Issue by flowblade-vibes** [jliljebl/flowblade#412]
I have added a music below a scene but I want the scene to be loud enough so you can hear it. I want to lower the music volume. I put in a volume filter and write in 25 or 35. The volume is the same. Sometimes it works but then I try to change it and nothing happens. Is this some bug or am I doing it wrong?

**Comment by bigalgeorge** [comment]
As my previous bug post - you need to move the slider. Entering a value wont work.

**Comment by flowblade-vibes** [comment]
Wait please explain further.

Do you mean if I type in 0 on the value nothing will happen? Now I'm in a project where I'm editing scenes but the music suddenly changes between them. I wanted the second scene to be quiet but for the audio to slowly fade in. Could you explain this in detail?

**Comment by Efenstor** [comment]
There's really nothing to explain. It's a bug. Entering a value and hitting 'Enter' must work but it doesn't.

**Comment by Efenstor** [comment]
This is a duplicate of https://github.com/jliljebl/flowblade/issues/409

**Comment by jliljebl** [comment]
Yes, closing as duplicate of #409, which is confirmed.
