### ISSUE TITLE
allow program to run on screens smaller than 1152x768

### ISSUE THREAD

**Issue by ricardobiehl** [jliljebl/flowblade#414]
I have a 1024x768 screen resolution. I removed [this](https://github.com/jliljebl/flowblade/blob/b6bd158538d6bdc24befa24a59db9b6d3bfcae63/flowblade-trunk/Flowblade/app.py#L231) and I've noticed Flowblade
is able to run on smaller screens by just allowing some widgets to be scrollable
at a lower minimum value (or lower their minimum size). Am I wrong?

**Comment by AGI-THB** [comment]
Is this related to #122 ?

**Comment by ricardobiehl** [comment]
Yes, it is. @jliljebl has mentioned in https://github.com/jliljebl/flowblade/issues/122#issuecomment-112869974:

> [...] I'm not sure however that I can make 1024 width work correctly

Well, it was almost two years ago. Perhaps it's worth bringing it back given
that some users probably will get unhappy with that message saying "your screen
is too small ..."

**Comment by PeteGozz** [comment]
I know users who have been put off by this.
FWIW here is a git diff that is a tweak that goes some way toward a fix.
I did not go down into the widgets themselves (yet)
(sigh (txt or gz is no good here ?) so this is not  a patch )
so markdown may work with this:
the file is 
    flowblade-trunk/Flowblade/app.py 
     # Refuse to run on too small screen.
    -    if scr_w < 1151 or scr_h < 767:
    +    if scr_w < 1024 or scr_h < 760:
         _too_small_screen_exit()
         return

This is less useful and not directly a solution

    @@ -757,8 +758,8 @@ def _set_draw_params():
             projectinfogui.PROJECT_INFO_PANEL_HEIGHT = 140
 
         if editorstate.SCREEN_WIDTH < 1153 and editorstate.SCREEN_HEIGHT < 865:
    -        editorwindow.MONITOR_AREA_WIDTH = 400
    -        positionbar.BAR_WIDTH = 100
    +        editorwindow.MONITOR_AREA_WIDTH = 460
    +        positionbar.BAR_WIDTH = 80
 
I also did some small tweaks to error messages probably as a test :)
 in editor_state I have made some small tweaks as well  but they look very tentative.

(according to git )

**Comment by jliljebl** [comment]
This is going 100%  *wontfix*.

Supported minimal screen resolutions place *massive* restrictions on design approaches that can used when developing the GUI. Even the current supported resolutions have drained large amounts of development time from other areas.

There are limits to the torture I'm willing to subject myself to support under specced systems.

**Comment by PeteGozz** [comment]
Fair enough :)
Totally understand.
