### ISSUE TITLE
Map Timeline tools shortcuts to Numpad for french and belgian keyboards (feature request)

### ISSUE THREAD

**Issue by fandali** [jliljebl/flowblade#415]
It will be very comfortable to map the Timeline tools shortcuts (1, 2, 3, 4, 5, 6, 7) to numpad for french and belgian keyboards. Because on such kind of keyboard, users have to use shift key to quickly access those tools (and we need it very often). Another possibility could be to map it on function keys (F1, F2, F3, ...) (like for example tools in Inkscape)

**Comment by jliljebl** [comment]
We can add this: I think this is in the new keyboard shortcuts code by @dvdlvr but I will make sure.

**Comment by fandali** [comment]
Thank you very mush ! It will be very helpful !

**Comment by jliljebl** [comment]
Fixed in repository, will be 1.14.
