### ISSUE TITLE
Gamma adjustment works improperly

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#418]
The Gamma parameter in the "Lift Gain Gamma" effect adjusts contrast instead of actual gamma. The two remaining parameters seem to work correctly to me, as well as the "Color Lift Gain Gamma" effect. I hope somebody else can confirm this. This is how the whole effect should normally work (in Adobe Premiere): https://www.youtube.com/watch?time_continue=170&v=lFjO2zFYRgo

**Comment by jliljebl** [comment]
I actually wrote the filter but I don't remember the exact Gimp filter I got the math from anymore.Filter is here:

https://github.com/mltframework/mlt/blob/master/src/modules/plusgpl/filter_lumaliftgaingamma.c

On quick inspection the math in the filter seems remarkably similar to the simplest form of gamma correction described here: https://en.wikipedia.org/wiki/Gamma_correction

Anyway this is going *wontfix*, I do intend to spend time investigating details of gamma correction math and how/if it differs from contrast adjustment. Also contrast adjustment is by definition a gamma correction operation, see wiki link above.

**Comment by Efenstor** [comment]
So is there a way to adjust gamma the way Gimp or Photoshop does?
