### ISSUE TITLE
Minor issue: Right arrow key doesn't work in "Monitor Clip"

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#425]
When the "Monitor Clip" is on hitting the right arrow key doesn't cause the cursor to move one frame further. It does nothing.

P.S.: Why is it called "Monitor Clip" anyway? On the tooltip it reads "Display Monitor Clip" which is pretty close to mumbo-jumbo, why not just "Display Clip" or "Display Selected Clip"? The same is with the "Display Current Sequence on Timeline", why not "Display Timeline Sequence"?

**Comment by jliljebl** [comment]
Confirmid.

I'll do next session on the weekend and I'l take a look at this and other issues then.

**Comment by jliljebl** [comment]
Fixed in repo, will be in 1.14. 

I could consider improvements on nomenclature in the next release cycle, but right now I'm days away from strings lock down and I don't wish to do any hurried changes here.
