### ISSUE TITLE
Better Region/Picture in Picture Compositor Controls

### ISSUE THREAD

**Issue by CodingKoopa** [jliljebl/flowblade#429]
The `Region` and `Picture in Picture` compositors have views where you can modify how the clip is translated and scaled. Currently, the only real precise actions you can do are center the image, fix the aspect ratio, and translate the clip with arrow keys. The latter doesn't extend to scaling, so scaling the image to a certain point can be finicky. Furthermore, when dragging it with the mouse, there's no snapping or anything.

So, what I propose is:
 - While shift is held down, the arrow keys can be used to scale the image instead of translating.
 - A checkbox to the right of the view combo box that enables/disables snapping to the edge of the grey rectangle (Or even just have it always enabled since arrow keys can be used for fine tuning.).

**Comment by jliljebl** [comment]
These are useful suggestions and something like this will be added in the future.

> While shift is held down, the arrow keys can be used to scale the image instead of translating.

This seems logical and useful and we'll do this but it could a bit of an hassle to actually do so I'm not sure when I'll get around to this.

> A checkbox to the right of the view combo box that enables/disables snapping to the edge of the grey rectangle (Or even just have it always enabled since arrow keys can be used for fine tuning.).

I see what is looked for here but I'm not sure the check box is the way to go. The more general solution of providing functionality to enter x,y,scale values numerically may be better.

**Comment by jliljebl** [comment]
I did the keyboard scaling as suggested: SHIFT + ARROW now scales in all geometry editors (all 4 arrows work) SHIFT + CONTROL + ARROW scales with bigger steps.

On the snapping i'm going *wontfix*, it would be quite a bit of work and we now have possibility to enter positions using numbers and that will help in this use case.

If I get pull requests on the snapping I can accept them, and it is somewhat possible that I do it myself in the future if there is time frame that I want to take up a medium sided patch for this, it would be useful feature.
