### ISSUE TITLE
Better support for several compositors

### ISSUE THREAD

**Issue by TheKoopaKingdom** [jliljebl/flowblade#430]
Adding more than one compositor on the same clip, with them overlapping, results in a messy situation because it's difficult to select one that's "under" the other.

To provide a use case:
![](https://i.imgur.com/xOT3OR8.png)
I have a video clip that I need picture in picture for, but I'd also like to have it dissolve (Fade in) in the first few seconds, but this issue makes managing it difficult.

EDIT: I now see that Picture in Picture has an opacity option. I still do feel like several compositors on one spot could be useful though.

**Comment by jliljebl** [comment]
This is going *wontfix* for now. This particular area of functionality is not something that I want to spend time on right now in view of other possible areas of development, I do not see the gain/pain ratio for working on this appealing.

If some exact designs that are address this issue and are easily implementable are proposed I will reconsider.
