### ISSUE TITLE
Cannot re-render proxies?

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#435]
What is the correct way to re-render a proxy file? I want to change it from MPEG-2 quarter-size to MPEG-4 half-size. I am doing this:
1. I select a couple of clips
2. Click the "Render Proxy Files" button
3. Get the dialog
4. Choose "Rerender all possible"
5. Click "Do Render Action"
6. Nothing happens

I see that it's written "You are trying to create proxies for 0 proxy files" (by the way, may be it should be "0 clips" or just "0 files"?) Why the 0 files if I've selected two?

**Comment by jliljebl** [comment]
To rerender proxies you need leave "Using Proxy Media" state and be in "Using Original Media" state to rerender proxies.

With the Flowblade approach which is to swap *all* proxy files to original media files at once (*by doing save/reload to a hidden temporary project file*) this is a hard limitation, and cannot be improved on.

This limitation does need to be communicated to the user better, but we are now strings and fix lock for 1.14 so this will go to 1.16.

**Comment by jliljebl** [comment]
Added info texts telling users to change to 'Use Original Media' mode if they wish to rerender proxy files, coming in 1.16.
