### ISSUE TITLE
Ruler marks do not correspond with time for 23.98 fps

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#436]
When it's zoomed out, the ruler marks do not correspond with the written time labels - just drag the cursor to any mark and you'll see it. The problem seems to exist only for fractional framerates.

**Comment by jliljebl** [comment]
Confirmed. This is 1.16 stuff now.

**Comment by jliljebl** [comment]
Fixed in repo, will be in 1.16.

**Comment by Efenstor** [comment]
Thanks, now it's mostly perfect. The only minor imperfection I've noticed is that when it's zoomed in until the smaller ruler marks are visible, the longer marks do not exactly correspond to the timecode displayed on the timecode indicator, they are shifted by 1 frame. Here is the screenshot.

![screenshot at 2017-12-02 02-19-42](https://user-images.githubusercontent.com/11175574/33499501-b1adf844-d707-11e7-9ab6-b0b4ab3da270.jpg)

**Comment by jliljebl** [comment]
Ok, I see it. Its similar issue to the previous one.

**Comment by jliljebl** [comment]
Pushed a patch, now we should have everything working to perfection.

**Comment by Efenstor** [comment]
Confirmed, it does.
