### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/Flowblade/res/shortcuts/'

### ISSUE THREAD

**Issue by martinkg** [jliljebl/flowblade#440]
when running flowblade-1.14 beta i get the following error message:

> $ flowblade 
> FLOWBLADE MOVIE EDITOR 1.14 - BETA
> ---------------------------
> Launch script dir: /usr/bin
> Running from installation...
> modules path: /usr/lib/python2.7/site-packages/Flowblade
> MLT found, version: 6.4.1
> numpy version: 1.12.1
> OS: Fedora 26 (Workstation Edition)
> Python 2.7.13 (default, Sep  5 2017, 08:53:59) 
> [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
> GTK+ version: 3.22.21
> User dir: /home/martin/.flowblade/
> Locale: de_DE
> Found translations at /usr/share/locale, using those.
> Use OS locale language.
> Traceback (most recent call last):
>   File "/usr/bin/flowblade", line 79, in <module>
>     app.main(modules_path)
>   File "/usr/lib/python2.7/site-packages/Flowblade/app.py", line 201, in main
>     shortcuts.load_shortcut_files()
>   File "/usr/lib/python2.7/site-packages/Flowblade/shortcuts.py", line 44, in load_shortcut_files
>     for f in os.listdir(respaths.SHORTCUTS_PATH):
> OSError: [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/Flowblade/res/shortcuts/'

i have solved it by adding this patch:
```
--- flowblade-889855c4f35a6c8ee5adc2c7da5b3ec31b2ff9d3/flowblade-trunk/setup.py.orig	2017-09-25 10:48:37.705785781 +0200
+++ flowblade-889855c4f35a6c8ee5adc2c7da5b3ec31b2ff9d3/flowblade-trunk/setup.py	2017-09-25 10:49:43.182790523 +0200
@@ -33,7 +33,7 @@
 flowblade_package_data = ['res/filters/*.xml','res/filters/wipes/*','res/img/*',
                           'res/profiles/*','res/render/renderencoding.xml',
                           'res/patternproducer/*','res/help/*','locale/Flowblade/*',
-                          'res/proxyprofiles/*','res/darktheme/*','launch/*','res/gmic/*']
+                          'res/proxyprofiles/*','res/darktheme/*','launch/*','res/gmic/*','res/shortcuts/*']
 
 locale_files = []
 for filepath in glob.glob("Flowblade/locale/*/LC_MESSAGES/*"):
```

**Comment by jliljebl** [comment]
OK, thanks, I added your patch. Are you using setup.py to do install, otherwise  your patch shouldn't make difference if I understood correctly?

**Comment by martinkg** [comment]
yes i use python2 setup.py  install ....

**Comment by jliljebl** [comment]
Thanks for info. I've had setup.py present  because .deb packaging has needed it, but I'll look into how one can actually do installs with it. I'll close this this as fixed now.
