### ISSUE TITLE
Nonfiltered frame on Monitor after clip trim

### ISSUE THREAD

**Issue by AS383** [jliljebl/flowblade#441]
If I trim clip with some filter effects (saturation, curves, denoise) Monitor shows nonfiltered frame. If I move playhead Monitor updated normally.

**Comment by jliljebl** [comment]
Yes, this the current functionality and it will remain so.

* The main purpose of Trim tool is to allow as resposive as possible way to select a cut frame.
* All filters make seek and playback at least a bit slower, and some considerably so.
* Filtering does not add relevant information when selecting a cut frame.

Closing as *wontfix*.

**Comment by AS383** [comment]
Ok. I partially agree. While user is trimming frame can be shown without effects for performance. But when the operation finished a frame need to be updated correctly without additional action. If it is not a user feel a bug (e.g. effects options reset or plugins hang).
P.S.: Trimming with effects on can be useful in some cases. For example when editing dark short a user can miss some details without brightness up. I think the option for this performance tuning will be good.

**Comment by jliljebl** [comment]
To update frame to show effects after the trim is complete would actually be a major addition of code complexity on an area which is pushing the limit of maintainable code complexity already.

I do not consider the small added user value worth the considerable risk of destabilizing a central part of application functionality, this will remain *wontfix*.
