### ISSUE TITLE
Videos imported to different bins if user switch it

### ISSUE THREAD

**Issue by AS383** [jliljebl/flowblade#443]
I have two bins: bin_1 & bin_2.
If I import a long set of videos into bin_1 and then switch to bin_2 while import not finished, remain videos are added to bin_2. It does not matter if I use add button or drag & drop for this.

**Comment by jliljebl** [comment]
Confirmed...and I guess it is a sort of bug as this can  be thought to go against user expectation on how media  import should work.

Fixing this will on the other hand can be bit annoying, there a some complications on chnaging how this works, but this will probably eventually get fixed.

**Comment by jliljebl** [comment]
This is now fixed.
