### ISSUE TITLE
Solus distro issue: ERROR: No module named mlt

### ISSUE THREAD

**Issue by maizuddin35** [jliljebl/flowblade#444]
Im running Solus 3 . Downloaded flowblade from git, and I can't run it . 

here's the output

`FLOWBLADE MOVIE EDITOR 1.14
---------------------------
Launch script dir: /home/adib/flowblade/flowblade-trunk
Running from filesystem...
MLT not found, exiting...
ERROR: No module named mlt
`
I have kdenlive,pitivi installed in my machine. and when I run "locate mlt.py"
I don't get any output.
What should I do to make it run? or is it still not ready for Solus ?

**Comment by dvdlvr** [comment]
Make sure you have both libmlt and python-mlt installed.

**Comment by maizuddin35** [comment]
I need to build python-mlt from scratch . Solus OS doesn't have that for now.

**Comment by jliljebl** [comment]
Yeah, after some googling it seemed that Solus doesn't have mlt-python bindings available so those need to made available to run Flowblade.

**Comment by maizuddin35** [comment]
@jliljebl , yes, so, does that mean, that, I need to atleast inform this about them, so that, they can implement it ?

**Comment by jliljebl** [comment]
Hi, sorry, I missed this last comment. They can look the contents on the "python-mlt" package that is Debian and provide a port of it to Solus, this should not be difficult for knowledgeable distro developers, they certainly have many similar Python packages already available.

**Comment by jliljebl** [comment]
This is upstream issue and cannot be fixed here.
