### ISSUE TITLE
Feature request: reverse luma wipe

### ISSUE THREAD

**Issue by JonasCz** [jliljebl/flowblade#446]
First, thanks for making such an awesome video editor :-)

I have a feature request: the ability to reverse luma wipes.

 Normally, when doing a luma wipe (e.g. with the "Wipe clip length" compositor), it goes from 0% visibility to 100%. I use this for animating in titles, so they gradually appear. However, I'd also like to use such a luma wipe to hide the titles, so they go from being 100% visible to 0%, according to the luma file. There does not seem to a way of doing this currently.

Kdenlive just has a "reverse transition" checkbox in the settings panel for the wipe, maybe Flowblade could do the same, and add a "Reverse" checkbox in the settings panel for "Wipe clip length" ?

**Comment by jliljebl** [comment]
Thanks for the nice words. 

Oh I see, the 'Invert' checkbox reverses the areas composited in and out, but does not reverse the direction of the wipe progression, which is what is looked for here.

I agree that this would be a useful feature, i'll add it to feature queue.

**Comment by jliljebl** [comment]
Feature in repository, will be 1.16.
