### ISSUE TITLE
MLT error with custom renderencoding.xml

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#448]
We use Flowblade 1.14 on 3 systems with a custom _renderencoding.xml_ file (see below). On one of those systems, when the custom XML is used, Flowblade crashes with the following message. We tried to pinpoint the cause without success but it seems it might be somehow related to MKV and MOV containers. Packages in the same versions seem to be installed on all systems (libavformat 7:3.4, libmlt 6.5, python-mlt 6.5). Looks like Flowblade or MLT might have some hidden dependencies.

**Error message:**

```
MLT detection succeeded, 152 formats, 84 video codecs and 68 audio codecs found.
464 MLT services found.
Loading render profiles...
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 74, in <module>
    app.main(modules_path)
  File "/usr/share/flowblade/Flowblade/app.py", line 174, in main
    renderconsumer.load_render_profiles()
  File "/usr/share/flowblade/Flowblade/renderconsumer.py", line 207, in load_render_profiles
    encoding_option = EncodingOption(eo_node)
  File "/usr/share/flowblade/Flowblade/renderconsumer.py", line 144, in __init__
    self.acodec)
  File "/usr/share/flowblade/Flowblade/mltenv.py", line 110, in render_profile_supported
    err_msg = "format " + frmt
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**renderencoding.xml** (custom lines marked with +++)

```xml
       <!-- User editable encodings -->
       <!-- encoding options group together codecs, file formats and quality option groups -->
+++    <encodingoption name="PREFKA / .mp4" extension="mp4" audiodesc=" aac" type="av" resize="True" qgroup="qgroup2">
+++        <profile args="f=mp4 s=%SCREENSIZE% hq=1 acodec=aac ab=160k pix_fmt=yuv420p vcodec=libx264 preset=slow profile=main"/>
+++    </encodingoption>
+++    <encodingoption name="BEZSTRATNY MONO / .mov" extension="mov" audiodesc=" flac"  type="av" resize="True" qgroup="lossless">
+++        <profile args="f=mov acodec=flac ac=1 pix_fmt=yuv420p vcodec=libx264 qp=0" />
+++    </encodingoption>
       <encodingoption name="MPEG-2 / .mpg" extension="mpg" audiodesc=" mp2" type="av" resize="True" qgroup="qgroup1">
           <profile args="f=mpeg acodec=mp2 ab=384k vcodec=mpeg2video minrate=0 vb=%BITRATE% bf=2 b_strategy=1 trellis=1" />
       </encodingoption>
```

**Comment by apienk** [comment]
**Update.** The cause turned out to be the Flowblade deb package itself. Recently, Flowblade 1.14 was added to Ubuntu universe repository, and this official repository version is damaged causing the above error, as well as a few others. Reinstalling the package from https://github.com/jliljebl/flowblade/releases fixes the issue.

**Comment by jliljebl** [comment]
Thanks for the info. I'll leave this open until the Ubuntu repo deb is fixed, I'll do bug report later if someone doesn't beat me to it, right now I have spend all my time with SDL2 upgrade caused problems.

**Comment by jliljebl** [comment]
This has been open now a few months for info, closing.
