### ISSUE TITLE
File extension not updated in GUI (minor)

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#450]
Steps to reproduce:

1. With a project loaded, open Render tab, set User Defined, and choose an Encoding Format.
2. Render the project, save and close.
3. Open the project again and open Render tab. Notice that the Encoding Format used last time is selected but file extension shown next to file name at the top does not match the format. It is updated only after selecting another format, and selecting the first again.

It is only a GUI issue. The project is rendered to a file with correct extension.

**Comment by apienk** [comment]
Update: This is not a GUI issue only. The rendered file is saved with a wrong extension.

**Comment by jliljebl** [comment]
This does not reproduce here. Some ideas:

1) You had that another Unicode related issue, does this go away if both movie and project names are ASCII  (English only) characters?
2) Can you start application from terminal with command 'flowblade' and see if you get any errors and post them here?

**Comment by apienk** [comment]
Our filenames never contain non-ASCII characters.
Flowblade does not report any errors in terminal.

Flowblade now remembers project-specific encoding options as well as output file path and filename. This bug seems related to this feature.

I can't find a consistent way to reproduce this behavior but it's happening every time I open one of my projects. I go to Render tab, and I see ".wav" next to the file name but ".mkv" encoding is selected. Look at the screenshot.
![zrzut ekranu z 2017-11-15 15-41-01](https://user-images.githubusercontent.com/9961826/32841742-7123adf8-ca1b-11e7-9d2e-8c2deebe8c4d.png)

**Comment by jliljebl** [comment]
Thanks, I do find it perfectly plausible that remembering project-specific encoding options etc. feature has caused some problems. I'll keep this open will retry later.

**Comment by jliljebl** [comment]
I was working on related issue and looked at the code and cannot see how this should fail. It is possible that some projects saved earlier could display this Issue, but I'm closing as *unreproduced.*
