### ISSUE TITLE
Sound distorted after conversion from stereo to mono

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#451]
**Steps to reproduce:**

1. Create a project containing clips with both stereo and mono audio.
2. Use "Render using args" to force mono output: `ac=1`.
3. Play the rendered file.

**Observed result:**
Audio of the stereo clips is distorted while mono clips are OK.

**Expected result:**
Both types of audio clips are OK.

This is likely an issue with MLT but I don't know hot to make sure.

**Comment by dvdlvr** [comment]
To make sure it's an mlt issue you could do the following:
1) Save an MLT XML file (File -> Export)
2) Issue the melt command on the command line as follows:
melt xml_file.xml -consumer avformat:outputfile.mp4 list_of_arguments
where list_of_arguments is what you can see in Flowblade when clicking 
'Render using args' and is a space separate list of arg=value - don't 
forget to change ac=1 here.

**Comment by apienk** [comment]
Tested. It's the issue with MLT. Using version: 6.5+git201704252005 from PPA.

**Comment by apienk** [comment]
Submitted to MLT: https://github.com/mltframework/mlt/issues/269
