### ISSUE TITLE
Packaging: AppImage, Snap. Flatpak

### ISSUE THREAD

**Issue by jliljebl** [jliljebl/flowblade#453]
Creating at least one of these is part of the <2.0 feature set.

**Comment by eszlari** [comment]
A flatpak version of Flowblade is now available on Flathub:

https://www.flathub.org
https://github.com/flathub/io.github.jliljebl.Flowblade

**Comment by eszlari** [comment]
By the way: I noticed some crashes while testing. For debugging you might want to know, that you can run` gdb` inside flatpak's sandbox like this:
```
$ flatpak -d --command=sh run io.github.jliljebl.Flowblade
in the sandbox:
$ gdb python2
$ (gdb) run /app/bin/flowblade
```

**Comment by jliljebl** [comment]
Alraight, great! I'll look into this sometime next week when I do my next session on the project. If we can get this working crash ffree that would be a good step forward with project now that theses packages are becoming more relevant all the time.

**Comment by eszlari** [comment]
The build is stable now (from my testing). It was during writing the build manifest, that I experienced crashes when trying to build flowblade with only minimal dependencies. Instead of complaining through error messages about missing dependencies it would crash in MLT. There was also a crash when using SDL1+pulseaudio, so I disabled that in the build.

I was uncertain about some of the dependencies. Maybe you could have a look at the build manifest. (e.g. should the gtk2 MLT module be included?)

Maybe you could also incorporate the workarounds (file naming, hard-coded paths) from the build manifest, see:
https://github.com/flathub/io.github.jliljebl.Flowblade/blob/master/io.github.jliljebl.Flowblade.json#L487

I guess it's on the road map anyway, but porting to python3 and sdl2 would also make it possible to drop libraries that are bundled at the moment (sdl1, pycairo, pygobject, dbus-python), because they are part of the flatpak runtime this build depends on.

As the author of Flowblade the Flathub admins would of course be happy, to give you access to https://github.com/flathub/io.github.jliljebl.Flowblade

**Comment by jliljebl** [comment]
@eszlari I tested the Flatpak from Flathub and it seemed to work perfectly with MLT 6.6.0 and Arc Darker theme. Excellent work!

With this proof I'm going to make Flatpak my preferred binary package format - and for the time being the only one. 

The AppImage I did was very hard to do. I needed to resolve some package version problems manually and was only able to get quite old version off MLT going. Also the script I wrote was very complex and I didn't feel I understood half of it.

To get this moving along I have some questions, I do not have much knowledge on Flatpak yet.

1) If I understood correctly, the hard part was what you did, creating this file: https://github.com/flathub/io.github.jliljebl.Flowblade/blob/master/io.github.jliljebl.Flowblade.json ?

2) What we need now is to update that .json file for the about 2 releases a year I do, create a new flatpak from it and make that available via Flathub, right, and the main workflow is:
 * Update https://github.com/flathub/io.github.jliljebl.Flowblade/blob/master/io.github.jliljebl.Flowblade.json
 * Build a flatpack from it on local system to test it.
 * Somehow flatpack becomes available in Flathub

3) Flathub is the flatpak project's preferred distribution method, so there probably is no need make this available elsewhere, as the interested parties can do that themselves if they so desire?

4) Would you be willing to do the updates if contact you once I have tagged the releases? You seem to have expert level of understanding on subject. Even doing every other release once a year would be massive improvement on availability of Flowblade across distros.

5) If not, did you create some script to build the flatpack from the .json file? I have always found it easiest to get going with something if there is a somewhat relevant example available. The available "Hello World" did not seem to offer much info on handling the added complexity needed to get this done.

On your questions on dropping dependencies:

1) **Going to Python3.** This is I think some years away, doing this will halt other development for at least half a year, I think. For exaple MLT does not have Python3 bindings available

2) **Dropping SDL 1.2**. This was already tried in the last few moths and we keep working on it.

3) **Dropping pycairo, pygobject, dbus-python.** I do "import cairo", "import dbus"  and "from gi.repository import GObject" . I need to look into this, maybe there are something like "from gi.repository import Cairo as cairo" and "from gi.repository import DBus as dbus" available, I might have missed that I could be using newer libraries here.

**Comment by eszlari** [comment]
> 1. If I understood correctly, the hard part was what you did, creating this file: https://github.com/flathub/io.github.jliljebl.Flowblade/blob/master/io.github.jliljebl.Flowblade.json ?

Yes.

> 2. What we need now is to update that .json file for the about 2 releases a year I do, create a new flatpak from it and make that available via Flathub, right, and the main workflow is:

When you commit to the master branch on flathub, that triggers a new build (https://flathub.org/builds/) and when all supported architectures (i386, x86_64, arm, aarch64) are built successfully the binaries get uploaded to the flathub repository.

You can also do a pull request and trigger a test build manually, by adding a comment with the message `"bot, build"`.

> 3. Flathub is the flatpak project's preferred distribution method, so there probably is no need make this available elsewhere, as the interested parties can do that themselves if they so desire?

Yes. Also notice that Flathub is intended for stable releases. GNOME and KDE provide their own repositories for nightly builds:

https://github.com/GNOME/gnome-apps-nightly
https://distribute.kde.org/kdeapps.flatpakrepo

> 4. Would you be willing to do the updates if contact you once I have tagged the releases? You seem to have expert level of understanding on subject. Even doing every other release once a year would be massive improvement on availability of Flowblade across distros.

I would do it, but believe me, it's very easy to do and if you do it yourself, you won't have to wait for me, when you're doing releases. You just have to update two files:

`io.github.jliljebl.Flowblade.json`  - URL and SHA256 of the release tarball
`io.github.jliljebl.Flowblade.appdata.xml` - the `<release>` tag

> 5. If not, did you create some script to build the flatpack from the .json file? I have always found it easiest to get going with something if there is a somewhat relevant example available. The available "Hello World" did not seem to offer much info on handling the added complexity needed to get this done.

You don't need scripts, because it is easy to build and test your app locally:

```
$ git clone https://github.com/flathub/io.github.jliljebl.Flowblade
$ cd io.github.jliljebl.Flowblade
$ flatpak-builder --install build_dir io.github.jliljebl.Flowblade.json
$ flatpak run io.github.jliljebl.Flowblade
```

You can use `flatpak-builder --ccache` to improve recompilation time.

**Comment by jliljebl** [comment]
@eszlari  Thanks for the answers, these are very helpful.You're right, I can probably get things going from here. I'll post updates when there is Flatpak for 1.16.

**Comment by eszlari** [comment]
Notice: If you want to have commit access to https://github.com/flathub/io.github.jliljebl.Flowblade you will have to contact the flathub admins. I'm just a contributor.

**Comment by eszlari** [comment]
I updated the version on flathub to 1.16:
https://github.com/flathub/io.github.jliljebl.Flowblade/commit/0d69a0b3a2460251d6e326e8b051c800bd47a017

**Comment by jliljebl** [comment]
@eszlari, thank you!

I added instructions on installing from Flathub and did a Google+ post:

https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md#installing-flatpak-from-flathub

https://plus.google.com/u/0/102624418925189345577/posts/8urfebeTRVi

**Comment by jliljebl** [comment]
@eszlari I was locally building Flatpak for Flowlbade 2.2 and got following error:

[32] .debug_loc compressed -> .zdebug_loc (488327 => 80781 16.54%)
[33] .debug_ranges compressed -> .zdebug_ranges (50064 => 8097 16.17%)
[36] Updating section string table
stripping /home/janne/codes/flatpak-build/io.github.jliljebl.Flowblade/.flatpak-builder/rofiles/rofiles-VPKVQV/files/lib/gtk-2.0/modules/libgail.so to /home/janne/codes/flatpak-build/io.github.jliljebl.Flowblade/.flatpak-builder/rofiles/rofiles-VPKVQV/files/lib/debug/lib/gtk-2.0/modules/libgail.so.debug
Committing stage build-gtk2 to cache

Any ideas on required changes on .yaml? I only changed the git commits for flowblade and MLT in the manifest.
Error: linkat: Operation not permitted

**Comment by jliljebl** [comment]
I'm building as 'root' now, lets see if that helps.

**Comment by jliljebl** [comment]
@eszlari Building as root seemed to go further but my 4GB system run out of memory when building G'mic.

I tried to push to flathub git on assumption that my build is correct but got:

```bash
root@janne-Lenovo-G50-80:~/codes/flatpak-build/io.github.jliljebl.Flowblade# git push
Username for 'https://github.com': jliljebl
Password for 'https://jliljebl@github.com': 
remote: Permission to flathub/io.github.jliljebl.Flowblade.git denied to jliljebl.
fatal: unable to access 'https://github.com/flathub/io.github.jliljebl.Flowblade.git/': The requested URL returned error: 403
```
...so I got no push access, I think.

The diff is below, can you push and see if it works?

```bash
diff --git a/io.github.jliljebl.Flowblade.yaml b/io.github.jliljebl.Flowblade.yaml
index aa48b35..18b9d35 100644
--- a/io.github.jliljebl.Flowblade.yaml
+++ b/io.github.jliljebl.Flowblade.yaml
@@ -252,7 +252,7 @@ modules:
     sources:
       - type: git
         url: https://github.com/mltframework/mlt.git
-        commit: eaf73b149347f2229eea44a038edea3170e03d39
+        commit: 179228302e0dabc0ee883a6abd790e9957271425
 
   - name: flowblade
     buildsystem: simple
@@ -268,4 +268,4 @@ modules:
     sources:
       - type: git
         url: https://github.com/jliljebl/flowblade.git
-        commit: dc58195fe7622fa1bece0c9ae1fbc1f7e97d003a
+        commit: d38b3edd47ee77855781c17c812d4042ffed8f26
```

**Comment by jliljebl** [comment]
With G'Mic removed from manifest the Flatpak builds and seems to work just fine, my system just can't build G'Mic.

Since I cant push to https://github.com/flathub/io.github.jliljebl.Flowblade.git/ I'll do pull request.

**Comment by jliljebl** [comment]
The pull request is in, build test passed and end result worked on my system if we just get it merged we'll have 2.2 on market for Flatpak users.

**Comment by eszlari** [comment]
According to https://github.com/flathub/io.github.jliljebl.Flowblade/issues/3 you should have commit access?!

**Comment by jliljebl** [comment]
Yeah, I tried to push but didn't go through. I might have made some mistake, I'll try again for next one.

**Comment by eszlari** [comment]
And why didn't you merge your Pull Request form the Github interface? Does this work?

Why are you not on the Watchers list?
https://github.com/flathub/io.github.jliljebl.Flowblade/watchers
Normally, you get added to that list when you accept the invitation.

**Comment by jliljebl** [comment]
I will look in to this, it is possible that my push attempt was not correct.

ti 27. elokuuta 2019 klo 15.23 eszlari <notifications@github.com> kirjoitti:

**Comment by jliljebl** [comment]
@eszlari I some missed your answer here. I added myself into Github watchers list and will try use Github interface for 2.4 update.

I'm closing this as sticky, we will handle Flatpak issues with separate new Issues in here and the Flowblade Flathub Issue list from now on.
