### ISSUE TITLE
obsolete DOCS "rendering"

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#454]
The description of the rendering panel on the help page does not correspond to the current flowblade rendering panel.

**Comment by jliljebl** [comment]
Ok, this needs updating.

**Comment by jliljebl** [comment]
I added following lines for GUI components which seemed to be missing:

<h5>Use Project Profile Checkbox</h5> <div class="r-widget">Uncheck to select some other then project profile to used for rendered video.</div>
<h5>Profile Select drop down menu</h5> <div class="r-widget">Select project profile for rendering</div>
