### ISSUE TITLE
Error: Add to Batch Render Queue.

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#456]
"Render->Add to Batch Render Queue..." does not work when using Cyrillic, in the original language everything works.
"Adding item to render queue failed!
Error message: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)"

**Comment by jliljebl** [comment]
Confirmed.

**Comment by jliljebl** [comment]
Fixed in repo, will be in 1.16.
