### ISSUE TITLE
Covering emails or passwords in video window V1.14

### ISSUE THREAD

**Issue by bigalgeorge** [jliljebl/flowblade#457]
Hi Ive been using a text box putting the words HIDDEN and then placing it over a video area that needs covering eg an email or password underneath. This is a particularly laborious process and Im wondering if there is any other method. 
![selection_107](https://user-images.githubusercontent.com/6935387/33151802-7a77d432-d03e-11e7-99f6-34f0357504cf.png)
Areas in the video that need protecting move all the time and desired ability is to be able to 'fuzzify' a box area, so that viewer cant see content underneath. Ideally to be able to draw a box on the video and apply a filter to the box and set period/length its visible

**Comment by dvdlvr** [comment]
See this post on how combining a compositor and a colour clip. This applies to any filter + compositor.
You can move the filtered part around by using keyframes in the compositor.
That should allow you to do this in a better manner.
https://plus.google.com/u/0/109592490599568940801/posts/B1hm44Yvami

**Comment by jliljebl** [comment]
I'll combine this with issue #458 and close as merged.
