### ISSUE TITLE
Apply filter to part of image

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [jliljebl/flowblade#458]
Hello, 
how to blur a small part of the screen, 
for example if i want to blur one line of a text in a video, how can i do that with flowblade? 

until now no linux video editor has success to improve that feature and make it simple like on Camtasia for example (windows).

**Comment by bigalgeorge** [comment]
See the previous question by me and how I do it; use a text box but that is cumbersome and I think there must be another way but nobody has responded.

**Comment by Ghostboy-287** [comment]
ah i didn' see it, i searched for blur keyword but i found no issue related to it, so i posted this :) 
( me i have always a windows in another pc where camtasia is installed just to blur and hide some sensitive informations )  but it s a good idea the way u use to hide them using flowblade

**Comment by bigalgeorge** [comment]
Its not a good solution at all because it needs to be redone all the time the sensitive area moves. There is already a blur filter and a box but seems no way to use that to do the same job.

**Comment by Ghostboy-287** [comment]
good idea don't mean good solution 😛

I think that we have just to hope to see a solution in future versions, or at least a tuto of an alternative solution since it's complicated and not easy to code (otherwise we'd already have this feature in at least one linux video editor )

**Comment by dvdlvr** [comment]
See this post on how combining a compositor and a colour clip. This applies to any filter + compositor.
You can move the filtered part around by using keyframes in the compositor.
That should allow you to do this in a better manner.
https://plus.google.com/u/0/109592490599568940801/posts/B1hm44Yvami

**Comment by jliljebl** [comment]
This needs to added in MLT level, Flowblade does not even have access to image data during filter application.. The approach is basically easy, but has not been done yet.

1) If filter requests partial application, create copy of image before applying filter
2) Apply filter on recived image
3) Composite filtered image on unfiltered image on area defined by user. This is simple alpha composite where user requested application area is expressed as alpha channel of filtered image.
4) Pass on the result.

In practice this could be quite task thought, details could very well be quite demanding here. 

Se dvdlvr suggestion above for approach on how to do this now.

**Comment by jliljebl** [comment]
MLT now has support for partial filter application, so we will be attempting this for 2.6.

**Comment by mIcHyAmRaNe** [comment]
good news

**Comment by jliljebl** [comment]
This is now in repo, will be 2.6.
