### ISSUE TITLE
Flowblade refuse to start depending the way the filsystem is configured

### ISSUE THREAD

**Issue by JeanLucCoulon** [jliljebl/flowblade#459]
Hi,
I've a filesystem spread on 2 disks.
One SSD with most of the system itself and my home directory.
And a 1TB disk for various data.

Due to the size of the SSD (quite small), my /opt directory is on the second HDD, not the SSD

If I install there Flowblade, I've the following messages and it failed to start cleanly:

[...]
G'MIC found
Natron not found
Player initialized with profile:  DV/DVD PAL
Selected color NOT detected
BG color detected
Create SDL1 consumer...
[swscaler @ 0x7f97c443fc20] Warning: data is not aligned! This can lead to a speed loss
Autosave started...
Save project autosave_b2238263b1384d0c2b2141fdac412e94
Traceback (most recent call last):
  File "./flowblade/flowblade-trunk/flowblade", line 78, in <module>
    app.main(modules_path)
  File "/extra/flowblade/flowblade-trunk/Flowblade/app.py", line 330, in main
    start_autosave()
  File "/extra/flowblade/flowblade-trunk/Flowblade/app.py", line 726, in start_autosave
    persistance.save_project(editorstate.PROJECT(), autosave_file)
  File "/extra/flowblade/flowblade-trunk/Flowblade/persistance.py", line 200, in save_project
    pickle.dump(s_proj, write_file)
  File "/extra/flowblade/flowblade-trunk/Flowblade/atomicfile.py", line 159, in __exit__
    os.rename(self.tmp_file_path, self.dest_file_path)
OSError: [Errno 18] Invalid cross-device link

Then I've to kill it, it is in en pending state.

if I change os.rename(self.tmp_file_path, self.dest_file_path) with
shutil.move(self.tmp_file_path, self.dest_file_path)

This fixes the problem.
[flowblade-os_rename.txt](https://github.com/jliljebl/flowblade/files/1502341/flowblade-os_rename.txt)

patch attached

Regards

Jean-Luc

**Comment by jliljebl** [comment]
Thanks, I applied the patch and seems to work on my more standard system. I'll close as fixed, reopen if more issues occur.
