### ISSUE TITLE
Rendering with multiple sequences in unecode does not work

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#460]
Good day to all
1) Flowblade version 1.14.0
2) MLT version 6.0.0
3) Your distribution Xubuntu 16.04
Again, the problem with Unicode.
If you create another sequence and save the project, then Flowblade will not open this project again. If you create another sequence and edit it, Flowblade will not be able to perform the rendering.

output from the terminal:
Player initialized with profile:  HD 720p 23.98 fps
Selected color NOT detected
BG color detected
Autosave started...
Save project autosave_84146e49129278db9ae1510425fb692b
Player initialized with profile:  HD 720p 23.98 fps
Autosave started...
Save project autosave_84146e49129278db9ae1510425fb692b
Save project current_render_project.flb
Save project Безымянный.flb
Autosave started...
Save project autosave_84146e49129278db9ae1510425fb692b
Loading Project, SAVEFILE_VERSION: 5
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/flowblade/Flowblade/projectaction.py", line 111, in run
    project = persistance.load_project(self.filename)
  File "/usr/share/flowblade/Flowblade/persistance.py", line 423, in load_project
    _show_msg(_("Building sequence ") + seq.name)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

**Comment by jliljebl** [comment]
Confirmed.

**Comment by jliljebl** [comment]
Fixed. This unicode thing originally worked, but something changed in underlieing platform sometime and broke quite a few of these.
