### ISSUE TITLE
Strange problem – please advise

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#463]
This is unlikely to be a bug in Flowblade because it happens only on some of our installations and Melt has problems too.

On affected systems, all placing/scaling compositors (Affine Blend, Picture in Picture, Region) work in Flowblade UI but **do not work in renders**. In rendered files, overlays using those compositors are distorted due to not-to-aspect scaling (still image clips, PNG or SVG – look at screenshots below) or garbled (movie clips – see below). Interestingly, when exported XML is run through Melt via command line, still image overlays are missing altogether (not rendered) while movie overlays are garbled. Is Flowblade using Melt differently for the preview and the render?

Additionally, in all affected systems, Affine Transform filter's Size/Height control moves the clip along Y axis instead of scaling it. I suspected that the root of the problem might be in frei0r plugins or cairo but I could not find anything constructive. Also, Flowblade tends to detect a different number of MLT services on different systems, despite frei0r, libmlt and python-mlt packages being exactly the same. Is there a hidden dependency? Could you please point me in a direction where to look for the cause?

Thank you!

Packages used on all systems:
```
flowblade     1.14.0-1
frei0r-plugins    1.6.1+git201703252353
gir1.2-gdkpixbuf-2.0     2.32.2-1ubuntu1.3
gir1.2-glib-2.0     1.46.0-3ubuntu1
gir1.2-gtk-3.0     3.18.9-1ubuntu3.3
gir1.2-pango-1.0     1.38.1-1
gmic     1.6.8-3
libmlt-data     6.5+git201704252005
librsvg2-common     2.40.13-3
python     2.7.12-1~16.04
python-cairo     1.8.8-2
python-dbus     1.2.0-3
python-gi     3.20.0-0ubuntu1
python-gi-cairo     3.20.0-0ubuntu1
python-mlt     6.5+git201704252005
python-numpy     1:1.11.0-1ubuntu1
python-pil     3.1.2-0ubuntu1.1
swh-plugins     2:0.4.15+1-8
```
In Flowblade, logo has a correct aspect.
![misscaled-logo1](https://user-images.githubusercontent.com/9961826/33602093-90e5ed66-d9ae-11e7-80ec-e1fef4742728.png)
In rendered video, logo is mis-scaled.
![misscaled-logo2](https://user-images.githubusercontent.com/9961826/33602095-913e62fc-d9ae-11e7-9ea8-e302d082c5fd.png)
Garbled video in rendered file (overlain using affine blend). In Flowblade looks OK.
![garbled-video-after-affine-blend](https://user-images.githubusercontent.com/9961826/33602642-3d48fd2c-d9b0-11e7-8da6-f43140cc7e6e.png)

**Comment by jliljebl** [comment]
HI, this will probably take some time get figured out.

Can you first do File ->Export ->MLT XML on affected systems and then do playback and maybe try to render with melt https://www.mltframework.org/docs/melt/  to make sure that this is not Flowblade issue.

Then if you could do a simplest possible program with the issue, do "Save Snapshot" and make the resulting folder available somehow.

**Comment by dvdlvr** [comment]
Just for easy of use, here's a full command line example for rendering 
using the XML file:

melt filename.xml -consumer avformat:"output_filename.mp4"  f=mp4 
s=1280x720 hq=1 acodec=libmp3lame ab=384k pix_fmt=yuv420p vcodec=libx264 
minrate=0 b=2000k b_strategy=1 subcmp=2 cpm=2 coder=1 flags=+loop 
qmax=51 subq=7 qmin=10 qcomp=0.6 qdiff=4 trellis=1 aspect=@16/9

filename.xml and output_filename.mp4 should obviously be adapted to suit 
your own.

The above example uses the default parameters that Flowblade uses for a 
standard 720p @25fps output using H.264 @2000kbps

I hope this helps.

**Comment by jliljebl** [comment]
Thanks.

5.12.2017 5.39 ip. "dvdlvr" <notifications@github.com> kirjoitti:

**Comment by apienk** [comment]
After a lot of experimenting problems are solved, except for one which is a Flowblade bug. I will file a separate report, so that this issue can be closed.

The garbled or mis-scaled video issue was caused by missing aspect information in `renderencoding.xml`. We use two custom encoding entries in that file: one MP4 and one MKV. The issue was fixed by changing this:

`<profile args="f=mp4 s=%SCREENSIZE% hq=1 acodec=aac ab=160k pix_fmt=yuv420p vcodec=libx264 preset=slow profile=main/>`

to this:

`<profile args="f=mp4 s=%SCREENSIZE% hq=1 acodec=aac ab=160k pix_fmt=yuv420p vcodec=libx264 preset=slow profile=main aspect=%ASPECT%"/>`

Strangely enough, the MKV output was correct despite missing %ASPECT% and similarly using libx264:

`<profile args="f=mkv acodec=flac ac=2 pix_fmt=yuv420p vcodec=libx264 qp=0" />`

Seems that only MP4 container needs this option to be set explicitly.

Thank you for suggestions.
