### ISSUE TITLE
Resizing still images does not work in affine transform filter

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#464]
**Steps to reproduce:**

1. Open Flowblade with any video clip on track V1
2. Put a still image clip (PNG, SVG, JPG) on track V2
3. Add Blend compositor to V2
4. Add Transform/Affine filter to the still image clip on V2
5. Adjust the Size/Height parameter

**Expected result:**

The image is scaled.

**Observed result:**

The image is moved up/down, not scaled.

**Packages:**

flowblade 1.14.0 (installed from https://github.com/jliljebl/flowblade/releases)
MLT 6.5.0
GTK 3.18.9

Ubuntu Xenial amd64

**Comment by jliljebl** [comment]
Confirmed. Video clips work, still images do not.

**Comment by apienk** [comment]
Also, with still images, positioning and scaling an inset using numerical parameter boxes does not have any effect at all.

Flowblade 2.0.0

**Comment by OCTOGONE-IT** [comment]
What i do to solve this is to use the size of the video format. For example you have a video in FullHD (1920X1080) and a logo of 250X250 pixels. just create an image of 1920X1080 in PNG32 with tranparency and place your logo in it.

**Comment by concretedog** [comment]
Hoping this can get solved for still images/png etc as it makes adding little label images to pop up in videos easier.

**Comment by jliljebl** [comment]
Release 2.4 will come with a complete overhaul  of 'Transform' filters group and the new 'Position Scale' filter solves all the issues presented here, closing as *fixed*.
