### ISSUE TITLE
Render to PNG codec in MOV container no longer possible

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#465]
**Steps to reproduce:**

1. Open Flowblade with any video clip
2. Export MLT XML
3. Run Melt in terminal: `melt test.xml -consumer avformat:test.mov f=mov s=1920x1080 hq=1 acodec=aac ab=160k vcodec=png`
4. In Flowblade go to Render tab
5. Select "Render with args"
6. Edit args and type: `f=mov s=1920x1080 hq=1 acodec=aac ab=160k pix_fmt=yuv420p vcodec=png`
7. Render the file

**Expected result:**

Both command-line Melt and Flowblade generate a MOV file.

**Observed result:**

Melt generates a MOV file but Flowblade generates a series of PNG files instead.

**Packages:**

flowblade 1.14.0 (installed from https://github.com/jliljebl/flowblade/releases)
MLT 6.5.0
GTK 3.18.9

Ubuntu Xenial amd64

**Comment by apienk** [comment]
Note: this used to work in Flowblade 1.10.

**Comment by jliljebl** [comment]
Ok, looked at code and it does use "vcodec=png" to decide that it should render image sequences and that was added to fix #428. Let's see if there is some way to special case this "image codec into movie file" use case.

**Comment by jliljebl** [comment]
Fixed, we had data available to separate the cases, will be in 1.16.

**Comment by apienk** [comment]
Great, thanks!
