### ISSUE TITLE
Batch Rendering not starting correctly.

### ISSUE THREAD

**Issue by goingalong** [jliljebl/flowblade#468]
Flowblade 0.14rc on Lubuntu 16.04 32bit (VirtualBox)

I have 3 jobs in the queue. When I start the queue nothing happens. Running from the terminal I get lots of format info then:

`
  - pulse
  - sdl
  - v4l2
  - xv
...
MLT detection succeeded, 152 formats, 84 video codecs and 65 audio codecs found.
341 MLT services found.
Loading render profiles...
Proxy encoding MPEG-4 Preset Ultrafast ...available
Proxy encoding MPEG-2 Transport Stream ...available
Loading filters...
MLT service ladspa.1210 not found.
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/launch/flowbladebatch", line 15, in <module>
    batchrendering.main(modules_path)
  File "/usr/share/flowblade/Flowblade/tools/batchrendering.py", line 280, in main
    mltfilters.load_filters_xml(mltenv.services)
  File "/usr/share/flowblade/Flowblade/mltfilters.py", line 375, in load_filters_xml
    if editorstate.mlt_version_is_equal_or_greater(filter_info.mlt_drop_version):
  File "/usr/share/flowblade/Flowblade/editorstate.py", line 132, in mlt_version_is_equal_or_greater
    mlt_parts = mlt_version.split(".")
AttributeError: 'NoneType' object has no attribute 'split'Save project autosave_5dae3f921b54fd5052f05da7c1654804
```
``
Thought this was working previously - but not now. At least one of the jobs works ok if run as not batch.
Should I try a reinstall?

**Comment by jliljebl** [comment]
Flowblade 0.14 was released on June 18, 2014, latest release is Flowblade 1.14. This has been fixed years ago.

Update to latest version https://github.com/jliljebl/flowblade/releases

**Comment by goingalong** [comment]
Thank you, and sorry for not checking. I am pretty sure I downloaded that version within the last few weeks from the repository. Never mind, updated and working now.
