### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by lEgeol** [jliljebl/flowblade#469]
How can i change language? I believe the default language is system language but i don't like the translation for flowblade for this language.

I searched in options but i couldn't change it

Thanks you,

Please include the following information.
1) Flowblade version 0.14
2) MLT version 6.0.0
3) Your distribution Ubuntu 16.04

**Comment by smolnp** [comment]
![_2017-12-27_00-45-41](https://user-images.githubusercontent.com/26217756/34365274-8c1df22c-ea9f-11e7-845a-5ef132edb776.png)

**Comment by lEgeol** [comment]
I'm confused. How did I install version 0.14? I think I downloaded the wrong version the last time.

Thanks you,
