### ISSUE TITLE
Speeding Up Audio

### ISSUE THREAD

**Issue by Noah11012** [jliljebl/flowblade#470]
Please include the following information.
Flowblade version: 1.14.0 (Dev Version)
2) MLT version: 6.5.0
3) Your distribution: Linux Mint 18.3 Cinnamon

Flowblade can slow down/speed up videos clips with the Slow/Fast Motion tool. The only problem is it doesn't speed up the audio that came from the clip. Instead, it removes the sound entirely. Is there a way to add the audio sped up to the sped up clip or could I just split the audio, speed up the clip and then speed up the audio? I couldn't find anything in the Audio Filters. Perhaps I could have missed something?

**Comment by jliljebl** [comment]
Hi, yes there is a possibility to do this I think, but I need to look at this a bit more. MLT has two filters that do   Slow/Fast motion and one of them does audo too, but we are currently using the older one that does not.do audio.

**Comment by jliljebl** [comment]
This is in repo and will be in 1.16. We're now using the newer "timewarp" producer that gives sound for motion clips if available.
