### ISSUE TITLE
Without translation the following dialog boxes:

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#472]
![_2018-01-23_16-45-19](https://user-images.githubusercontent.com/26217756/35284616-49504ea8-006c-11e8-9f8e-abd0f6a6608b.png)
Open last autosave?
![_2018-01-11_18-21-59](https://user-images.githubusercontent.com/26217756/35284628-56c7bcc4-006c-11e8-957d-70d741cb15a9.png)
Render target file exists!
![dd](https://user-images.githubusercontent.com/26217756/35284634-5bf7fa6a-006c-11e8-86fd-ed9e90cafae6.png)
Can I publish this here?

**Comment by jliljebl** [comment]
Yes, missing translations are bugs so this the right place to inform project when you have found them.

I fixed the ones above and pushed the patch, but I'll keep the issue open for a while. If you find more missing translations you can comment here to tell us about them.

**Comment by smolnp** [comment]
Thank you!

**Comment by smolnp** [comment]
![_2018-01-23_19-02-50](https://user-images.githubusercontent.com/26217756/35289710-2c6cbf80-0079-11e8-8ddf-d1e98ffe4a47.png)

**Comment by jliljebl** [comment]
Fixed that one too, just happen at machine right now, usually these will take bit more time...

**Comment by smolnp** [comment]
it does not matter, the main thing that will be translated

**Comment by smolnp** [comment]
![_2018-01-23_19-02-50](https://user-images.githubusercontent.com/26217756/35290693-0008e7c2-007c-11e8-98b0-23a9e3ef1673.png)

**Comment by smolnp** [comment]
![_2018-01-23_20-36-34](https://user-images.githubusercontent.com/26217756/35291054-2b1e163e-007d-11e8-8e77-2c033494b933.png)

**Comment by smolnp** [comment]
Sequence Watermark
![2018-01-23_19-02-50](https://user-images.githubusercontent.com/26217756/35291549-ab1e8106-007e-11e8-82cc-8c87bd3e0b4a.png)

**Comment by jliljebl** [comment]
Alright, thanks. I always miss some of these, but these should now be fixed. 

I created a sticky issue #473 for these because these can always come up later, I unfortunately seem to be unable to get these 100% right.

**Comment by smolnp** [comment]
Thank you for your understanding! This is a problem for many programs, I just decided to devote my free time to only Flowblade and try to learn all of its details in detail.
