### ISSUE TITLE
Translations Issues

### ISSUE THREAD

**Issue by jliljebl** [jliljebl/flowblade#473]
This is a sticky issue for making reports on missing translation strings and other translations issues.

Please comment here to inform the project  on these issues.

**Comment by smolnp** [comment]
Media files already present in project were opened!...
![_2018-01-23_23-40-01](https://user-images.githubusercontent.com/26217756/35406526-30a9e008-021a-11e8-85fc-80a732d08e0b.png)

**Comment by smolnp** [comment]
![_2018-01-26_17-18-49](https://user-images.githubusercontent.com/26217756/35481766-25be60e2-043b-11e8-9eb4-cc9a49c0b1a6.png)

**Comment by jliljebl** [comment]
Fixed in repo.

**Comment by smolnp** [comment]
![_2018-02-18_16-26-19](https://user-images.githubusercontent.com/26217756/36352615-a6502f32-14cc-11e8-8822-84d05a8122eb.png)

**Comment by jliljebl** [comment]
Probably back on project next weekend, will fix.

18.2.2018 3.56 ip. "Николай Смольянинов" <notifications@github.com>
kirjoitti:

[image: _2018-02-18_16-26-19]
<https://user-images.githubusercontent.com/26217756/36352615-a6502f32-14cc-11e8-8822-84d05a8122eb.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jliljebl/flowblade/issues/473#issuecomment-366517923>,
or mute the thread

**Comment by smolnp** [comment]
![_2018-02-21_15-44-43](https://user-images.githubusercontent.com/26217756/36487855-f5a40d5c-1732-11e8-9ec3-1fbda9e40e87.png)

**Comment by smolnp** [comment]
I do not know if I need to create a separate topic, so I'll post it here. Many English words in the Russian language can have several meanings (depending on the context in which they are read).
For example, the word "BOX" can mean both a geometric figure in the value of the filter and an editing tool. So the word "LIFT" in the first value of the filter sets the black level, and in the second value it shifts the adjacent clip while deleting the selected clip.
In Russian, these words in different contexts have different meanings, is it possible to insert a context separator in these words to get several occurrences of one word?
![_2018-02-21_21-03-36](https://user-images.githubusercontent.com/26217756/36502051-cf71f758-1759-11e8-82ac-2673098aebce.png)
![_2018-02-21_21-29-26](https://user-images.githubusercontent.com/26217756/36502063-d3fd6492-1759-11e8-8cf1-0dc5d6ebda04.png)

**Comment by jliljebl** [comment]
@smolnp Ok, fixed and pushed the missing translations.

I'm doing a release next week, so to get your new translations in 1.16 release I need "flowblade.po" file send to me or pull request here at Github by 27.2.

I see what you mean with *'word "BOX" can mean both a geometric figure in the value of the filter'* and *'In Russian, these words in different contexts have different meanings,'*, and yes, these should be made possible to have different translations.

I think this can be done, but it will break some existing translations. I'll put a fix for this in early 1.18 release cycle, so there is a greater change of getting  these fixed in other languages too.

**Comment by smolnp** [comment]
I understand you, thanks. Now I translate the latest documentation file "Rendering" https://github.com/smolnp/flowblade/tree/gh-pages/webhelp (In case you want to make a website with support for other languages). Then I want to add the translation to help files https://github.com/smolnp/flowblade/tree/master/flowblade-trunk/Flowblade/res/help. 25.02 I will send you "flowblade.po" by mail.22.02.2018, 15:53, "jliljebl" <notifications@github.com>:@smolnp Ok, fixed and pushed the missing translations.
I'm doing a release next week, so to get your new translations in 1.16 release I need "flowblade.po" file send to me or pull request here at Github by 27.2.
I see what you mean with 'word "BOX" can mean both a geometric figure in the value of the filter' and 'In Russian, these words in different contexts have different meanings,', and yes, these should be made possible to have different translations.
I think this can be done, but it will break some existing translations. I'll put a fix for this in early 1.18 release cycle, so there is a greater change of getting  these fixed in other languages too.

**Comment by smolnp** [comment]
(Proxy Render Info)
![_2018-02-24_17-19-44](https://user-images.githubusercontent.com/26217756/36631346-42a5c1d0-1987-11e8-93a2-503ac44f1a00.png)

**Comment by jliljebl** [comment]
Thanks, pushed a fix.

**Comment by smolnp** [comment]
![2018-02-25 17-50-56](https://user-images.githubusercontent.com/26217756/36643270-1c975412-1a5a-11e8-88c7-d150dc4f75f2.png)

**Comment by jliljebl** [comment]
Fixed and pushed.

**Comment by smolnp** [comment]
Not translated "Blend Mode" into Compositors "Affine Blend" and "Blend".
![2018-03-02 22-06-46](https://user-images.githubusercontent.com/26217756/36918025-8f6be562-1e69-11e8-985e-d9474da6e310.png)

**Comment by jliljebl** [comment]
Fixed on repo.

**Comment by smolnp** [comment]
Rendering Motion Clip
![default](https://user-images.githubusercontent.com/26217756/38215424-7d35b2ea-36d0-11e8-9fb7-a0977052b5a0.png)

**Comment by jliljebl** [comment]
Thanks, fixed and pushed.

**Comment by smolnp** [comment]
![2018-06-13 14-53-31](https://user-images.githubusercontent.com/26217756/41350468-ea19af46-6f1b-11e8-8cd4-eb26bc3fcfbc.png)

**Comment by smolnp** [comment]
![2018-06-13 14-53-55](https://user-images.githubusercontent.com/26217756/41350482-f5f88134-6f1b-11e8-923e-5f533d68c978.png)

**Comment by smolnp** [comment]
![2018-06-13 14-54-32](https://user-images.githubusercontent.com/26217756/41350502-09aaa6b2-6f1c-11e8-8190-362ed563fba3.png)

**Comment by jliljebl** [comment]
Hi, yes, this is still a work-in-progress and there might be some more changes. I want to get maybe 90% strings done when I push to Github.

I'll push to GithHub on first week of July and comment here then too.

**Comment by jliljebl** [comment]
@smolnp sorry for the long delay on translations, but there was so much changes that there was not much point in commenting on this.

The Natron tool is not coming in 2.0 so the issue above is not relevant yet. 

The strings are now frozen for next release. If you wish to get translations in next release (2.0) I can get them in if I get them latest Monday 12.11, after that the release is probably coming shortly. I'll  be testing and updating docs until then.

**Comment by smolnp** [comment]
Got it. The translation lines will be ready and sent to you. 10.11

**Comment by jliljebl** [comment]
@smolnp I don't see the screenshot here, maybe it somehow didn't get attached.

**Comment by smolnp** [comment]
I beg your pardon
![_2018-11-06_17-56-14](https://user-images.githubusercontent.com/26217756/48076366-18dad880-e1f6-11e8-9bef-ceeeba37942f.png)

**Comment by jliljebl** [comment]
It is the number of panels on the top half of the application.

"3 panels if width available"
![screenshot from 2018-11-06 18-07-37](https://user-images.githubusercontent.com/1823444/48077010-17f27880-e1ef-11e8-888b-5d489e932a6b.png)
"2 panels always"
![screenshot from 2018-11-06 18-08-17](https://user-images.githubusercontent.com/1823444/48077011-17f27880-e1ef-11e8-99d1-f37070cb45d0.png)

**Comment by smolnp** [comment]
Thank. I probably have the width is not available, so I do not see the changes on my PC

**Comment by jliljebl** [comment]
Good that this came up, I read the code and it seems that made it require 1980 x 1080 for 3 panel to work, which is way too much.

I pushed patch that made 1680 x 1050 work too, I'll test and look to drop down more.

**Comment by jliljebl** [comment]
Smallest I got working was SCREEN_WIDTH > 1440 and SCREEN_HEIGHT > 898  so 1600 x 1024 and 1600 x 900 work now too.

**Comment by jliljebl** [comment]
@smolnp I changed and pushed "3 panels if width awailable" -> "3 panels if width (1450px+) available" so that people understand why it does not change anything on their system, and also typo "awailable" ->  "available" .

**Comment by jliljebl** [comment]
I'm still fixing bugs for 2.0, now so if translations come before 19th I can now guarantee that they get in, it has taken longer to get this to releasable state.

**Comment by smolnp** [comment]
Thanks I got it. And do not tell me why we need the following items (I do not know how to translate them correctly)?

**Comment by jliljebl** [comment]
> why we need the following items
 
The message doesn't have items or an attachment, maybe something was left out?

**Comment by smolnp** [comment]
Again I apologize, I replied from the mail and the screenshots I put in the mailbox.
![_2018-11-12_18-28-41](https://user-images.githubusercontent.com/26217756/48361413-808b9a80-e6b2-11e8-9b32-b125c6065ea6.png)
![_2018-11-12_18-34-53](https://user-images.githubusercontent.com/26217756/48361421-82555e00-e6b2-11e8-8984-b1f9ab6fb4dd.png)

**Comment by jliljebl** [comment]
If user scrolls timeline horizontally with (CTRL +) Mouse Scroll, then scrolling up can move timeline either forward or backward as per this preference (opposite for scrolling down). Some users didn't like the direction Flowblade had by default, so now it is user settable.

Keyframes *in clips* are set in relation to clips *media*, not in relation to clip start. If user changes clips start/end then there can be keyframes out side of clip area and those are NOT auto deleted, they continue to exist.

Leading keyframes = keyframes  that exist before first frame of clip, There is a keyframe almost always 
 at frame 0. If user sets keyframes at frames 10 and 20 and then moves clip start position into media frame 30, then there are 3 "Leading keyframes" at frames 0, 10, 20.

Trailing keyframes = keyframes after clips end, if clip ends at media frame 50 and there are keyframes at 60 and 70, then there are 2 Trailing Keyframes

"Playhead Follows ..." if this is ON playhead stays with the frame that the dragged keframe is in, if OFF playhead stays where it  was.

**Comment by smolnp** [comment]
![1](https://user-images.githubusercontent.com/26217756/48917342-5054b080-ee97-11e8-918f-9bda034da06e.png)

**Comment by jliljebl** [comment]
Thanks, updated and pushed. I'm still taking updates at least until next Wednesday, haven't gotten the last fixes in yet.

**Comment by smolnp** [comment]
![_2018-11-23_22-40-15](https://user-images.githubusercontent.com/26217756/48958576-0cce7500-ef71-11e8-98b2-c42ce8ac02a2.png)

**Comment by jliljebl** [comment]
Added the "Translate" filter name to translation strings.

**Comment by smolnp** [comment]
![_2018-12-12_09-13-09](https://user-images.githubusercontent.com/26217756/50022757-4897b000-ffee-11e8-81d2-83f6bb2c093d.png)

**Comment by jliljebl** [comment]
Fixed and pushed.

**Comment by smolnp** [comment]
![_2019-01-05_20-16-08](https://user-images.githubusercontent.com/26217756/50727116-2f82aa80-1127-11e9-8d46-ad83cc9faffd.png)

**Comment by jliljebl** [comment]
I'm pushing this fix post 2.0, we're now in full string freeze only bug fixes go in now. Release coming hopefully next week.

**Comment by jliljebl** [comment]
I fixed the last 2 items and opened a new sticky thread #601 as this is quite long already, continue reporting issues there.
