### ISSUE TITLE
pygobject 3.27.1 breaks Flowblade 

### ISSUE THREAD

**Issue by sergiomb2** [jliljebl/flowblade#476]
Please include the following information.
1) Flowblade version (Help->About):
1.14
2) MLT version (Help->Runtime Environment):
mlt 6.0.0 com SDL2

3) Your distribution (Ubuntu, Debian, Mint etc.):
Fedora 28 pre-alfa 

starting Flowblade a lot of deprecation warning are displayed about pygobjet  and program crash with a core dump 
[flowble_error.txt](https://github.com/jliljebl/flowblade/files/1700842/flowble_error.txt)

**Comment by jliljebl** [comment]
Is MLT 6.6.0 compiled with SDL 1.2 support, see here: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/SDL_2_AND_MLT_6_6_0.md ?

**Comment by jliljebl** [comment]
I will need to fix the deprecated stuff sometime anyway, even if it is not the cause of the crash as I believe.

**Comment by sergiomb2** [comment]
OK ! after compile mlt with SDL 1 and SDL2 , flowblade starts and don't show these warnings .
So closing the issue was not a bug 
Thanks
