### ISSUE TITLE
Does not start, crashes

### ISSUE THREAD

**Issue by mrkaato** [jliljebl/flowblade#477]
1.14-1 and v1.0.r318.ga807cf7-1
both crash immediately upon launch.
Manjaros after the last update has come.
Linux 4.14.16-1

**Comment by jliljebl** [comment]
Since Manjaro is Arch based, this likely duplicate of fixed Issue #445, see the latest comments. @mrkaato  Can you confirm?

**Comment by mrkaato** [comment]
Yes, sorry for the duplicate.

**Comment by jliljebl** [comment]
Closing as duplicate of #445.
