### ISSUE TITLE
Fall when using composers

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#478]
Please include the following information.
1) Flowblade version 1.14
2) MLT version 6.4.1
3) Your distribution Rosa linux r10 xfce
Flowblade is guaranteed to fall when using three composers with the application of key frames when creating a title animation. After opening the saved project and removing the top composer, Flowblade first stops responding to the commands, then closes abnormally.
![_2018-02-10_18-55-00](https://user-images.githubusercontent.com/26217756/36064121-3bed312a-0e97-11e8-918d-0d67e8168c2e.png)
terminal output: ... Autosave started...
Save project autosave_20b4dd70991aec799f3e32f0fe296b5c
[swscaler @ 0x8ed41000] **Warning: data is not aligned! This can lead to a speed loss**
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Flowblade/rendergui.py", line 699, in <lambda>
    self.type_combo.connect('changed', lambda w: render_type_changed_callback())
  File "/usr/lib/python2.7/site-packages/Flowblade/render.py", line 315, in _render_type_changed
    widgets.args_panel.load_selection_button.set_sensitive(False)
AttributeError: RenderArgsPanelSmall instance has no attribute 'load_selection_button'

**Comment by jliljebl** [comment]
Seems very much like bug, will look into this.

**Comment by smolnp** [comment]
Now I'm working on rendering to a file, a little later I can throw off a backup copy of the project. If needed.

**Comment by jliljebl** [comment]
Confirmed and fixed, will be in 1.16.
