### ISSUE TITLE
The location of the filter control drop-down menu

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#479]
The button of the drop-down menu for managing the filters (Save Values, Load Values, Reset Values,  Delete Effect) is overlapped by the scroll slider, creating some inconvenience. What if you move it to the left.
![_2018-02-21_15-38-49](https://user-images.githubusercontent.com/26217756/36488767-5a70536a-1735-11e8-8955-a899e8f9e25b.png)

**Comment by jliljebl** [comment]
I see, needs fixing.

**Comment by jliljebl** [comment]
Fixed, will be in 1.16. I moved them to left as suggested.
