### ISSUE TITLE
Flowblade as linux commands?

### ISSUE THREAD

**Issue by JonasR888** [jliljebl/flowblade#480]
Hello,
we're running on a Jetson TX2 (microcontroller, Ubuntu 16.4, ARM) and we want to trim/cut videos with a pythonscript. Since we have a ARM(?) we're unable to use "ffmpeg" for this, but we got a tip that Flowblade supports arm64, but we don't need a full video-editor with GUI, we just need some commands that we can run where we can feed in for example a videopath, startClipAt, duration.

I'm sure Flowblade in itself(gui) can trim/clip videos, but can this be done somehow by script/program/commands?

Thanks

**Comment by jliljebl** [comment]
Flowblade uses MLT  (https://www.mltframework.org/) Python bindings to do the things you are interested in. Reading files *edit.py* and *mltplayer.py* could help you.

If you can get MLT and its Python bindigs running on arm64 you should be able to do all you here. MLT how ever depends on FFMPEG project, so you will need to get that code running on arm64 too. I do not think MLT has been ported to arm64, so you would need port both MLT to arm64.

Please DO NOT file issues on mlt github project, they do not offer suppor theer, but you can try this   https://sourceforge.net/p/mlt/mailman/mlt-devel/ instead after doing all the googling you can do.

**Comment by dvdlvr** [comment]
Furthermore, take a look at the Renderfarm script by Brillemans Smurf on 
the google plus page of Flowblade 
(https://plus.google.com/u/0/communities/103860400113389238474).
It uses an MLT XML file, typically created with Flowblade, as base for 
the command line.
This XML file could obviously be created by hand as well, but it's 
easier to edit the videos in Flowblade and then generate the XML file 
and use it as input for the script.
The script will give you a lot of info on how to generate the output 
from the command line.
