### ISSUE TITLE
Image sequence : image per source image

### ISSUE THREAD

**Issue by ylaizet** [jliljebl/flowblade#483]
Hi, when I import a image sequence, whatever the value I set for **the number of image per source image**, the ratio seems to always stick to 1/1. Indeed, when I view the result int the clip panel, the animation is very fast (as for a 1/1 ratio) although I set 25 images per source image.
Did I miss something for the image sequence import? Thanks for help

Flowblade 1.14
MLT 6.4.1
Ubuntu 17.10

**Comment by jliljebl** [comment]
Yeah, confirmed. Used to work, not any more it seems.

**Comment by jliljebl** [comment]
Fixed, will be in 1.16.
