### ISSUE TITLE
Make Change Sequence Tracks Count dialog default to current number of tracks on timeline

### ISSUE THREAD

**Issue by eliotb** [jliljebl/flowblade#489]
In Change Sequence Tracks Count,  The initial values of the spinboxes should  be the current number of V/A tracks in the sequence.  Currently it is hardcoded to 5, 4 in dialogs.py.
I'd have a go at a patch for this, but not sure where the counts are stored in the sequence object, and how to pass them to the dialog?

Also
For new project, sequence #V,#A is hardcoded to 5,4
IMO the default project should not have all tracks populated, maybe 4V, 2A or even 2V, 1A to start.  This leaves room for e.g. adding video tracks, without removing audio tracks.
Maybe define constants DEFAULT_[V,A]_TRACKS = ?

An idea for a more obvious gui for adding tracks: If it is possible to add a track, show a [Add track +] in the slot beyond the highest V, A tracks in the timeline.  Clicking on this would still pop up the change dialog with the warnings, with the numbers set as expected,  e.g. #V+1, #A. A very rough picture with two options for where the button would be positioned:
![flowblade-add-track](https://user-images.githubusercontent.com/421383/38841029-70fc3e60-4236-11e8-9f24-85bb39811624.png)

For removal of tracks,  "Remove track" item could be added to the context menu of the highest numbered track,  would open the change dialog with e.g. #V-1, #A

**Comment by jliljebl** [comment]
I gave this quite a bit of thought but decided against doing this.

   * If user is given the option to add /remove tracks one by one it is my view that user would then expect to be able to add as many tracks as they wish
  * Flowblade does not offer vertical scrolling in the timeline and therefore cannot offer arbitrary amount of   tracks to be made available to the user
  * With no vertical scrolling offered the current GUI of selecting a configuration of video and audio tracks in a dialog is logically more in line with that idea then giving "Add/Remove tracks" options 

If we sometime decide to let go of the "no vertical scrolling" idea then we will obviously just do what Premiere/KDEnlive do and let users add tracks one by one, but I really like never having to do vertical scroll when editing, and we will keep this functionality as is.

**Comment by eliotb** [comment]
Leaving aside the gui part, how about my very first point:

> In Change Sequence Tracks Count, The initial values of the spinboxes should be the current number of V/A tracks in the sequence. Currently it is hardcoded to 5, 4 in dialogs.py.  

Currently, if you say have 7 video tracks and 1 audio, and you want to add an audio track, you open this dialog. You have to increment the video count from 5 to 7 to avoid losing two video tracks, and decrement the audio count from 4 to 2 to add one audio track.  This is clunky and error-prone.
What I think should happen is that the counts should start at 7, 1 and you just need to increment audio count to 2.

**Comment by jliljebl** [comment]
Ok, so you mean that if when e.g trying to a Video track the number of tracks would exceed 9, then the number of Audio tracks would automatically be reduced, so that user does not manually have to decrease number of Audio tracks to be able to add video tracks?

**Comment by eliotb** [comment]
No.  I just mean that when I invoke the Change Sequence Tracks Count, the initial values in the dialog should be equal to the current number of V/A tracks the sequence.
Right now, the initial values are always 5/4 

![screenshot from 2018-04-18 22-01-46](https://user-images.githubusercontent.com/421383/38925578-274d11a8-4354-11e8-8de2-e465aab79a9b.png)

Here if I want to add 1 audio track, and keep the 6 video tracks, I have to Increase Video from 5 to 6, and decrease audio from 4 to 2.

**Comment by jliljebl** [comment]
Ok, that would be acceptable. I can take a patch or do myself later before 1.18.

**Comment by eliotb** [comment]
I'd try a patch if you would complete the following lines for me:

current_video_tracks = ???
current_audio_tracks = ???
I looked for a member or method of  PROJECT().c_seq, but it isn't obvious...
Is it just sequence.VIDEO_TRACKS_COUNT etc?  This seems odd to me that this is a global var and not a property of the sequence class

**Comment by jliljebl** [comment]
There is a comment in *sequence.py*:

      TRACKS LAYOUT:
        index                                           track type
        -----                                           ----------
        0                                               black bg track
        1 - (self.first_video_index - 1)                audio tracks    
        self.first_video_index - (len(self.tracks) - 2) video tracks
        (len(self.tracks) - 1)                          hidden track for trimmming
        
        Tracks are never changed after creation, changing tracks count feature is
        achieved by creating a new sequence.
        """
So we get:

current_video_tracks = len(editorstate.current_sequence().tracks) -  editorstate.current_sequence().first_video_index - 1
current_audio_tracks =  editorstate.current_sequence().first_video_index - 1

**Comment by jliljebl** [comment]
Pull request did this, will be in 1.18.
