### ISSUE TITLE
Choosing Movement => Freeze filter with too low a frame number crashes Flowblade

### ISSUE THREAD

**Issue by cefn** [jliljebl/flowblade#498]
Please include the following information.
1) Flowblade version (Help->About): 1.16.0
2) MLT version (Help->Runtime Environment): 6.4.1
3) Your distribution (Ubuntu, Debian, Mint etc.): Lubuntu 17.10

I have a Logo sting which animates from one logo configuration to another. I wanted to extend the 'still' at the beginning and at the end.

So far, Flowblade has crashed spectacularly through every attempt I have made to achieve this, using still PNG images, or Freezing a video, across four versions of Flowblade (Ubuntu distribution 1.12-1, .deb 1.16.0, flatpak and Github) and two versions of MLT (Ubuntu distribution 6.4.1, Kdenlive 6.6.0).

On this occasion I chose 'Freeze' using a copy of the sting media 'frozen' to the final frame as a following clip, and then trying to add a copy of the same sting media as a preceding clip, but frozen to its starting frame. Then I can fade into and out of the stills before the animation.

Unfortunately, attempting to set the Freeze frame of the preceding sting to any number lower than about 16 frames in causes a fatal crash of Flowblade, possibly linked to these messages from the console...

```
    audio decoding error -1094995529
[mp2 @ 0x7f28b0645400] Header missing
[producer avformat] /home/cefn/Documents/shrimping/vgkits/git/vanguard/vector/logo/sting/logo_sting_x6.mpg
    audio decoding error -1094995529
[mp2 @ 0x7f28b0645400] Header missing
[producer avformat] /home/cefn/Documents/shrimping/vgkits/git/vanguard/vector/logo/sting/logo_sting_x6.mpg
    audio decoding error -1094995529
[mp2 @ 0x7f28b0645400] Header missing
[producer avformat] /home/cefn/Documents/shrimping/vgkits/git/vanguard/vector/logo/sting/logo_sting_x6.mpg
    audio decoding error -1094995529
[mp2 @ 0x7f28b0645400] Header missing
[producer avformat] /home/cefn/Documents/shrimping/vgkits/git/vanguard/vector/logo/sting/logo_sting_x6.mpg
    audio decoding error -1094995529
[mp2 @ 0x7f28b0645400] Header missing
[producer avformat] /home/cefn/Documents/shrimping/vgkits/git/vanguard/vector/logo/sting/logo_sting_x6.mpg
    audio decoding error -1094995529
*** Error in `python': free(): invalid next size (fast): 0x00007f28b0b2d560 ***
Aborted (core dumped)
```

**Comment by jliljebl** [comment]
Will investigate, my first couple of tests did not reproduce this.

**Comment by cefn** [comment]
I have uploaded the sting .mpg to http://vgkits.org/tmp/logo/ in case the format matters. It succeeded in creating the Freeze when I selected it to freeze to the last frame, but trying to set/slider the frame to an earlier value caused a failure.

**Comment by cefn** [comment]
I have been unable to recreate the crash within Flowblade created using the flatpak build against https://github.com/jliljebl/flowblade/commit/6e06bb65c3f0e12a0b371d4a08d405c299ceeb7f, so I will close, but Freeze has unusual behaviour I will file separately.
