### ISSUE TITLE
Preference for Mouse horizontal scroll direction

### ISSUE THREAD

**Issue by ericfont** [jliljebl/flowblade#499]
The horizontal scroll direction is opposite what I am used to in other programs.  In kdenlive, scroll wheel down will advance the timeline, while flowblade does the opposite.  Please allow this direction to be set in preferences so users can navigate as they are accustomed. 

my info:
1) Flowblade version 1.16.0
2) MLT version 6.6.0
3) Arch Linux

**Comment by jliljebl** [comment]
This can be done and is a useful preference for users who prefer this, so I'm adding it in feature queue.

**Comment by Efenstor** [comment]
I second that.

**Comment by jliljebl** [comment]
Fixed in repo, will be in next release.
