### ISSUE TITLE
Not an issue, just a question about restart

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#500]
Hi Janne,

I'm working on something that requires a restart after some preferences are updated (Subtitle support).
Currently it only shows a message and the user has to manually restart.

Is there an objection to adding a button to 'Restart now' on the preferences_window._preferences_dialog_callback ?
The user would then have the option to either restart right away (with the option to save the current project too) or to continue without restarting.

Regards,
Steven.

**Comment by jliljebl** [comment]
Hi Steven,

If you can make this work (mostly) reliably, sure this can be done. 

The problematic bit is that starting apps is a bit distro/environment specific issue on Linux so there could be some problems with this down the line, but this could be made to work in most cases I think.

In an another Issue I needed to ask one user to start app with:

```bash
 env GDK_BACKEND=x11 GDK_SCALE=1 flowblade %f
```

to prevent unwanted GDK_SCALE=2 which caused the application to not start at all, so there are complications here.

**Comment by dvdlvr** [comment]
Ok, thanks.
On my system the restart works fine. I'll try and see if I can extract / recreate the extra settings, if needed.
I'll do some extensive testing.

**Comment by eszlari** [comment]
I encounter no problems at all when I run flowblade (flatpak version) with GDK_SCALE=2.

**Comment by dvdlvr** [comment]
I tested. The method that I've got retains the environment setting, so we should be ok.
