### ISSUE TITLE
Sequence timeline cursor - add "follow" option

### ISSUE THREAD

**Issue by m-dp** [jliljebl/flowblade#503]
The cursor on the timelines can leave the visible range. 
It would be useful to have an option for the visible range to follow the cursor: as the cursor is moved automatically through playing the sequence, or as the cursor is moved manually through the arrow keys (etc.), the visible range should be moved so that (for example) the cursor disappearing on the right at 00:01:23:15 reappears on the left at 00:01:23:16. 

(Flowblade 1.16.0; MLT 6.0.0; XUbuntu 16.04 LTS)

**Comment by m-dp** [comment]
Incidentally: I thought that issue #303 was very similar (I prefer a static range with a moving cursor, while oluja1973 wrote about a moving range with a static cursor - in his words, «It would be fine that the cursor is centred in the project middle when jumping with the keys»), and the feature is marked as implemented, so I may be missing something.

**Comment by jliljebl** [comment]
#303  is indeed similar but that centers after Up/Down keys, you want different displayed ranges after cursor leaves timeline.

Sure, this should be easy enough to do and might look nice and provide more information to the user, so we can do this.,

**Comment by jliljebl** [comment]
Feature in repo, will be in 1.18.  Made it default too, most users will probably prefer this.
