### ISSUE TITLE
Render Args with parameter containing '='

### ISSUE THREAD

**Issue by m-dp** [jliljebl/flowblade#504]
The rendering arguments are "key=value" pairs, and I trust they are `ffmpeg` parameters. 
But some `ffmpeg` parameters may contain the '=' character. Examples are: 
`-filter:v "crop=640:480:123:234"`
`-metadata title="my title"`
Such parameters (e.g. `filter:v="crop=640:480:123:234"`, `metadata='title="my title"'`) raise an error. 
The ability to use the full range of the possible parameters would add flexibility, useful in some cases (e.g. it was one of the workarounds I tried for #501 - working on a 16:9 that should eventually had been rendered cropped to a 4:3). 

(Flowblade 1.16.0; MLT 6.0.0; XUbuntu 16.04 LTS)

**Comment by jliljebl** [comment]
Ok, I agree that this would be useful. I'm however taking a bit stricter approach on focusing more on stuff I find important.

I changed "patches can be accepted" label to "contributions hoped" to communicate a more positive vibe on these kind of Issues. I agree that they would be enhancements, but I am not probably going to let myself be distracted from project objects I think are more important.

**Comment by dvdlvr** [comment]
As far as I know, these parameters are MLT Framework parameters, not ffmpeg parameters.
They are being passed to the MLT output rendering process.
Some ffmpeg parameters have been implemented in MLT, but not all. I couldn't find the metadata and filter arguments, for instance.

You can find a list of the implementation in the MLT doc:
https://www.mltframework.org/plugins/ConsumerAvformat/

**Comment by jliljebl** [comment]
This is now fixed, will be in 2.10.
