### ISSUE TITLE
Comply with XDG Base Directory Specification

### ISSUE THREAD

**Issue by eszlari** [jliljebl/flowblade#514]
At the moment flowblade stores all of it's user configuration and data under `$HOME/.flowblade`.

It would be nice if it could be made compliant to the XDG Base Directory Specification:
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

In practice this would mean, three environment variables are used to specify the location of user data:
`$XDG_CONFIG_HOME` - usually `$HOME/.config`
`$XDG_DATA_HOME` - usually `$HOME/.data`
`$XDG_CACHE_HOME` - usually `$HOME/.cache`

For example `$HOME/.flowblade/prefs` would then be stored in `$HOME/.config/flowblade/prefs` when using a distribution supplied version of flowblade and stored in `$HOME/.var/app/io.github.jliljebl.Flowblade/config/flowblade/prefs` for the flatpak version.

Edit: I just noticed https://github.com/jliljebl/flowblade/issues/161, so if you don't want to implement this (although it would be useful), of course just close this issue.

**Comment by jliljebl** [comment]
Well, no that Flatpak is more of thing I can reconsider. I need to look at this, but basically I'm not opposed anymore.

**Comment by jliljebl** [comment]
The three env variables are not present in my system $XDG_CONFIG_HOME, $XDG_DATA_HOME, $XDG_CACHE_HOME all give *None*. I installed *python-xdg* but that had no effect.

@eszlari Maybe I can hard code something like this.

If started with no flag affecting this the files would be where they have always been. 

If started with flag "-xdg" I would store stuff in:
$HOME/.config
$HOME/.data
$HOME/.cache

If started with flag "-flatpak" I would store stuff in:
$HOME/.var/app/io.github.jliljebl.Flowblade/config/flowblade
$HOME/.var/app/io.github.jliljebl.Flowblade/data/flowblade
$HOME/.var/app/io.github.jliljebl.Flowblade/cache/flowblade

I'll try this for 2.2, 2.0 is kind of feature complete and this could cause bugs.

**Comment by eszlari** [comment]
https://askubuntu.com/questions/457047/how-can-i-get-the-xdg-default-user-directories-from-python

**Comment by eszlari** [comment]
```
If started with flag "-xdg" I would store stuff in:
$HOME/.config
$HOME/.data
$HOME/.cache

If started with flag "-flatpak" I would store stuff in:
$HOME/.var/app/io.github.jliljebl.Flowblade/config/flowblade
$HOME/.var/app/io.github.jliljebl.Flowblade/data/flowblade
$HOME/.var/app/io.github.jliljebl.Flowblade/cache/flowblade
```

This wouldn't improve the situation much. The whole point of using these XDG environment variables is to make the location of these files user configurable.

**Comment by jliljebl** [comment]
Ok, I copied from pitivi https://gitlab.gnome.org/GNOME/pitivi/blob/master/pitivi/settings.py and got values:

/home/janne/.config/flowblade
/home/janne/.local/share/flowbl
/home/janne/.cache/flowblade

for 

os.path.join(GLib.get_user_config_dir(), "flowblade")
os.path.join(GLib.get_user_data_dir(), "flowblade")
os.path.join(GLib.get_user_cache_dir(), "flowblade")

which they say are xdg locations, I can do this with this.

**Comment by jliljebl** [comment]
Ok, this is in and tested, will be in 2.2. Let's hope all eventualities were accounted for.

We will force convert everyone to use this, it really is not logical to allow user choice in this matter if we are seeking to comply with the spec and also trying to keep code base workable.
