### ISSUE TITLE
-gtk-outline-radius is not a valid property name

### ISSUE THREAD

**Issue by Bene81** [jliljebl/flowblade#518]
When starting flowblad I from master I get the following stack trace:

FLOWBLADE MOVIE EDITOR 1.16
---------------------------
Launch script dir: /home/bene/Entwicklung/Projekte/flowblade/flowblade-trunk
Running from filesystem...
MLT found, version: 6.0.0
numpy version: 1.11.0
OS: Linux Mint 18.2
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
GTK+ version: 3.18.9
User dir: /home/bene/.flowblade/
Locale: de_DE
Found translations at /home/bene/Entwicklung/Projekte/flowblade/flowblade-trunk/Flowblade/locale/, using those.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Loading shortcuts: Flowblade
Traceback (most recent call last):
  File "flowblade-trunk/flowblade", line 78, in <module>
    app.main(modules_path)
  File "/home/bene/Entwicklung/Projekte/flowblade/flowblade-trunk/Flowblade/app.py", line 225, in main
    gui.apply_gtk_css()
  File "/home/bene/Entwicklung/Projekte/flowblade/flowblade-trunk/Flowblade/gui.py", line 242, in apply_gtk_css
    provider.load_from_path(respaths.ROOT_PATH + "/res/css/gtk-dark-fix.css")
GLib.Error: gtk-css-provider-error-quark: gtk-dark-fix.css:15:21'-gtk-outline-radius' is not a valid property name (3)

--------------------------

Tracing the logs and checking out each commit it seems to have been introduced with commit 8cb53d93da3734ad72bfc2456ec1f7e32d13e6b8 .
Maybe is there a commit related to this 'Theme work' missing?

**Comment by jliljebl** [comment]
This is the new hand crafted Gtk theme CSS which only works with Gtk 3.22. 

Gtk devs notoriously kept changing the CSS throughout the 3.x series and I'm only providing the CSS for 3.22 as that is the last one and is going to be stable for many years to come. 

Doing backports to earlier Gtk versions is not something I do not want to do as I would need to set up dev system on earlier Gtk versions and acquire knowledge on the exact differences between versions.

 I re-enabled the theme selection functionality and will push patch that only makes the new CSS available for Gtk 3.22. Select "Dark Theme" or "Light Theme" from "Preferences-> View" for now.

**Comment by jliljebl** [comment]
Ok, I pushed a patch that disables Flowblade theme for non 3.22 Gtk.
