### ISSUE TITLE
It is the inquiry of how to use the character flowing.

### ISSUE THREAD

**Issue by iyagicom** [jliljebl/flowblade#524]
Please include the following information.
1) Flowblade version (Help->About): 1.16
2) MLT version (Help->Runtime Environment): 6.6.0
3) Your distribution (Ubuntu, Debian, Mint etc.): ubuntu 18.04

I am writing a lot of writing from bottom to top,
or,
Top to bottom
or,
I want to make a character flowing from right to left.

The top text disappears and a new text appears at the bottom.

How can I do it?

**Comment by jliljebl** [comment]
Flowblade does not support right to left text. If we get contribution for that, then we can have it.

**Comment by iyagicom** [comment]
Does not the new 2.0 support flowing text?
If you do not have animated character support, I do not need to use this program.
