### ISSUE TITLE
Some new Keyboard shortcuts

### ISSUE THREAD

**Issue by jliljebl** [jliljebl/flowblade#525]
**'C' for zoom to center sequence end on timeline**
1. User presses some shortcut key like 'C'
2.Timeline is zoomed so that sequence ends at center of timeline area.
3. Playhead is automatically also moved to end of sequence which is now at the center of timeline area.

**'A' for append media item to V1 with auto select next item**
1. User presses 'A'
2. The currently selected Media Item in Media Panel (and not the clip loaded in monitor) is appended to track V1 whether or not track V1 is active or not.
3. In case multiple items are selected, the one selected last is appended
4. After append, next Media Item is selected automatically

**Comment by jliljebl** [comment]
Hmm, maybe/maybe not but this does not need an issue here.

**Comment by jliljebl** [comment]
This got done with ALT + A doing what is suggested here.

**Comment by PanderMusubi** [comment]
Can the available keyboard shortcuts also be listed in the menus? For example + and - for zoom in and out. Or is a new issue needed for this?

**Comment by jliljebl** [comment]
Please open new issue, this one already has unrelated content and using this will just make things harder to follow.
