### ISSUE TITLE
preserve render settings between launches

### ISSUE THREAD

**Issue by miniskipper** [jliljebl/flowblade#529]
It would be nice if all properties of the render-panel would be preserved between program launches:
- Render In-Out-Marking (the state of the render range dropdown is already saved!)
- checkbox "render using args" + the render args themselves
- checkbox "Use Project Profile"

Maybe they could be saved in the .flb Project file?

Flowblade version: 1.16 from AUR
MLT version: 6.10 with patch reverting 7bf5da8
Distribution: Arch Linux

**Comment by jliljebl** [comment]
Sure, we have been expanding these per requests, so we can add these too.

**Comment by jliljebl** [comment]
Will be in 2.2.
