### ISSUE TITLE
lossless mpeg2 render broken

### ISSUE THREAD

**Issue by oberon-manjaro** [jliljebl/flowblade#532]
Please include the following information.
1) Flowblade version (Help->About): 1.16.0
2) MLT version (Help->Runtime Environment): 6.10.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Manjaro

When I select 'lossless mpeg2' as format, the resluting file has a whitespace between the dot and the extention and is only a black image and one half screen image after a while with a supposed clip length way too long.

**Comment by jliljebl** [comment]
Confirmed, something has gone wrong here.

**Comment by jliljebl** [comment]
I could not get it to work and decided to remove lossless mpeg2 rendering, it is outdated anyway.
