### ISSUE TITLE
Suggestion: Add donations

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#535]
Please give a way for the users to donate for the product development! You can make a project on [Patreon](https://www.patreon.com/), besides the standard PayPal button for one-time donations. Please promote donation subscriptions. As an example, [Ardour](https://community.ardour.org/community) developers manage to receive about $10,000 every month from donations so they are able to work on their product full-time. There's also an [interview](https://artmusictech.libsyn.com/podcast-214-paul-davis-ardour) with its head developer Paul Davis where he discusses the matters of donation financing. I think there's still no really good (I mean really fast, precise, stable, feature-full and convenient) open-source video editor out there because no one has yet been able to put enough effort into it, and such efforts should absolutely be rewarded.

**Comment by jliljebl** [comment]
This has been a task on my private todo list forever, but I have not been interested in pursuing it so far, basically I has been my view that the money received will not be enough to justify the effort. The one time campaigns by OpenShot, Pitivi and that one third thing were all disappointments and have probably shut down that road, but the PayPal button could produce some revenue.

Thanks for the link. I'll close this for now as I'm not doing anything here in the next few months but I will post a longer comment here later in the autumn to clarify my views on this subject, as this is as good place as any to write down my views on this matter.  But it would take much more time then I'm willing to spend right now.

**Comment by openmindculture** [comment]
Hi @jliljebl I just wanted to encourage people to donate for free and open-source software they use regularly, in a blog post where I will also mention Flowblade, only to find out that there is no donation option, and I can't even sponsor you on GitHub? If you don't care about the money, you could pass it on to a charitable cause. If you ever manage to set up a donation option please let me know!
