### ISSUE TITLE
Issue: Keyframes outside the clip range are not deleted

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#536]
Please include the following information.
1) Flowblade version (Help->About): 1.16.0
2) MLT version (Help->Runtime Environment): 6.8.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Debian Stretch

I have put an audio clip into the timeline, put in the volume effect, added a keyframe to create a short fade in,  then I've decided that the clip should begin a bit later, so I have dragged its in point. Now I can still see the first keyframe marker located outside the clip range. If I move the in point further, it's still there although now behind the edge of the window.

I guess all keyframes that happen to be outside the new clip range should be deleted, but before doing that a new keyframe should be created at the new in/out point with the current value at that point. That would be logical to expect.

**Comment by jliljebl** [comment]
I see your point. I will need to think about this,I need to decide if your suggested approach best or are there some other approaches.

**Comment by jliljebl** [comment]
Looking at this the first thing to consider is how MLT handles case where some frame X is displayed but first keyframe is at e.g X + 10. It might work but I'm not going to approach problem with unfounded trust that my upstream for some lucky reason does what I would like it to do.

So I'm really do not want to drop always having a keyframe at frame 0. MLT might swallow it, but I'm not going to find out, this can and should handled application side.

Auto adding and deleting keyframes when clip lengths are changed on the other hand does things behind users back and would require updating all keyframes on all clips after all edits. 

This is difficult to do in such a way that it is guaranteed to NOT change output. 

We already add keyframes on clip starts on editor open and that could actually change out put in certain cases, but this could be made optional.

This still needs further thinking but I agree that we need some improvement here. Possible approaches:
  * confirurable keyframe auto creation/delete with user preferences on when and this is how it is done
  * more info and control on Keyframe editor, maybe displaying keyframes out side of clip frame explicitly, and providing menu actions to editdit them and their values, something like this
![kfeditor_2](https://user-images.githubusercontent.com/1823444/45505399-36ab3480-b795-11e8-821b-e98d24db45b8.png)

**Comment by jliljebl** [comment]
This has a new feature in repo now, works as follows.

* frame 0  always has keyframes
* no auto deletes are done, these would be invisible side effects of edits to user and with option to turn sliders into keyframe editors in next release we always need kf at frame 0, so this does not really seem appropriate.
* if keyframes exist outside clip range keyframe icons and number of keyframes are displayed before or after clip editor range as shown above
* clicking icon shows popup menu with options: *Delete all but first Keyframe before Clip Range*, *Set Keyframe at Frame 0 to value of next Keyframe* for keyframes before clip range and option *Delete all Keyframes after Clip Range* for keyframes after clip range
