### ISSUE TITLE
Suggestion: Frame by frame moving of keyframes

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#539]
Flowblade version (Help->About): 1.16.0
MLT version (Help->Runtime Environment): 6.8.0
Your distribution (Ubuntu, Debian, Mint etc.): Debian Stretch

It would be great if the <| and |> buttons below the keyframe line would move the currently selected keyframe frame by frame instead of moving the timeline cursor: there are already buttons for that in the monitor bar. I would really appreciate a way of precise moving of existing keyframes.

**Comment by jliljebl** [comment]
The use case of moving keyframes one frame at a time with keyboard is definitely a good idea. We just need to figure out the implementation, I'm not sure that I want to drop the local buttons for moving playhead, but there are many options that can be considered to get this done.

**Comment by jliljebl** [comment]
Added new buttons into keyframe editors that move active keyframes one frame +/-. Will be in next release.
