### ISSUE TITLE
Minor issue: Keyframed control value is not always updated

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#540]
Flowblade version (Help->About): 1.16.0
MLT version (Help->Runtime Environment): 6.8.0
Your distribution (Ubuntu, Debian, Mint etc.): Debian Stretch

The keyframed control value is not updated when moving the main timeline cursor, it is updated only when moving the red cursor in the keyframe line and only when releasing the mouse button. In general this behaviour is quite confusing.

**Comment by jliljebl** [comment]
I agree on this, we'll change the behavior.

**Comment by jliljebl** [comment]
Keyframed values in filters now update on mouse release on timeline, too. I didn't want to make them update on every mouse moved event, this was historically crashy on some filters.

**Comment by jliljebl** [comment]
Filter editors now update with all mouse movements too and work the same way as Compositor keyframe editors. Hopefully this does not decrease application stability, it should not, but will test and revert if necessary.
