### ISSUE TITLE
Issue: The Slip tool should not move the timeline cursor

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#542]
Flowblade version (Help->About): 1.16.0
MLT version (Help->Runtime Environment): 6.8.0
Your distribution (Ubuntu, Debian, Mint etc.): Debian Stretch

I am trying to sync a specific soundtrack position to some event in the clip. For that I need to move in and out points simultaneously: that's what the Slip tool is for, I suppose. But when I place the cursor to the needed position and try to drag the clip contents, the cursor instantly jumps to the end of the clip. I want to see how the current frame changes when I am "slipping" a clip, but here even turning off the Trim view doesn't help.

Just to choose the best moment to be synchronized with some specific moment in the soundtrack (I am making a music video) or to choose the best cut point, it is quite impossible to see the overall effect beforehand, when previewing the footage, so it is always the trial-and-error process which requires making a great lot of small adjustments so even a small hindrance is always a big problem.

**Comment by jliljebl** [comment]
Ok, I get your use case. This could be made user configurable. This might be a bit more involved when I would like or could it be easy, haven't looked at the code in a long time, but we'll see if we can get this for next release.

**Comment by jliljebl** [comment]
Oh, now I remember.  To get it working as is it was needed to do some complex calculations...

```python
def _update_slide_trim_for_mouse_frame(frame):
    global edit_data
    clip = edit_data["clip"]
    mouse_delta = edit_data["press_start"] - frame

    # make sure slided clip area stays inside available media
    # fix_diff, herp, derp ... jeessus
    fix_diff_in = _legalize_slide(clip.clip_in + mouse_delta, clip)
    fix_diff_out = _legalize_slide(clip.clip_out + mouse_delta, clip)

    if fix_diff_in == 0 and fix_diff_out != 0:
        fix_diff = fix_diff_out
    elif  fix_diff_in != 0 and fix_diff_out == 0:
        fix_diff = fix_diff_in
    elif  fix_diff_in != 0 and fix_diff_out != 0:
        if abs(fix_diff_in) > abs(fix_diff_out):
            fix_diff = fix_diff_in
        else:
            fix_diff = fix_diff_out
    else:
        fix_diff = 0

    edit_data["mouse_delta"] = mouse_delta - fix_diff
    
    # Get display frame on hidden track
    if edit_data["start_frame_being_viewed"]:
        display_frame = clip.clip_in + mouse_delta - fix_diff
    else:
        display_frame = clip.clip_out + mouse_delta - fix_diff

    return display_frame
```

...and move the playhead in *opposite direction* of mouse movement to create an illusion of playhead staying in place and displaying frame it currently hits. All this relies heavily on fake playhead remaining on clip area. This feature would be major under taking and this is going *wonfix*.

Playhead jumps to start or end of clip depending on which is closer to mouse press point. I think you can work around this issue by having a cut at (audio) position you want to sync to and then drag clip ends after the syncing slip edit is done.
