### ISSUE TITLE
Adding Color Clip causes problems

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#546]
Please include the following information.
1) Flowblade version (Help->About): 1.16.0
2) MLT version (Help->Runtime Environment): 6.6.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.04.1 LTS

Hi,
When adding a (black) color clip to V1 (With clips in V2) the display is messed up. The color clip doesn't show on the V1 as usual - it 'may' say 'COLOR CLIP' in text, but the clip isn't there. After a few more tries it just hung Flowblade and I had to force close it. 
Tried it a number of times closing Flowblade and opening it again and it is reproducable on my system.

[flowblade.txt](https://github.com/jliljebl/flowblade/files/2345962/flowblade.txt)

When I first saw the problem of a bad color clip I saved the project. Now, when I open the project I don't see my edits in V2 and I don't see the color clip in V1. There are more error messages on the command line after I open the saved project.

[flowblade-project-load.txt](https://github.com/jliljebl/flowblade/files/2345987/flowblade-project-load.txt)

PS: I just tried to do the same simple thing is Flowblade 1.14. I used this all the time, but now adding a color clip also causes problems. Maybe some sort of shared library that was updated that's causing this?
The default time for the color clip is 250 frames (10 minutes) but when it shows up on the timeline it goes on for days!!! I couldn't see the end of it.

**Comment by dvdlvr** [comment]
Update:
The problem happens when:
1) Dragging the color clip from the bin to the timeline
2) Adding the color clip to the clip monitor, deleting the default mark-in/out and hitting the 'add to timeline' button. With video clips this will insert the entire clip to the timeline. It seems there is a problem with the default start/end tags of color clips.

The problem doesn't happen when:
Adding the color clip to the clip monitor. Setting a mark in/out. Hitting the 'add to timeline' button. You can then edit the clip length on the timeline and copy/paste that color clip on the timeline without problem, but you still cannot drag the one from the bin to the timeline.

Another problem seems to be that you cannot set the mark-out on the color clip in the clip monitor beyond 1 frame.
The default mark-in/out is also the length of 1 frame only, yet it inserts 150 frames of the color clip. It seems like the default mark-out is being used but the mark-in isn't.
See screenshot of default in/out marks for color clip.
![screenshot_20180903_175619](https://user-images.githubusercontent.com/7942463/44995295-b9b4d980-afa2-11e8-8f5d-a0584b6a9100.png)

**Comment by jliljebl** [comment]
Ok, tried all of these and is does not reproduce. I'm also not getting the warning print outs:

[mpeg2video @ 0x7f29b00050a0] Invalid frame dimensions 0x0.
(Repeating messages deleted)
[mpegts @ 0x7f29b00099c0] PES packet size mismatch
(Repeating messages deleted)

I believe this is somehow related to your system, you don't e.g. seem to have frei0r or lapdspa installed so the environment is not what it would be if you if you installed Flowblade from latest .deb. You can get .deb package in here: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md and maybe see if that version will work.

I'm closing this as *unreproduced*, will reopen if we get some data that aupport idea that there is something wrong with Flowblade/MLT that should be fixed.
