### ISSUE TITLE
Flowblade audio fade : how ?

### ISSUE THREAD

**Issue by tissatussa** [jliljebl/flowblade#547]
Can anyone explain how to do audio fade? I read this should be done with volume, a "keyframeable filter", but how does that work ?
Flowblade 1.12.0 * MLT version 6.6.0 * Ubuntu 18.04

**Comment by smolnp** [comment]
https://www.youtube.com/watch?v=FClxqpJkepY

**Comment by jliljebl** [comment]
This is not fixable Issue and we have a helpful link so I'm closing this.

**Comment by tissatussa** [comment]
thanks ! Although this is a Russian (!?) version, i think i understand .. i also found "Flowblade vs. Kdenlive - Good Linux Video Editors", see https://www.youtube.com/watch?v=BK1LGv0HGI8 .. this man alsostruggles with the functions in Flowblade .. you really should set up a good tutorial to learn users how to use all your functions, filters, keyframes, etc .. most is not clear and documentation lacks, as well as examples .. i really think this would boost your GOOD editor !

**Comment by smolnp** [comment]
Yes, I've seen this video before. I have (in Russian) my own channel https://www.youtube.com/channel/UCVBxWbJtEXxCEY25MIcq5aQ?view_as=subscriber and page vkontakte https://vk.com/flowblade, where in my spare time I upload video and text lessons on Flowblade.21.09.2018, 01:42, "Roelof Berkepeis" <notifications@github.com>:thanks ! Although this is a Russian (!?) version, i think i understand .. i also found "Flowblade vs. Kdenlive - Good Linux Video Editors", see https://www.youtube.com/watch?v=BK1LGv0HGI8 .. this man alsostruggles with the functions in Flowblade .. you really should set up a good tutorial to learn users how to use all your functions, filters, keyframes, etc .. most is not clear and documentation lacks, as well as examples .. i really think this would boost your GOOD editor !

**Comment by petrelharp** [comment]
For other people ending up here: right-click the audio track; select Edit > Volume Keyframes, then create the volume profile. Here's a fade-out:
![Screenshot from 2021-02-10 18-51-35](https://user-images.githubusercontent.com/1046249/107597920-0b7cd780-6bd1-11eb-9e6c-3dd017a7a07b.png)
