### ISSUE TITLE
Most of filters don't have any effect

### ISSUE THREAD

**Issue by goldanorak** [jliljebl/flowblade#550]
Hello ! When i try to apply a filter on a clip, often no effect is shown, and the filter settings don't have any effect. Sometimes as i move the cursor left to right, on the screen i see the image switch between two different states, but not gradually. The states can be : un-modified / modified but without any access to variations / black image / full grey image ... And in rare cases, some filters are working (apparently) correctly ; for example "color grading" or "curves". It's not about "alpha filters" ( i understood they have a specific operating ). And i already verified the "all filters on" option. Thanks for any help ! - Flowblade version 1.16.0 - MLT version 6.8.0 - running on Linux Mint

**Comment by jliljebl** [comment]
Hi, unfortunately I have no idea what is going here. I'll be looking into this but it may take same time before I have any answers.

**Comment by jliljebl** [comment]
I do not believe this is valid in vast majority of system, closing as *unreproduced*.
