### ISSUE TITLE
Rendering stopped working

### ISSUE THREAD

**Issue by oberon-manjaro** [jliljebl/flowblade#556]
I'm running flowblade on Manjarolinux with current **mlt 6.10.0** and experience this issue with both **v1.16** and also latest **git master**.
When starting a render, the process window opens and then nothing else happens. It just sits there and the rendering never starts. I've tried this with different output formats - always the same.
So at the moment flowblade has become unusable for me.
Please let me know what further debug information will be helpful to narrow down the problem.

**Comment by oberon-manjaro** [comment]
When running the application from the terminal, there isn't any additional output.
The render window looks like this with all information empty The `Stop Render` button doesn't do anything. The only thing I can do is xkill the extra window.

![screenshot_2018-10-14_09-13-25](https://user-images.githubusercontent.com/11800714/46913645-a88fbd00-cf91-11e8-9e23-d9fe80615847.png)

**Comment by jliljebl** [comment]
Ok, thanks for the report. I'm on testing and last fixes with the next release hwitch will take 2-3 weeks, and I'll look this and other possible MLT regression after that.

**Comment by oberon-manjaro** [comment]
@dvdlvr, rendering via commandline with melt works fine.
Here are the .xml and .out files
[TEST.zip](https://github.com/jliljebl/flowblade/files/2478751/TEST.zip)

**Comment by dvdlvr** [comment]
Yeah, looks normal.
Too bad. I hoped it would've given us some clues.

The only thing I noticed was this line, multiple times
[filter swresample] Invalid Parameters: 0S - 48000Hz 2C s16 -> 48000Hz 
2C s16
But there is no resampling to be done, by the looks of it. I don't think 
this causes the problem.

Thanks. It was worth a shot.

**Comment by LeosWelt** [comment]
I have the same thing with the actual version provided by my arch linux.

**Comment by taintedsushi** [comment]
Having the same problem.  Did the melt thing with the same output dvdlvr reported.


MLT found, version: 6.10.0
numpy version: 1.14.5
OS: Ubuntu 18.10
Python 2.7.15+ (default, Oct  2 2018, 22:12:08) 
[GCC 8.2.0]
GTK+ version: 3.24.1

**Comment by knoma3** [comment]
I have the same problem, but i figured out, flowblade is rendering successful if i start it over a ssh connection (X forwarding enabled): ssh 127.0.0.1 -> log in -> run flowblade -> rendering works
I am using arch linux updated today with xfwm4 as desktop
MLT found, version: 6.12.0
numpy version: 1.15.4
OS: Arch Linux
Python 2.7.15 (default, Jun 27 2018, 13:05:28) 
[GCC 8.1.1 20180531]
GTK+ version: 3.24.2

**Comment by jliljebl** [comment]
I'll try to reproduce more thoroughly after 2.0 release, no idea yet on cause.

**Comment by jliljebl** [comment]
@oberon-manjaro @LeosWelt @LeosWelt THere is a fix (https://github.com/jliljebl/flowblade/commit/f48a9bd22e1e96c03e05eb14c66f37acc427f5ad#diff-3c8a18c044e2804a4a03725c2c858c84) related to rendering with MLT 6.6+ in 2.0, is this still reproducing?

**Comment by knoma3** [comment]
Thank you, great work ! i updated and it is working now.

**Comment by jliljebl** [comment]
I'm closing as fixed as I believe I know the and believe it be fixed. Will reopen if further reports come in.
