### ISSUE TITLE
User Luma does not work in the Wipe Clip Length Composer

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#558]
"Better to see once than hear a hundred times"
https://youtu.be/JcGEf36ZnSA

**Comment by jliljebl** [comment]
Confimed. It works if after setting the user luma with file selector you select "Preset Luma" and then back to "User Luma".  We seem to have some updating issue here.

**Comment by jliljebl** [comment]
Thanks, I was just flat out using wrong signal and somehow on my testing I missed that, don't use wipes much myself.

Fixed in repo, will be in next release.

**Comment by smolnp** [comment]
I rarely use them myself ... people just ask me, but I have to check first and then answer here and come across some problems. Thanks for the correction.
