### ISSUE TITLE
How can I disable the automatic snapping?

### ISSUE THREAD

**Issue by unfa** [jliljebl/flowblade#561]
I know it's a nice feature, but I'm used to working in a completely different way.
Maybe I'll learn  the benefits of the snapped "flow" editing.

For starters - how can I get back to a more "conventional" timeline behavior?

**Comment by smolnp** [comment]
What is your version of flowblade?

**Comment by jliljebl** [comment]
In 1.6 use "Overwrite" tool and drag clips ends to change their length. 

In 2.0 (coming soon) select Workflow Preset "Standard"

2.0 comes out in next few weeks.

**Comment by unfa** [comment]
Thank you! I'm looking forward to see Flowblade 2.0!
