### ISSUE TITLE
Custom alpha mask in Flowblade?

### ISSUE THREAD

**Issue by unfa** [jliljebl/flowblade#562]
Hi!

I'm a complete Flowblade noob. I've used Blender for many years and Kdenlive for a year now to edit video, but Flowblade is very new to me.

Is there a way to use a custom image or video as an alpha mask in compositing?

Since Flowblade only allows 9 tracks, I figure it might not be possible to do some crazy tricks with subtracting the alpha form the bottom, multiplying with the top and adding both together manually, am I right?

**Comment by unfa** [comment]
I've just found some mentions of a node-based compositor being developed, with bezier curve masks.
That's insane!

Is it going to be in the 2.0 release?

**Comment by jliljebl** [comment]
* Use 'Region' compositor with 'User luma' and select file there was a (now fixed) bug here, see the work around https://github.com/jliljebl/flowblade/issues/558
* Roto mask with Bezier curves is coming in 2.2 release hopefully
* The node compositor thing is cancelled, but there may be a simpler layer compositor coming a year down the road, the code still exists and works mostly.
* We are also working with Natron integration, Blender integration can come later if we find a good way to get values Flowblade -> Blender, Natron is much better in this

**Comment by unfa** [comment]
I think a Natron integration would be a great thing. Though one problem I have with Natron is that it's pretty unstable for me. I always have lots of problems using it in any serious production.

But once it's stable enough - a NLA integration would be a dream. Would Natron then become the main image handling engine for FlowBlade?

**Comment by jliljebl** [comment]
Natron does not provide multitrack realtime video playback, so we will stay with MLT for timeline.

Natron will be used to provide animations and effects such as text rotation flips or 3D layers that are not available in MLT.

Natron has been quite stable for me, so this has not been a factor for me when doing this (we already have code in for this).
