### ISSUE TITLE
Allow more then 9 tracks on  systems with larger screens.

### ISSUE THREAD

**Issue by unfa** [jliljebl/flowblade#563]
One thing that bothers me is that Flowblade limits the amount of tracks available to the maximum of 9 audio and video tracks total.

My current template in Kdenlive has 12 tracks, and though I rarely use more than 10 - I still often need more than 9.

Why does this limitation exist in Flowblade?

**Comment by unfa** [comment]
Thank you for considering lifting this limitation!

I imagine for strict movie editing it might be enough to use even 2 tracks often, but when you need to composite multiple sources, and add some effects the amount of tracks you need can grow significantly.

I once reach the track limit in Blender ([making the "They Know I'm A Freak" music video](https://www.youtube.com/watch?v=ZwYY34d6qvc)) - it was like 32, I believe.
And Blender has Meta Strips, so I could compact some clips together to free up space.

I sometimes go above 12 tracks in Kdenlive when making my tutorial videos.  A typical breakdown is:

```
Video:  Series logo overlay in the corner
Video: Text captions / effects 1
Video: Text captions / effects  2
Video: Text captions / effects  3
Video: Second camera
Video: Corner face overdrop onto the Screen
Video: Full frame Face
Video: Screencast
Audio: Main
Audio: Effects
```

I think making Flowbalde support more than 9 tracks total would make it considerable for a wider range of productions. I myself might want to use it, though I wouldn't be able to do all my work on just 9 tracks.

Anyone has other thoughs?

**Comment by jliljebl** [comment]
Seems that the comment I left here ...wasn't left here, maybe I didn't press "Comment" button.

Anyway, the reason this limitation is that I am quite fixed on the idea of never adding vertical scroll for timeline, it just feels more solid when you can only scroll in one direction. 9 tracks limit comes from supporting 768px height displays, those are still quite common.

What I can do is (maybe) allow up to 12 tracks on screens with 1050+ pixels but this will also require quite difficult dealing with possible scaling factors > 1 for HDPI screens. This will probably not be in next release.

I would strongly suggest using the "Sequences" feature to help with your workflow here:

*Sequence 1, content edit:*
Video: Second camera
Video: Corner face overdrop onto the Screen
Video: Full frame Face
Video: Screencast
Audio: Main

Edit this sequence until you have content edited to your satisfaction and then render it in lossless format.

*Sequence 2, master edit:*

(Video:  Series logo overlay in the corner (Use watermark ffeature for thisor this)
Video: Text captions / effects 1
Video: Text captions / effects  2
Video: Text captions / effects  3
Video: Content, from Sequence 1
Audio: Effects

Try it, you will probably (I think) find working this way easier and maybe faster as editing content with fewer tracks is going to faster.

**Comment by jliljebl** [comment]
I found a way to do this so that we don't have to do free 2d letterbox scrolling, we are instead using up/down buttons that always come to same centered position as the established tracks layout. For 2.12 we upped maximum number of tracks from 9 -> 21.

**Comment by unfa** [comment]
Awesome, thanks!
