### ISSUE TITLE
Titler fonts can not be Noto Sans CJK SC Light

### ISSUE THREAD

**Issue by classenu** [jliljebl/flowblade#569]
Hi,
I love blowblade, it's very beautiful to me. 
But the Titler can not work as i wish.
The font Noto Sans CJK SC include Regular/ normal/bold/light;
but i cannot choose them, there is only "Noto Sans CJK SC"; 
Am i missing any settings?

Please include the following information.
1) Flowblade version (Help->About):1.16.0
2) MLT version (Help->Runtime Environment):6.4.1
3) Your distribution (Ubuntu, Debian, Mint etc.):Debian 9.6

Best regards,
Peter,

**Comment by jliljebl** [comment]
You are onto something here as on my system Flowblade only makes available *Noto Sans CJK SC* but Gimp makes *Noto Sans CJK SC* and *Noto Sans CJK SC Bold* available.

I'm not sure if I will work on this. I'll leave it open for now and maybe look at this later, but this could go *wontfix*, depending on what i find on closer inspection.

**Comment by jliljebl** [comment]
Closing as *wontfix*. Titler currently works with text in exactly the same way as Gimp and Inkscape, it offers Normal, Bold and Italic options for fonts. It just might be possible to get Light options too, but I don't think the added functionality is worth the dev time.
