### ISSUE TITLE
segfault when loading libraries via dlopen

### ISSUE THREAD

**Issue by gnif** [jliljebl/flowblade#570]
Flowblade 1.16.0
MLT: 6.10.0
OS: Debian buster (testing)

Flowblade segfaults when trying to create a pixmap via XCreatePixmap via gtk due to corruption of the dlopen function. It is possible to get Flowblade to launch by placing a break point on the python main function and loading the libraries early, like so:

```
geoff@aeryn:~$ gdb /usr/bin/python
GNU gdb (Debian 8.1.90-1+b1) 8.1.90
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python...(no debugging symbols found)...done.
(gdb) set args /usr/bin/flowblade
(gdb) break main
Breakpoint 1 at 0xb9100
(gdb) r
Starting program: /usr/bin/python /usr/bin/flowblade
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, 0x000055555560d100 in main ()
(gdb) call dlopen("libXcursor.so.1", 0x2)
$1 = (void *) 0x5555558f82d0
(gdb) call dlopen("libcairo-gobject.so.2", 0x2)
$2 = (void *) 0x5555558fbbb0
(gdb) call dlopen("libpangocairo-1.0.so.0", 0x2)
$3 = (void *) 0x555555911190
(gdb) r
```

Doing so avoids calling dlopen after it's screwed up and as such Flowblade launches correctly.

I do not believe this to actually be a flow-blade problem, but a bug elsewhere, likely in MLT, but I do not know enough about MLT to debug the issue.

**Comment by jliljebl** [comment]
Could try Flowblade repo head to see if it still happens? There was an issue with some Qt services being made default in MLT which was worked around in Flowblade application code by dropping related services from MLT repo. The stack trace seems similar.

**Comment by gnif** [comment]
Yes, this was tried with the head version also.

**Comment by jliljebl** [comment]
OK, thanks, I'll need to get 2.0 out and then return to this.

**Comment by jliljebl** [comment]
This is likely related to SDL 1.2/2 and probably not productive to investigate before we have new video display in place, also unreproduced, closing.
