### ISSUE TITLE
Some wipe luma files for wide screen do not work correctly

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#572]
Please include the following information.
1) Flowblade version: 1.16
2) MLT version: 6.10.0
3) Your distribution: Rosa Linux r10 xfce
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

![_2018-12-03_17-26-22](https://user-images.githubusercontent.com/26217756/49381429-f371b980-f724-11e8-8d5a-3def256df1b9.png)

    • add composer Wipe Clip Length between clips
    • Wipe Type, for example, Diagonal 4
the screen shows that Preset Luma does not completely fill the monitor
It seems to me that with the selected profile 4K UHD 2160p 29.97 fps, Wipe Type: Diagonal 4  should fill the entire monitor

![_2018-12-03_17-32-11](https://user-images.githubusercontent.com/26217756/49381438-f8cf0400-f724-11e8-86ce-942eaf83797e.png)

**Comment by jliljebl** [comment]
Confirmed, this has some weird behavior.

1. PNG luma files seem to cause this, PGM does not, didn't test SVG. I changed file and code in *mltfilters.py* to use luma file *wipe_diagonal_4.png* to *wipe_diagonal_4.pgm* and artifact went away.
2. Once you get this artifact, then change to PGM luma file and back and the problem goes away, MLT has some internal state that changes. I'm not sure if this happen always.

The apparent solution is to convert all PGN files to PGM files and change *mltfilters.py*  code to use changed files. The image sizes need to be dropped too or we will get files that are too large.

**Comment by jliljebl** [comment]
SVG images also failed on some Profiles, so those need to be updated too.

**Comment by smolnp** [comment]
Okay, I'll do it. It is a pity that SVG is not suitable for some profiles, then you would get a smaller size.

**Comment by jliljebl** [comment]
If we can get contribution here, that would be great. I dropped the resolution to 720 x 576 when going to PGM files to get  smaller file sizes, this won't make difference in quality for this use case.

**Comment by smolnp** [comment]
Everything works for me, but the napkins designed for 16:9 screens look lent in 4:3 profiles

**Comment by jliljebl** [comment]
You should be able to do pull request from your Github clone of Flowblade following this:

https://help.github.com/articles/creating-a-pull-request/

If for some reason this does not succeed, I can get changes from your clone.

**Comment by smolnp** [comment]
I do not know how to choose the right one
![_2018-12-04_17-18-58](https://user-images.githubusercontent.com/26217756/49447945-d4d4f680-f7e8-11e8-862b-7d9560053701.png)

**Comment by smolnp** [comment]
it seems I am starting to understand that I had to think about it before making changes to the clone

**Comment by smolnp** [comment]
sent, but he gave all the changes including obsolete

**Comment by jliljebl** [comment]
Ok, I'll give it  a look later tonight.

**Comment by jliljebl** [comment]
Fixed, will be in 2.0.
