### ISSUE TITLE
Flowblade 1.16 consistently fails to render

### ISSUE THREAD

**Issue by peyre** [jliljebl/flowblade#576]
When I updated to the latest version of Xubuntu (18.10), Flowblade updated with it of course, but ever since then it's become unusable.  Using it is slower than before, which is no big deal, but when I tell it to render a video the progress bar never gets beyond around 5%.  It sucks up all the RAM, then soaks up all the swap, then the render crashes.  The resulting video, of course, doesn't play (and is much smaller than it should have been anyway).

I've tried this on three separate computers, a desktop and two laptops, one an HP, one a Toshiba, and another by a small vendor, and they all give me the same result.  Removing and reinstalling doesn't do a thing, just in case anyone wants to suggest that.

1) Flowblade version (Help->About): 1.16.0
2) MLT version (Help->Runtime Environment): 6.10.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Xubuntu 64-bit

![afterflowbladehangs](https://user-images.githubusercontent.com/3118014/49964648-df217f80-fecf-11e8-9442-299464123827.png)

**Comment by jliljebl** [comment]
Thanks for the report, I'll be taking a break for rest of the year, I'll comment when activity resumes in January.

**Comment by peyre** [comment]
Thanks jliljebl!  Flowblade is a rockin' video editor and I'd rather stick with it than switch to something else, so if you plan to look at it I'll hold off for the time being.

I [i]would[/i] simply uninstall, then install an older version (1.12), except that one has its own problem - when I hit X to make a cut, rather than simply cutting that section in two, it deletes everything after the cut.  So that's not an option either.

**Comment by jliljebl** [comment]
@peyre Version 2.0 is out, could you test it, does the problem still exist?

**Comment by peyre** [comment]
Great to hear!  Ok, I tried it out tonight.  I made several cuts in a movie, then told it to render the movie, as if I were finished.  It's still doing something kind of similar: it ran for a bit, then locked up the computer for several seconds, then dropped back to the render screen without saying it completed, failed, etc.  It created a 0 byte mp4 file.

**Comment by mayanksuman** [comment]
I was having the same issue with flowblade 1.16. The system used to get hanged with 100% memory use during render. Needless to say, render was also failing.

However, with flowblade 2.0, the render is working fine with low memory usage (~500MB).
The video was 164 minute long and output preset was MP4 1080p 25fps.

**Comment by uniomni** [comment]
I have the same problem. I can see using top that the python process spawned by flowblade slowly takes up all memory. Then the whole system freezes. This consistently happen for MTS input files with about 1 hour of video recording time. I am running Ubuntu 18.10 and continually up to date.
I would suggest rendering the video in blocks then merge them on disk.

**Comment by mayanksuman** [comment]
@uniomni Flowblade 2.0 is not having this problem. However, it is not available for Ubuntu 18.10. You can try to install it using [the released deb file](https://github.com/jliljebl/flowblade/releasese).

**Comment by pbeeken** [comment]
I am running FlowBlade 2.0.0 on Mint 19 (Tara).  I have fresh install of FlowBlade and rendering seems to be dependent on the target file.  For some target profiles (DVD MPEG NTSC) the rendering is fine.  If I try to output to HD 1080p 30fps, the rendering stalls at 14% and goes no further. It doesn't crash, mind you, the estimated time rolls up into days if you leave it long enough.  

My videos are very simple, They are a single clip being trimmed, titled and rendered for a video analysis references. My point is that there isn't a lot of work for the system to do other than transfer the high resolution frames.

Is it possible there is a missing codec?

**Comment by jliljebl** [comment]
Merged with #924.

**Comment by rvwhitney** [comment]
Hello! I am using Flowblade 2.8. I just finished a movie that will not render. Screenshot attached
![Screenshot_2023-12-09_15-10-46](https://github.com/jliljebl/flowblade/assets/746353/0fdc9ba5-8405-4ca9-b222-5c6d84079474)
I wonderif there is some setting I need to make - however, it will render smaller pieces. Mine is 1:06 in length, with about 250 images and 1 audio track.
Any ideas?
Thanks!
