### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by sdnian** [jliljebl/flowblade#578]
Please include the following information.
1) Flowblade version (Help->About): 1.16
2) MLT version (Help->Runtime Environment): 6.10
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

My OS is English language, but I'd like to use another language in Flowblade, could you add a new setting item to let's assign language?

**Comment by jliljebl** [comment]
Yes, this feature can be added.

**Comment by jliljebl** [comment]
Ok, this is now in, will be in 2.2.
