### ISSUE TITLE
Can't start Flowblade

### ISSUE THREAD

**Issue by alexpolevoy** [jliljebl/flowblade#579]
### What's wrong
I can't even start Flowblade. Every time I try to launch it, I'm left with an immediate crash. The problematic strings in program output are:

`pa_write() failed while trying to wake up the mainloop: Bad file descriptor`
`The X11 connection broke: I/O error (code 1)`
`XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0" after 32 requests (32 known processed) with 0 events remaining.`

Then there's KCrash output, which has nothing unusual in it. Also there's a mention of Natron missing, but it hopefully has nothing to do with the crash. Other apps using Pulseaudio and X work well.
### Environment:
- Flowblade 1.16
- MLT 6.10.0
- KDE Neon 5.14

**Comment by jliljebl** [comment]
There is good possibility that this is fixed for 2.0. I will keep this open atleast until next release is tested for this issue.

**Comment by vayulove** [comment]
I have same or similar crash on launch. I just downloaded whatever was up on the site. did dpkg -i to the deb, installed whatever dependencies it complained about, then went to the menu. Something flashed and then nothing so I tried from the command line here's the output starting from what looks like the error: 

```
G'MIC found
Natron not found
Player initialized with profile:  DV/DVD PAL
Selected color detected
BG color detected
Create SDL1 consumer...
[swscaler @ 0x7efd402a3380] Warning: data is not aligned! This can lead to a speed loss
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = python2.7 path = /usr/bin pid = 32683
KCrash: Arguments: /usr/bin/python2.7
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 82 requests (82 known processed) with 0 events remaining.

[1]+  Stopped                 flowblade

```
`flowblade-1.16.0-1_all.deb
`
```
Operating System: Debian GNU/Linux 
KDE Plasma Version: 5.14.3
Qt Version: 5.11.3
KDE Frameworks Version: 5.54.0
Kernel Version: 4.20.4-towo.1-siduction-amd64
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-4770K CPU @ 3.50GHz
Memory: 7.7 GiB of RAM

```

**Comment by sixtyfive** [comment]
Getting this trying to run the Flatpak:

![image](https://user-images.githubusercontent.com/192860/51697774-f09a9300-2008-11e9-835a-b0971e08d9fb.png)

No KCrash anywhere, but maybe the same root cause?

**Comment by darkshram** [comment]
I had the same issue:

```
MLT detection succeeded, 157 formats, 93 video codecs and 67 audio codecs found.
509 MLT services found.
Loading render profiles...
Loading filters...
Brightness dropped, MLT version too high for this filter.
Brightness Keyframed dropped, MLT version too high for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Natron not found
Player initialized with profile:  DV/DVD PAL
Selected color detected
BG color detected
Create SDL1 consumer...
Segmentation fault
```

Segfaults while trying to 'Create SDL1 consumer'

Then realized my mlt-6.12.0 installation had no SDL(1) support. I built mlt only with SDL2 support because SDL(1) is supposed to be deprecated (most projects had moved to SDL2). So, rebuilt mlt with SDL-devel and SDL_image-devel and now flowblade works like a charm.

**Comment by jliljebl** [comment]
@alexpolevoy @sixtyfive @vayulove Are you sure that your MLT is compiled with SDL1 support?

KDEnlive does not need SDL1 anymore, so it is quite possible that a KDE first system compiles MLT with SDL2 only.

**Comment by jliljebl** [comment]
@alexpolevoy @sixtyfive @vayulove Here is how you find out, give command in terminal:

    locate libmltsdl2.so

you should get some results because MLT is installed on the system, then give:

    locate libmltsdl.so

If get results for the first but not for the second, then we should know what the issue is.

**Comment by eszlari** [comment]
@sixtyfive What's your flatpak version?

**Comment by sixtyfive** [comment]
@eszlari 1.0.6 ... not good?

**Comment by jliljebl** [comment]
This no longer active and if we get similar stuff we can open new issue.
