### ISSUE TITLE
Improve deb install instructions

### ISSUE THREAD

**Issue by mikhailnov** [jliljebl/flowblade#580]
https://jliljebl.github.io/flowblade/download.html

`sudo dpkg -i ./flowblade-1.16.0-1_all.deb`

It's not a good idea to do this, modern apt versions (Ubuntu >= 16.04) support:  
`sudo apt install ./flowblade-1.16.0-1_all.deb`

`sudo apt -f install` is not needed then.

**Comment by jliljebl** [comment]
Alright, I trust that you are better informed then me here and did the requested change, thanks.
