### ISSUE TITLE
Wrong text in a window title

### ISSUE THREAD

**Issue by sdnian** [jliljebl/flowblade#582]
Please include the following information.
1) Flowblade version (Help->About): 1.16.0
2) MLT version (Help->Runtime Environment): 6.10.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Edit -> Preferences, General tab, click 'Select Folder' for Rendered Clips folder..
The popup window title is 'Select Thumbnail Folder', it should be 'Select Rendered Clips Folder'.

**Comment by jliljebl** [comment]
Closing as *wontfix* because 'Select Rendered Clips Folder' feature is going away for 2.2 because we will do #514 and this feature is in conflict with that.
