### ISSUE TITLE
Jittery playback between clips, 1080p 30fps ~35mbps on actual cpu (Ryzen5 mobile 8GB), normal?

### ISSUE THREAD

**Issue by awiprayitno** [jliljebl/flowblade#584]
Please include the following information.
1) Flowblade version (Help->About): 1.16
2) MLT version (Help->Runtime Environment): 6.6
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

I'm editing 1080p 30fps mp4 videos (bitrate ~ 35 mbps) on my laptop (2018 Ryzen5  8GB memory). When doing timeline playback, everytime it switch between 2 clips there is like a half second freeze, sometimes longer sometimes shorter.

Is this normal because my CPU/HDD cannot handle the stream well, or maybe somebody has a tip how to fix this? Many thanks in advance. Great program, I have used flowblade for many-many projects.

**Comment by jliljebl** [comment]
Are you getting different playback preformance for example with KDEnlive or maybe with VLC.

This likely is not a Flowblade bug, but if KDEnlive or Shotcut have better performance here we need to investigate more.

**Comment by jliljebl** [comment]
I'm merging this with #625, they are essentially the same.
