### ISSUE TITLE
Show some "doing work" indication when computing audio sync 

### ISSUE THREAD

**Issue by awiprayitno** [jliljebl/flowblade#585]
Please include the following information.
1) Flowblade version (Help->About): 1.16 and 2.0
2) MLT version (Help->Runtime Environment): 6.6
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.04
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

I tried to audio sync two clips that was recorded by 2 cameras and the same time.
Initially I tried with 1.16, nothing happened. Then I tried with 2.0, nothing happened too, but since I started 2.0 from command line, I noticed an error in the command line points out to key does not exist for the file name. One of the folder in the path has blank character.
Then I tried to rename that folder, now it works for both 2.0 and 1.16.

I also noticed that during the syncing process there is no user feedback, so user does not know whether it's still processing or simply not doing anything.

**Comment by jliljebl** [comment]
Confirmed.

I also agree that we should communicate somehow to user that there is work in progress as the results are not immediate.

As stated abovr **workaround** is to remove all spaces from folder names in file path.

**Comment by jliljebl** [comment]
The bug was fixed and will be in 2.0. Changed title for progress feature which will come later.

**Comment by awiprayitno** [comment]
This is really great, thanks for all your effort.

**Comment by jliljebl** [comment]
We now have a pulse progress bar dialog going when audio compare is done, will be in 2.2
