### ISSUE TITLE
Save BacKup Snapshot… does not work

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#587]
Please include the following information.
1) Flowblade version : MASTER
2) MLT version (Help->Runtime Environment): 6.10.0
OS: ROSA Desktop Fresh R10 EE 2016.1 Desktop
Python 2.7.15 (default, Sep 14 2018, 15:33:53)
[GCC 5.5.0 20171010 (ROSA)]
GTK+ version: 3.22.24
I am trying to make a backup snapshot of the project, but nothing happens further than copying files to the Media subdirectory. The operation just freezes in this place.
![_2019-01-19_23-59-37](https://user-images.githubusercontent.com/26217756/51432585-0267e900-1c4b-11e9-83c3-b6c88d5044fb.png)

**Comment by smolnp** [comment]
I had to move media files manually

**Comment by jliljebl** [comment]
Not happening here, I tried with Chinese project name that should hit possible UTF bugs, but still works. Can you post terminal output.

**Comment by smolnp** [comment]
bash-4.4$ ./flowblade
FLOWBLADE MOVIE EDITOR 1.16
---------------------------
Launch script dir: /home/semya/Рабочий стол/flowblade-master/flowblade-trunk
Running from filesystem...
MLT found, version: 6.12.0
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/clipeffectseditor.py:478: SyntaxWarning: name 'current_filter_index' is used prior to global declaration
  global current_filter_index
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/propertyeditorbuilder.py:184: SyntaxWarning: name 'changing_slider_to_kf_property_name' is used prior to global declaration
  global changing_slider_to_kf_property_name
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/tlinewidgets.py:369: SyntaxWarning: name 'TRACK_GRAD_ORANGE_STOP1' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/tlinewidgets.py:369: SyntaxWarning: name 'TRACK_GRAD_ORANGE_STOP3' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/tlinewidgets.py:369: SyntaxWarning: name 'TRACK_GRAD_STOP1' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/tlinewidgets.py:369: SyntaxWarning: name 'TRACK_GRAD_STOP3' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/kftoolmode.py:152: SyntaxWarning: name '_kf_editor' is assigned to before global declaration
  global _kf_editor
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/projectaction.py:756: SyntaxWarning: name 'force_overwrite' is used prior to global declaration
  global force_overwrite, force_proxy
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/projectaction.py:756: SyntaxWarning: name 'force_proxy' is used prior to global declaration
  global force_overwrite, force_proxy
numpy version: 1.15.0
Application version: 1.16.0
OS: ROSA Desktop Fresh R10 EE 2016.1 Desktop
Python 2.7.15 (default, Sep 14 2018, 15:33:53) 
[GCC 5.5.0 20171010 (ROSA)]
GTK+ version: 3.22.24
User dir: /home/smol/.flowblade/
Locale: ru_RU
Found translations at /home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/locale/, using those.
Force use English.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: premiere.xml
Loading shortcuts: Premiere-ish/ US keyboard
Gtk version is 3.22.24, Flowblade theme is available.
Screen size: 1366 x 768
Small height: True
Small width: True
Detecting environment...
---

...
MLT detection succeeded, 167 formats, 100 video codecs and 74 audio codecs found.
559 MLT services found.
Loading render profiles...
Loading filters...
Brightness dropped, MLT version too high for this filter.
Brightness Keyframed dropped, MLT version too high for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Natron not found
Player initialized with profile:  1366 x 768 29.97 fps
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 21: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 43: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 53: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 64: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 75: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 86: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 98: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 110: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 120: Having multiple values in <test> isn't supported and may not work as expected
Selected color NOT detected
BG color detected
Create SDL1 consumer...
[swscaler @ 0x7eff20b24040] Warning: data is not aligned! This can lead to a speed loss
Autosave started...
Saving project...
Loading Project, SAVEFILE_VERSION: 5
Player initialized with profile:  1366x768 30 fps
Create SDL1 consumer...
Autosave started...
Saving project...
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/projectaction.py", line 643, in run
    save_path = self.root_folder_path + self.project_name
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 11: ordinal not in range(128)

**Comment by smolnp** [comment]
bash-4.4$ ./flowblade
FLOWBLADE MOVIE EDITOR 1.16
..........................
Launch script dir: /home/semya/Рабочий стол/flowblade-master/flowblade-trunk
Running from filesystem...
MLT found, version: 6.12.0
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/clipeffectseditor.py:478: SyntaxWarning: name 'current_filter_index' is used prior to global declaration
  global current_filter_index
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/propertyeditorbuilder.py:184: SyntaxWarning: name 'changing_slider_to_kf_property_name' is used prior to global declaration
  global changing_slider_to_kf_property_name
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/tlinewidgets.py:369: SyntaxWarning: name 'TRACK_GRAD_ORANGE_STOP1' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/tlinewidgets.py:369: SyntaxWarning: name 'TRACK_GRAD_ORANGE_STOP3' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/tlinewidgets.py:369: SyntaxWarning: name 'TRACK_GRAD_STOP1' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/tlinewidgets.py:369: SyntaxWarning: name 'TRACK_GRAD_STOP3' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/kftoolmode.py:152: SyntaxWarning: name '_kf_editor' is assigned to before global declaration
  global _kf_editor
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/projectaction.py:756: SyntaxWarning: name 'force_overwrite' is used prior to global declaration
  global force_overwrite, force_proxy
/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/projectaction.py:756: SyntaxWarning: name 'force_proxy' is used prior to global declaration
  global force_overwrite, force_proxy
numpy version: 1.15.0
Application version: 1.16.0
OS: ROSA Desktop Fresh R10 EE 2016.1 Desktop
Python 2.7.15 (default, Sep 14 2018, 15:33:53) 
[GCC 5.5.0 20171010 (ROSA)]
GTK+ version: 3.22.24
User dir: /home/smol/.flowblade/
Locale: ru_RU
Found translations at /home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/locale/, using those.
Force use English.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: premiere.xml
Loading shortcuts: Premiere-ish/ US keyboard
Gtk version is 3.22.24, Flowblade theme is available.
Screen size: 1366 x 768
Small height: True
Small width: True
Detecting environment...

...
MLT detection succeeded, 167 formats, 100 video codecs and 74 audio codecs found.
559 MLT services found.
Loading render profiles...
Loading filters...
Brightness dropped, MLT version too high for this filter.
Brightness Keyframed dropped, MLT version too high for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Natron not found
Player initialized with profile:  1366 x 768 29.97 fps
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 21: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 43: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 53: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 64: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 75: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 86: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 98: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 110: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 120: Having multiple values in <test> isn't supported and may not work as expected
Selected color NOT detected
BG color detected
Create SDL1 consumer...
[swscaler @ 0x7eff20b24040] Warning: data is not aligned! This can lead to a speed loss
Autosave started...
Saving project...
Loading Project, SAVEFILE_VERSION: 5
Player initialized with profile:  1366x768 30 fps
Create SDL1 consumer...
Autosave started...
Saving project...
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/smol/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/projectaction.py", line 643, in run
    save_path = self.root_folder_path + self.project_name
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 11: ordinal not in range(128)

**Comment by jliljebl** [comment]
Pushed another patch, how about now? None of this makes any changes on my system, so I'm working blind.

**Comment by smolnp** [comment]
................
Player initialized with profile:  1366 x 768 29.97 fps
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 21: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 43: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 53: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 64: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 75: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 86: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 98: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 110: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 120: Having multiple values in <test> isn't supported and may not work as expected
Selected color NOT detected
BG color detected
Create SDL1 consumer...
[swscaler @ 0x7f4038b24040] Warning: data is not aligned! This can lead to a speed loss
Loading Project, SAVEFILE_VERSION: 5
failed to make icon from: /home/semya/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/res/darktheme/audio_file.png
Player initialized with profile:  1366x768 30 fps
Create SDL1 consumer...
Deleting /home/semya/.flowblade/autosave/autosave_01b607079762d922fb753363a17e204b
Autosave started...
Saving project...
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/semya/Рабочий стол/Новый каталог/flowblade-master/flowblade-trunk/Flowblade/projectaction.py", line 591, in run
    media_file_copy = media_folder + file_name
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

Saving project...

**Comment by jliljebl** [comment]
Another patch, is it working there?

**Comment by smolnp** [comment]
Player initialized with profile:  1366 x 768 29.97 fps
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 21: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 43: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 53: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 64: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 75: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 86: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 98: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 110: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 120: Having multiple values in <test> isn't supported and may not work as expected
Selected color NOT detected
BG color detected
Create SDL1 consumer...
[swscaler @ 0x7f00e4b24340] Warning: data is not aligned! This can lead to a speed loss
Loading Project, SAVEFILE_VERSION: 5
Player initialized with profile:  1366x768 30 fps
Create SDL1 consumer...
Deleting /home/semya/.flowblade/autosave/autosave_57e6a1d8c31564457cfa17bbf5aefff1
Autosave started...
Saving project...
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/semya/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/projectaction.py", line 627, in run
    clip_file_copy = media_folder + file_name
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

**Comment by smolnp** [comment]
Yes, the latest patches

**Comment by jliljebl** [comment]
So this works now?

**Comment by smolnp** [comment]
It does not work, nothing has changed

**Comment by smolnp** [comment]
Please forgive me, I did not notice your last patch, now I rechecked, everything works. Thank!

**Comment by smolnp** [comment]
Player initialized with profile:  1366 x 768 29.97 fps
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 21: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 43: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 53: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 64: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 75: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 86: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 98: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 110: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 120: Having multiple values in <test> isn't supported and may not work as expected
Selected color NOT detected
BG color detected
Create SDL1 consumer...
[swscaler @ 0x7f8cdcb24040] Warning: data is not aligned! This can lead to a speed loss
Autosave started...
Saving project...
Loading Project, SAVEFILE_VERSION: 5
Traceback (most recent call last):
  File "/home/semya/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/app.py", line 319, in <lambda>
    window_state_id = gui.editor_window.window.connect("window-state-event", lambda w, e:updater.window_resized())
  File "/home/semya/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/updater.py", line 127, in window_resized
    current_sequence().resize_tracks_to_fit(gui.tline_canvas.widget.get_allocation())
  File "/home/semya/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/editorstate.py", line 152, in current_sequence
    return project.c_seq
AttributeError: Project instance has no attribute 'c_seq'
Traceback (most recent call last):
  File "/home/semya/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/app.py", line 318, in <lambda>
    window_resize_id = gui.editor_window.window.connect("size-allocate", lambda w, e:updater.window_resized())
  File "/home/semya/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/updater.py", line 127, in window_resized
    current_sequence().resize_tracks_to_fit(gui.tline_canvas.widget.get_allocation())
  File "/home/semya/Рабочий стол/flowblade-master/flowblade-trunk/Flowblade/editorstate.py", line 152, in current_sequence
    return project.c_seq
AttributeError: Project instance has no attribute 'c_seq'
Player initialized with profile:  1366x768 30 fps
Create SDL1 consumer...
Autosave started...

**Comment by jliljebl** [comment]
Thank you, closing.

 I'm probably leaving that  AttributeError: Project instance has no attribute 'c_seq' alone for 2.0 because I can actually break more stuff if I try to fix it, its a long time issue with no functional impact.
