### ISSUE TITLE
something broke in  Render Slow / Fast Motion File ( Render Reverse Motion File)

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#588]
Please include the following information.
1) Flowblade version (Help->About): MASTER
2) MLT version (Help->Runtime Environment): 6.10.0
3) Your distribution (Ubuntu, Debian, Mint etc.): ROSA Desktop Fresh R10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
ACTIONS:
..."Creating Motion Clips 
    1. Right click on a Media File and select Render Slow / Fast Motion File from menu 
    2. Edit parameters for the new motion Clip 
        ◦ Set speed 
        ◦ Give name and location for motion Clip 
        ◦ Select rendering parameters for motion Clip. It is probably a good idea to use a lossless format here to avoid any generational quality losses. 
        ◦ Select render range, either: 
            ▪ Full Source Clip 
            ▪ From Source Clip Mark In to Mark Out 
    3. Click Render button to create a new motion Clip 
Creating Reverse Clips 
    1. Right click on a Media File and select Render Reverse Motion File from menu 
    2. Edit parameters for the new motion Clip 
        ◦ Set speed 
        ◦ Give name and location for reverse Clip 
        ◦ Select rendering parameters for reverse Clip. It is probably a good idea to use a lossless format here to avoid any generational quality losses. 
        ◦ Select render range, either: 
            ▪ Full Source Clip 
            ▪ From Source Clip Mark In to Mark Out 
    3. Click Render button to create a new reverse Clip"... 
PROBLEMS:
a) Progress text message is not displayed.
b) The created media file is not added to the Media panel, although it is saved to the folder with the original video.
https://youtu.be/NQ5sGk05fPo

**Comment by jliljebl** [comment]
Could you post terminal output on this, i'm not getting this.

**Comment by smolnp** [comment]
...
MLT detection succeeded, 167 formats, 100 video codecs and 74 audio codecs found.
553 MLT services found.
Loading render profiles...
Loading filters...
Brightness dropped, MLT version too high for this filter.
Brightness Keyframed dropped, MLT version too high for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Natron not found
Player initialized with profile:  1366 x 768 29.97 fps
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 21: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 43: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 53: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 64: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 75: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 86: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 98: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 110: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 120: Having multiple values in <test> isn't supported and may not work as expected
Selected color NOT detected
BG color detected
Create SDL1 consumer...
[swscaler @ 0x7f2914b24040] Warning: data is not aligned! This can lead to a speed loss
Autosave started...
Saving project...
[image2 @ 0x7f29300008c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Saving project...
Loading Project, SAVEFILE_VERSION: 5
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Flowblade/app.py", line 318, in <lambda>
    window_resize_id = gui.editor_window.window.connect("size-allocate", lambda w, e:updater.window_resized())
  File "/usr/lib/python2.7/site-packages/Flowblade/updater.py", line 127, in window_resized
    current_sequence().resize_tracks_to_fit(gui.tline_canvas.widget.get_allocation())
  File "/usr/lib/python2.7/site-packages/Flowblade/editorstate.py", line 152, in current_sequence
    return project.c_seq
AttributeError: Project instance has no attribute 'c_seq'
Player initialized with profile:  HD 720p 23.98 fps
Create SDL1 consumer...
Autosave started...
Saving project...
Updating media lengths:
Updating media lengths done.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Flowblade/app.py", line 658, in _do_window_resized_update
    splash_screen.destroy()
AttributeError: 'NoneType' object has no attribute 'destroy'
....

[mpeg @ 0x7f28dc0008c0] buffer underflow st=1 bufi=825 size=1152
[mpeg @ 0x7f28dc0008c0] buffer underflow st=1 bufi=558 size=1152
FileRenderPlayer stopped, producer frame: 389

**Comment by smolnp** [comment]
try media files with other profiles
does not work with these parameters:
![_2019-01-20_15-06-46](https://user-images.githubusercontent.com/26217756/51439028-970f2d00-1cc5-11e9-8f03-ca8fc7b9839f.png)

**Comment by smolnp** [comment]
с этими параметрами работает:
![_2019-01-20_15-07-16](https://user-images.githubusercontent.com/26217756/51439041-b312ce80-1cc5-11e9-8de3-6a2edaada007.png)

**Comment by jliljebl** [comment]
Thanks, we have actionable error now.

Николай Смольянинов <notifications@github.com> kirjoitti su 20. tammikuuta
2019 klo 14.12:

**Comment by smolnp** [comment]
I only work with video files created in flowblade

**Comment by jliljebl** [comment]
Ok, I found a bug and pushed a fix 95a7d364e2733c3ddc84b. The thing is that on my system I wasn't getting any errors. so can you try master. Could you also look at the terminal output even if it works now to see if there are any error prints.

**Comment by jliljebl** [comment]
Pushed a patch for this, can you try master.

**Comment by smolnp** [comment]
everything works, but for verification I post the terminal output:

MLT detection succeeded, 167 formats, 100 video codecs and 74 audio codecs found.
559 MLT services found.
Loading render profiles...
Loading filters...
Brightness dropped, MLT version too high for this filter.
Brightness Keyframed dropped, MLT version too high for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Natron not found
Player initialized with profile:  1366 x 768 29.97 fps
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 21: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 43: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 53: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 64: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 75: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 86: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 98: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 110: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/01-culmus.conf", line 120: Having multiple values in <test> isn't supported and may not work as expected
Selected color NOT detected
BG color detected
Create SDL1 consumer...
[swscaler @ 0x7f7a24b24040] Warning: data is not aligned! This can lead to a speed loss
Autosave started...
Saving project...
Loading Project, SAVEFILE_VERSION: 5
Player initialized with profile:  1366x768 30 fps
Create SDL1 consumer...
Autosave started...
Saving project...
Using timewarp producer, sound available.
Motion clip render starting...
FileRenderPlayer started, start frame: 0, stop frame: 2770
[mpeg @ 0x7f79e0201e40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpeg @ 0x7f79e0201e40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpeg @ 0x7f79e0201e40] VBV buffer size not set, using default size of 230KB
If you want the mpeg file to be compliant to some specification
Like DVD, VCD or others, make sure you set the correct buffer size
[mpeg @ 0x7f79e0201e40] buffer underflow st=0 bufi=2002 size=141059
[mpeg @ 0x7f79e0201e40] buffer underflow st=0 bufi=2002 size=141059
[mpeg @ 0x7f79e0201e40] buffer underflow st=0 bufi=4043 size=141059

**Comment by jliljebl** [comment]
Excellent, thanks. Closing. 

All of this has been working all the time here. It is fundamentally unacceptable for Python + Gtk to work this much differently on different systems, but what can one do.
