### ISSUE TITLE
missing icon on video editor website

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#589]
the documentation site (https://jliljebl.github.io/flowblade/webhelp/edit_tools.html) lacks an icon workflow.png. Which must be added to the address ./gh-pages/webhelp

![_2019-01-22_13-16-21](https://user-images.githubusercontent.com/26217756/51528634-26dce480-1e48-11e9-8f85-69df055fa1fc.png)

**Comment by jliljebl** [comment]
Confirmed and fixed. This i would have 100% missed, thanks.
