### ISSUE TITLE
some filters are not displayed in the flowblade interface

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#592]
Please include the following information.
1) Flowblade version (Help->About): master
2) MLT version (Help->Runtime Environment): 6.12.0
3) Your distribution (Ubuntu, Debian, Mint etc.):rosa linux r10

RGB Adjustment, Gamma, Hue filters are missing in the flowblade interface (in the same OS, the filters are displayed in kdenlive and are editable). Filters, I suppose, should be displayed in the interface, since they are present in filters.xml.
![_2019-01-25_18-37-56](https://user-images.githubusercontent.com/26217756/51755875-b694c400-20d0-11e9-91b2-fa7e05731b12.png)

**Comment by jliljebl** [comment]
These are replaced with never, better filters if available. There is printout on terminal for these on startup:
...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
...
