### ISSUE TITLE
german language file

### ISSUE THREAD

**Issue by martinkg** [jliljebl/flowblade#594]
Hi,

 I translated the German language file flowblade.po from the current flowblade version.
flowblade.po.txt is attached.
[flowblade.po.txt](https://github.com/jliljebl/flowblade/files/2813254/flowblade.po.txt)

**Comment by smolnp** [comment]
https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/CREATING_TRANSLATION.md

**Comment by jliljebl** [comment]
Thank, I can still add this as I need to do some changes still before release, will probably do this on weekend.

**Comment by jliljebl** [comment]
This is now in.
