### ISSUE TITLE
2.4 will be the first Python3 supporting version

### ISSUE THREAD

**Issue by martinkg** [jliljebl/flowblade#597]
Hi,

since python2 support will soon end at Fedora [1], so I ask if flowblade 2.0.0 will support python3?
 
[1] https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3

Regards
Martin

**Comment by jliljebl** [comment]
Unfortunately no. MLT for example does not have Python 3 bindings, other dependencies probably should have, but MLT does not have those and there are no contributors in sight who would be creating those.

As for myself, creating Swig bindings is something I know nothing about, I would need to stop all other development to learn to create those. 

Even with  those being available I'm estimating a full year of dead feature development should I change my focus to executing the Python 3 port. This could be an over estimation, but I have no way of knowing currently.

With these points in mind the current plan is as follows.

1) During 2019-2020 do 4-6 releases to get the feature set to a sort of complete level, the current road map indicates the main points.

2) Do Python 3 conversion during 2021.

3) If some distros will not be able to satisfy Python 2 dependencies of Flowblade before the Python 3 version is done, offer Flatpak version as a replacement  for users.

If I get someone to do the MLT Python 3 bindings and help with the conversion work, I'm wiling revise this plan, all help will greatly be appreciated.

**Comment by cclauss** [comment]
mltframework/mlt#407

**Comment by jliljebl** [comment]
I added a doc and looked all the Python 3 packages: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/PYTHON_3_PORT_INFO.md

MLT is the only one we're missing.

**Comment by jliljebl** [comment]
I think this can be brought forward. I will create a test repo during this cycle and try to run some conversion scripts and inform myself on the MLT bindings situation better.

If anyone knows anything about creating Python 2/3 bindings with Swig, post info here

**Comment by cclauss** [comment]
Would it be possible to light up #610 before we proceed?  Some automated testing will smooth out the porting process.  The FREE plan @ https://travis-ci.com/jliljebl would be sufficient.

**Comment by jliljebl** [comment]
I'll be first doing extensive tests on yet-to-be-created test repo, I'm not going to commit anything on this repo until I have a clear picture on related issues. I'll look #610 as a separate thing helping in keeping the errors away here.

**Comment by jliljebl** [comment]
Dan Dennedy claimed that MLT Python 3 support is already working: https://github.com/mltframework/mlt/issues/410

**Comment by jliljebl** [comment]
I'll open a test repo in a few weeks and start looking where were at.

**Comment by sergiomb2** [comment]
Latest version of MLT (v6.14.0) supports python3

**Comment by cclauss** [comment]
@martinkg Can this issue be closed?

**Comment by jliljebl** [comment]
Yes, we will do 2.2 release and 2.4 will be the Python 3 conversion.

**Comment by sergiomb2** [comment]
Thanks for the reply , I will maitain pyhton2-mlt until next release.

**Comment by jliljebl** [comment]
**master** is on Python 3 now.

**Comment by alexmyczko** [comment]
How long until the release?

**Comment by jliljebl** [comment]
About 2 months.

**Comment by cclauss** [comment]
Before 1/1/2020?

**Comment by jliljebl** [comment]
Yes, but not by much.

**Comment by alexmyczko** [comment]
jfi: current master works for me with python3

**Comment by alexmyczko** [comment]
will there be a christmas 2019 release? a happy new year 2020 release?

**Comment by jliljebl** [comment]
@alexmyczko Depends on how things go next week, unfortunately there is still some things to do and I didn't get much done this week.

**Comment by jliljebl** [comment]
This now done.
