### ISSUE TITLE
icon for web site

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#599]
![_2019-02-04_21-36-27](https://user-images.githubusercontent.com/26217756/52229042-f32ca080-28c4-11e9-8a98-75113a7fad5a.png)
 this line (with the image attached to the specified path) will add an icon to the web site.
example:
![21-29-52](https://user-images.githubusercontent.com/26217756/52229101-17887d00-28c5-11e9-9f5f-9a1a21b6e126.png)

**Comment by jliljebl** [comment]
I added to other pages but not doc files, maybe do that later. Yeah, its bit better, and most pages seem to have one now that I gave this a bit of attention.

**Comment by smolnp** [comment]
I do not want to create a new discussion. Therefore, I will write here. I reconstructed the manual for the Russian site, I can take the time to do the same work for the official site (keeping the original color scheme). If this is interesting to you. https://smolnp.github.io/flowblade/webhelp/help.html 
![_2019-02-06_20-54-51](https://user-images.githubusercontent.com/26217756/52362389-88f53680-2a51-11e9-8987-168231862224.png)
