### ISSUE TITLE
Translations issues for >= 2.0

### ISSUE THREAD

**Issue by jliljebl** [jliljebl/flowblade#601]
Report all translations issues here, please, so we have a single place for them.

**Comment by smolnp** [comment]
couldn't find a line to translate...
![DeepinScreenshot_выберите-область_20190816215211](https://user-images.githubusercontent.com/26217756/63191289-d2fa4d00-c070-11e9-80b8-1ad9ff85764a.png)
![DeepinScreenshot_flowblade_20190816214942](https://user-images.githubusercontent.com/26217756/63191395-11900780-c071-11e9-8c9b-e5d33bce8463.png)

**Comment by jliljebl** [comment]
Thanks, fixed now. If you can get me one more translation version for 2.2 in about week I'll include it.

**Comment by smolnp** [comment]
the following lines are translated, not displayed in the interface
![DeepinScreenshot_flowblade_20190818152207](https://user-images.githubusercontent.com/26217756/63224395-3947b280-c1cc-11e9-98d0-0b2aba0f55a5.png)
![DeepinScreenshot_mousepad_20190818152710](https://user-images.githubusercontent.com/26217756/63224439-e5899900-c1cc-11e9-8bfa-7ed82988c404.png)

**Comment by smolnp** [comment]
could not find a string to translate
![DeepinScreenshot_выберите-область_20190818153054](https://user-images.githubusercontent.com/26217756/63224455-313c4280-c1cd-11e9-983d-51e3381660bd.png)

**Comment by smolnp** [comment]
could not find the line for translation (Normalize audio filter)
![DeepinScreenshot_выберите-область_20190818153306](https://user-images.githubusercontent.com/26217756/63224498-cdfee000-c1cd-11e9-96f3-4b2219558769.png)

**Comment by jliljebl** [comment]
Good catches, thanks. I pushed an update, all should work now.

**Comment by smolnp** [comment]
Thank you, it works. Now I will provide an updated translation file.

**Comment by smolnp** [comment]
The following lines are translated, not displayed in the interface.
![Screenshot_20200417_113819-1](https://user-images.githubusercontent.com/26217756/79551158-f6631500-80a1-11ea-81c4-e01ff22441d3.png)
![Screenshot_20200417_114744](https://user-images.githubusercontent.com/26217756/79551168-f95e0580-80a1-11ea-886e-60c4668e416c.png)

**Comment by jliljebl** [comment]
Ok, thanks. This seems to be a bit more complex issue then usually with translations, may take a bit get sorted.

**Comment by smolnp** [comment]
There is still a lot of time before the release of the new version :-)

**Comment by jliljebl** [comment]
@smolnp Ok, I found the issue. I removed some '#, fuzzy' determinations with this patch https://github.com/jliljebl/flowblade/commit/726e54d252cab3e1eabf0ad915058adaada04c3c and compiled the Russian language translation and the translations appeared. 

If you don't see your translation in GUI, open the .po file an remove the '#, fuzzy' and compile the translation and it should appear. If you are using app it should probably have some switch that shows if translation string is fuzzy

if you can get the remaining changes in translation next week I'll be able to get it in the 2.6, it might be possible a bit later if I don't get stuff sorted my self but i do need to push 2.6 in 10-14 days to get things moving.

We had 144  '#, fuzzy' markings in .po file, we should look into removing some, I think at least some of them are strings that are now unused.

https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html

**Comment by smolnp** [comment]
The translation "Change Render Item Path" is not #fuzzy, the compiled file ignores this, the original English version of the line opens.

**Comment by jliljebl** [comment]
Unfortunately I don't get it then right now.

**Comment by jliljebl** [comment]
@smolnp I opened a new sticky thread, actions continues there: https://github.com/jliljebl/flowblade/issues/954
