### ISSUE TITLE
Rezising window does not work

### ISSUE THREAD

**Issue by hausi14** [jliljebl/flowblade#602]
Flowblade 2.0, just downloaded, then startet, It is not possible (Debian) to change the window size). It is not possible to get it using the full screen. On my 1920x1080 screen, it uses full width, but not full height. Is this normal?

**Comment by jliljebl** [comment]
No, I have the same screen size and everything works. Could you:

1) Take screenshot displaying the problem,
2) Start application with command 'flowblade' from terminal and post output here,
3) Specify the Debian version you are using?

**Comment by hausi14** [comment]
It is a debian 8 installation, Floblade 1.x works perfect, but after 2.0 installation, a switch to fullscreen blocks window on screen (even it goes not to fullscreen). Resizing itself is possible (if not blocked in fullscreen), but going to fullscreen does not work.

**Comment by jliljebl** [comment]
Debian has multiple deskstop environments(Gnome, Kde..), which one you are using?

**Comment by hausi14** [comment]
It is Mate 1.8.1

**Comment by jliljebl** [comment]
Debian 8 (Jessie), released 25–26 April 2015

Ok, this is quite old. I'll leave open to get additional reports, but if we're not getting any in a few months, I'll close as *wontfix*, 4 year old releases cannot be reasonably supported.

**Comment by hausi14** [comment]
Yes, it has some age, but what I don't understand, it worked without any problems in flowblade 1.x.

**Comment by jliljebl** [comment]
There is a hidden file in your home folder *<home>/.flowblade/prefs*

Does deleting that help?

I did do some changes to window size setting code and those may affect you, but I can't go back if the more up-to-date systems work, because the changes fixed bugs on those.

**Comment by jliljebl** [comment]
Ok, I do not think this a workable issue, holding.
