### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by arkdlite** [jliljebl/flowblade#604]
1) Flowblade 2.0.0
2) MLT 6.12.0
3) Debian 10 (testing)
Hello! This is great video editor but performance is its "Achilles' heel". I tried to install all dependencies with PyPy (Python interpreter with JIT compiler). I can install all of them via `pip` except one: `python-dbus`. PyGobject, MLT bindings, NumPy can be installed to PyPy.
Can you use another DBus bindings? Here's the list of them: https://www.freedesktop.org/wiki/Software/DBusBindings/ For example, `pydbus` works with PyPy.
PyPy's performance is much better then CPython (http://speed.pypy.org/) and it can make your project faster.

**Comment by jliljebl** [comment]
At this point, sorry, no, I don't want to touch my established bindings. My approach to dependencies is about as conservative as it can get: if it works, don't touch it. Closing as *wontfix*.
