### ISSUE TITLE
Website text so small it's hardly readable

### ISSUE THREAD

**Issue by mikaeleiman** [jliljebl/flowblade#609]
I clicked https://jliljebl.github.io/flowblade/ to read about the project, but could hardly read the small text.

Text is now 10px, to make it comfortably readable I had to make it 15px.

Firefox, macOS, low-res screen.

**Comment by jliljebl** [comment]
Yeah, you're absolutely right. When did this happen, it used to look good. This needs some work, I'll drop some changes every now and then, for now I made the text bigger.

**Comment by jliljebl** [comment]
I changed the font to 16px,  seems readable now. Closing as fixed.
