### ISSUE TITLE
Installation error: Unknown media type 

### ISSUE THREAD

**Issue by jakesalomon** [jliljebl/flowblade#617]
OS: Linux Mint 4.4.0-142-generic #168-Ubuntu x86_64 GNU/Linux (From uname -a)
MLT Version: 6.0.0
GTK Version: 3.18.9
Installation command: sudo apt install ./flowblade-2.0.0-1_all.deb

I ran the above command in /var/downloads.  Progress seems normal until about 56% done.  The I got these two warnings:

> Unknown media type in type 'all/all'
> Unknown media type in type 'all/allfiles'

Otherwise, it progressed to a normal end and $? is 0.

I just started it to see if it's missing something fundamental.  Apparently not.  I won't know for sure until I start trying to edit movies.

**Comment by jliljebl** [comment]
My .deb file might not be completely up to standards, I'll test with lint tool sometime near next release.

**Comment by jliljebl** [comment]
Found info here: https://askubuntu.com/questions/18806/why-does-update-mime-database-complain-about-uri-rtspt-and-other-unusual-types

This does not seem to require any action, this has no functional impact, closing as *wontfix*.
