### ISSUE TITLE
2.0.0: GTK check buttons not displaying their state

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#618]
Flowblade Version 2.0.0
GTK Version 3.24.4
MLT Version 6.13.0
Fedora 29

The GTK checkbuttons aren't showing their state in the latest flowblade release. For example, in the attached image, "Freeze Before" is selected, and the filter is working as expected, but this is not displayed on the check button itself.

![checkbutton bug](https://user-images.githubusercontent.com/25953969/52544552-93268480-2e05-11e9-92d8-52f4ecaf95eb.png)

**Comment by jliljebl** [comment]
Not reproducing on my system, but it is possible that we have some theme or packaging bug. Only way to reproduce is probably to install a machine Fedora, so this will maybe need to some time to get addressed.

**Comment by thennicke** [comment]
Looks like you were right that it's a bug in the new "Flowblade" theme. I reverted to the old "Dark" theme and it seems to be working fine now.

![freeze check button working](https://user-images.githubusercontent.com/25953969/52635397-e12eab80-2f1d-11e9-8939-441464a79496.png)

**Comment by jliljebl** [comment]
I tested on Ubuntu 18.10 and Debian Stretch virtual machines and bug wasn't present.

Maybe you could check if the checkbox image got installed, it is in file *../<install_dir>/res/css/assets/checkbox-checked.png* , If the file is not there that would explain the issue. On system the full path is */usr/share/flowblade/Flowblade/res/css/assets/checkbox-checked.png* but might be different on Fedora.

**Comment by jliljebl** [comment]
On my system GTK+ version is 3.24.1, so hopefully this isn't some change in how themes work  GTK+ 3.24.1, -> GTK+ 3.24.4

**Comment by thennicke** [comment]
My installation is via Flatpak, and so I'm looking in the directory /var/lib/flatpak/app/io.github.jliljebl.Flowblade (I hope this is the right place to be looking).

A quick search in Nautilus for "checkbox-checked.png" only shows matches in the "Adwaita" folders.
![screenshot from 2019-02-12 23-56-15](https://user-images.githubusercontent.com/25953969/52636847-d249f800-2f21-11e9-8e51-5fc18857205d.png)

**Comment by jliljebl** [comment]
Ok, the */assests* folder is missing from Flatpak installation:
![screenshot from 2019-02-12 15-09-38](https://user-images.githubusercontent.com/1823444/52637615-62fbe600-2ed8-11e9-8b65-31c9e12c2eb0.png)

**Comment by thennicke** [comment]
Yep, can confirm that here on my end too.

**Comment by jliljebl** [comment]
It was a typo in *setup.py* file that Flatpak uses to get assets included. I pushed a patch just now and will close once the Flatpak gets updated.

**Comment by jliljebl** [comment]
Tested install from Flathub and the problem is fixed. Thanks for the report and feedback, missed this during release testing.
