### ISSUE TITLE
2.0.0 Preview - Window transparent

### ISSUE THREAD

**Issue by treborxy** [jliljebl/flowblade#619]
Please include the following information.
1) Flowblade version 2.0
2) MLT version 6.6.0
3) Your distribution: elementary OS 5 Juno
4) When starting FB, the preview - Window appears transparent. When loading a video-file, it is dispayed, but "combined" with the background behind FB-window (see attached screenshots)

![bildschirmfoto von 2019-02-11 13-53-59](https://user-images.githubusercontent.com/19653937/52564939-b18c8000-2e05-11e9-99b7-7fa7249ab26e.png)
![bildschirmfoto von 2019-02-11 13-54-57](https://user-images.githubusercontent.com/19653937/52564947-b3eeda00-2e05-11e9-8ad4-08e7db758928.png)

**Comment by jliljebl** [comment]
Does Flatpak version give different results?

**Comment by jliljebl** [comment]
No, I think this all related SDL1.2 on elemtaryOS and  we will probably only get Flowblade working on elementary once we have new way to display video.

**Comment by treborxy** [comment]
Is there a way to find out which version is beeing used? Because it is installed libsdl2.0 (Version 2.0.8+dfsg1-1ubuntu1.18.04.1)...?

**Comment by jliljebl** [comment]
It uses SDL 1.2 because SDL 2 video consumer just crashes and is not created by application code, they are different MLT services.

 SDL 2 changed API  is such a way that it cannot be used with Flowblade.

**Comment by jliljebl** [comment]
I'm merging this with #603 because I believe all elementaryOS related display issues get fixed with that.
