### ISSUE TITLE
Can not apply and / or copy / paste keyboard shortcuts from Edit -> Keyboard Shortcuts Dialog

### ISSUE THREAD

**Issue by softwarelimits** [jliljebl/flowblade#620]
--I want to learn keyboard shortcuts, but with the Keyboard Shortcuts dialog open I can not apply any of these keyboard shortcuts, as the dialog seems to intercept all of them. So I want to copy the list of shortcuts and paste it to an open editor window - what also does not work,---

**Comment by jliljebl** [comment]
Ok, let's see if we can do something about this.

**Comment by jliljebl** [comment]
The dialog has been made non-modal as requested, will be in 2.2.
