### ISSUE TITLE
Audio Level Meter does not follow Resize of Monitor Window

### ISSUE THREAD

**Issue by softwarelimits** [jliljebl/flowblade#621]
Resizing the "monitor" - the part of the window where the video is shown - does not resize the audio level meter, see attached screenshot.

![flowblade-2-audio-meter-does-not-adjust-size](https://user-images.githubusercontent.com/5655497/52816380-67bfc600-30a1-11e9-8f38-15eec3001797.png)

**Comment by jliljebl** [comment]
I know. This...has not been central focus of development effort, but I do agree it would be better if it did.

**Comment by jliljebl** [comment]
Added to feature queue.

**Comment by jliljebl** [comment]
Fixed in repo, will be in 2.2. This took all of 10 minutes, should have done long ago.
