### ISSUE TITLE
Welcome Screen Text Not Readable - leads to frustration on first interaction. 

### ISSUE THREAD

**Issue by softwarelimits** [jliljebl/flowblade#622]
The welcome screen presents some text that is not readable, see attached screenshot. This leads to a frustratiion of the user on the _very first interaction with the program_ - don´t do that.
![flowblade-2-welcome-sreen-not-readable](https://user-images.githubusercontent.com/5655497/52816511-b5d4c980-30a1-11e9-9e7b-39b9230ee7d4.png)

**Comment by jliljebl** [comment]
Which OS and desktop environment? It looked OK on my tests but apparently not everywhere.

**Comment by jliljebl** [comment]
This is now fixed in repo, will be in 2.2.
