### ISSUE TITLE
please do not just write into $HOME - respect XDG_ dirs, thank you!

### ISSUE THREAD

**Issue by softwarelimits** [jliljebl/flowblade#626]
Well, easy as that - please respect $XDG_ vsriables  - there are many reasons why these exists and why you as a software developer should look for them. E.g. I do not want all that dot directories in my $HOME because it breaks my backup scripts. Please do not just blindly create $HOME/.flowblade directory, thank you.

**Comment by jliljebl** [comment]
Closed as duplicate.
