### ISSUE TITLE
Issues Launching in Arch Linux

### ISSUE THREAD

**Issue by DanitiKain** [jliljebl/flowblade#629]
1) 2.0
2) Won't Launch
3) Arch - Installed from latest AUR
4) Just trying to launch Flowblade after install

LOWBLADE MOVIE EDITOR 2.0
--------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/pyshared/Flowblade
MLT found, version: 6.12.0
/usr/share/pyshared/Flowblade/clipeffectseditor.py:478: SyntaxWarning: name 'current_filter_index' is used prior to global declaration
  global current_filter_index
/usr/share/pyshared/Flowblade/propertyeditorbuilder.py:184: SyntaxWarning: name 'changing_slider_to_kf_property_name' is used prior to global declaration
  global changing_slider_to_kf_property_name
/usr/share/pyshared/Flowblade/tlinewidgets.py:370: SyntaxWarning: name 'TRACK_GRAD_ORANGE_STOP1' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/usr/share/pyshared/Flowblade/tlinewidgets.py:370: SyntaxWarning: name 'TRACK_GRAD_ORANGE_STOP3' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/usr/share/pyshared/Flowblade/tlinewidgets.py:370: SyntaxWarning: name 'TRACK_GRAD_STOP1' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/usr/share/pyshared/Flowblade/tlinewidgets.py:370: SyntaxWarning: name 'TRACK_GRAD_STOP3' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/usr/share/pyshared/Flowblade/kftoolmode.py:152: SyntaxWarning: name '_kf_editor' is assigned to before global declaration
  global _kf_editor
/usr/share/pyshared/Flowblade/projectaction.py:761: SyntaxWarning: name 'force_overwrite' is used prior to global declaration
  global force_overwrite, force_proxy
/usr/share/pyshared/Flowblade/projectaction.py:761: SyntaxWarning: name 'force_proxy' is used prior to global declaration
  global force_overwrite, force_proxy
numpy version: 1.15.4
Application version: 2.0.0
OS: Arch Linux
Python 2.7.15 (default, Jan 10 2019, 23:20:52) 
[GCC 8.2.1 20181127]
GTK+ version: 3.24.3
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 91, in <module>
    app.main(modules_path)
  File "/usr/share/pyshared/Flowblade/app.py", line 174, in main
    editorpersistance.load()
  File "/usr/share/pyshared/Flowblade/editorpersistance.py", line 65, in load
    write_file = file(prefs_file_path, "wb")
IOError: [Errno 2] No such file or directory: '/home/user1/.flowblade/prefs'

**Comment by jliljebl** [comment]
Is this pulling from repo the head of development code?

**Comment by DanitiKain** [comment]
source=(git+https://github.com/jliljebl/${_pkgname})

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=flowblade-git

**Comment by jliljebl** [comment]
This is:
- pulling from git unstable development code
- using setup.py to install which is not supported

It is not reasonable to expect this to work constantly. The workaround is to use stable releases.

**Comment by jliljebl** [comment]
Closing as poster got app running I believe.
