### ISSUE TITLE
Chroma Key White Background

### ISSUE THREAD

**Issue by DanitiKain** [jliljebl/flowblade#630]
Currently, we use Cyberlink Powerdirector.

We use white background in our clips. Cyberlink Powerdirector was able to Chroma Key a white background and all we do is put a pure white background in its place. This works very well.

I am testing moving to editing in Linux but cannot find an editor that works with white backgrounds. I tried flowblade today and attempting to use chromakey on white to bring a fulll white background it is place does not work. 

Below is a screenshot with Variance all the way down it has some spots it doesn't get right. 

https://i.imgur.com/q67Ogb0.png

**Comment by jliljebl** [comment]
Maybe Luma Key on white backdround clip with Dissolve Compositor doing the compositing.

In Flowblade alpha filters need a Compositor to work, they only write to alhpa channel Compositors to the combining of images. (see F.A.Q)

Try this:
![screenshot from 2019-02-15 21-57-35](https://user-images.githubusercontent.com/1823444/52881410-272d7e80-316d-11e9-9118-b4fbad604ef2.png)

I just created a new forum for this kind of questions to replace the old Google+ group: https://github.com/jliljebl/flowblade-forum

Issues here need to be related to the development and  programming of the application.
