### ISSUE TITLE
Function request, text gradient in titler

### ISSUE THREAD

**Issue by korotkovaolga** [jliljebl/flowblade#631]
When adding text using titler, besides choosing the text color, I would like to see the gradient settings. Please add a gradient for text if possible.

**Comment by jliljebl** [comment]
Yes, this can be done, Cairo has loads of different gradient functionality.

I think we should do quite a moderate feature set for this: no trigonometry code, no tilted gradients, etc.

* user can turn gradient on/off
* user can select second color to be used for gradient
* user can select gradient width
* user can select Vertical/Horizontal gradient direction

That's probably enough for start.

**Comment by korotkovaolga** [comment]
Thank you, this will be enough.
I am new to not only in the flowblade, but also in video editing, before that I worked in imagination. Now decided to develop further. In general, another question may not be entirely correct, but you mentioned, the flowblade uses the cairo library for work. In imagination there are many transitions in the form of plug-ins that also use cairo, you can even create your own plug-ins and transitions look beautiful. And it will be unnecessary to render them. Maybe look in this direction? http://imagination.sourceforge.net/transitions.html, http://imagination.sourceforge.net/understanding.html

**Comment by jliljebl** [comment]
We do have wipes, use Compositors "Wipe Clip Length" or "Region"

**Comment by jliljebl** [comment]
This is now in repo, will be in 2.8.
