### ISSUE TITLE
Unbound luma files

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#632]
I accidentally discovered that some of the Lumas files available in the "wipes" are missing in "mlttransitions.py", which means they are useless. At first I thought that it was my fault (# 572), but I looked at the source code of version 1.16, there the number of files (wipes) does not correspond to the number of lines (mlttransitions.py). Unbound files are spiral_small.pgm, square.pgm and square2.pgm.

**Comment by smolnp** [comment]
For personal use, at home, I replaced some files and added new ones from openshot, linking them to "mlttransitions.py". Now they are 50. If you want me to send a merge request.
![_2019-02-17_19-28-10](https://user-images.githubusercontent.com/26217756/52915927-efe4dc00-32ea-11e9-88e5-b0a2e5f2e1ac.png)

**Comment by smolnp** [comment]
_("Vertical From Center"):"bi-linear_x.pgm",
                _("Vertical Top to Bottom"):"wipe_top_to_bottom.svg",
                _("Vertical Bottom to Top"):"wipe_bottom_to_top.svg",
                _("Horizontal From Center"):"bi-linear_y.pgm",
                _("Horizontal Left to Right"):"wipe_left_to_right.svg",
                _("Horizontal Right to Left"):"wipe_right_to_left.svg",
                _("Clock Left To Right"):"clock_left_to_right.pgm",
                _("Clock Right to Left"):"clock_right_to_left.pgm",
                _("Clock Symmetric"):"symmetric_clock.pgm",
                _("Stripes Horizontal"):"blinds_in_to_out.pgm",
                _("Stripes Horizontal Big"):"blinds_in_to_out_big.pgm",
                _("Stripes Horizontal Moving"):"blinds_sliding.png",
                _("Stripes Vertical"):"vertical_blinds_in_to_out.pgm",
                _("Stripes Vertical Big"):"vertical_blinds_in_to_out_big.pgm",
                _("Burst"):"burst.pgm",
                _("Circle From In"):"circle_in_to_out.svg",
                _("Circle From Out"):"circle_out_to_in.svg",
                _("Cloud"):"cloud.pgm",
                _("Hatched 1"):"hatched_1.png",
                _("Hatched 2"):"hatched_2.png",
                _("Hourglass"):"hourglass_1.png",
                _("Puddles"):"mountains.png",
                _("Rings"):"radial-bars.pgm",
                _("Rectangle From In"):"rectangle_in_to_out.pgm",
                _("Rectangle From Out"):"rectangle_out_to_in.pgm",
                _("Rectangle Bars"):"square2-bars.pgm",
                _("Sand"):"sand.svg",
                _("Sphere"):"sphere.png",
                _("Spiral Abstract"):"spiral_abstract_1.png",
                _("Spiral"):"spiral.pgm",
                _("Spiral Galaxy"):"spiral2.pgm",
                _("Spiral Big"):"spiral_big.pgm",
                _("Spiral Medium"):"spiral_medium.pgm",
                _("Spots"):"spots.png",
                _("Star"):"star_2.png",
                _("Arch"):"fractal_1.png",
                _("Patches"):"fractal_4.png",
                _("Free Stripes"):"fractal_5.png",
                _("Free Curves"):"fractal_7.png",
                _("Diagonal 1"):"wipe_diagonal_1.png",
                _("Diagonal 2"):"wipe_diagonal_2.png",
                _("Diagonal 3"):"wipe_diagonal_3.png",
                _("Diagonal 4"):"wipe_diagonal_4.png",
                _("Checkerboard"):"checkerboard_small.pgm"}

**Comment by smolnp** [comment]
_("Vertical From Center"):"bi-linear_x.pgm",
                _("Vertical Top to Bottom"):"wipe_top_to_bottom.pgm",
                _("Vertical Bottom to Top"):"wipe_bottom_to_top.pgm",
                _("Horizontal From Center"):"bi-linear_y.pgm",
                _("Horizontal Left to Right"):"wipe_left_to_right.pgm",
                _("Horizontal Right to Left"):"wipe_right_to_left.pgm",
                _("Clock Left To Right"):"clock_left_to_right.pgm",
                _("Clock Right to Left"):"clock_right_to_left.pgm",
                _("Clock Symmetric"):"symmetric_clock.pgm",
                _("Stripes Horizontal"):"blinds_in_to_out.pgm",
                _("Stripes Horizontal Big"):"blinds_in_to_out_big.pgm",
                _("Stripes Horizontal Moving"):"blinds_sliding.pgm",
                _("Stripes Vertical"):"vertical_blinds_in_to_out.pgm",
                _("Stripes Vertical Big"):"vertical_blinds_in_to_out_big.pgm",
                _("Burst"):"burst.pgm",
                _("Circle From In"):"circle_in_to_out.pgm",
                _("Circle From Out"):"circle_out_to_in.pgm",
                _("Cloud"):"cloud.pgm",
                _("Puzzle"):"Puzzle.pgm",
                _("Cross"):"Cross.pgm",
                _("Rays"):"rays.pgm",
                _("Puddles"):"mountains.pgm",
                _("Rings"):"radial-bars.pgm",
                _("Rectangle From In"):"rectangle_in_to_out.pgm",
                _("Rectangle From Out"):"rectangle_out_to_in.pgm",
                _("Rectangle Bars"):"square2-bars.pgm",
                _("Sand"):"sand.pgm",
                _("Sphere"):"sphere.pgm",
                _("Spiral Abstract"):"spiral_abstract_1.pgm",
                _("Spiral"):"spiral.pgm",
                _("Spiral Galaxy"):"spiral2.pgm",
                _("Spiral Big"):"spiral_big.pgm",
                _("Spiral Medium"):"spiral_medium.pgm",
                _("Spots"):"spots.pgm",
                _("Star"):"star_2.pgm",
                _("Arch"):"fractal_1.pgm",
                _("Patches"):"fractal_4.pgm",
                _("Free Stripes"):"fractal_5.pgm",
                _("Free Curves"):"fractal_7.pgm",
                _("Diagonal 1"):"wipe_diagonal_1.pgm",
                _("Diagonal 2"):"wipe_diagonal_2.pgm",
                _("Diagonal 3"):"wipe_diagonal_3.pgm",
                _("Diagonal 4"):"wipe_diagonal_4.pgm",
                _("Deform"):"deform.pgm",
                _("Dunes"):"Dunes.pgm",
                _("Flower"):"flower.pgm",
                _("Torn frame"):"Torn_frame.pgm",
                _("Luminous spiral"):"luminous_spiral.pgm",
                _("Luminous frame"):"luminous_frame.pgm",
                _("Checkerboard"):"checkerboard_small.pgm"}

**Comment by jliljebl** [comment]
Sure, If you do a pull request we can add those. There is a limit how much we can add these, but I think we can add some more for now and consider later what is the upper limit for these.

**Comment by smolnp** [comment]
...but first I wanted to ask you. It is not better to specify the resolution of the frame of the luma file. For example, 16:9 - Diagonal 1, and 4:3 - Horizontal Left to Right. In kdenlive, files with different resolutions of the frame are in different folders and are switched when you select the appropriate profile. But in the flowblade group them in the list. Do not want to do this? Or is it better to leave as is?

**Comment by jliljebl** [comment]
I'll look at what would be the easiest way to do this, I don't want additional GUI but maybe it is easy to always provide user with correct aspect ration wipe image. I'll look at this in a few days.

**Comment by jliljebl** [comment]
After giving this some thought i believe that this should be postponed until after the python 3 port has been done, there are other issues that i believe are more interesting before that.

**Comment by smolnp** [comment]
Ok, I'll do everything then 16: 9 1024x576 (on average, the file will weigh ~ 577 KiB), since 4: 3 is hardly used today.

**Comment by smolnp** [comment]
I apologize, the error was due to my negligence and because I did not recheck for myself. Now everything is fixed and works.
![screenshot_20190223_165344](https://user-images.githubusercontent.com/26217756/53287449-4770c500-378d-11e9-9203-35135555c19f.png)

**Comment by smolnp** [comment]
https://github.com/smolnp/flowblade/commit/675634aaa37dbfc0862d105006be89f3a791c673

**Comment by jliljebl** [comment]
Ok, you will need to do another pull request, I don't think you can update
the previous one because it was already merged.
