### ISSUE TITLE
"Clip Filters Stack" confused filter menu buttons

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#641]
Using the "Clip Filters Stack" context menu, select "Move Up". Assuming the filter moves up (1 screenshot), but in fact the filter has been moved Down (2 screenshot).

1 screenshot
![Снимок экрана от 2019-03-13 23-43-31](https://user-images.githubusercontent.com/26217756/54314063-b783a580-45eb-11e9-977a-08ecea3b560a.png)

2 screenshot
![Снимок экрана от 2019-03-13 23-48-05](https://user-images.githubusercontent.com/26217756/54314066-b9e5ff80-45eb-11e9-9567-b2ce1c51e426.png)

**Comment by jliljebl** [comment]
There indeed seems to be some problems, I have created a regression a some point.

**Comment by jliljebl** [comment]
This is fixed now, will work in 2.2. No idea how this has reached production, very silly bug.
