### ISSUE TITLE
Оffer to add a Wiki section.

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#643]
There was an idea, but I do not know how much it will work. It may make sense to include a Wiki section, and then some users might want to take part in writing additional documentation for Flowblade. Where the most useful and relevant articles can be included in the official manual. Also there is the possibility of placing with ease thematic video tutorials and illustrations. As an example, the Olive video editor repository (see screenshots below).
![Снимок экрана_2019-03-27_18-17-33](https://user-images.githubusercontent.com/26217756/55089443-78128a00-50be-11e9-8b97-6fa3b2874279.png)

**Comment by jliljebl** [comment]
Alright, seems like I good idea. Flowblade repository does  not seem to have the wiki tab available as described here: https://help.github.com/en/articles/adding-or-editing-wiki-pages#adding-wiki-pages

I'll look at the Settings to see if its there to be added.

**Comment by jliljebl** [comment]
Yes, Settings had a checkbox for this so now it is there. You can try to do a pull request on adding text there, but if that is not available you can send me the text for the first version of it in comments here and I can copy paste it.

I'll add one wiki page for testing and we can keep this issues open unttil we have the first version done.

**Comment by jliljebl** [comment]
Or maybe you can edit it without me doing anything it is a bit difficult to say as I have the admin rights.

**Comment by jliljebl** [comment]
There was another checkbox to make it public, now you can edit directly. I'll leave it open, we probably won't get any malicious edits, but if we do, we need to consider making it private again.

**Comment by smolnp** [comment]
There are no "edit" and "nev page" buttons
![Снимок экрана_2019-03-29_17-42-59](https://user-images.githubusercontent.com/26217756/55240713-8c838d80-524a-11e9-9935-dadb4251fd37.png)

**Comment by jliljebl** [comment]
I read the checkbox wrong I think, it needs to checked *off* for public wiki. How about now, can you edit it now?

**Comment by smolnp** [comment]
Yes, now everything is okay. Tomorrow I will inform everyone I can that the wiki is open for editing.

**Comment by jliljebl** [comment]
This is now in.
