### ISSUE TITLE
Playback not working when "cut" tool selected

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#647]
What the description says. This one should be fairly easy to replicate:

1. select the cut tool
2. hit space bar or press the play button
3. nothing happens

I'm also getting the following error messages in terminal:

`[h264 @ 0x7f3a12e70980] mmco: unref short failure`
`[h264 @ 0x7f3a12e70980] mmco: unref short failure`

**Comment by jliljebl** [comment]
Confirmed and fixed, probably should cleanup the related code a bit.
