### ISSUE TITLE
UI Elements Too Bright

### ISSUE THREAD

**Issue by Chadt54** [jliljebl/flowblade#659]
Please include the following information.
1) Flowblade version (Help->About):
2.0.0
2) MLT version (Help->Runtime Environment):
6.13.0
3) Your distribution (Ubuntu, Debian, Mint etc.):
CentOS 7
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

I'm using the flatpak

The UI elements are too bright any idea why?:

![image](https://user-images.githubusercontent.com/1322965/57206676-ce021800-7002-11e9-8727-69c308dc43d5.png)

**Comment by smolnp** [comment]
Select the options that are more suited to your OS theme.
![Снимок экрана_2019-05-06_17-51-51](https://user-images.githubusercontent.com/26217756/57233799-010ad280-7028-11e9-8d4d-6c71bae62f0c.png)

**Comment by jliljebl** [comment]
Confirmed, I've seen a few times. For some reason buttons colors do not always get overwritten from the theme .css.

**Comment by jliljebl** [comment]
Fixed in repo, will be in 2.2.
