### ISSUE TITLE
Minor bug: Curves not applied when parameters are loaded from file

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#661]
Please include the following information.
1) Flowblade version (Help->About): 2.0.0 (latest git clone)
2) MLT version (Help->Runtime Environment): 6.12.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Debian 10 (Buster)
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

1. Add the Curves effect to a clip
2. Create some fancy curve
3. Click the Effects submenu > Save Effect Values
4. Add the Curves effect to another clip
5. Click the Effects submenu > Load Effect Values
6. Curves are loaded properly but not applied right away to the image
7. Try moving any curve point and it's got applied as should be

**Comment by jliljebl** [comment]
Confirmed. Not sure why we are getting this but there is probably quick fix.

**Comment by jliljebl** [comment]
Fixed, the update method just wasn't called and on other filters it probably gets updated anyway.
