### ISSUE TITLE
A couple of minor suggestions

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#663]
Please include the following information.
1) Flowblade version (Help->About): 2.0.0
2) MLT version (Help->Runtime Environment): 6.12.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Debian 10 (Buster)
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

1. I think the buttons "Add Fade In/Out" and their durations should be swapped or, better, a simple text "Add Fade In/Out" added instead before duration, and the "Add" button after that. This way it would be less confusing and more in the style of other programs.
2. How about clip markers? I mean markers _inside_ a clip, signifying certain precise moments (e.g. flash of light, lowering of a foot, etc.), which could then be used to synchronize it with some precise moment in audio. It is very useful for making music videos.

**Comment by dvdlvr** [comment]
I would also like persistent clip markers inside the clip. Preferably 
not only on the timeline, but also directly in the clip monitor.

**Comment by timbze** [comment]
Another feature suggestion:
When hovering over timeline marker (and clip marker), pop up tool-tip with the marker name.

**Comment by jliljebl** [comment]
@Efenstor 
> 1. I think the buttons "Add Fade In/Out"...

I do agree that the current approach is a bit idiosyncratic to this app and would be improved by something that is more generic or common to all media apps. I'll add a Label for this, its just a question of looking through a selection of media apps and seeing what they do.

@Efenstor @dvdlvr 
> 2.How about clip markers? 

So, we do have these. Right click on clip, select "Markers", "Add Clip Marker at Playhead position", give name, press "Add Marker"

Are you talking about *Media Item* markers that would get added as clip markers when clips are created? Doable, but we 100% can't add a monitor button just for these.

If we ever get around to clonining *the drag on the media item* feature from Final Cut X (actually probably quite easy), see at 6.17 here:
https://www.youtube.com/watch?v=4UET7QptHtc 
then this could be one of the thing added at that time

We also have Range Log feature that is of some relevance here. So no immediate action on this I think but maybe later.

Also related: https://github.com/jliljebl/flowblade/issues/651

@timbze 
> When hovering over timeline marker (and clip marker), pop up tool-tip with the marker name.

This is a bit of computation overhead on every mouse move action and will probably not get attention from me but if we get patch maybe then. Timeline markers are much easier to do but then user would expect to have this clip markers too and that would get a bit unpleasant to program.

**Comment by timbze** [comment]
> This is a bit of computation overhead on every mouse move action and will probably not get attention from me but if we get patch maybe then. Timeline markers are much easier to do but then user would expect to have this clip markers too and that would get a bit unpleasant to program.

Maybe showing name on marker click would be easier to do, that would be good too.

**Comment by jliljebl** [comment]
@timbze  Ok, on click this is in the realm of possible. 

I'll give it a go some time, but I have to make sure that user does not expect them to be selectable/dragabble, markers cannot be elevated into category of fully intractable GUI objects.

**Comment by Efenstor** [comment]
> So, we do have these. Right click on clip, select "Markers", "Add Clip Marker at Playhead position", give name, press "Add Marker"

Oops, I looked high and low and couldn't find how to do it. I got used to that the clip markers are made from the clip monitor, not from the project timeline. Why not to add a couple of buttons (add marker and remove marker) to the clip monitor? Or there's a technical difficulty to that? I mean to adding a clip marker when clip is not yet added to the timeline? Adding a marker is an action which usually comes together with trimming the original clip around the marker. Also, displaying the clip markers in the clip timeline (the one below the preview) is also quite useful to navigate by them quickly. Additional button for jumping forwards and backwards by the markers would be even better, of course.

**Comment by jliljebl** [comment]
>  I got used to that the clip markers are made from the clip monitor, not from the project timeline

Which app? I can look there how its done there for reference. 

> Why not to add a couple of buttons (add marker and remove marker) to the clip monitor?

I don't think the feature is high impact enough to merit a button as big as Play button, sort of catgegory error. With current design timeline has its own Markers menu and clips have markers inside menu too 

> Also, displaying the clip markers in the clip timeline (the one below the preview) is also quite useful to navigate by them quickly. 

Well, I kind of agree here. (we are calling the thing Position Bar)

I made a mock-up that shows I'n my view
 * we can add another menu button under monitor for markers specially
 * markers need to be displayed under Position Bar) which necessitates creating a new GUI component and some layout work.

So yes, this can be done but atm. I have to say I feel I have a lot of better time sinks with the project.

But we'll leave this open and revisit later, there could be additional value to be had here.

![monitormarkers](https://user-images.githubusercontent.com/1823444/58111984-2e947600-7bfb-11e9-8e2b-f8e8f811e589.png)

**Comment by Efenstor** [comment]
The mockup looks fine :) Take a look how it's made in Sony Vegas and Adobe Premiere. Although it's been years since I used them (since moved to Linux) I can still remember how incredibly convenient they were.

**Comment by jliljebl** [comment]
The position bar now shows timeline markers. We now have the fade buttons update and position bar markers so I'm closing this as *feature added*. I will still add the timeline markers drop down menu on the right when I get around to it.

**Comment by jliljebl** [comment]
THe timeline markers menu didn't look good or feel in place when I tried to add it on the right side under monitor so that addition won't be coming. One additional thing I did was to make markers yellow for dark and custom themes and they do pop out better now.
