### ISSUE TITLE
[features] Batch Render

### ISSUE THREAD

**Issue by parti-zanu** [jliljebl/flowblade#665]
Please include the following information.
1) Flowblade version (Help->About): 2.0.0
2) MLT version (Help->Runtime Environment): 6.16.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Linux Mint 19 Tara

New user here, some thoughts while using Batch Render:

1) drag&drop should re-arrange items in queue
2) a way to import / export the queue content
3) right click-> Render Properties: doesn't show if the project will render with original media or proxies
4) right click-> Render Properties: doesn't show what user args are in use (if any)
5) would be nice for MLT to output to terminal _all_ the arguments it passes to ffmpeg just before any rendering starts

Hope this helps. **Thank you** very much for your work & for this free product.

**Comment by jliljebl** [comment]
Thanks for the nice feedback.

The points you made all seem to be small improvements, so I believe I will implement at least most of them in the next few cycles, they look quite easy to do.

**Comment by jliljebl** [comment]
I only did item 3) right click-> Render Properties: doesn't show if the project will render with original media or proxies.

The rest are going *wontfix*, just can't see them as something I'm willing spend energy even though they could be small imrovements.
