### ISSUE TITLE
Clip length maximum size capped at 15000 frames

### ISSUE THREAD

**Issue by parti-zanu** [jliljebl/flowblade#671]
Please include the following information.
1) Flowblade version (Help->About): 2.0.0
2) MLT version (Help->Runtime Environment): 6.16.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Linux Mint 19 Tara

Is the still image clip length hardcoded with a maximum length of 15000 frames?

1) insert a still image in V2
2) right click -> Edit -> Set Clip Length
3) in the "Frames" field, any number above 15000 is rolled back to 15000

Is this by design?

**Comment by jliljebl** [comment]
This is MLT feature. There may have been some development on this but I'm not looking to change this in next several releases.

Closing as *wontfix* for now but there may eventually be some developments on this.
