### ISSUE TITLE
[Feature Request] "Import Media Folders as Bins"

### ISSUE THREAD

**Issue by davej453** [jliljebl/flowblade#674]
Please include the following information.
1) Flowblade version (Help->About): 2.0.0
2) MLT version (Help->Runtime Environment): 6.14.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Manjaro

This would probably need to be some sort or recursive search through an imported folder to pull the compatible media files and arrange them in a project bin. I have looked for a way to do this in flowblade but to no avail, so forgive me if I'm missing something obvious here.

**Comment by jliljebl** [comment]
This seems like something that could be a somewhat useful additional feature since right now all media needs to be imported by selecting files in a single folder and no recursive automatic import is available. We will look at this later and try think a design that would help with this use case.

**Comment by jliljebl** [comment]
I looked around a bit.

I think the Avid feature of searching recursively for *file types* from given folder and making the result set available as import list is the most interesting one. 

We don't want to just blindly import every media file recursively, we want finer grain control and a confirmation from user before starting import as recursive search can result in import set of unlimited size.

So we'll add a dialog for selecting import folder, setting searched file type and panel to show the resulting set of files to import. This is a medium large feature from required work point of view, might take a few cycles for this to land.

**Comment by davej453** [comment]
I think this would be a very useful feature and a great way to improve workflow. I do think that adding some way to allow drag and drop support for a singular type media folder would be valuable. For example, many cameras record metadata and clips together in a directory. To be able to add the entire camera 'card' folder and have flowblade import the media clips (and perhaps even the metadata) would likewise be a boon to many workflows.

**Comment by jliljebl** [comment]
This is now in, will be in 2.8.
