### ISSUE TITLE
About "SEQUENCE".

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#675]
The message was read by me in one of the social networks:
"What is this clear. It is not clear why.
For example, in the wonderful VSDC editor there is an analogue of the Sequence and it is called Scene. Just like a sequence, a scene is a collection of media files, effects, transitions, etc. When rendering the Project, the Scenes are rendered in succession forming a single video. Scenes can be excluded from the final video, you can change the order of scenes in the final video.
The sequences are not rendered in the overall video. Sense then from them?
That I will do two separate Projects, that I will do two sequences in one Project - at the output I will receive two separate files.
Or did I not understand something?!"

**Comment by jliljebl** [comment]
This does not describe an Issue, please repost here, 

https://github.com/jliljebl/flowblade-forum

i created that repository for the purpose of this kind of discussion so that we can always link to some post if same questions come back repeatedly.
