### ISSUE TITLE
Unable to install flowblade in arch

### ISSUE THREAD

**Issue by warlock20** [jliljebl/flowblade#679]
Please include the following information.
1) Flowblade version (Help->About): 
Version 2.0

2) MLT version (Help->Runtime Environment):
mlt-python2-bindings-6.14.0-2

3) Your distribution (Ubuntu, Debian, Mint etc.):
Arch

4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
Tried to install flowblade by clone from the git repository and makepkg to install.

Following is the error message:

> curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
==> ERROR: Failure while downloading https://github.com/jliljebl/flowblade/archive/v2.0.tar.gz
    Aborting...

**Comment by jliljebl** [comment]
The exact link you posted works here. Maybe the issue was temporary you should retry to see if issue has gone away.

**Comment by yaymukund** [comment]
For what it's worth, I installed flowblade on arch less than 5 days ago, no problem :)

**Comment by alfredopalhares** [comment]
I did intall flowblade recently too.

**Comment by jliljebl** [comment]
This is very likely some glitch closing.
