### ISSUE TITLE
Feature request: More playback speeds (e.g. 1.5x, 2x)

### ISSUE THREAD

**Issue by timbze** [jliljebl/flowblade#680]
1) Flowblade version (Help->About): 2.0.0
2) MLT version (Help->Runtime Environment): 6.12.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.04

When playing my timeline, I can press L for "Forward faster" option and it jumps to playback x3. That is a little too fast to really be able to understand the words in a speech, etc.
Having the options for at least 2x, and maybe also 1.5x would be very helpful.

**Comment by dvdlvr** [comment]
Hi, This is available in Preferences. You can set your own playback speed on the following key accellerators: Shift, Control and Caps Lock. Press the right arrow key and any combo of the accellerators and the speed will be combined. Reverse keyback works the same way with the left arrow key. Example: Set shift to 2, Control to 3 and Caps Lock to 3.If you press Caps Lock AND Shift AND Control on playback it will set speed to 3 * 2 * 3 = 18 times the normal speed. I can't remember if half fractions are allowed, but you can try. The max speed is limited by your system capabilities. So you have to experiment a bit on what is comfortable for you. Any combo is possible to vary the speed. The 2/3/3 combo allows you to do x2, x3, x6, x9 and x18 speeds. 2/3/4 would allow x2, x3, x4, x6, x8, x24. Etc. Sent from my Huawei tablet-------- Original Message --------Subject: [jliljebl/flowblade] Feature request: More playback speeds (e.g. 1.5x, 2x) (#680)From: timbze To: jliljebl/flowblade CC: Subscribed Flowblade version (Help->About): 2.0.0MLT version (Help->Runtime Environment): 6.12.0Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.04
When playing my timeline, I can press L for "Forward faster" option and it jumps to playback x3. That is a little too fast to really be able to understand the words in a speech, etc.
Having the options for at least 2x, and maybe also 1.5x would be very helpful.

**Comment by jliljebl** [comment]
@timbze  I agree that we could have a speed step between 1.0x and 3.0x for **JKL** scrubbing, I'll try 1.7x at first and if that seems good we'll go with that. Next release 2.2 is feature locked but this feature will easily make in for 2.4.

@dvdlvr you are right, setting preference will give the speed that is looked for here with arrow keys and Shift, Control and Caps Lock.  **JKL** scrubbing presents a bit different usage model, similar to using a jog to shuttle on video recorders of old.

**Comment by timbze** [comment]
@dvdlvr @jliljebl Thank you both very much! I think I saw the preference settings but wasn't able to get it to work (think I didn't know how to use it, i.e. shift etc with **arrow key**)

I will try doing this again soon when I get a chance. But I'm sure I'll be able to use it now for what I need.

**Comment by dvdlvr** [comment]
@jliljebl, for info, I will try to implement real Jog Shuttle support once we get to python3. There is no proper HID USB support in python2. It should be easy to implement with python3. I guess it could be easy to adapt the current system for finer control by allowing fractions in the settings. Also, in python3 there is better control of dead keys, like detecting left or right shift and left or right ctrl, so we could do a lot more with that. Sent from my Huawei tablet-------- Original Message --------Subject: Re: [jliljebl/flowblade] Feature request: More playback speeds (e.g. 1.5x, 2x) (#680)From: jliljebl To: jliljebl/flowblade CC: dvdlvr ,Mention @timbze  I agree that we could have a speed step between 1.0x and 3.0x for JKL scrubbing, I'll try 1.7x at first and if that seems good we'll go with that. Next release 2.2 is feature locked but this feature will easily make in for 2.4.
@dvdlvr you are right, setting preference will give the speed that is looked for here with arrow keys and Shift, Control and Caps Lock.  JKL scrubbing presents a bit different usage model, similar to using a jog to shuttle on video recorders of old.

**Comment by jliljebl** [comment]
@dvdlvr Yeah, the current JKL code in monitorevent.py can probably be adjusted for shuttle control.

**Comment by timbze** [comment]
Does the Arrow key with shift etc only work with holding down the keys continually? I was looking for a way to set it to play at 2x, but it doesn't keep on playing when I release the keys, so I guess that still is not really what I'm looking for unless I just don't get it yet...

**Comment by dvdlvr** [comment]
You get it. You need to keep the keys down. I get what you mean, now. I can take a look at that feature. Sent from my Huawei tablet-------- Original Message --------Subject: Re: [jliljebl/flowblade] Feature request: More playback speeds (e.g. 1.5x, 2x) (#680)From: timbze To: jliljebl/flowblade CC: dvdlvr ,Mention Does the Arrow key with shift etc only work with holding down the keys continually? I was looking for a way to set it to play at 2x, but it doesn't keep on playing when I release the keys, so I guess that still is not really what I'm looking for unless I just don't get it yet...

**Comment by jliljebl** [comment]
I added new speed 1.8 and fixed some GUI issues.
