### ISSUE TITLE
Header bar option for better integration into Gnome desktop.

### ISSUE THREAD

**Issue by ripefig** [jliljebl/flowblade#681]
Might it be possible to use a headerbar design when running on Gnome or elementary?

I know that Gnome HIG, which was created for barebones apps, offers no replacement for the menubar. This of course makes it difficult or impossible to port complex programs to the new design. However, if a standard substitute for the menubar is devised then it becomes feasible.

Here's an idea I came up with for a similarly menu-rich program: export the menus to a searchable command palette. https://github.com/Qalculate/qalculate-gtk/issues/95
I think in many ways this would be even better than a menubar, which hogs space even when it's not used and is difficult to navigate.

Perhaps you could could consult with the Gnome design team, as they've stated that they would work on redesigns with developers. Obviously if they suggest that everything be custom-redesigned from scratch then that's a non-starter. But if they help design a drop-in replacement for the menubar then this could help fast-track many apps to the new CSD design, including your own.

**Comment by jliljebl** [comment]
Unfortunately closing this as *wontfix.*

I really believe that the traditional application menu is the superior UX for complex editor applications like Flowblade, and being 100% compliant with Gnome HIG isn't a project goal, even if we are following it loosely with margins sizes etc.

I actually mostly like headerbars, I think they look quite nice in most applications, but in my view Flowblade cannot utilize them successfully .

**Comment by ripefig** [comment]
@jliljebl you don't think the menu hierarchy could be moved to a popup palette (such as the one in my mockup)? the advantages would be allowing search, decluttering the main interface, and having a less cramped interface than a cascading menu.

Then you would just need a single button in the headerbar and alt accelerator that brings up the popup

Ofc I completely understand if you want to stick to traditional menubars, I am just trying trying to say that, since you "mostly like headerbars", a relatively non-intrusive implementation of headerbars is possible.

**Comment by jliljebl** [comment]
I've come to firmly believe that it is better provide users with UI patterns that they are familiar with as much as possible. Palo Alto paradigm interfaces have been worked on 40+ years and in my view the optimal solutions have been discovered.

We *can* have Flowblade provide headerbar interface under some quite strict conditions.

1. The code and resources need to be contributed.
2. The provided solution needs to be of high quality both visually and from code point of view.
3. Headerbars UI has to be optional, most users will prefer traditional application menu.
4. Earliest version that I could accept this would be 2.6, for next few releases we have other plans that would affected by inclusion of large amount new UI code.

So if someone does this and does it well I can accept a pull request.

**Comment by MuhammadMouradG** [comment]
The discussion at  https://github.com/beeware/toga/issues/874 may help.
