### ISSUE TITLE
Cannot change aspect ratio of project profile or render

### ISSUE THREAD

**Issue by bergamote** [jliljebl/flowblade#682]
I've been filming in anamorphic 2.35:1 aspect ratio and cannot find a way to edit the footage with flowblade without getting black bars added at the top and bottom of my shots.
Is there a way to change the aspect ratio to anything other than the available presets: 16:9, 4:3 or 1:1?

flowblade v2.0
mlt v6.10
ubuntu

**Comment by jliljebl** [comment]
HI, yes:

Select "Edit"-> "Profiles Manager" and use the "Create user Profile" panel to create a profile with dimensions of your choosing by setting *Width, Height* and *Display aspext num, Display Aspect den.* values.

Use *Load Profile values* to get starting values from some Profile you think would be good.

Save your custom profile and create a new Project.

**Comment by bergamote** [comment]
Excellent, thank you!!
