### ISSUE TITLE
“Titler” problem on small displays

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#688]
Please include the following information.
1) Flowblade version (Help->About): 2.2
2) MLT version (Help->Runtime Environment): 6.16.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Rosa linux xfce

The window of the “Titler” tool on a laptop (monitor resolution 1366x768) looks very large, is located beyond the edge of the system control panel and does not decrease in size:

![DeepinScreenshot_20190823201029](https://user-images.githubusercontent.com/26217756/63610433-1fe6a200-c5e2-11e9-8c10-572041caee55.png)

**Comment by jliljebl** [comment]
Thanks, confirmed...I just keep effin this up, it's so marginal that every time I touch it it goes bad. And last time did something I though I checked it.

**Comment by jliljebl** [comment]
Ok, back in working order.
