### ISSUE TITLE
Preferences / General / Autosave

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#690]
Please include the following information.
1) Flowblade version (Help->About): 2.2.0
2) MLT version (Help->Runtime Environment): 6.6.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
1) Open Preferences
2) Change Autosave time to 5 minutes.
3) Close Preferences and Flowblade
4) Open Flowblade and Preferences
5) Autosave time is set to 1min. 

This may just be a display issue - I didn't check that, but it should be set to whatever value was saved when you reopen the preferences.

I can take a further look at that and submit a pull request.

**Comment by jliljebl** [comment]
Ok, this may be some actual problem.

**Comment by jliljebl** [comment]
I got around to testing this finally and #692 looks to have fixed, everything nicely, thanks.
