### ISSUE TITLE
Feature request: Give user possibility to increase button size

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#694]
Please include the following information.
1) Flowblade version (Help->About): 2.2.0
2) MLT version (Help->Runtime Environment): 6.6.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
When, like me, you have a 4K display the buttons are very very small and it takes a lot of concentration to find a place to be able to click on them.

I would like to add a Button size preference (e.g. 1 (Default, current size), 2, 3) that will make the buttons bigger.

I am happy to do this myself.

See size of edit buttons at full desktop in this image.
![Standard](https://user-images.githubusercontent.com/7942463/63939154-e2ad6480-ca66-11e9-988c-47f15c85e6e9.png)
Proposed x2 size at full desktop  (The timeline buttons have not yet been altered here).
![TwiceStandard](https://user-images.githubusercontent.com/7942463/63939155-e345fb00-ca66-11e9-8c88-79e387348a61.png)

**Comment by jliljebl** [comment]
Ok, I don't have HiDPI screen to test,  but for Issue you described I want the buttons to just scale automatically with the same scale factor user has set for the application.

So we need to detect if user has set scaling to 2x, and if so the draw buttons double sized.

**Comment by dvdlvr** [comment]
Alright. I'll get on it. Sent from my Huawei tablet-------- Original Message --------Subject: Re: [jliljebl/flowblade] Feature request: Give user possibility to increase button size (#694)From: jliljebl To: jliljebl/flowblade CC: dvdlvr ,Author Ok, I don't have HiDPI screen to test,  but for Issue you described I want the buttons to just scale automatically with the same scale factor user has set for the application.
So we need to detect if user has set scaling to 2x, and if so the draw buttons double sized.

**Comment by dvdlvr** [comment]
Pull request submitted
#696

**Comment by jliljebl** [comment]
Pull request merged.
