### ISSUE TITLE
Failed render of slowmotion/speedup videos

### ISSUE THREAD

**Issue by samytichadou** [jliljebl/flowblade#695]
Hi, and first of all thanks for this nice piece of software !
I had an issue when trying to change speed from clips from kazam (screenrecording). Video is only white (blank) no matter what speed and encoding used...

Flowblade 2.2.0
MLT 6.12.0
Ubuntu 19.04

To reproduce :
Import a video clip in a new project (mine was from kazam, a h264 mp4 15 fps)
Try to render a slowmotion/speedup out of it.

Cheers !

**Comment by jliljebl** [comment]
Are you having the same problemt when rendering  slowmotion / speedup clips from *ALL* different kinds of clips or does the problem occur only with *SOME* clips?

**Comment by samytichadou** [comment]
Yep sorry I didn't mention it, it is happening randomly on some video clips only, some works perfectly. if you want I can send you one which causes this bug, I'll try to find one!

**Comment by jliljebl** [comment]
Yes, if you can make available example file that causes problem that would help a lot.

**Comment by samytichadou** [comment]
Hi, here's a link to a buggy project, with original rush, and resulting file (speed up video) which appears blank. Cheers
[https://my.pcloud.com/publink/show?code=XZclKVkZHbQ6gRSIVx4m5wheuK98fQ46eWJk](url)

**Comment by jliljebl** [comment]
Thanks, downloaded it. I'm currently working on Python 3 conversion, I will post additional info once I have something.

**Comment by samytichadou** [comment]
thanks for your quick answer ! Ok let me know if there is a workaround, cheers !

**Comment by dvdlvr** [comment]
Hi, can you give some more info on what do you exactly?
I just tried it with your file on Flowblade 2.2 and it worked fine.
I used the following settings
![Screenshot from 2019-09-30 12-50-35](https://user-images.githubusercontent.com/7942463/65872496-f529ff00-e380-11e9-9d1a-c10fd73d7b59.png)

**Comment by dvdlvr** [comment]
BTW: I noticed the source file is 15 fps and your project has 25 fps. Could that be one of the common factors with the troublesome files?

**Comment by samytichadou** [comment]
Yeah it could have been the common factors ! i didn't check with some files with proper project framerate, i'll try it in the week when i got some spare time and come back to you ! 
About what i did to get this bug, seems to be exactly the same as you. just open the project, import a file from kazam screenshot software, and render slowmotion... I'll retry that asap and get back to you ! 
Thanks for feedback on this matter, cheers !

**Comment by jliljebl** [comment]
I found a file that reported s 17.5 fps on totem but that worked just fine. 

@samytichadou Maybe if we can get the file that causes the issue made available for download we could try to advance with this somehow.

**Comment by jliljebl** [comment]
There is no forward movement on this, closing. Anyone can reopen similar issues with new data and example files.
