### ISSUE TITLE
Python3 - Preferences window doesn't show spin values

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#700]
Please include the following information.
1) Flowblade version (Help->About): 2.2 - upgrade to Python3
2) MLT version (Help->Runtime Environment): 6.17.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
In the Preferences window, it looks like the value (1st column) passed to Gtk.Adjustment in the python3 version is not working properly. The spin adjustments end up with a default of 1.
The internal value seems to be ok and you can change it and the new value will be saved, just not displayed.
Instead you seem to need to pass an explicit spin_adl.set_value(x)
I have GTK Version 3.22.30.

In the Control key I added the set_value code to the source to show the difference.
![Screenshot from 2019-09-12 16-34-14](https://user-images.githubusercontent.com/7942463/64802635-6731d400-d58b-11e9-9673-24b2576afe73.png)

Not sure if this is only on my system so I am missing something or if it's a general problem.
If it's a general problem I'm happy to make a fix for it, but it does seem weird.

**Comment by dvdlvr** [comment]
I tried both. Restart my computer didn't do anything.
Removing the prefs didn't work either (It reset me to dark theme and asked for the default workflow, so the removing worked - but all the spin values still showed 0).

I'll investigate further.

**Comment by dvdlvr** [comment]
Ok, when I run this on one system using python3.7 I get below warning and it works fine.
When I run it on another system using python3.7 I also get the warning, but it doesn't actually work (i.e. still shows 0 instead of 3). So this is probably a setup/config problem on that system.

I don't get the warning when I run it on python3.6 AND it doesn't work properly.
I don't get the warning on python2.7 AND it WORKS as intended.

_PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "value, lower, upper, step_increment" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.spin_adj = Gtk.Adjustment(3, 1, 10, 1)_

When I add the keywords, giving the following:
self.spin_adj = Gtk.Adjustment(value=3, lower=1, upper=10, step_incr=1)
it works on all versions of python.

I think it would be wise to start adapting all the GObject calls that issue the warning to include keywords, since using positional is going to be deprecated beyond python3 and keywords work fine in python2.

I'm happy to start working on this (After I fix my python3 environment).

Out of interest, what python3 version are you using?

**Comment by jliljebl** [comment]
Ok, that explains that, thanks for figuring it out. A bit annoying GTK change but there we go.

 I'm on Python 3.7.3, so this working here is consistent with your observations.

Yes, I'll gladly take patches for this, there can be many users like you out there on 3.6.
