### ISSUE TITLE
Load MLT as clip or timeline

### ISSUE THREAD

**Issue by eliotb** [jliljebl/flowblade#703]
Flowblade 2.2.0, MLT 6.12.0, Debian 10

This is a new feature request.

Would it now be possible to allow load any* MLT timeline as a clip, or as a new sequence?
This is currently  disabled because:
```
projectaction.py line 966
# We're disallowing opening .mlt or .xml files as media beause MLTs behaviour of overwriten project profile properties
# when opening MLT XML files as nedia
# Underlying reason: https://github.com/mltframework/mlt/issues/212
```
Given a couple of features of current flowblade it seems possible:
1. Export as MLT
2. Create compound clip (as hidden MLT)

* maybe not _any_ MLT file.
E.g. limited to MLT files with the same profile settings as the current project?, or even limited to MLT files saved by flowblade MLT export feature to begin with.

**Comment by jliljebl** [comment]
We could allow the importing MLT XML files that have the exactly the same Profile as the Project they are being imported into.

It might also be possible to just manipulate the XML of the imported file to force it to be the same as the current Project.

I'll look around a bit to asses how easily we can do this, but if we have some relatively workable way of doing this, we should probably do it,

**Comment by jliljebl** [comment]
We now allow loading MLT XML files with exactly matching profiles to be loaded.  I can accept patches that go further then this, but right now I'm marking this as *feature added*.
