### ISSUE TITLE
Rendered Quartersize Proxy Wrong Size

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#704]
Using Flowblade 2.2 (MLT 6.6.0) on xubuntu 18.04

When importing a 4K clip, which is reported by ffprobe as:
`Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 3840x2160, 99929 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
`
Then selecting quarter size proxies, and having flowblade render a proxy, which results in:

`Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, unknown/unknown/iec61966-2-1), 960x536 [SAR 1:1 DAR 120:67], 3021 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)`

I would have expected the proxy to be 960x540 not 960x536, and the resulting video has a 4px black edge both on the left and right encoded into the proxy.

This kinda makes sense given 536/9*16 ~= 952 and (960-952)/2=4

**Comment by jliljebl** [comment]
Confirmed. Most codecs only accept dimensions divisible by 8 and the code we have that makes sure we get this for proxies fails here.

3840/960 = 4
2160/536 = 4,029850746

This happens because 540 is not divisible by 8

 540 mod 8 = 4

I think the best fix is just to hard code values for 4K, 2K and 720p frames sizes. I don't know how to solve the math correctly, these are not polynomial equations systems I think because of the *mod 8*.

**Comment by dvdlvr** [comment]
How about coding exceptions for the codecs and sizes that accept it?
So if 4K is ok with non mod 8 we calculate it without it. Anything not in the exception list is calculated with mod8. That way we avoid hardcoding.
We could make a list of exceptions in a file read at the start of the calculation, so all we have to do is add an exception to the file if we need to - no code change required in that case.

We could, for example, make a file like this:
*index*:*definition*
Where *index* would indicate if we test on codec of resolution and *definition* gives that resolution or codec name.
C:mp4
C:h.264
R:3840x2160
etc.

**Comment by pmjdebruijn** [comment]
Are we really sure that mod8 limit is still valid? The only limit I've run into is mod2 (using ffmpeg at least).

Also, I don't really think half/quarter resolution makes much sense to begin with, specific hardcoded resolution make more sense to me. Given it's my editing rig that determines which resolution of video it can handle, not the input video resolution.

So maybe replace half/quarter by 360p, 720p, 1440p as proxy resolutions, as those will satisfy the mod8 rule if that really relevant.

**Comment by jliljebl** [comment]
Not sure yet on the approach here, but I do want to keep it as simple as possible, probably with some level of hard coding.

**Comment by pmjdebruijn** [comment]
My theory of only needing an alignment of 2 as opposed 8 seems to hold true: #717

**Comment by pmjdebruijn** [comment]
As far as I'm concerned this issues has been resolved by the merging of #717

**Comment by jliljebl** [comment]
Yes, forgot to close.this.
