### ISSUE TITLE
Titler: Text Shadow Blur

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#706]
It would be really nice, if it were possible to apply a configurable (in px) blur to the shadow of text in the titler tool.

**Comment by jliljebl** [comment]
Agreed, this has always been on my back-of-the-mind to do list, but since we can't get blur trivially from Cairo this just hasn't been done.

**Comment by pmjdebruijn** [comment]
Apparently there is an example available:

[(https://www.cairographics.org/cookbook/blur.c/)]

And:

[http://stevehanov.ca/blog/?id=53]

**Comment by jliljebl** [comment]
Approach on your links won't work on Python app, we would get 2M FFI calls for every HD frame. We need to use numpy or something, here is example more like what we need:
https://stackoverflow.com/questions/29920114/how-to-gauss-filter-blur-a-floating-point-numpy-array

**Comment by pmjdebruijn** [comment]
Ah of course... But aren't the titles prerendered overlays?

**Comment by jliljebl** [comment]
This is now in, will be in 2.8. Somehow we're still getting different amounts of blur in preview and out but that is because we are not using right scale for preview and we can fix this before release.
