### ISSUE TITLE
Can I create subtitles in batches ?

### ISSUE THREAD

**Issue by yichuang-zh** [jliljebl/flowblade#718]
Hi,
I can only edit one subtitle at a time in the menu **tools > titler**. But there are a lot of subtitles to edit in the project, and they are all the same parameters, just the text is different.
I did not found Batch processing method in the menu, is there something that I have missed?

Please include the following information.
1) Flowblade version (Help->About): 2.2.0
2) MLT version (Help->Runtime Environment): 6.17.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Debian/Stretch/Gnome
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

**Comment by dvdlvr** [comment]
Hi, The titles option is not made for subtitles, but for hardcoded titles (i. e. titles that always appear and can't be turned off by the user). So it has no support for batch processing. Subtitle support is not yet available but it is being worked on. It will be a while, though. The only way to add proper subtitles at the moment is to use an external subtitle editor.

**Comment by yichuang-zh** [comment]
Got it ~
Thank you.

**Comment by yichuang-zh** [comment]
Is there a way to batch process hard titles?
For example,  batch generation of required PNG hard title files?

**Comment by jliljebl** [comment]
No, these the kind of the very specific tasks that usually require a contribution to be included. 

If you can point to an example in an another application that does this functionality it may be easier to evaluate adding this functionality.

**Comment by yichuang-zh** [comment]
Got it ~
Thank you.
