### ISSUE TITLE
How to reduce noise with Noise Gate and Equalize - Multiband filters ?

### ISSUE THREAD

**Issue by yichuang-zh** [jliljebl/flowblade#721]
I searched with bing and found this: https://blog.landr.com/noise-gates/
But the result of the operation is different with flowblade.
Or, is there any other web page that can provide an operational guide(noise reduction) about Noise Gate and Equalize - Multiband filters ?

Please include the following information.
1) Flowblade version (Help->About):
2) MLT version (Help->Runtime Environment):
3) Your distribution (Ubuntu, Debian, Mint etc.):
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

**Comment by jliljebl** [comment]
Unfortunately I'm not a specialist on audio noise issues. I do believe that from quality point of view Audacity "Noise Reduction" will be superior, it is 2 -pass filter with an analyzing pass and code seems complex and professional.  For the time being I don't believe we can get similar level functionality in Flowblade.

We do have a forum for questions, could you please post further questions here: https://github.com/jliljebl/flowblade-forum

**Comment by yichuang-zh** [comment]
Got it~
