### ISSUE TITLE
hashlib.md5(str(os.urandom(32)).encode('utf-8')).hexdigest()

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#722]
From git master:

Traceback (most recent call last):
  File "/usr/bin/flowblade", line 93, in <module>
    app.main(modules_path)
  File "/usr/share/flowblade/Flowblade/app.py", line 323, in main
    set_instance_autosave_id()
  File "/usr/share/flowblade/Flowblade/app.py", line 750, in set_instance_autosave_id
    instance_autosave_id_str = "_" + hashlib.md5(str(os.urandom(32)).encode('utf-8')).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xba in position 1: ordinal not in range(128)
Killed

Deconstructing the relevant bit of code:

hashlib.md5(     str(      os.urandom(32)        ).encode('utf-8')       ).hexdigest()

So there's 32bytes of random data, and I don't understand why it's being cast as a string at all, given that random data has no reason to be interpreted as a character set at all, and the md5 function should take that random data directly just fine.

These commits are likely relevant:
866cb38883ecee28df9487d0d1e320044bc89633
3789e6a77bbc34ecfa4dce9eb73c168bcf286312
d6b9834dd57a416d9a2f0caf3d3af6f3b75c763f

Technically str(os.urandom(16)).hexdigest() should suffice, but I can see what you'd want to put it through MD5, as it makes this construct easily greppable, if this ever needs upgrading to another hash, making it much easier to do consistently over the entire project.

**Comment by jliljebl** [comment]
Are you running Python 2?

FLOWBLADE MOVIE EDITOR 2.2
--------------------------
Launch script dir: /home/janne/codes/flowblade/flowblade/flowblade-trunk
Running from filesystem...
MLT found, version: 6.17.0
numpy version: 1.16.2
Application version: 2.2.0
OS: Ubuntu 19.04
Python 3.7.3 (default, Aug 20 2019, 17:04:43)  <- THIS ONE!!!

**Comment by pmjdebruijn** [comment]
Are you correct. I totally missed that. My bad.

Though that code does seem somewhat odd still :)

**Comment by jliljebl** [comment]
This may be useful to you:

https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/creating_user_folder_bindings.md

The code is quite old at this point and original motivations are lost in mists of time but it works.
