### ISSUE TITLE
Filter/Transform/Translate not keyframable

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#724]
Flowblade 2.2 (MLT 6.16)

It would be rather convenient if the Translate filter could be keyframed.

I'm aware the picture-in-picture compositor can be used as a workaround, but for simply moving an image around on the screen that's a bit clumsy.

**Comment by jliljebl** [comment]
Absolutely. I'm going to add a GUI editor similar to "Affine Blend" Compositor into these during this cycle.

**Comment by jliljebl** [comment]
There are now new versions of Transform filters created, all keyframable and "Position Scale" filter comes with GUI editor.
