### ISSUE TITLE
Clip Filter Stack not following selected focus

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#725]
Flowblade 2.2 (MLT 6.16)

New project
Import footage
Drag footage to the V1 timeline
Select new clip on the V1 timeline (see it's highlighted)
Switch to the Filters tab (in the upper-left part of the user interface)
Select a filter (for example Translate from the Transform category)
Try to click the + to add it on the stack
(you'll note the + is greyed out and cannot be pressed)

Then, when a random filter is added via the filmstrip, rightclick, Add Filter, categorie, whatever filter, you'll find that suddently the + becomes active in the upper-left part of the screen as well, and from that point on all filter management can be done in the upper-left part.

Also, when switching between clips on the filmstrip, the upper-left "clip filter stack" remains "active" on the same clip, which can be very confusing.

**Comment by jliljebl** [comment]
Confirmed. I just use the clip context pop-up menu always, so this didn't come up on my usage patterns.

**Comment by jliljebl** [comment]
This actually not a bug, but rather a behavior that is working as designed currently, but can feel like a bug because behavior does not match user expectations. 

To "load" clip into Clip Effects editor a double click is required, single clip only selects clip on timeline but does not load it as edit target in Clip Editor.

There are three ways to go forward:
1) Make single clip load clip into effects editor
2) Make Add button click load the (first) selected clip into effects editor and add the effect
3) Leave things as is 

Not sure what to do 1) can get a bit busy, currently leaning towards 2).

**Comment by pmjdebruijn** [comment]
Aha, coming from a background of few if any video editing experience, #1 is absolutely how I'd expect any tool to behave. If explicitly select something, I'd expect any tool that is contextual, to apply to what I just selected.

regarding:
1. with busy, you mean if you'd select multiple clips in a row, you'd see the UI update that many times? but isn't that also a great way to quickly see what filters are applied where?
2. i'm not sure about this, because when you press the add button, you expect the filter to be added to whatever the situation is displayed in the panel itself. as opposed to a clip that may already have filters previously applied, which would suddenly popup along with the new filter. So then it might feel like a bug when you see for example three filters popup when you'd expect only one.
3. the problem if this approach is discoverability, when you know this isn't so bad, if you don't know, it's confusing at best. this can to some extent be mitigated by a short document explaining merely the ui quirks as succinctly as possible (like for example the inverse compositing order), so folks don't need to scour through the entire manual to isolate the non-obvious stuff spread throughout all the more or less obvious stuff.

**Comment by jliljebl** [comment]
I did a bit of looking around and seems that 1) is indeed the most common approach, so let's add is as a user preference. 

We can "calm down" single click load into effects editor by *not* making single click always open "Filters" tab like double click does.

**Comment by pmjdebruijn** [comment]
That sounds very reasonable.

**Comment by jliljebl** [comment]
This is now in repo as a user preference.

**Comment by pmjdebruijn** [comment]
Much appreciated!
