### ISSUE TITLE
Compositor text entry field changes won't apply to preview

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#729]
Flowblade 2.2 (MLT 6.16)

Import two still images
Drop one still image onto V1
Drop the second still image onto V2
Then apply a Affine Blend compositor "between V2 and V1"
Then in the compositor change the numbers (text entry fields) (X/Y/ScaleX/ScaleY/Rot) below graphical tool, you'll note nothing changes. Manipulate the compositor using the graphical tool, then both the actual image changes in the preview and the numbers follow suit.

Perhaps the text entry fields are missing an on-change event handler.

I'm currently under the impression that this isn't specific to Affine Blend.

**Comment by dvdlvr** [comment]
You need to hit Enter in the field to apply the change.

**Comment by pmjdebruijn** [comment]
Oh that kinda make sense...

I guess I'm used to having spinbuttons for these kinds of usecases...

**Comment by jliljebl** [comment]
We can't feed values in the middle of typing here because that would cause some absurd values being displayed, closing as *invalid*. The GTK SpinButtons are too big to use here, this has to be this way.
