### ISSUE TITLE
Improve the performace by enabling section in-project rendering

### ISSUE THREAD

**Issue by tiotrom** [jliljebl/flowblade#730]
Please include the following information.
1) Flowblade version (Help->About): 2.2.0
2) MLT version (Help->Runtime Environment): 6.14.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Manjaro Gnome
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Say I make a title, then add a few effects to it (very simple - some blur with keyframes). I simply cannot properly preview it. It is very choppy.  Adding video effects to videos seems a bit better. Keyframes seem a struggle. I have a core i7 with 8 threads + 32GB of RAM. I tested on the Intel GPU, though I suppose it doesn't use the GPU for much.

I have to say I am a Kdenlive suer for the past 5 years and made documentaries with it, but Flowblade is hands down more promising (much easier to use), and I feel a lot more control because of the keyframing. Too bad the performance is not great, but so is Kdenlive. The way Kdenlive kinda fixes it is by allowing users to select a portion of the video and render it on the spot. And that section becomes viewable inside the project. Are you familiar with that?

On top of this, after I render any project, the CPU is still at 60% more or less. Or even after I add some effects and try to preview some parts. Flowblade keeps my CPU running very high.

Why is video editing so bad on Linux though? I have used Windows in the past to make documentaries and performed a lot better. As I understand is because in Linux the GPU is not really used for video editing.

Cheers and hands down this is the most promising video editor. Thank you very much for your work!

**Comment by jliljebl** [comment]
>  ...allowing users to select a portion of the video and render it on the spot. And that section becomes viewable inside the project

Yes, timeline rendering. This is a planned feature and I have some ideas on how to do this a bit better then KDEnlive. First code will hopefully land on master around February and development will go from there.

> ...performed a lot better. As I understand is because in Linux the GPU is not really used for video editing.

Yes, doing stuff on GPU is the main performance differentiator right now. Hopefully we get there in future. Thanks for the positive feedback, that's always appreciated.

**Comment by tiotrom** [comment]
Awesome to hear about the timeline rendering. Can't wait. I love flowblade. You are awesome :)
