### ISSUE TITLE
Allow tracks to be re-ordered and edited

### ISSUE THREAD

**Issue by tiotrom** [jliljebl/flowblade#732]
I usually need to add more tracks on top/bottom and it seems I cannot do it here. Also, I would like to re-arrange them by drag-drop. Is this possible? Thanks!

**Comment by jliljebl** [comment]
Use "Edit"->"Change Sequence Tracks Count..." to add or remove tracks, note that to get more then 9 tracks you need to have less audio tracks.  We are not allowing timeline vertical scroll so we have max tracks count at 9.

> Also, I would like to re-arrange them by drag-drop

This is not possible currently and I'm going *wontfix* on this, *usefulness/coding work* ratio just isn't there for this one.

I will improve on clips copy-paste which currently a bit restricted, I'll post additional comment here when that lands.

**Comment by tiotrom** [comment]
Ok. Thanks. I think would be fantastic to allow for vertical scroll like most video editors do, and the re-arrange tracks could be a must if you create a project that later on needs this. Else you have to manually adjust/re-arrange the items from one track to another.
