### ISSUE TITLE
Scaling Possibly in the wrong place in the pipeline

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#736]
Flowblade 2.2 (MLT 6.16)

I'm not sure if this is a Flowblade or MLT issue...

I'm under the impression that when I import footage, for example 2160p, and then export it as 1080p, the following (rough) pipeline is applied:

original footage -> decode -> downsampling -> apply filters -> re-encode

However many filters have pixel dimension specific parameters, and will therefore have completely different results depending at what resolution footage they are being applied, therefore the pipeline should probably be like this:

original footage -> decode -> apply filters -> downsampling -> re-encode

This will however make processing 1080p almost as slow as 2160p, but at the very least the 1080p footage will be always be as expected.

The other approach would be to make all plugins pixel independent, with everything expressed as a floating point ratio of the vertical dimension of the video footage, but I'm guessing that will not be trivial too do, as that requires a degree of precision in some plugins that might simply not be there to begin with.

**Comment by jliljebl** [comment]
At first look this seems item 3. in https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/KNOWN_ISSUES.md

Basically doing this in backwards compatible way would eat way too much dev. time. If we get large community of contributors with someone interested in tackling this I would take the patches, but right now I do not see this getting attention anytime soon.

**Comment by pmjdebruijn** [comment]
It's related, though not quite the same. As my issue is at export time, so it's not really a change in profile, at least not explicitly.

Do you have any control in which order the filters and resampling is applied?
If so, this could probably be fixed by moving the resampling to the end of the pipeline before the video is re-encoded...

**Comment by jliljebl** [comment]
> Do you have any control in which order the filters and resampling is applied?

No, and i am quite sure that MLT will not take any patches on this, they'll say: you can fix this on app and this is fundamental operation of library and we will not mess with it.
