### ISSUE TITLE
Inkscape integration

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#737]
Given that Flowblade seems to support SVG fairly well, I was wondering if basic integration with Inkscape would possibly offer a high-powered alternative to the built-in Titler, with nearly the same convenience as the Titler.

So when the user presses the inkscape tool button, the following would happen:

1. Render current frame as a JPEG (possibly downscaled)
2. Generate a temporary SVG file, with content like so, with the just rendered JPEG embedded as a data uri:

```
<svg height="2160" width="3840">
  <g inkscape:groupmode="layer" id="layer1" inkscape:label="Background" sodipodi:insensitive="true">
    <image height="2160" width="3840" x="0" y="0" id="image0" xlink:href="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAAJABADAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAn/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AL8AAAA//9k=" style="image-rendering:optimizeSpeed" />
  </g>
  <g inkscape:groupmode="layer" id="layer2" inkscape:label="Foreground">
  </g>
</svg>
```
3. Start Inkscape, opening the temporary SVG as commandline parameter
4. This is where the user may draw their text or whatever suits them in the SVG, after which the user saves the SVG in place, and quits Inkscape.
5. Flowblade then processes the just now saved SVG, removing the background group/layer, as this was just there as a guide.
6. The resulting SVG can now be applied in the Flowblade timeline.

**Comment by dvdlvr** [comment]
That sounds good but I would add the option to not include the current frame as image. A simple tickbox would do if we use a startup screen - or two menu options to start it - or a flag in the (apparently dreaded 😊) Preferences screen.I know for sure I would prefer not seeing that in most cases. But it would certainly be handy to have to possibility.

**Comment by pmjdebruijn** [comment]
While I usually don't need to background either, that is the primary advantage of having proper integration. Without the background, there is little benefit left to just starting inkscape, drawing something, and importing it into Flowblade.

And, even if Flowblade always includes the background, it's trivial to remove in Inkscape anyhow, it's just a matter of making the background removal code in Flowblade tolerant enough to not error, if it's missing already.

So I'm not sure if there's any real value in complicating Flowblade's UI around a feature like this, given the two points above.

**Comment by dvdlvr** [comment]
Whatever you use the svg for it will be on more than 1 frame, so having a still frame could be annoying more than anything else. The biggest bugbear of any integration is not having control of what it does. Allowing the use to choose is, in my opinion, an absolute necessity. Sent from my Huawei tablet-------- Original Message --------Subject: Re: [jliljebl/flowblade] Inkscape integration (#737)From: Pascal de Bruijn To: jliljebl/flowblade CC: dvdlvr ,Comment While I usually don't need to background either, that is the primary advantage of having proper integration. Without the background, there is little benefit left to just starting inkscape, drawing something, and importing it into Flowblade.
And, even if Flowblade always includes the background, it's trivial to remove in Inkscape anyhow, it's just a matter of making the background removal code in Flowblade tolerant enough to not error, if it's missing already.
So I'm not sure if there's any real value in complicating Flowblade's UI around a feature like this, given the two points above.

**Comment by pmjdebruijn** [comment]
I don't see how having an option in Flowblade makes it a lot better, when you already have the option to remove it in Inkscape. Having an option in Flowblade seems somewhat redundant. 

The only value I would see would be in a global option, possibly, so you can tell Flowblade to never include it, if you're sure you never want it, so you don't end up having to remove that background every time.

**Comment by jliljebl** [comment]
This could be a useful capability, Some points:

* since this depends on users selecting "Save" and not "Save As.. we need to have a dialog (as first step) telling user to select Save and close Inkscape to get created image automatically saved and opened in Flowblade
* we would like to have text box for inputting default text before opening Inkscape, that would give a "better impression" in a sense that the feature seems more integrated with Flowblade. In the same dialog box as info above.
* we need launch time availability detection for Inskape.
* the appropriate module would be something like */tools/inkscapeintegration.py*
* in we can really nuke the bg then I don't think we *need* the option this time, but we might want to add it into the dialog above, again to better *sell* the the ingratiation to the user.

For me this definitely post-moving-on-fromSDL1.2 stuff but if we get contributions then great.

**Comment by jliljebl** [comment]
We now have following workflow available for using Inkscape as e.g. title editor.

1. Create and save SVG image with Inkscape and keep it open in application 
2. Open file as media item make a clip from it
3. Do some changes in Inkscape and save file again
4. Select from Clip pop-up menu "Reload Media From Disk" and see changes updated on timeline.

I believe this the best we can do for the moment and I'm closing this as *wontfix* as I don't feel there will further development on this for the time being.
