### ISSUE TITLE
Lens Correction Filter Duplication

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#742]
I noticed before adding defish0r, which has marked benefits over the other two, there were already two lens correction plugins available:

frei0r.lenscorrection "Lens Correction"
avfilter.lenscorrection "Lens Correction (av)"

I don't quite understand why they are both there though, looking at this:
https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_lenscorrection.c
It seems the avfilter filter is just a port of the frei0r filter to the ffmpeg internal API, including the lack of interpolation and/or automatic image fitting.

So you might want to consider dropping either of them, since it's essentially a duplicate where neither has any significant advantage over the other. Except...

The avfilter plugin has easily avoidable "math" parameter names, which would be trivial to fix.

I could see wanting to favour the avfilter one, as ffmpeg is already a hard dependancy via mlt, while frei0r may or may not be as dependable as avfilter.

**Comment by jliljebl** [comment]
Ok, will look. I also noticed that there are 3 similar filters now, so dropping one will not be a problem if we're not getting differentiated functionality.

**Comment by pmjdebruijn** [comment]
For many (if not most usecases) defish0r will likely be the best available solution by a country mile :)

**Comment by jliljebl** [comment]
Went through the filters and decided to drop LensCorrectionAV, it seemed to offer least amount of useful functionality.

frei0r will absolutely stay, it is not being actively developed right now but it is maintained, mostly by Dan Dennedy.

**Comment by ddennedy** [comment]
Hi, I happened upon this issue while searching around something similar for Shotcut, and I made frei0r.lenscorrection hidden and deprecated and added Fisheye in the newest version. I am doing only light maintenance of frei0r at this time as its age is really showing, and I will not be improving its lenscorrection.
