### ISSUE TITLE
Text-based project file format  - discussion

### ISSUE THREAD

**Issue by eliotb** [jliljebl/flowblade#746]
Proposal: Use a text-based format for project file. 

Flowblade's project save format is very opaque, being a python pickle of manipulated project object. This concerns me, I'd rather see a text based format that can be version-controlled, and manually edited or manipulated by other tools. Also it would help to decouple the project format from the internal data structures.

Other NLE use a text based format:
- Kdenlive : xml MLT (uses 'kdenlive:' prefix for own data)
- Cinelerra : xml EDL
- Pitivi : xml XGES
- Openshot : json or yaml?
- Shotcut : xml MLT

Given that Flowblade can save a sequence as MLT xml,  basing on this makes sense to me.
Flowblade would need to be able to import MLT xml as sequence as first step?

I guess there are other things stored in the project file too?

Also FB has multiple sequences.  I'm not sure if MLT support this in one file. One approach would be like openoffice, use a zip file as container for metadata and multiple sequence files.

**Comment by dvdlvr** [comment]
You can use File / Export to create an xml MLT file for your current project. That you can manipulate, like I did to create a renderfarm script, for instance, allowing rendering of portions of the movie on different computers at the same time. Sent from my Huawei tablet-------- Original Message --------Subject: [jliljebl/flowblade] Text-based project file format  - discussion (#746)From: Eliot Blennerhassett To: jliljebl/flowblade CC: Subscribed Proposal: Use a text-based format for project file.
Flowblade's project save format is very opaque, being a python pickle of manipulated project object. This concerns me, I'd rather see a text based format that can be version-controlled, and manually edited or manipulated by other tools. Also it would help to decouple the project format from the internal data structures.
Other NLE use a text based format:
Kdenlive : xml MLT (uses 'kdenlive:' prefix for own data)Cinelerra : xml EDLPitivi : xml XGESOpenshot : json or yaml?Shotcut : xml MLT
Given that Flowblade can save a sequence as MLT xml,  basing on this makes sense to me.
Flowblade would need to be able to import MLT xml as sequence as first step?
I guess there are other things stored in the project file too?
Also FB has multiple sequences.  I'm not sure if MLT support this in one file. One approach would be like openoffice, use a zip file as container for metadata and multiple sequence files.

**Comment by jliljebl** [comment]
This is a hard no from me.

The downsides completely outweigh the benefits here. The application would be massively de-stabilized and we would lose any forward momentum for months.

The MLT XML export is the best we can do for the foreseeable future.
