### ISSUE TITLE
Transitions Dialog improvement

### ISSUE THREAD

**Issue by GameCy** [jliljebl/flowblade#763]
Enhancement, Flowblade  2.2 ..

When selecting 2 consecutive clips to add a transition between them, and there are not enough frames available to use for the transition, a warning is displayed.

Instead add a tick box to 'Steal frames' from each clip edge, and adjust the clips accordingly.

E.g.  Clip 1 [ 0 - 100]  , Clip 2 [ 0 - 200]
after steal:
  Clip 1 [ 0 - 60]  , Transition [40 frames], Clip 2 [ 40 - 200]

**Comment by jliljebl** [comment]
Yes, I have come to this conclusion as well. Handles seems somewhat difficult concept for some users, and if we can give them button that out fixes this, then we should add it.

This is kind of task that seems easy at first but make sure everyhing works correctly and the created new GUI is undesandablr for those users who do not get the handles thing will take some work.

We are just closing down on new features development so this probably wont make 2.4, but is almost sure to be in 2.6.

**Comment by jliljebl** [comment]
This has now been fixed along the lines suggested here, will be in 2.6.
