### ISSUE TITLE
Flatpak can not input Chinese(zh-cn) 

### ISSUE THREAD

**Issue by yichuang-zh** [jliljebl/flowblade#764]
I can not input Chinese(zh-cn), only English.

This version of flowblade is flatpak version.

ps:
I have another version of flowblade officially installed from debian, Chinese input is ok. But, it has other problem, especially too serious to use.

The Chinese input OK version of flowblade:
1) Flowblade version (Help->About):1.10.0
2) MLT version (Help->Runtime Environment):6.4.1
3) Your distribution (Ubuntu, Debian, Mint etc.):Debian Stretch 9.11/Gnome

The Chinese input NG version of flowblade(flatpak):
1) Flowblade version (Help->About):2.2.0
2) MLT version (Help->Runtime Environment):6.17.0
3) Your distribution (Ubuntu, Debian, Mint etc.):Debian Stretch 9.11/Gnome
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: Click tools > titler, then press the Ctrl+Space, then, no Chinese input method display(fcitx). In libreoffice, the Chinese input is ok.

**Comment by yichuang-zh** [comment]
OK.
I will report to Flatpak next time  encountered questions about flatpak.

**Comment by luzpaz** [comment]
@yichuang-zh is this still an issue ?

**Comment by yichuang-zh** [comment]
It's OK on KDE plasma desktop(Debian12).
I don't know if it was ok on Gnome.

**Comment by jliljebl** [comment]
I'll close this as we have info on fix at least on some systems.
