### ISSUE TITLE
Flowblade crash on Gentoo on start

### ISSUE THREAD

**Issue by makalega** [jliljebl/flowblade#765]
Flowblade version 2.2 
MLT version : 6.16.0
Distribution : Gentoo Linux

FLOWBLADE MOVIE EDITOR 2.2
--------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade
MLT found but version info not available. MLT probably too old to work reliably...
/usr/share/flowblade/clipeffectseditor.py:483: SyntaxWarning: name 'current_filter_index' is used prior to global declaration
  global current_filter_index
/usr/share/flowblade/propertyeditorbuilder.py:193: SyntaxWarning: name 'changing_slider_to_kf_property_name' is used prior to global declaration
  global changing_slider_to_kf_property_name
/usr/share/flowblade/tlinewidgets.py:370: SyntaxWarning: name 'TRACK_GRAD_ORANGE_STOP1' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/usr/share/flowblade/tlinewidgets.py:370: SyntaxWarning: name 'TRACK_GRAD_ORANGE_STOP3' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/usr/share/flowblade/tlinewidgets.py:370: SyntaxWarning: name 'TRACK_GRAD_STOP1' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/usr/share/flowblade/tlinewidgets.py:370: SyntaxWarning: name 'TRACK_GRAD_STOP3' is assigned to before global declaration
  global TRACK_GRAD_ORANGE_STOP1,TRACK_GRAD_ORANGE_STOP3,TRACK_GRAD_STOP1,TRACK_GRAD_STOP3
/usr/share/flowblade/projectaction.py:774: SyntaxWarning: name 'force_overwrite' is used prior to global declaration
  global force_overwrite, force_proxy
/usr/share/flowblade/projectaction.py:774: SyntaxWarning: name 'force_proxy' is used prior to global declaration
  global force_overwrite, force_proxy
numpy version: 1.14.5
Application version: 2.2.0
OS: Gentoo/Linux
Python 2.7.16 (default, Oct 13 2019, 04:44:58) 
[GCC 8.3.0]
GTK+ version: 3.24.10
XDG user data exists.
Locale: en_US
Translations at /usr/share/locale were not found, using program root directory translations.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Loading shortcuts: Flowblade
Gtk version is 3.24.10, Flowblade theme is available.
Screen size: 1680 x 1050
Small height: False
Small width: False
Traceback (most recent call last):
  File "/usr/bin/flowblade", line 93, in <module>
    app.main(modules_path)
  File "/usr/share/flowblade/app.py", line 230, in main
    repo = mlt.Factory().init()
AttributeError: 'module' object has no attribute 'Factory'

**Comment by dvdlvr** [comment]
Hi

You indicate you have MLT 6.16.0 but this is the cause of the issue:
"MLT found but version info not available. MLT probably too old to work reliably..."
So the 6.16 version is not found, as that will not give this error message.

Please check the version of the python-mlt package installed on your system and let us know what version you have.

Another user had dome a 'pip install mlt' and had to do a 'pip uninstall mlt' to get it to work. You may try that.

Please let us know if you got it solved.

**Comment by jliljebl** [comment]
Maybe related:

https://github.com/jliljebl/flowblade/issues/649

I'm not taking any Gentoo related Issues until SDL 1.2 is no longer used for video display.
