### ISSUE TITLE
Python3 version won't load project saved by python2 version.

### ISSUE THREAD

**Issue by eliotb** [jliljebl/flowblade#767]
Please include the following information.
1) Flowblade version (Help->About): 2.2.0 (master @ 26ff5471563a)
2) MLT version (Help->Runtime Environment): 6.17.0 [mlt master@abcd989e](https://github.com/mltframework/mlt/commit/abcd989ea7b437921e7e36b182685134db068932)
3) Your distribution (Ubuntu, Debian, Mint etc.): Debian 10 64 bit
4) To reproduce:
Try to load project saved with recent (python2) version.

> Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/eliot/src/python/flowblade-ewb/flowblade-trunk/Flowblade/projectaction.py", line 123, in run
    project = persistance.load_project(self.filename)
  File "/home/eliot/src/python/flowblade-ewb/flowblade-trunk/Flowblade/persistance.py", line 394, in load_project
    project = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 1: ordinal not in range(128)

This [blog post](https://rebeccabilbro.github.io/convert-py2-pickles-to-py3/) has some ideas.

I swear I didn't seek this out on purpose, but this is the kind of thing I was thinking of when I opened #746

**Comment by jliljebl** [comment]
Can you post the terminal output?

pe 1. marraskuuta 2019 klo 10.46 Eliot Blennerhassett <
notifications@github.com> kirjoitti:

**Comment by eliotb** [comment]
The traceback is quoted above?
Full terminal output: [load-old.log](https://github.com/jliljebl/flowblade/files/3797365/load-old.log)

**Comment by jliljebl** [comment]
Sorry, on mobile, GMail app didn't show full message.

pe 1. marraskuuta 2019 klo 11.44 Eliot Blennerhassett <
notifications@github.com> kirjoitti:

**Comment by eliotb** [comment]
no problem
BTW I am in UTC+13 timezone (22:50) so going to sleep now...

**Comment by jliljebl** [comment]
Ok, I got example project file givivg the same, so I can work with that.

On my system 2.2->repo head works, so we need to find the diff.

**Comment by jliljebl** [comment]
@eliotb  I pushed a patch that loads my problem file, can you test if it loads your file too?

**Comment by eliotb** [comment]
On 6/11/19 2:49 am, jliljebl wrote:
> @eliotb <https://github.com/eliotb> I pushed a patch that loads my
> problem file, can you test if it loads your file too?

Yes, it loads my file too thanks!
And with very little code change - nicely done.

**Comment by jliljebl** [comment]
Great, thanks, having two test cases is so much better then having one with stuff like this.
