### ISSUE TITLE
Deleting clip deletes space too

### ISSUE THREAD

**Issue by tiotrom** [jliljebl/flowblade#768]
Please include the following information.
1) Flowblade version (Help->About): 2.2.0
2) MLT version (Help->Runtime Environment): 6.14.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Manjaro Gnome Stable
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Say I have a clip in between 2 others. If I delete it the other 2 clips snap together. If I "lift" the same clip, it does not happen. Why is this by default? It seems a bit confusing. Couldn't delete just delete the clip and not the space? Cheers!

**Comment by tiotrom** [comment]
Ah ok I think the "spanning" is on bu I can't turn it off. Every time I do it it gets enabled again.

**Comment by jliljebl** [comment]
I do need see actionable Issue here, closing.
