### ISSUE TITLE
Clickable area of video/audio mute is not aligned with icon

### ISSUE THREAD

**Issue by kellen** [jliljebl/flowblade#771]
Flowblade version: 2.0.0
MLT version: 6.16.0
Distro: Ubuntu 19.10

The clickable area of the video or audio mute buttons is to the left of the icon itself ending roughly at the center of the icon, so clicking on the right side of the icon has no effect, but clicking in the empty space to the left of the icon will successfully mute the audio or video.

**Comment by jliljebl** [comment]
After testing now it looks like that you're right. Seems that I can also make the Icons 1 pix wider and higher without having to re-layout track heads, so should probably do that too.

**Comment by jliljebl** [comment]
I made hit area wider and better centered, the experience is much improved now, thanks. Fix will be in 2.4.
