### ISSUE TITLE
Opening help results in non-exting location 

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#774]
Please include the following information.
1) Flowblade version (Help->About): 2.0.0
2) MLT version (Help->Runtime Environment): 6.16.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: Choose from Help menu the item called Contents

This opens in a web browser the url file:///usr/share/flowblade/Flowblade/res/help/en/help.html which doesn't exist. The package only offers this:

    xxx@yyy:/usr/share/flowblade/Flowblade/res/help$ ls -lrta
    total 60
    -rw-r--r--  1 root root   402 Feb  4  2019 translations
    -rw-r--r--  1 root root   499 Feb  4  2019 help.html
    -rw-r--r--  1 root root 34685 Feb  4  2019 gpl3
    -rw-r--r--  1 root root    61 Feb  4  2019 developers
    -rw-r--r--  1 root root   103 Feb  4  2019 contributors
    drwxr-xr-x 13 root root  4096 Apr 23  2019 ..
    drwxr-xr-x  2 root root  4096 Oct 22 22:39 .
    xxx@yyy:/usr/share/flowblade/Flowblade/res/help$ cat help.html 
    <!DOCTYPE html>
    <html>
    <head>
    <title>Flowblade help</title>
    <script type="text/javascript">
    var lang=(navigator.language||navigator.systemLanguage||navigator.userLanguage).substr(0, 2).toLowerCase();
    function actLang() {
    if (lang=='en') {nameweb='en/help.html';}
    else if (lang=='ru') {nameweb='ru/help.html';}
    else if (lang=='your_lang') {nameweb='your_lang/help.html';}
    else {nameweb='en/help.html';}
    parent.location=nameweb;
    return true;}
    actLang()
    </script>
    </head>
    <body></script></body></html>

**Comment by smolnp** [comment]
Sorry, but what language is installed on your system?

**Comment by jliljebl** [comment]
Hi, this seems to be related to Flowblade functionality that offers Russian language help files if OS is running in Russian.

Can you tell me what is your OS language, that might help in fixing this?

**Comment by smolnp** [comment]
I will report the problem to the author of the script. Be sure to unsubscribe about the results

**Comment by smolnp** [comment]
Andrei Grigoriev (the person who provided me the code) blocked me because of our difference in geo-flying views, I wrote about the problem to several more people who hope they can figure this out out, anyway I will answer you on Sunday.

**Comment by smolnp** [comment]
it seems a problem has been found, maybe the problem is in (lang == 'your_lang'), this command needs to be replaced with (lang == 'fr'), but you need to double-check everything from a different locale except English or Russian.

**Comment by smolnp** [comment]
tomorrow I will do it and unsubscribe

**Comment by PanderMusubi** [comment]
My OS language is default en_US.

**Comment by Survolog** [comment]
> This opens in a web browser the url file:///usr/share/flowblade/Flowblade/res/help/en/help.html which doesn't exist.

As you can see, this file [exists in the source](https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/Flowblade/res/help/en/help.html).
So it could be lost outside this project. For example, when building a distribution package or when configuring the system (moved or erased /usr/share/flowblade/Flowblade/res/help/en/).

**Comment by PanderMusubi** [comment]
Works in version 2.2 for me and can be closed if there is no further action to be taken.
