### ISSUE TITLE
Choosing dark theme shows light theme.

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#775]
Please include the following information.
1) Flowblade version (Help->About): 2.0.0
2) MLT version (Help->Runtime Environment): 6.16.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.10 (Lubuntu)
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Choosing Dark theme results in showing Light theme. Choosing Flowblade theme and Light theme work properly.

**Comment by jliljebl** [comment]
This depends on your GTK  theme, not all themes have dark variants.

**Comment by PanderMusubi** [comment]
Thanks for the extra information. Lubuntu has a LXQt Theme called Dark (but is not the default theme and also not active for me). It has also some dark icon themes and support GTK themes etc.

Since the Flowblade theme has improved for 2.2, I desire to use the dark (or light) theme. For those who want this in Lubuntu, those people need to investigate this further. For me good to keep this issue closed.
