### ISSUE TITLE
Flowblade theme has barely readible low-contrast buttons

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#776]
Please include the following information.
1) Flowblade version (Help->About): 2.0.0
2) MLT version (Help->Runtime Environment): 6.16.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.10 (Lubuntu)
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Simply start Flowblade and look at e.g. the render window, see attachment. The contrast on the buttons is of very low contrast. Note that this is in Lubuntu with default LXQt window manager. The problem does not occur in the Light theme. Could not test the Black theme, see https://github.com/jliljebl/flowblade/issues/775

![2019-11-20-032001_1920x1080_scrot](https://user-images.githubusercontent.com/198964/69203856-c1c84d00-0b45-11ea-9ca1-8044f82067c2.png)

**Comment by jliljebl** [comment]
Issue was fixed in 2.2, you should use latest version for bug reports.
