### ISSUE TITLE
Use ~/.config for configuration directory

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#777]
Please include the following information.
1) Flowblade version (Help->About): 2.0.0
2) MLT version (Help->Runtime Environment): 6.16.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Simply start Flowblade, it will create a configuration directory in `~/.flowblade`, this should be `~/.config/flowblade` when adhering more to conventions.

When this is changed, check on startup if  `~/.flowblade` exists but no `~/.config/flowblade` exists and ask the user to move that directory to there. If `~/.config/flowblade`exists, then `~/.flowblade` will be ignored.

**Comment by jliljebl** [comment]
Issue was fixed in 2.2, you should use latest version for bug reports.

**Comment by PanderMusubi** [comment]
Thanks, hope this can help https://github.com/jliljebl/flowblade-packaging/issues/2
