### ISSUE TITLE
Disable INFO logging to command line

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#778]
Please include the following information.
1) Flowblade version (Help->About): 2.2.0
2) MLT version (Help->Runtime Environment): 6.16.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Simply start Flowblade from the command line and a lot of INFO-level logging is being written. This can be written to a log file in Flowblade's configuration directory, but not on the screen as it clutters up the command line and drowns important messages. For production build applications, only warnings and errors are desirable on the command line.

Optionally, offer command line arguments to set the command line log level such as --verbose (show INFO) or --quiet (don't even show WARNINGS).

**Comment by jliljebl** [comment]
I have mechanics to direct printouts to log file so I can at some point offer a "--uselogfile" switch or something.

This information is continually useful for getting immediate data where seqfault type crashes happen (e.g. SDL related problems have benefited from this) so the verbose thing will stay default

**Comment by jliljebl** [comment]
We added **--quiet** command line switch that directs prints to /dev/null.
