### ISSUE TITLE
2.2.0: Unusable playback performance

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#779]
Fedora 31
MLT 6.17.0
Flowblade 2.2.0 (flatpak)

I've been making fairly complex 1080p videos using flowblade (e.g. https://www.youtube.com/watch?v=Tt3ahk2qsmw) using a small fanless laptop (Asus Ux360CA) with an Intel Core m3-6Y30 in it. Playback was sufficiently smooth in the past to manage such work, even on such an underpowered machine.

However, playback performance went south in the latest version 2.2.0 (I should've created this bug report a while ago but haven't had time). It is so bad that I've had to stop using Flowblade altogether for the time being. The footage stutters and freezes every few seconds, making it impossible to edit with.

Steps to reproduce: Get vanilla Fedora and download the latest Flowblade flatpak, then load up some videos and watch the lag. Not sure if this is reproducible for other distros.

I've tried downgrading MLT but that didn't fix the issue.
I've tried Kdenlive and Shotcut and they don't seem to have the same issue.
With these two facts in mind I don't think it's an MLT issue.

I've also tried a more powerful processor (Intel Core i5-3470S), but playback was just as unusable there.

I heard there was a kernel update that slowed down intel processors a bit, but I'm not convinced that's the issue, given that Kdenlive and Shotcut still work fine.

Happy to provide more info. If I get time later in the week I can make a screencast demonstrating the issue. Thanks.

**Comment by jliljebl** [comment]
Well, that's really very unfortunate.

To confirm that something went wrong with Flowblade 2.0 -> 2.2 cycle it would be extremely useful if you could test with 2.0, having MLT and OS stay the same.

1. Install Flowblade from Fedora repo to get the current bindings installed.
2. Install Flowblade from repository, see here https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md
3. Checkout version 2.0 from git: *git checkout tags/v2.0*
4. Launch Flowblade 2.0 and test playback
5. Checkout 2.2 from repo: *git checkout tags/v2.2*
6. Launch Flowblade 2.2 and test playback

**Comment by jliljebl** [comment]
BTW, Flatpak comes with its own MLT so changing OS MLT when running Flatpak Flowblade has no effect.

**Comment by thennicke** [comment]
Okay, this is strange. There's been a spontaneous remission. The issue has resolved itself; I'm unable to make the editor lag like it was. It may have been a new patch of some sort that came through.

And yeah I forgot about the whole flatpak sandboxing thing. For my future reference, is there a way to downgrade or upgrade the flatpak version of MLT?

**Comment by jliljebl** [comment]
Well, great, I think they put some patches in Flatpak just few days a go, so this may have been a Flatpak issue...or something in Fedora has been patched, it will be very difficult to know now.

With Flatpaks it  is not possible to change the MLT version, everything comes packaged together. It is possible to create another Flatpak with different a MLT version but we only have the one from Flathub available (usually accessed using Gnome Software application).

I'll leave this open until next release to see if additional info comes in.

**Comment by jliljebl** [comment]
2.4 is out so this is no longer current.
