### ISSUE TITLE
Transition Color Dip and Fade In or Out Not Working

### ISSUE THREAD

**Issue by dpack4** [jliljebl/flowblade#792]
Please include the following information.
1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment): 6.18.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.04.3 LTS 64bit
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easiest way to understand what is happening.:

I am a new user to Flowblade. I am liking it so far. Since the DEB is not provided for 2.4, my installation is from the Flatpak portal. I am able to successfully create any transitions using Dissolve or Wipe. For two clips, Color Dip applies but removes the second video clip from the timeline. Have to undo and not use it. I was unable to locate any documentation on how to properly use this feature. My guess is that it will Fade to black (or other color) between the two selected clips.
![ColorDip1](https://user-images.githubusercontent.com/59346602/71564148-14145c00-2a6a-11ea-8bd8-43dddfe9450d.png)
![ColorDip2](https://user-images.githubusercontent.com/59346602/71564151-1d052d80-2a6a-11ea-8c61-cd8ae7a99d87.png)
![ColorDip3](https://user-images.githubusercontent.com/59346602/71564154-20001e00-2a6a-11ea-9ba3-7296c09ea315.png)

For one clip, using either a Fade In or Fade Out applies but does not show the actual color picked nor does a "fade" to it. For the frames the Fade is applied, it is a solid blank white screen between the selected clips.
![Fade1](https://user-images.githubusercontent.com/59346602/71564163-360dde80-2a6a-11ea-932e-c482db4ef4fb.png)
![Fade2](https://user-images.githubusercontent.com/59346602/71564166-38703880-2a6a-11ea-9a90-4c8ddf0ee099.png)
![Fade3](https://user-images.githubusercontent.com/59346602/71564167-3b6b2900-2a6a-11ea-9d77-738c10e3c60c.png)

If I am doing something wrong, please let me know. I will try removing 2.4 and install the 2.2 DEB file to see if I get different results. At the time of this writing, I am unable to determine if it is user error, 2.4 bug, or issue with Flatpak image.

**Comment by dpack4** [comment]
I have fully removed 2.4 and all associated Flatpak configurations and installed 2.2 DEB clean. I re-tested and both Color Dip and Fade In/Out work properly. So, I at least now know it is not user error. There is either a bug in 2.4 or the Flatpak image needs to be recompiled. I'll be sticking with 2.2 for now especially with it being a much smaller installation. I will continue using/learning Flowblade for my needs. With 2.2 operating normally, I have not encountered anything that would force me to use something else. Loving the software so far! Great job and keep up the good work!

**Comment by smolnp** [comment]
I think this is a previous bug: https://github.com/jliljebl/flowblade/issues/791
You can work around this problem by changing the encoding settings. For example, on MPEG-4/.mp4.
![screen-12-30-09-51](https://user-images.githubusercontent.com/26217756/71571427-37332000-2aeb-11ea-8d35-edfa00365913.png)
![screen-12-30-09-52](https://user-images.githubusercontent.com/26217756/71571444-4fa33a80-2aeb-11ea-92a4-149c8c63a1b4.png)

**Comment by jliljebl** [comment]
Thanks for detailed report. Yes, this a regression for 2.4. We are looking to fix this and then backport the bugfix.

This is very likely caused by the same underlying problem that caused  #791 so I'm merging this with that. If it turns out that this is separate problem I will reopen this.

**Comment by dpack4** [comment]
Thank you for reviewing! I do see where this is the same as #791 but it did not mention the Color Dip; only Fade In/Out. The underlying problem may be associated to or be separate code to address for Color Dip.

**Comment by jliljebl** [comment]
Yes, it is good that we have Issues on all detected problems, I do frequently forget to check everything possibly related and having problems written down in an Issue helps a lot, thanks.
