### ISSUE TITLE
Select and move multiple clips in timeline

### ISSUE THREAD

**Issue by niveK77pur** [jliljebl/flowblade#794]
Please include the following information.
1) Flowblade version (Help->About): 2.2.0
2) MLT version (Help->Runtime Environment): 6.0.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 16.04
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

After spending quite some time trying to find an answer online, I came to the conclusion that the only way to select multiple clips is to do `ctrl+<left click>`. And this only seems to work within a track (so I cannot select two clips from track `V1` and `V2` for example). However it might happen that I have lots of little clips that I want to move all together---which would be an absolute nightmare if I had to select each clip on each track and move them individually (especially if everything needs to line up correctly). 
![little-clips](https://user-images.githubusercontent.com/10981161/71645496-b128fc00-2cd9-11ea-9a8b-8b72c9579638.png "lots of little clips in blender")

It also happens that I first work on the middle portion of a video and then later finish up the beginning of the video. This implies that I would leave a lot of blank space before the middle portion such that there is enough room for the beginning portion. When I am done and want to tie the lose ends I would again have to select all the clips that go with the middle portion and move them to where the beginning portion ends.
![tying-clips](https://user-images.githubusercontent.com/10981161/71645698-75dbfc80-2cdc-11ea-8d3e-3f43ff188ed2.png "putting together two parts in kdenlive using its spacer tool")

To make these tasks easier I have the following in mind (unless they already exists and I just could not find them for the love of god):

1) **Box select.** Akin to how blender does it where you can simply select everything that is within a specified area. This would make it very easy and convenient to move around lots of little clips or even larger chunks that maybe need to line up perfectly.
2) **Kdenlive's spacer tool.** Check [this video](https://www.youtube.com/watch?v=U8Yzy3AdKys&feature=youtu.be&t=280) to see how it works. This is absolutely perfect and a real life saver for me if I need to put together parts of a video (like in my second example above).
3) **Move synced clips together.** I find it a little annoying that I have to move the parent clip and then re-sync the clips by right-clicking on the child and selecting *Sync with Origin Clip*. I would consider this a bonus though, the above are way more important imo.

As I said, I am not aware of these features existing in flowblade and it may very well be that they were left out intentionally to favour a different work-flow. If this is the case, I'd be happy to know how to get around these problems elegantly without painstakingly select absolutely everything by hand.

**Comment by dvdlvr** [comment]
With the Move pointer selected, left-click on an empty space in the timeline and drag around all your clips to do a box select. Make sure the entire clip is selected to include it. So top and bottom, left and right need to be in the box for it to work. Works across tracks. Drag it where you want once selected.

**Comment by niveK77pur** [comment]
Indeed, this works! Although a little clunky and I need to use the *Standard* Workflow preset. I say clunky because
1) it doesn't seem like I can extend the selection with the box select ... Like I select something (either with the box select or simply by left clicking) and then I want to add something else to the selection using box select again. As soon as I left click (or ctrl+left click) outside the selected clips the selection is gone. 
2) What do I do if there does not happen to be any blank space around where I can start the box select from? Say I have tracks A1, V1, V2 and V3 (like in the image below) and there is a specific part where I want to select a bunch of clips from V1 (and also V2 if you're going to say I could just *ctrl+left click* the wanted clips). However, A1, V2 and V3 are all full (so don't have any blank spaces) in that specific part. If I understand correctly, I would only be able to select according to the yellow box (which would also select tons of other clips I don't want) and not according to the red box, right?
![clips](https://user-images.githubusercontent.com/10981161/71666358-c39a4880-2d60-11ea-99b4-2d26fc9e1dc7.png "example in blender")

Any way around these? uwu

**Comment by dvdlvr** [comment]
Sorry, I don't really use this feature, so this is too detailed for me 
to answer.

**Comment by jliljebl** [comment]
> Kdenlive's spacer tool. Check this video to see how it works. This is absolutely perfect and a real 

@niveK77pur So Flowblade does have *Spacer* tool, works the same is even named the same. How come you are unable to find it from tools dropdown menu.?

If for some reason Spacer tool is not available currently in your tool selection, use the Workflow menu available from Flowblade icon in left side of middlebar to activate it.

**Comment by niveK77pur** [comment]
It wasn't in the tools dropdown menu but I found it in the Workflow menu :+1:
My bad, it somehow never caught my attention, thank you @jliljebl !

**Comment by jliljebl** [comment]
Alrighty, closing.
