### ISSUE TITLE
JKL Scrubbing faster speed No Audio

### ISSUE THREAD

**Issue by timbze** [jliljebl/flowblade#795]
Please include the following information.
1) Flowblade version (Help->About): 2.4.0 (installed with Flatpak)
2) MLT version (Help->Runtime Environment): 6.18.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.10

Related: #680 
For JKL scrubbing, once the speed is faster than 1x, there is no audio playing. I know it was working in Flowblade 2.0

**Comment by jliljebl** [comment]
![audiomenu](https://user-images.githubusercontent.com/1823444/71898025-e9f52500-3160-11ea-8a88-6803676dec36.png)
Check *Audio scrubbing* checkbox in the menu above and you will get audio for speeds above 1x.
