### ISSUE TITLE
Video speed and audio out of sync.!

### ISSUE THREAD

**Issue by KamenkoTV** [jliljebl/flowblade#796]
Please include the following information.
1) Flowblade version: 2.2.0
2) MLT version: 6.16.0
3) Your distribution: Ubuntu 19.10

I edited video added a couple of pictures in it audo and when i render it 
video is too fast and oudio is out of sync and then on the end of video there's nothing moving just lagged video i tried using different video codecs nothing works.

**Comment by jliljebl** [comment]
Is it possible to provide a screenshot of timeline showing the situation that causes the problem? I am not able to understand the issue from the given text description only.

**Comment by jliljebl** [comment]
The report is not detaled enough to actionable and no further info was provided closing as *not active*.
