### ISSUE TITLE
Compression artifacts in video that contains screen recordings

### ISSUE THREAD

**Issue by micfe03** [jliljebl/flowblade#797]
Please include the following information.
1) Flowblade version (Help->About):
1.12.0
2) MLT version (Help->Runtime Environment):
6.6.0
3) Your distribution (Ubuntu, Debian, Mint etc.):
Ubuntu
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
I recorded my screen during a presentation with ffmpeg -f x11grab and wanted to stitch it together with a life video recorded during the presentation. Besides the rendering being extremely slow (takes about 10 times the video time on a core i7 7th G), the part of the video with the screen recording suffers from severe compression artefacts which makes the result unusable.
I managed to export to Shotcut via XML and just did the rendering there: Shotcut makes use of all cores instead of only one and therefore needs just twice the time of the video + the resulting file is smaller and contains fewer artefacts.

**Comment by dvdlvr** [comment]
HiI can't comment on the compression artifacts. I never saw them in my projects. It might help if you give more details of the original file info and render settings. As for performance, there is a performance tab in the preferences. Set the number to half of your number of cores (default is 1). That gives the best result for me on 2 different systems. You could experiment a bit to get the optimal setting for your system.

**Comment by micfe03** [comment]
I have deleted the files in the meantime, but I use the screencast- and audioscreen2video-scripts by Steven Gordon. They produce high-quality mp4 files that are fairly small. I did not change any rendering settings from the default ones, except for resolution and framerate.
The artefacts looks like those you gat if you use too aggressive compression in ffmpeg.

**Comment by micfe03** [comment]
... and I checked the setting: Render threads was set to 8.

**Comment by dvdlvr** [comment]
It would most likely give better performance at 4. That's what I use on my i7. Sent from my Huawei tablet-------- Original message --------From: micfe03 <notifications@github.com>Date: Tue, 7 Jan 2020, 10:29To: jliljebl/flowblade <flowblade@noreply.github.com>Cc: dvdlvr <dvdlvrdb@gmail.com>, Comment <comment@noreply.github.com>Subject: Re: [jliljebl/flowblade] Compression artifacts in video that contains screen recordings (#797)... and I checked the setting: Render threads was set to 8.

**Comment by dvdlvr** [comment]
BTW: render threads is an mlt feature. Flowblade just passes the parameter (rt/realtime) to mlt. Sent from my Huawei tablet-------- Original message --------From: micfe03 <notifications@github.com>Date: Tue, 7 Jan 2020, 10:29To: jliljebl/flowblade <flowblade@noreply.github.com>Cc: dvdlvr <dvdlvrdb@gmail.com>, Comment <comment@noreply.github.com>Subject: Re: [jliljebl/flowblade] Compression artifacts in video that contains screen recordings (#797)... and I checked the setting: Render threads was set to 8.

**Comment by jliljebl** [comment]
@micfe03 

> Besides the rendering being extremely slow (takes about 10 times the video time on a core i7 7th G),...I managed to export to Shotcut via XML : Shotcut makes use of all 

Rendered with which settings, Apple Prores, H. 264? I can do direct comparison rendering params if know which Fllowblade setting you used to render.

> The part of the video with the screen recording suffers from severe compression artefacts which makes the result unusable.

Is it possible for you to make sample of this video file available for download so that I can do some testing?

**Comment by micfe03** [comment]
I have found a stub of a rendering attempt that was small enough to send

[movie.zip](https://github.com/jliljebl/flowblade/files/4031008/movie.zip)

**Comment by jliljebl** [comment]
Thanks.

So you rendered as output:
1920 x 1080, 50fps, Mpeg-2 file and Shotcut was multiple times faster in doing that, correct? 

I can look into this now in regards with the render speed issue. 

Do have any of the input files available, that would help with artifact issue?

**Comment by pmjdebruijn** [comment]
(as slightly off-topic sidenote, 50fps is a rather odd choice for screen recordings, given most displays refresh at 60Hz)

**Comment by jliljebl** [comment]
I did a reproduction test with the provided file and movie I made rendered just fine. This maybe fixed with the h264 blank rendering fix we did but otherwise this is just unreproduced.

I'll merge this with render issues sticky thread but I don't see a clear path forward with this.
