### ISSUE TITLE
Flowblade doesn't save correctly if working directory name is changed

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#801]
I have a directory with an .flb file in it. I changed the name of the directory and then opened that same .flb file in flowblade. The program worked fine, doing a relative path search for the resources it needed. I did a few hours' worth of work, then clicked save and closed the program.

Next day I went to open the file again and none of my work had been saved. It appears that flowblade isn't able to detect that the directory has changed names for the purposes of saving.

I find that I have to click save as, as a new file, before flowblade seems to be able to save and autosave correctly again.

This is a trap for young players, which could be gotten rid of so that people don't lose their work.

**Comment by jliljebl** [comment]
Ok, projects have property "last_save_path" which is updated when project is saved, so in the your described sequence of events project will think project file still is located in the earlier location and this can indeed cause problems.

We can detect that load path and "last_save_path" are different and just autosave the project with updated "last_save_path" data into latest load path to avoid the issue. Unless I think of some scenario where doing that would cause other problems I will do that change.

The assumption was that users would do "Save As..." when they are presented with window showing that relative search is happening (to avoid it happening again), but as shown here, this may not always be the case.

**Comment by thennicke** [comment]
Thanks. Yeah I guess the other option is to use the same root directory as the relative file search finds? I don't know how easy that would be to implement, or how reliable the solution would be, so I'll leave that to you.

**Comment by jliljebl** [comment]
I fixed this with autosave on load if project file has moved, we do really need Control+S to save on loaded project file always.
