### ISSUE TITLE
Not an ASCII comment before or before tlineaction.py:1001.

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#803]
The comment "weäre not doing the callback brcause we are not in trim tool that needs" is defined as a non-ASCII comment, and therefore does not allow xgettext to update the translation template flowblade.pot. I think the problem is in the symbol "ä". Removing / modifying a comment solves the problem.
![Screenshot_20200116_141427](https://user-images.githubusercontent.com/26217756/72522341-852b8000-386e-11ea-9e7b-024432a6d478.png)

**Comment by jliljebl** [comment]
Uh, yes, thanks. Python 2 prevented this kind error because it crashed on launch for non ASCII characters. Python 3 seems to allow this  in comments at least. gettext is such an old tool that it knows nothing about Unicode.

I pushed a patch to fix this.
