### ISSUE TITLE
module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by Shamaoke** [jliljebl/flowblade#804]
The [`clock`](https://docs.python.org/3.3/library/time.html#time.clock) method of the `time` module was deprecated in Python 3.3 and was [removed](https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals) in Python 3.8, so the functions of the program related to saving projects, which actively use this method, is completely broken.

One of many examples:

_Media_ → _Right Click to Add Media_ → _Add Video, Audio or Image..._ → choose any clip → _Open_ → _Change To File Profile_ → the program freezes with the following:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/share/pyshared/Flowblade/projectaction.py", line 191, in run
    _save_project_in_last_saved_path()
  File "/usr/share/pyshared/Flowblade/projectaction.py", line 457, in _save_project_in_last_saved_path
    save_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

Linux (Arch); Python 3.8.1; MLT 6.18.0; Flowblade r3132.7730ebed

**Comment by jliljebl** [comment]
I only found 3 lines with *time.clock()*, I'll fix those::

    $ ack time.clock
    mlt.py
    180:mlt_time_clock = _mlt.mlt_time_clock

    Flowblade/projectaction.py
    457:    save_time = time.clock()
    501:        save_time = time.clock()
    757:    save_ago = (time.clock() - save_time) / 60.0

**Comment by jliljebl** [comment]
Alright, fixed in repo.

**Comment by Shamaoke** [comment]
@jliljebl Thank you.
