### ISSUE TITLE
Deprecated lines in dialogs.py

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#805]
The following Compositors - Dissolve, Picture-In-Picture, Region were changed or removed from flowblade, but there are lines with them.
![Screenshot_20200117_163952](https://user-images.githubusercontent.com/26217756/72621655-bc735d00-3952-11ea-9fe9-24b903b1ec8e.png)
It is also advisable to replace Dissolve with another Compositor
![Screenshot_20200117_164110](https://user-images.githubusercontent.com/26217756/72621829-1116d800-3953-11ea-8b9e-54d28cc49350.png)

**Comment by jliljebl** [comment]
Thank you, fixed both with a patch just now. The first one was a dead feature and we got 150 lines deleted, which is great.
