### ISSUE TITLE
where is Compositor "Dissolve" ???

### ISSUE THREAD

**Issue by welon68** [jliljebl/flowblade#806]
Question 1
where is Compositor "Dissolve" ??? is missing?
![fl0](https://user-images.githubusercontent.com/32037656/72661164-73b1b780-39d7-11ea-8c6a-05dae851a293.png)

Question 2

Grey gray selection is missing too ?
![fl1](https://user-images.githubusercontent.com/32037656/72661229-2c77f680-39d8-11ea-82f9-edef917e6350.png)
picture from 2.2

1) Flowblade version flowblade 2.4
2) MLT version 6.18
3) Ubuntu,18.04
4) Simple. Right click on clip :-)

Best regards
Welon

**Comment by smolnp** [comment]
https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/RELEASE_NOTES.md
![Screenshot_20200118_120839](https://user-images.githubusercontent.com/26217756/72661456-58e93e00-39eb-11ea-9f0c-86e7b7e6e176.png)

**Comment by welon68** [comment]
Sorry 
What about question
![fl4](https://user-images.githubusercontent.com/32037656/72663378-7ff73e00-39f2-11ea-8220-1ae003ddc827.png)
 number two? Gray selection is missing ? It's not cool for me :-(

**Comment by jliljebl** [comment]
I think we may have had some Issue with projects moving from 2.2 to 2.4, Go to application menu and select *Sequence->Compositing Mode->Top Down Free Move* and apply "Blend" compositor on clip.

**Comment by jliljebl** [comment]
Closing as *resolved* if there are more related questions using forum is preferred for those: https://github.com/jliljebl/flowblade-forum
