### ISSUE TITLE
seems to have found more dead code

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#807]
![Screenshot_20200118_120839](https://user-images.githubusercontent.com/26217756/72727389-d8b60a80-3b9b-11ea-8770-b3c0b9e840b2.png)

**Comment by jliljebl** [comment]
This one needs to stay for backwards compatibility. When existing projects loaded with Dissolve compositors are loaded they will request this and if we have nothing available in dict we get an error probably making loading those projects impossible.
