### ISSUE TITLE
Function request: Add an option to change the path in the batch rendering window

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#810]
Today, you can change the path to the render file, only through the render tab. And then you can add the item to the batch rendering queue. In my opinion it will be more convenient if you choose the path to the file in the batch rendering window.

![Снимок экрана_2020-01-23_11-05-44](https://user-images.githubusercontent.com/26217756/72967438-61b68700-3dd2-11ea-98b7-0217527c8706.png)

**Comment by jliljebl** [comment]
Alright, i will give this further look sometime during cycle. Not quite sure if we should allow changing path here or later, this does not add absolute capability, this is more of an convenience feature with the always present cost of added code complexity.

**Comment by smolnp** [comment]
Yes, this is just a convenient function, but it will greatly speed up the editing process if you have more than 2 items in the batch queue.

**Comment by jliljebl** [comment]
I'll add a text entry into the dialog to change name, should not be too difficult for 2.6.

**Comment by jliljebl** [comment]
This is in repo now. I added "Change Item Render File Path..." context menu item and changed the dialog to inform about it.
