### ISSUE TITLE
[Request] Export without rendering.

### ISSUE THREAD

**Issue by Neocazen** [jliljebl/flowblade#811]
Congratulations !!!
It would be nice to have this function so that you don't have to resort to other applications (Avidemux or Lossless Cut) for simple cuts in videos.

**Comment by jliljebl** [comment]
MLT does not support this and have stated that they never will. 

We are only doing MLT rendering.Serializing timeline data to some ffmpeg script is a large task and unfortunately we will not be spending development time on it.

Someone should create and app that would read all possible file formats and like MLT XML or EDL then do copy rendering from files.

Closing as *wontix.*
