### ISSUE TITLE
List of bugs and feature requests

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#814]
This is just a list I've been compiling while using the software; just a lot of random things that came to mind, as well as bugs I've observed. Some are easy to implement, others are hard.

* ~~Drag and drop from file manager to media bins should work; especially annoying on multi monitor setups~~ *Drag and drop works on media panel. To target given bin user needs to select it to be active. Making bins on bin list drag and drop targets will require contributions, I consider the current functionality adequate.*
*  ~~Drag and drop from one media bin to another should work with multiple clips selected~~ **invalid**, *user needs just keep CTRL button pressed at drag begin to not do a single select and dragging multiple files works just fine*
* ~~Ctrl-alt-v pastes filters info, but ctrl-alt-c doesn't copy it. Also need a hotkey for deleting all effects, even whilst multiple clips selected.~~ *Wonfix on ctrl-alt-c to copy. I checked and neither Final Cut nor Premiere have that, they have ctrl(or Option)+c to copy. Alt+c now deletes filters from all selected clips.*
* When cutting a clip, filters info is deleted from the newly created second clip
* Dynamic background rendering would be really useful, by instructing system to place caps upon CPU/memory resources -- this way we could use the computer for general tasks whilst rendering, and then when AFK could ramp up the resource allowance to 100%. This feature would also be very useful for proxy rendering (from memory KDENlive doesn't use full system resources when rendering proxies, making it possible to use the computer for other things at the same time).
* ~~Proxy rendering can only be done with clips from a single media bin at once (annoying if we have multiple bins but want to render overnight/AFK for example)~~ Done: https://github.com/jliljebl/flowblade/commit/5f638c107ca0e488adbe21fa0ac94b7c1477b61e
* Some lag (on my mid-range computer) when playback hits a new clip or cut; makes it difficult to check smoothness of cuts (this lag is probably just caused by the same thing that causes scrubbing to be laggy though, because it doesn't occur when editing with proxies)
* ~~Timeline: It should be possible to scroll a little bit past the end of the final clip (when zoomed in), so as to make it easy to drag and drop more clips onto the end~~ Done: https://github.com/jliljebl/flowblade/commit/24e80531ad2f361787c67c89494a6798d1506188
* ~~Cannot right-click on multiple selected clips on timeline. To delete effects for multiple clips it's therefore necessary to go to the edit menu. This isn't well-designed.~~ Done: https://github.com/jliljebl/flowblade/commit/c6c5ade576e679e8a128918eeed1d9c13b9fa3c9
* Box select of clips is not very usable (although I think I remember reading that this would be overhauled).
* Would be nice to be able to save/load groups of filters/effects with set values
* ~~Can't recombine an audio track with a video track~~ * Just realised this isn't a problem, because I realised that splitting audio just mutes the original video clip, which can then be unmuted again.
* ~~Hotkey should exist for resyncing all clips, and for resyncing compositers~~ Done: https://github.com/jliljebl/flowblade/commit/c6c5ade576e679e8a128918eeed1d9c13b9fa3c9
* Timeline cursor context zoom (in and out) doesn't work properly when slip tool is selected
* Position scale is very buggy; starts off offset, does not centre images of non-16:9 aspect ratios, sometimes automatically resets, preventing use. Ken Burns effects look nice though when it does choose to work; much smoother interpolation than the old 'picture in picture' method.
* Position scale would be a lot easier to use if it were possible to zoom out a lot further (zoom in effect is very limited otherwise)

Bugs I've observed, but haven't put effort into replicating
* It is still possible to make weird noises at the end of the sequence (post-render) due to slide-cuts
* Some tools still prevent playback when in use (not the cut tool though)
* Managed to break the "unmute" button somehow

Sorry for such a long and disorganised list, hopefully some of this is useful. Cheers

**Comment by jliljebl** [comment]
On first look these seem largely reasonable, useful and based on pain points felt by an experienced user with good knowledge of the application.

There are quite a few them so it will take at least two development cycles to implement or classify these but overall I can put *In Feature Queue* on this as I believe eventually we will do a large number of them.

**Comment by jliljebl** [comment]
@thennicke I think I got the gist of these mostly but on box selection you say:

> Box select of clips is not very usable (although I think I remember reading that this would be overhauled.

Is there some more detail on on why this is not felt to be useful?

**Comment by jliljebl** [comment]
> Timeline: It should be possible to scroll a little bit past the end of the final clip (when zoomed in), so as to make it easy to drag and drop more clips onto the end

This is done with https://github.com/jliljebl/flowblade/commit/24e80531ad2f361787c67c89494a6798d1506188

**Comment by jliljebl** [comment]
> Proxy rendering can only be done with clips from a single media bin at once (annoying if we have multiple bins but want to render overnight/AFK for example)

This was done with https://github.com/jliljebl/flowblade/commit/5f638c107ca0e488adbe21fa0ac94b7c1477b61e

**Comment by jliljebl** [comment]
> Drag and drop from file manager to media bins should work; especially annoying on multi monitor setups

@thennicke Works here, I have Gnome Shell and Nautilus, is your setup different?

**Comment by jliljebl** [comment]
> * Cannot right-click on multiple selected clips on timeline. To delete effects for multiple clips it's therefore necessary to go to the edit menu. This isn't well-designed.

We now have Alt + C to Clear Filters from all selected clips: https://github.com/jliljebl/flowblade/commit/c6c5ade576e679e8a128918eeed1d9c13b9fa3c9

**Comment by jliljebl** [comment]
> * Hotkey should exist for resyncing all clips, and for resyncing compositers

Resync shortcut is now Alt + R, Compositors already had Alt + S

**Comment by thennicke** [comment]
> @thennicke I think I got the gist of these mostly but on box selection you say:
> 
> > Box select of clips is not very usable (although I think I remember reading that this would be overhauled.
> 
> Is there some more detail on on why this is not felt to be useful?

Because currently it's not possible to move the box selected clips onto a new track. If I want to do this I have to simply ctrl-click all the clips and then move them once they're all selected. I don't know why box select doesn't just select all clips, but instead creates an icon around the clips and prevents track changes.

**Comment by thennicke** [comment]
> > Drag and drop from file manager to media bins should work; especially annoying on multi monitor setups
> 
> @thennicke Works here, I have Gnome Shell and Nautilus, is your setup different?

Yes Gnome shell and nautilus for me, on Fedora 31. I think I got drag and drop working yesterday so this might now be fixed for me. I'll confirm this when I can.

**Comment by thennicke** [comment]
>     * ~Drag and drop from one media bin to another should work with multiple clips selected~ **invalid**, _user needs just keep CTRL button pressed at drag begin to not do a single select and dragging multiple files works just fine_

Okay that's good to know, but I still don't think this will suit new users very well, even if we explain it to them. I would think it is better to just make the behaviour the same as any file manager, so that the user finds it intuitive.

**Comment by jliljebl** [comment]
> Okay that's good to know, but I still don't think this will suit new users very well, even if we explain it to them. I would think it is better to just make the behaviour the same as any file manager, so that the user finds it intuitive.

I get the diff now, file managers unselect all other of current multiple selection on *mouse relese* not on *mouse press* like Flowlbade does. This could actually be changed, I'll give it a go for nexrt release.

**Comment by jliljebl** [comment]
> Because currently it's not possible to move the box selected clips onto a new track. 

Yes, this is because:
  * re-attaching existing Compositors (mlt.Transition) didn't work on MLT (haven't re-tested in years) and we had go through big hacky contortions to get stuff working. This has put me off trying to add any more complexity to Compositors undo/redo behaviour.
  *  Compositors also have target tracks and allowing moving clips to another track with compositors could make compositors have source rtack and target track to be the same.
* We can't allow moving audio clips on video tracks.

Over all if we a) destroy Compositors when moving clips from track to track b) make sure audio clips are not moved to video tracks then we could possibly do this.

Main hurdle is that i don't much "fancy" working this right now, but maybe 2.8 late cycle if there is time I could try, let's see.

**Comment by thennicke** [comment]
> > Because currently it's not possible to move the box selected clips onto a new track.
> 
> Yes, this is because:
> 
>     * re-attaching existing Compositors (mlt.Transition) didn't work on MLT (haven't re-tested in years) and we had go through big hacky contortions to get stuff working. This has put me off trying to add any more complexity to Compositors undo/redo behaviour.
> 
>     * Compositors also have target tracks and allowing moving clips to another track with compositors could make compositors have source rtack and target track to be the same.
> 
>     * We can't allow moving audio clips on video tracks.
> 
> 
> Over all if we a) destroy Compositors when moving clips from track to track b) make sure audio clips are not moved to video tracks then we could possibly do this.
> 
> Main hurdle is that i don't much "fancy" working this right now, but maybe 2.8 late cycle if there is time I could try, let's see.

Yep no problem. I figured audio would be an issue but at least I think you now understand why I find the box select limited in usefulness. Thanks.

**Comment by jep-fa** [comment]
> When cutting a clip, filters info is deleted from the newly created second clip

As said above, a split of a clip remove the audio and brightness filters settings of the new second clip. In the first it's ok.
This is the same result with the _range delete_  tool : if you try to produce the range delete on the end part of a clip and on the start part of the next clip, the filters are kept in the first clip but removed in the next clip. 
Astonishingly, when you use the _trim start_  or _ripple trim start_ with the mouse, the settings of the filters are preserved. 
In which module(s) can I find the explanation ?

**Comment by jliljebl** [comment]
> trim start or ripple trim start with the mouse, the settings of the filters are preserved.
In which module(s) can I find the explanation ?

@jep-fa I missed this comment, the module in question is *edit.py* . Technical explanation is simple: cut creates new mlt:Producer object, trims set in/out for an existing one.

**Comment by jliljebl** [comment]
@thennicke Ok,I did a part of these and picked some as to-do items on own next/later/longterm lists. I think we will get more of these for 2.8. Closing this item as *fixed* even if only got some done, but this kind of list Issue is bit unwieldy to keep track even if we got a lot of good feedback.

You can always reopen items that were here as single Issues if you feel they should get more attention.

**Comment by jep-fa** [comment]
@jliljebl Thanks. I'll try to add the filters to the cut action which is really a split action.
