### ISSUE TITLE
Broken light theme in release 2.4

### ISSUE THREAD

**Issue by gombosg** [jliljebl/flowblade#815]
Hi, version is 2.4 in Fedora RPMFusion.
Light theme is broken due to missing `compositor_icon.png`.
Apparently this has been fixed in [f2fd90](https://github.com/jliljebl/flowblade/commit/f2fd9037ba9059eed1f6f661052f7a6430077411).

Are you planning to release a patched version (2.4.1) so that downstream RPMs can be updated?

[RPMFusion bug](https://bugzilla.rpmfusion.org/show_bug.cgi?id=5529)

**Comment by jliljebl** [comment]
Hi, I have a fix breach for that and an other fix here: https://github.com/jliljebl/flowblade/commits/release-2-4-fix

Could just use the latest commit there: https://github.com/jliljebl/flowblade/commit/6a180252261b94b72959ac8fa562c916c99ecfaf ?

**Comment by gombosg** [comment]
Thanks for the quick response! I'm not the maintainer but the maintainers can also decide to package any commit snapshot.

Generally downstream maintainers don't have the capacity to keep track of branches and package snapshots, because they often maintain dozens or hundreds of packages. Also, they probably won't know when it would be safe to release some branch.

As an upstream developer, downstream package maintainers expect you to mark a commit every now and then as some patch release (AFAIK Github makes that easy), when you think that it's warranted (i.e. contains fixes for some breaking bug or a bunch of unreleased fixes). This way, they will know when to release a new package version.

Otherwise they will probably won't know about fixes and users (like me) will run into bugs that could be avoided.

It would be appreciated if you could adopt this scheme - the Flatpak releases are good, but many users prefer the small footprint and convenience of native packages, which are widely available for this great piece of software.

**Comment by jliljebl** [comment]
Allright, I tagged and pushed this: https://github.com/jliljebl/flowblade/releases/tag/v2.4.0.1-fix_release

All the version strings say 2.4.0 but as this only has 2 patches I think that is okay, this *is* now the 2.4 release from the project point of view. Hopefully packagers understand to pick this up. There is also some added info on front page.

**Comment by gombosg** [comment]
Awesome, thanks! Yes, the only important thing is that each released version must have a larger version string to not confuse package manager apps.
