### ISSUE TITLE
buttons far too small

### ISSUE THREAD

**Issue by axd1967** [jliljebl/flowblade#818]
Please include the following information.
1) Flowblade version (Help->About): 1.12.0
2) MLT version (Help->Runtime Environment): 6.6.0
3) Your distribution (Ubuntu, Debian, Mint etc.): KUbuntu
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

the buttons are far too small for use on a laptop!

![image](https://user-images.githubusercontent.com/3529789/75635546-55b2b600-5c17-11ea-84f5-71c4793edddb.png)

**Comment by dvdlvr** [comment]
In the preferences there is a double-height setting that will also enlarge the buttons. Sent from my Huawei tablet

**Comment by axd1967** [comment]
ok - where is tat?

![image](https://user-images.githubusercontent.com/3529789/75636354-48e59080-5c1e-11ea-97f0-29de13f78845.png)
![image](https://user-images.githubusercontent.com/3529789/75636356-513dcb80-5c1e-11ea-8ee8-e1cecf8068db.png)

![image](https://user-images.githubusercontent.com/3529789/75636363-6286d800-5c1e-11ea-9fe9-78699ab7257e.png)

**Comment by dvdlvr** [comment]
I'm not near my computer. Can't check. It may have been introduced in a later version. You are well behind. The current version is 2.4. I suggest you upgrade. Sent from my Huawei tablet

**Comment by jliljebl** [comment]
@axd1967 What is your screen resolution, do you have a HiDPi screen?

Flatpak for version 2.4 should available for Kubuntu, you should try that and see if the problem stays the same.

**Comment by jliljebl** [comment]
This is not going to get  attention in the near future, if decide to re-layout tracks column with icons presented horizontally, then we will get about 2X hit target sizes here.
