### ISSUE TITLE
Recommended Desktop and Distro

### ISSUE THREAD

**Issue by dpack4** [jliljebl/flowblade#820]
Next month, new LTS versions of Linux distros will be coming out. I wanted to ask which distribution (Ubuntu, Debian, Mint, etc.) and which desktop environment (Unity, Xfce, LXQT, MATE, Gnome, etc.) is best supported for Flowblade for stability and rendering performance? The different desktop environments all have different setups and may require additional dependencies to be installed depending on which one is used. I believe it would be best to get the one that has most if not all needed dependencies. (PS - I stick with Debian based distros. I do not care for Fedora/CentOS/Arch/OpenSUSE etc.)

**Comment by jliljebl** [comment]
Hi, Flowblade is being developed on latest Ubuntu with Gnome Shell as DE. This should not make much difference on stability compared to other main distributions. 

Based on information from Issues list here we have had some more issues with Gentoo and Kde Neon distributions, so those may not be the best choices for running Flowblade.
