### ISSUE TITLE
Two buttons to position playhead at start or at end of the timeline

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#821]
This is a new feature. 
I added two buttons in the transport widget (PlayerButtons class) because I often use these functions. I prefer use the mouse rather than the keyboard.

![Écran start end_reduit](https://user-images.githubusercontent.com/61981966/76515063-3d356d80-6459-11ea-80af-e4352c79071d.jpg)

Modified files - glassbuttons.py, editorwindow.py, monitorevent.py, movemodes.py

1) Flowblade version 2.4.0
2) MLT version 6.21.0
3) Distribution Ubuntu 19.10

**Comment by jliljebl** [comment]
Hi, so you need to do a pull request so that I can see if the code looks ok and then I can merge. There isn't any particular reason for me to not merge a feature that does what you are describing here, but I may make it optional so used needs to set a preference to get buttons displayed.

**Comment by jliljebl** [comment]
We got contribution for this, will be in 2.6
