### ISSUE TITLE
Feature Request - Added to Timeline Indicator

### ISSUE THREAD

**Issue by dpack4** [jliljebl/flowblade#822]
Please include the following information.
1) Flowblade version (Help->About): 2.2
2) MLT version (Help->Runtime Environment): 6.6.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.04.4
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

It would be nice to have an indicator mark on the video thumbnail to show when it is added to the timeline. If we have multiple videos imported for editing, it can be easy to lose track which ones are on the timeline and which are not. A simple check mark, bullet, or other icon added to the media thumbnail to indicate "This is currently on the timeline" would be great. At a glance, the user will be able to tell which video has not been added to work on yet. I created a mock up example of what could possibly be shown for videos when added to the timeline: Green check in top right corner of imported video thumbnail.

![Sample Image](https://user-images.githubusercontent.com/59346602/76537044-913d5380-6453-11ea-8074-c0b936976c2c.png)

**Comment by jliljebl** [comment]
I looked around and Premiere, Avid and Final Cut X all seem to have some version of this feature, so we should add it since it has been widely considered useful.

They all had different visual representations and some needed user action to be taken to get the info displayed. Your suggestion might be too heavy visually for this so we may choose same other way to convey the information.

Not sure if this makes it for 2.6, 2.8 seems quite likely, 2.6 is still possible.

**Comment by dpack4** [comment]
Thanks! 2.8 is fine. I'd rather the voice over capability be implemented first. (#793)

**Comment by smolnp** [comment]
I think the presentation in the form of numbers would be more useful. That is, to Flowblade to report how many times I added a clip to the timelane.

**Comment by jliljebl** [comment]
@smolnp I did a 2 minute test on your suggestion, it is an possible approach if we do only '1'-'9' and maybe '+' for >= 10 items on time line.  I will anyway make this optional from the hamburger menu with a check menu item.

**Comment by jep-fa** [comment]
You can also change the color of the name of the media in the media panel rather than a check symbol on its thumbnail (2020-03-12 10-1.. as shown above). For example change white in green when the media is in the timeline.

**Comment by jliljebl** [comment]
@jep-fa Changing clip name color would in my view result in a somewhat restless visuals, the @smolnp suggestion would best get us the "information available but not distracting" thing we are looking for, see test below.

![media_tline](https://user-images.githubusercontent.com/1823444/77146233-421aa280-6a93-11ea-9e11-ce4024c5070f.png)

**Comment by jep-fa** [comment]
I found an another way to show the unused files in the timeline : I added an item menu in the pop menu to show the visible media files by type (All, video, audio, graphics, ..., unused).
Does that suit you in the meantime?
![Unused](https://user-images.githubusercontent.com/61981966/81467503-4896e200-91d9-11ea-8a6f-711edf059469.png)

**Comment by jliljebl** [comment]
@jep-fa  Your idea is the best solution proposed so far and has the additional benefit of not requiring full timeline computation after every edit. 

Adding icons to Media Panel objects will always be visually messy and users will not know immediately what the displayed number means,  whereas your solution gives complete information in textual form on what is being displayed.

We will do this, not the icon thing.

**Comment by jep-fa** [comment]
Thanks. I'll make a merge request.

**Comment by jliljebl** [comment]
Feature was added via PR from @jep-fa implementing his design.
