### ISSUE TITLE
Failing to load projects with assets located in folder special charachers

### ISSUE THREAD

**Issue by F4FXL** [jliljebl/flowblade#823]
Please include the following information.
1) Flowblade version (Help->About): 2.4, installed fro, debian testing
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.):Debian Testing
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
I have a project created with earlier version of FlowBlade. I have several images, videos located in folders with accents e.g. "Vidéo". Flowblade fails to load them.

**Comment by F4FXL** [comment]
![image](https://user-images.githubusercontent.com/5264350/76685799-bfb75c00-6616-11ea-976f-d4c802e50c49.png)
![image](https://user-images.githubusercontent.com/5264350/76685818-f2615480-6616-11ea-91d2-2aa34e8d2048.png)

**Comment by F4FXL** [comment]
Creating a brand new project works fine.

**Comment by jliljebl** [comment]
Ok, this some special case where moving from Python 2 bytearray strings to Python 3 UTF-8 strings fails. We did testing and fixed multiple relates issues but not all it seems.

Can you post the path string displayed in the error message here, I think the comment boxes support unicode?

**Comment by F4FXL** [comment]
Not sure to understand what you want from me
The path contains the word **vidéo** (note the accent on the e)
Here is a screenshot of an older project in hex editor, highlighted is the **é** char :
![image](https://user-images.githubusercontent.com/5264350/76707286-20fe2e80-66ee-11ea-88b3-b446b300c7e5.png)
Same screenshot of freshly created project:
![image](https://user-images.githubusercontent.com/5264350/76707305-5acf3500-66ee-11ea-9dc5-b75d1b1783a8.png)

**Comment by jliljebl** [comment]
Thanks, knowing that the word 'vidéo' is at fault here is enough for reproduction attempt.

Screenshot has some corrupt version of the word so having the correct string available is useful.

**Comment by jliljebl** [comment]
Closing this as  *wontfix*. Everything has moved from Python 2 to Python 3 and I'm having difficulties in testing Python 2 versions of Flowblade now.

Unfortunately this error was part of the cost of moving to Python 3. We didn't fully succeed in doing the switch without some adverse effects on users, but now we just have to move on.
