### ISSUE TITLE
keyframe interpolation

### ISSUE THREAD

**Issue by mandhaniya** [jliljebl/flowblade#827]
Please include the following information.
1) Flowblade version (Help->About): **2.4**
2) MLT version (Help->Runtime Environment): **6.18.0**
3) Your distribution (Ubuntu, Debian, Mint etc.): **MX linux 19.1**
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
...........................

+) Please help me how can I find keyframe smoothness or bezier curve option in editor
How to change linear key frame to smooth

+)  And please add customization option for flowblade interface with mouse drag and drop (like timeline, preview , filter, all).... In present layout I have to scroll down again and again for applying effects..

**Comment by jliljebl** [comment]
> +) Please help me how can I find keyframe smoothness or bezier curve option in editor
How to change linear key frame to smooth

So this is a feature request for Bezier curve keyframes. We currently only have linear keyframes but curve keyframes will be added.

> +) And please add customization option for flowblade interface with mouse drag and drop (like timeline, preview , filter, all).... In present layout I have to scroll down again and again for applying effects..

This is a bit unclear to me. Do you mean a Drag'n'Drop source panel for filters like in e.g. Final cut X below?

![FCPX-dnd-panel](https://user-images.githubusercontent.com/1823444/77853470-f1225100-71ec-11ea-9e40-047c213b247d.jpg)

If yes, I have some tests on this feature on a branch and we will eventually do this sometime.

**Comment by mandhaniya** [comment]
First of all I really thank u for having my view .

Yes.. I means to say in present flowblade timeline, preview or filter panels have fixed position ..want to Drag'n'Drop option to change the position even width & height also..Like Final cut X

**Comment by jliljebl** [comment]
I watched a video on custom Final Cut X workspace layouts. 

Totally free positioning and layout of panels is not going to come in one big new feature.  We will move forward with some incremental improvements like adding drag'n'drop source panel for Filters.

Long term we could end up with a quite heavily customizable window layout but it will take time before we have anything like what is available on Final Cut X currently.

**Comment by jliljebl** [comment]
We now have all the interesting bits of keyframe interpolation in repo, feature will be in 2.10. Customizable layout has already been added.
