### ISSUE TITLE
flowblade-2.4.0.1 fails while creating user folders

### ISSUE THREAD

**Issue by juanitotc** [jliljebl/flowblade#830]
The following occurs whether or not xdg-user-dirs-update has been run.

Commenting out a couple of lines in Flowblade/userfolders.py allows flowblade to start, but some of the folders under ~/.flowblade and ~/.local/share are not created.

```
#    if not os.path.exists(utils.get_hidden_screenshot_dir_path()):
#        os.mkdir(utils.get_hidden_screenshot_dir_path())
```

```
./flowblade
MLT found, version: 6.20.0
numpy version: 1.16.3
Application version: 2.4.0
OS: TinyCoreLinux 11.1
Python 3.6.9 (default, Dec 11 2019, 17:44:28) 
[GCC 9.2.0]
GTK+ version: 3.24.13
CREATED XDG CONFIG DIR.
CREATED XDG DATA DIR.
XDG user data exists.
userfolders.init():  UNABLE TO CREATE XDG FOLDERS! Usinf .flowblade dir forced!
Traceback (most recent call last):
  File "./flowblade", line 93, in <module>
    app.main(modules_path)
  File "/usr/src/flowblade-2.4.0.1-fix_release/flowblade-trunk/Flowblade/app.py", line 164, in main
    userfolders.init()
  File "/usr/src/flowblade-2.4.0.1-fix_release/flowblade-trunk/Flowblade/userfolders.py", line 90, in init
    _maybe_create_dot_dirs()
  File "/usr/src/flowblade-2.4.0.1-fix_release/flowblade-trunk/Flowblade/userfolders.py", line 142, in _maybe_create_dot_dirs
    if not os.path.exists(utils.get_hidden_screenshot_dir_path()):
AttributeError: module 'utils' has no attribute 'get_hidden_screenshot_dir_path'
```

**Comment by jliljebl** [comment]
Was just on machine and fixed this. Seems that  TinyCoreLinux does not support  xdg user directories specification. I will eventually remove support for dot dirs for user data, so to keep this and many other applications working TinyCoreLinux should support xdg user directories.

**Comment by juanitotc** [comment]
OK - thanks

Note the problem occurred with and without xdg user directories being set up.

**Comment by jliljebl** [comment]
There is this line in your print out:

    userfolders.init():  UNABLE TO CREATE XDG FOLDERS! Usinf .flowblade dir forced!

So something went wrong with xdg folders handling and I'm 99% sure that problem is with  TinyCoreLinux, not Flowblade app code.

I will be removing the dot dirs option for 2.6, there is no good reason to keep supporting it anymore, if something goes wrong with xdg dirs we will display info and refuse to run.

**Comment by juanitotc** [comment]
xdg-user-dirs-update was run before ./flowblade - is something more than this required?

(gnome-3.36.0 runs fine with only xdg-user-dirs-update)
