### ISSUE TITLE
Rendering to a nonexistent directory causes rendering to go on indefinitely, with no error message

### ISSUE THREAD

**Issue by DaMightyZombie** [jliljebl/flowblade#832]
1) Flowblade version: 2.4.0
2) MLT version: 6.20.0
3) Your distribution: Manjaro Linux 64bit, KDE Plasma DE
4) Steps to reproduce:
- Select a new folder as output for rendered movies
- Rename or delete the folder
- Render a movie
-> The progress bar will forever remain at 0%, and no error message is shown.

**Comment by jliljebl** [comment]
Confirmed and fixed. We will just auto create missing folder, no info windows.
