### ISSUE TITLE
Couple of minor bugs

### ISSUE THREAD

**Issue by domotic-29** [jliljebl/flowblade#833]
1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Manjaro

1- When we "enable single Play/Pause button", the information displayed when we put the mouse over the buttons is not updated, it always act as if there were two buttons for Play / Stop
![Infomisplaced](https://user-images.githubusercontent.com/30129045/78908497-74139900-7a82-11ea-9e4a-0196daafb58b.png)
Here the mouse is over the ] so it is suppose to say "Mark In - I"

2- When creating a compound clip, the default file name suggested has the extension .xlm. When saving the file, the extension is added again, so the result file has it twice (filename.xml.xml).

**Comment by jliljebl** [comment]
Thanks.

1) This was fixed recently by pull request adding optional new buttons: https://github.com/jliljebl/flowblade/pull/825/commits/a3d751cb9064975eb007cff423a15e95ad98c745

2) I just pushed a patch to fix this.
