### ISSUE TITLE
Flatpak: Cannot open Batch Render Queue window

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#835]
Flowblade 2.4.0
MLT 6.18.0
Fedora 31, gnome shell

Cannot open batch render queue window, either by clicking it in the render menu, or by clicking the icon next to the G'Mic effects icon. No errors are showing up in the terminal window for me.

**Comment by jliljebl** [comment]
Are you running Flatpak? See from menu *Help-> Runtime Environment* if not sure.

**Comment by thennicke** [comment]
Yes I am. Sorry I should've clarified that. Also all other windows (mixer, titler, Gmic) work as expected. Just the batch render queue window.

**Comment by dvdlvr** [comment]
The log file for the flatpak installation is:
$USER_HOME/.var/app/io.github.jliljebl.Flowblade/cache/flowblade/log_batch_render

It contains the following errors:
Traceback (most recent call last):
  File "/app/share/flowblade/Flowblade/launch/flowbladebatch", line 16, in <module>
    batchrendering.main(modules_path)
  File "/app/share/flowblade/Flowblade/tools/batchrendering.py", line 388, in main
    _dbus_service = BatchRenderDBUSService()
  File "/app/share/flowblade/Flowblade/tools/batchrendering.py", line 210, in __init__
    bus_name = dbus.service.BusName('flowblade.movie.editor.batchrender', bus=dbus.SessionBus())
  File "/app/lib/python3.7/site-packages/dbus/service.py", line 131, in __new__
    retval = bus.request_name(name, name_flags)
  File "/app/lib/python3.7/site-packages/dbus/bus.py", line 303, in request_name
    'su', (name, flags))
  File "/app/lib/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

**Comment by jliljebl** [comment]
Ok, Flatpak sets its own XDG variables. I thought those were user/os controlled, guess not.

This should be straightforward to fix, I just need to set:

    --socket=system-bus or --socket=session-bus

In Flatpak build file.

Thanks.

**Comment by jliljebl** [comment]
Okay, this is now working on my local test Flatpak. Flatpak for point release 2.6.1 will contain the fix for this.
