### ISSUE TITLE
Off by one error on transitions

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#836]
Flowblade 2.4.0

Putting an 8 frame transition in returns a 9 frame rendered transition clip, which shunts the following clips on that track to the right by 1 frame. The last frame in the transition seems to be exactly identical to clip B, so can be safely removed.

This error occurs with all types of transitions I've tried (dissolve, fade) and seems to also happen for all codecs.

**Comment by jliljebl** [comment]
I believe you mean frames, ms(milliseconds)?

**Comment by thennicke** [comment]
Yes sorry, 8 frame. My mistake. I'll correct it.

**Comment by jliljebl** [comment]
Also, these are rendered single track transitions, not Compositors?

**Comment by thennicke** [comment]
Yes, rendered single track transitions

**Comment by jliljebl** [comment]
Ok,will look. I don't what is going on, this the exact thing I've always looked at with these.

**Comment by jliljebl** [comment]
Fucking hell yeah, don't when this broke. This is the first you test when creating a feature like this. I have half a mind to nuke the feature, never used it myself.

**Comment by thennicke** [comment]
Just to add some more detail to this bug:
- Creating both a 7-frame and an 8-frame transition yields the same length transition (8 frames). This is unexpected behaviour. If we are only able to create even-sized transitions we should tell that to the user in the prompt.
- When creating the transition it creates its own audio track. Using the keyframe tool to try to fade the audio levels from 0 to 100 works for fade outs, but not for fade ins. This is because two duplicated frames are added at the end of the transition, whereas only one is added to the start (stretching the clip out by its handles demonstrates this). Proper behaviour should be that no duplicate frames are added to either end at all, and that the clip is only the length the user entered into the prompt.

I use this feature a lot, so please don't nuke it (or if we do, we need some other method to replace it -- I know a lot of editors use keyframes for their transitions).

**Comment by jliljebl** [comment]
Oh, now I get it. Its the Python 3 conversion with "/" and "//" divisions. I never understood why they had to change how division works. Well, that gives a method for trying to fix this, look where we get different values out of divisions in Python 2 and 3 in the relevant code.

**Comment by jliljebl** [comment]
Ok, I got it working again. This is 100% about semantics changing from under the application, mainly suspevting Python2 -> 3 transition but not wholly sure.

> When creating the transition it creates its own audio track. Using the keyframe tool to try to fade the audio levels from 0 to 100 works for fade outs, but not for fade ins. This is because two duplicated frames are added at the end of the transition, whereas only one is added to the start (stretching the clip out by its handles demonstrates this). Proper behaviour should be that no duplicate frames are added to either end at all, and that the transition clip is only the length the user entered into the prompt.

We have to use MLT in a certain way to get the transition rendered correctly and the handles at the beginning and end are quite compulsory, I don't see any other way to pull this functionality from MLT. I'll add item on my long term dev items list to see if there is some improvement here.
