### ISSUE TITLE
G'Mic Video Render Step Hangs at 94%.

### ISSUE THREAD

**Issue by DroWnThePoor** [jliljebl/flowblade#838]
Please include the following information.
1) Flowblade version (Help->About): 2.4 Flatpak
2) MLT version (Help->Runtime Environment): Flatpak
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.04
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

When using the G'MIC with video-encoding the video render hangs at 94%. The video file appears in the directory and plays, but is all black. The frames folder populates with the rendered frames indicating G'Mic succeeds.
I've only tested this on very short 3-5 second clips in lossless .mp4.

**Comment by jliljebl** [comment]
Ok, this may be Flatpak specific, will need to investigate.

**Comment by ullika** [comment]
I have the same issue with varying percentages also in 2.4 flatpak RE on nixos. i can solve it by avoiding empty space before the first clip and between the clips

**Comment by jliljebl** [comment]
I think this is fixed now, code didn't handle spaces in paths correctly as @ullika observed, and this likely is not Flatpak related. I will close as fixed and test later with Flatpak, reopen if needed.

**Comment by DroWnThePoor** [comment]
When will you be publishing 2.6.1 Flatpak? I ended up removing my Flatpak to revert to older .deb's and they can't unpickle my projects, so then I tried the latest git and it complains about missing MLT or python3-mlt on 18.04.
