### ISSUE TITLE
Flowblade 2.4.0.1

### ISSUE THREAD

**Issue by mandhaniya** [jliljebl/flowblade#840]
Please include the following information.

    Flowblade version (Help->About): 2.4
    MLT version (Help->Runtime Environment): 6.18.0
    Your distribution (Ubuntu, Debian, Mint etc.): MX linux 19.1
    If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
    ...........................

How to install the latest Flowblade 2.4.0.1 only source code present.

**Comment by jliljebl** [comment]
We only have Flatpak but I will need look this week if the fixes actually got pushed though from flathub, I might have not updated all necessary data to get Flatpaks updated.

2.6 will come with .deb package available as MLT 6.18 will be widely available.

**Comment by jliljebl** [comment]
I'm closing this as *wontfix* because we can't spend time on any more point releases before next release. Next release will come with .deb again and a lot bugs fixed that were present with e.g Position Scale GUI editor.
