### ISSUE TITLE
fitting flowblade window full for 1600x900 fails

### ISSUE THREAD

**Issue by speefak** [jliljebl/flowblade#841]
Please include the following information.
1) Flowblade version (Help->About): 2.0.0 
installed from : https://github.com/jliljebl/flowblade/releases =>> flowblade-2.2.0-1_all.deb =>> but installed version is 2.0.0 - Version should be 2.2.0 instead 2.0.0 ?!
2) MLT version (Help->Runtime Environment): 6.16.2
3) Your distribution (Ubuntu, Debian, Mint etc.): Debian 10 / Gnome shell / X Sever
4) Flowblade windows is wider than screen (1600x900), fullscreenmode doesn`t work, window maximize buttons is missing .

![Bildschirmfoto von 2020-04-14 00-12-18](https://user-images.githubusercontent.com/63617780/79166279-14e8b800-7de5-11ea-9bc9-574e4e34ba91.png)
![Bildschirmfoto von 2020-04-14 00-11-56](https://user-images.githubusercontent.com/63617780/79166282-16b27b80-7de5-11ea-99fb-c696ebf3c4d3.png)
![Bildschirmfoto von 2020-04-14 00-11-11](https://user-images.githubusercontent.com/63617780/79166286-17e3a880-7de5-11ea-85af-d2029897d799.png)

4) Flowblade windows is wider than screen, fullscreenmode doesn`t work, and windowmaximize buttons is missing

**Comment by alexmyczko** [comment]
I'd recommend to use the latest debian package, built from source (it's called simple sid backport):

```
1. dget http://deb.debian.org/debian/pool/main/f/flowblade/flowblade_2.4.0.1-2.dsc
2. dpkg-source -x flowblade_2.4.0.1-2.dsc
3. cd flowblade*/
4. debuild
5. cd ..
6. dpkg -i flow*.deb
```

**Comment by jliljebl** [comment]
For 2.4 we did a fix for 900px height screens, those sort of dropped through the cracks of our code that sets panel sizes for different screen dimensions. 

I  tested this on my system just now and everything seems good. I'm closing this as fixed. If version 2.4 or higher still has problems in 900px height screens, please comment here and I'll reopen.
