### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#843]
Please include the following information.
1) Flowblade version (Help->About): 2.4 **Flatpak** 
2) MLT version (Help->Runtime Environment): 2.18
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Go to preferences. Set light theme and double icon sizes.

  File "/app/share/flowblade/Flowblade/tlinewidgets.py", line 347, in load_icons
    COMPOSITOR_ICON = guiutils.get_cairo_image("compositor_icon")

Flowblade will not start up anymore.
Missing icon: compositor_icon@2.png

**Comment by dvdlvr** [comment]
![compositor_icon@2](https://user-images.githubusercontent.com/7942463/79987008-2e58c680-84ad-11ea-85cf-dd2b2abe49d4.png)
I have multiple commits in my repository that I don't want to upload to master so I attached the missing file, to go into the res/img and res/darktheme directory. Same icon for both.

**Comment by dvdlvr** [comment]
Created pull request #844 to add the 2 icons.
With that, you can ignore the previous comment.

**Comment by jliljebl** [comment]
Fixed by #844 as stated, closing. I've tried to remember to add these but seems that not with complete success.
