### ISSUE TITLE
Flowblade 2.4 splash screen

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#846]
Please include the following information.
1) Flowblade version (Help->About): 2.4 Flatpak
2) MLT version (Help->Runtime Environment): 2.18
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 19.10
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easiest way to understand what is happening.:
Start up application with Splash screen.

Splash screen still shows 2.2 as version.

**Comment by jliljebl** [comment]
Ok, fixed. I never use the light theme during development anymore, and just failed getting the resources updated properly last time. Well, we have good time to do testing and bug fixes this time as I'm not adding anymore features, so I think next release will be better.
