### ISSUE TITLE
Flowblade in DE Cinnamon does not expand to full screen

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#850]
Flowblade in DE Cinnamon does not expand to full screen (fedora 31, Flowblade Master, mlt 6.20.0).

**Comment by smolnp** [comment]
also in cinnamon rendering lasts longer than in xfce and lxde / lxqt

**Comment by smolnp** [comment]
![Снимок экрана от 2020-04-27 07-01-29](https://user-images.githubusercontent.com/26217756/80332960-21452a00-8855-11ea-8124-3a4da762df7b.png)

**Comment by smolnp** [comment]
Launched in xfce
![Снимок экрана_2020-04-27_07-06-21](https://user-images.githubusercontent.com/26217756/80333159-cfe96a80-8855-11ea-9bb7-f7503df91f1c.png)
Works properly

**Comment by jliljebl** [comment]
Is the Cinnamon thing some multi-monitor set-up?

Does changing *Edit-> Preferences,* *View panel 'Do GUI layout based on"* combobox value help?

When launching from terminal, what do you get for these lines?

    ---
    Gtk version is 3.24.12, Flowblade theme is available.
    Using Full Screen size for layout: 1920 x 1080
    ---


Do other Gnome apps like Gimp behave well?

**Comment by smolnp** [comment]
"Does changing Edit-> Preferences, View panel 'Do GUI layout based on" combobox value help?" - Thanks, everything now works as it should
