### ISSUE TITLE
Autosaving causing single thread 100% CPU usage?

### ISSUE THREAD

**Issue by adworacz** [jliljebl/flowblade#851]
Please include the following information.
1) Flowblade version (Help->About): 2.4.0.1 (installed via ArchLinux AUR)
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Manjaro
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
1. Start Flowblade from Terminal (or using launcher, either way)
1. Load an existing project
1. Open up Htop (or similar).
1. Do nothing in flowblade (just wait).
1. Note autosaving start in Terminal, and CPU usage spikes in a single thread to 100%.

See screenshot below.

![2020-04-28-082326_3440x1440_scrot](https://user-images.githubusercontent.com/561689/80507057-3f7d5980-892b-11ea-9f6b-f77cc6084833.png)

**Comment by jliljebl** [comment]
Not sure about underlying issues causing this. Does not reproduce here but there could be something. 

Manjaro has for some reason been really bad distro for us, not sure why.

**Comment by jliljebl** [comment]
Closing as *unreproduced*. Manjaro and Gentoo seem to present users with non-functional Flowblade very often. I will reopen if we get reproductions from non-Manjaro distros.

**Comment by adworacz** [comment]
Sounds good. I’ll try messing around with the git/source version of Flowblade to see if I can reliably debug the issue.
