### ISSUE TITLE
UI request: please zoom timeline in/out leaving the cursor where it is

### ISSUE THREAD

**Issue by duanev** [jliljebl/flowblade#854]
(2.4, MLT 6.20.0, GTK 3.24.17, Arch)

Sometimes while zooming the timeline the cursor moves out of view completely, sometimes it moves to near the beginning of the window ...  would prefer if the zoom was centered around the cursor so that it stays where it is during zoom.

**Comment by jliljebl** [comment]
I can observe cursor moving closer to beginning of the window sometimes but not out of view.

I'm mostly happy with the current behavior but perhaps there is room for improvement. I will try out  new behaviors some time in the future, but unless I can identify a clear improvement we will leave this as is.

**Comment by jliljebl** [comment]
For this issue I found an improvement already for 2.10, but forgot mark this as 'fixed', closing now.
