### ISSUE TITLE
Render Slow/Fast Motion ignored Mark In / Mark Out

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#855]
Flowblade 2.0.4.1, MLT 6.20.0, Ubuntu 20.04

When I set a Mark In en Mark Out on a video fragment, and then 
Export to Tool
Render Slow/Fast Motion Video File
Speed: 50%
Render Range: Source Mark In to Mark Out

I get an MOTION file that is 2x the length of the entire source clip
As opposed to a MOTION file that is 2x the length of the marked region (which is ~3 seconds), so I  would have expected a MOTION clip that is 6-7 seconds long.

**Comment by pmjdebruijn** [comment]
I just noticed that Source Mark In and Source Mark Out does actually work, it just doesn't work like I expected it to.

That make this effectively a feature request...

It would be rather nice, if it were possible to render a slomo video based on the regular Mark In / Mark Out on the timeline...

**Comment by jliljebl** [comment]
> It would be rather nice, if it were possible to render a slomo video based on the regular Mark In / Mark Out on the timeline...

We got something similar to this for timeline clips. From clip pop-up select *Export to tool -> Slow/Fast Motion*. Source Mark In and Source Mark Out get set to clip's in/out and now you can render slow fast motion for clip range

Going *wontfix* on this as we already have 2 ways to set render range for motion clips, Clip Monitor and the way above.

I don't believe making Timeline Mark In / Mark Out part of the equation adds much extra value and this would necessitate another error dialog as it is possible for Mark In/out be out of clip media range.

We already have thousands of lines of error dialogs making getting new translations less likely to happen as potential contributor can get overwhelmed., I have taken a position to try to avoid adding any more whenever possible.
