### ISSUE TITLE
Bad behaviour & hang during "Copying user data to XDG folders" - first use

### ISSUE THREAD

**Issue by pc-bil** [jliljebl/flowblade#856]
1) Flowblade version: 2.4.1 Flatpak
2) MLT version: 6.18.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Mint 19.3
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
1. Dowloaded and installed Flatpak using instructions at https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md#2b-install-from-commandline
2. Ran the software using the given command
Notes: This is the very first installation and use of the software

Result: the "Copying user data to XDG folders" window appeared and didn't go away (it's been well over 10 minutes now). In the terminal there is the following:

```
Create SDL1 consumer...
Autosave started...
Saving project...
Copying CONFIG...
Copying DATA...
Copying CACHE...
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/app/share/flowblade/Flowblade/userfolders.py", line 205, in run
    _copy_data_from_dot_folders_xdg_folders()
  File "/app/share/flowblade/Flowblade/userfolders.py", line 223, in _copy_data_from_dot_folders_xdg_folders
    dir_util.copy_tree(_dot_dir + appconsts.GMIC_DIR, get_cache_dir() + appconsts.GMIC_DIR, verbose=1)
  File "/usr/lib/python3.7/distutils/dir_util.py", line 124, in copy_tree
    "cannot copy tree '%s': not a directory" % src)
distutils.errors.DistutilsFileError: cannot copy tree '/home/ben/.flowblade/gmic': not a directory

Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...
Saving project...

```
Apart from the obvious problem of the software not starting, the purpose of the window is not clear. What user data? Why should it take a few minutes? Why does anything need to be copied during the first run of the software?

**Comment by jliljebl** [comment]
We used to have application data *USERHOME/.flowblade* but now application data is where XDG folders are set to be in your system.

The feature that is not working for you was the code that transferred data from *USERHOME/.flowblade* to XDG folders on first launch of new version.

We will be removing all code related to  *USERHOME/.flowblade* 'which will fix this issue for you.

**Comment by jliljebl** [comment]
Maybe we need to keep the data port code until 2.8. I need to do some more testing on Flatpak.

**Comment by pc-bil** [comment]
Thanks for the response. Just testing for the existence of the directory before copying it should be enough to avoid the problem, shouldn't it?

**Comment by jliljebl** [comment]
This is how we launch copy we test existance of the prefs file, not just folder. 

    _dot_dir = os.getenv("HOME") + "/.flowblade/"
   ....
    _dot_prefs_file_exists = os.path.exists(_dot_dir + "prefs" )
    ...
if _dot_prefs_file_exists == True and _xdg_prefs_file_exists == False:
        print("userfolders.init(): .flowblade/ data exists, we need to copy to XDG folders.")
        global _copy_needed
        _copy_needed = True

There has been some

**Comment by jliljebl** [comment]
We have now been using XDG folders for so long that trying to fix Issues relating to porting older projects to XDG folders no longer provides meaningful user value. Closing as 'wontfix'
