### ISSUE TITLE
ERROR: No module named 'processutils'

### ISSUE THREAD

**Issue by phenax** [jliljebl/flowblade#857]
I get the following response when I run `flowblade`
```
$ flowblade
FLOWBLADE MOVIE EDITOR 2.4
--------------------------
Launch script dir: /sbin
Running from filesystem...
MLT found, version: 6.20.0
Failed to import module app.py to launch Flowblade!
ERROR: No module named 'processutils'
Installation was assumed to be at: /sbin/Flowblade
```

* Flowblade version: `2.4`
* MLT version: `6.20.0`
* Distr.: Arch linux

**Comment by jliljebl** [comment]
Well the file is here: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/Flowblade/processutils.py

This is some installation Issue. Did you try to use *setup.py* to install flowblade?

**Comment by jliljebl** [comment]
Closing this one, I'm fully convinced that this is installation issue that cannot be fixed by Flowblade code changes.

**Comment by phenax** [comment]
I tried installing it via `setup.py` but still no luck. Got a slightly different error message this time.

```
FLOWBLADE MOVIE EDITOR 2.4
--------------------------
Launch script dir: /sbin
Running from filesystem...
MLT found but version info not available. MLT probably too old to work reliably...
Failed to import module app.py to launch Flowblade!
ERROR: No module named 'processutils'
Installation was assumed to be at: /sbin/Flowblade
```
