### ISSUE TITLE
Delete a media in the MediaPanel erases all the medias

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#858]
Flowblade 2.4.0 developpement environnement
MLT 6.21.0
GTK 3.24.18
Ubuntu 20.04

Operations :
1. Visible media files type : All

- Select a media - right click on the media
- In the pop menu choose Delete
- The media is deleted

That's ok

2. Visible media files type : Video or audio or graphics

- Select a media - right click on the media
- In the pop menu choose Delete
- All media are erased and no operation is allowed in the MediaPanel even if we come back to  Visible media files type : All

In the bin, the number of files decreases by one, so I think it is a view issue. Deleted files were not in the timeline.

**Comment by jliljebl** [comment]
Ok, thanks, this one we will we work to confirm and fix for next release.

**Comment by jliljebl** [comment]
Thanks, confirmed and fixed. 

Code used current displayed bin item indexes for some reason without any real need to do so, maybe a carry over when media bin was a treeview list in early releases.
