### ISSUE TITLE
flatpak: blender (and other external programs)

### ISSUE THREAD

**Issue by eszlari** [jliljebl/flowblade#859]
Just a heads-up, since I'm seeing you are implementing blender support:
To start a process outside the sandbox:

```
$ flatpak-spawn --host COMMAND
```
For example to start blender (flatpak) from the sandbox:

```
$ flatpak-spawn --host flatpak run org.blender.Blender
```

If you are dealing with file paths as arguments, it gets a bit more tricky.

Something like

```
blender -b file.blend -P script.py
```
can be achieved by a wrapper script `blender.sh`:

```
#!/bin/sh

INPUT_FILE="$(awk -F "=" '/app-path/ {print $2}' /.flatpak-info)${2:4}"

exec flatpak-spawn --host flatpak run --filesystem=~/.local/share/flatpak
                                      --filesystem=/var/lib/flatpak
                                      org.blender.Blender -b ${INPUT_FILE} -P "$4"
```
Explanation:

A path like `/app/share/flowblade/file.blend` is only valid inside the flatpak sandbox. You can get the real path on the host filesystem from the file `/.flatpak-info` (at top of the root directory inside the sandbox). In the above script, `/app` gets stripped from the file name (see `${2:4}`) and then merged with the real path on the host. The two `--filesystem` parameters are needed, to give the blender flatpak the permission to read the files of installed flatpak apps (including flowblade's).

Of course, such a wrapper script exist only to emulate a regular `blender` binary. The proper solution is, to detect if the app is running inside flatpak (test for `/.flatpak-info`) and then execute the proper commands.

You can test this yourself with the flatpak version of OpenShot:
https://github.com/flathub/org.openshot.OpenShot

**Comment by jliljebl** [comment]
@eszlari  Thank you for your input on this, this will help quite a bit in getting this done. This is the kind of technical issue that can be time consuming to figure out yourself, but with relevant information being available will hopefully be a much easier task.

**Comment by jliljebl** [comment]
I spend some time on time this and made quite a bit a advancement. It turned that it was needed to create some quite complex differentiated code paths to support this feature in both normal installation and Flatpak. I have decided to not support the Blender container clip feature on Flatpak. The feature not seem to provide high value to users and we will have new features providing similar functionality that will be both more valuable to users and trivial to support on Flatpak and development time will be better spend on those.
