### ISSUE TITLE
Image sequence frame rate

### ISSUE THREAD

**Issue by john-cheesman** [jliljebl/flowblade#860]
Please include the following information.
1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Manjaro 20
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easiest way to understand what is happening.:

I'm trying to import an image sequence from 36 frames to run at 12 fps. I have the profile set to HD 1080p 24 fps and I select frames per source image to 2. The time displayed on the clip in the media window is 3 seconds as expected. However, looking at the file properties for the clip it has a playtime of ~1 second and is running at 25fps. When I drag it to the timeline it takes up 3 seconds, however it will only play for 1 second and is clearly running at 25fps. The same thing happens when previewing the clip. I've tried rendering the timeline and I get a video of ~1 second. I've tried increasing the frames per source image but I always end up with a clip that only seems to use each image once.

**Comment by jliljebl** [comment]
I will probably need to return to this after next release coming in June. I will do some testing to see if there are some simple bugs we could fix, but if we' are dealing with something a bit more complicated we probably won't be able do much in this cycle.

**Comment by john-cheesman** [comment]
Thanks, I'm using ffmpeg to make video clips from images and then importing them so I can still use Flowblade.

**Comment by jliljebl** [comment]
Confirmed, there is a problem here.

**Comment by jliljebl** [comment]
I found the underlying cause. For image sequences we are getting an "avformat" producer created, not a "pixbuf".   "avformat" producer seemingly only has one-to-one frame correspondence on playback. This is some MLT change, now we need to look how to get around/fix this.

**Comment by jliljebl** [comment]
I have this figured out 
  * "pixbuf" works correctly, "avformat" does not.
  * all systems with MLT 6.20 load "avformat" producer and bug is present
  * all systems with MLT 6.22 load "pixbuf" producer and everything works.

The fix is to use MLT 6.22 or higher and make sure "gdk" module is build and available. Bug probably came to being when "gtk2" module was deprecated in facour "gdk" module that does not use GTK2.
