### ISSUE TITLE
Error at start. 

### ISSUE THREAD

**Issue by BourzRoss** [jliljebl/flowblade#862]
1) Flowblade version 2.4.0
2) MLT version 6.20.0
3) Your distribution Gento o x86_64
4) Install all [depends](https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/DEPENDENCIES.md). After install flowblade (no means - from overlay or from git). Start.
`...Create **SDL1** consumer...
: segmentation fault`

MLT build with sdl2

**Comment by jliljebl** [comment]
Gentoo does not work currently, I don't know why.
