### ISSUE TITLE
Poor filter performance with 540p proxy in 4k project, smooth with raw 1080p project?

### ISSUE THREAD

**Issue by adworacz** [jliljebl/flowblade#868]
Please include the following information.
1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Manjaro, latest updates applied.
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

540p Stutter:
* Load a 4k movie clip into an empty project, allowing flowblade to change the project settings to match the 4k clip.
* Enable proxies via the proxy manager (using H.264, Quarter Resolution), and ensure proxy's are rendered using the bin menu item "Render proxies for selected media".
* Once proxy is created, drag clip to timeline.
* Double click on clip, go to filters -> Color -> Color Adjustment, setting the Color Adjustment to something extreme (deep red, etc).
* Try playing back the filtered timeline clip -> likely results in stutters, even with a Threadripper 3960x + 64GB RAM

1080p Smooth:
* Load a 1080P clip in a NEW project. Let flowblade match project settings to clip.
* Don't enable proxies.
* Drag clip to timeline.
* Enable same color filter as "Stutter" example.
* Enjoy smooth playback.

So it seems that Flowblade is possibly running filters at the target project resolution, even when using proxy media? So if I had to guess, it's computing a 4k color adjust for a 960 x 540p proxy clip?

If that's not it, why are the color adjust filters so slow in 4k project, even when using <<4k media?

**Comment by jliljebl** [comment]
> Once proxy is created, drag clip to timeline.

So you need to do:
  * select from application menu **Project->Proxy Manager** 
  * press **Use Proxy Media** button

Did you do this? Rendering Proxy files only makes them available to be used when actually turning proxy editing on.

More info here: http://jliljebl.github.io/flowblade/webhelp/proxy.html

**Comment by adworacz** [comment]
Yup, it's definitely on. 

Here's a video demonstrating the issue, my filter settings, proof that it's a cached proxy file, etc.

https://mega.nz/file/3BtThLra#w4VVWua62zWnyqANNN4oKUqfhE0_IYWK4WvxdAF6AGs

**Comment by jliljebl** [comment]
Ok, I downloaded the file.

So, the thing is that proxy files only help with performance by making decoding take less CPU and use less disk bandwidth.

Once the image from proxy file is decoded **it is scaled up to project image size** and **all filters will operate on this 4k image** if you have 4K project.

There are 2 ways we can improve the performance in the application
  * improve filter performance, This is something we are starting to work towards this year.
  * make MLT somehow operate on lower, preview/proxy image size on request when filtering images. While in principle possible, it is not something I believe is feasible in practice.

So we are left with improving on filter performance, this is a long term project and improvement will come gradually.

You have two ways to work around the current performance restrictions.

1. Use **Edit->All Filters Off** and **Edit->All Filters On** actions to allow for better performance when editing and turning/filters back on for color correction.

2. Manual proxy project. Edit on 2K Project Profile with 4K material and 2K or lower proxies so filters will be applied on 2K images. Once edit is complete: 
  * turn proxy editing off
  * select **Project->Change Project Profile** and  select the 4K profile that matches your material.
  * note: you will lose correct positioning from Compositors and filters as they use pixels for their work not normalized values, so you may need to redo some work.

I'm closing this as this is the established functionality and long term work is required for improvement. Hopefully my explanations helped  you to understand the situation.
