### ISSUE TITLE
Minor: weird behaviour in name field of the render tab

### ISSUE THREAD

**Issue by axelsimon** [jliljebl/flowblade#870]
Please include the following information.
1) Flowblade version: 2.4.0
2) MLT version: 6.2.0
3) Your distribution: Fedora 31

Tiny issues, but a bit annoying:
- You can't jump to the beginning or the end of the text field in the "name" field of the render tab ('home' and 'end' keys don't work in field).
- You can't paste with ctrl+V (however, my physical keyboard's dedicated paste key works, so this may have to do with my layout, as i'm not using qwerty/azerty)

Might be worth mentioning otherwise that ctrl+←  and ctrl+→ to jump from word to word *do* work.

Hope this helps.

**Comment by jliljebl** [comment]
This could happen because we are capturing ('home' and 'end as timeline playhead commands. There is probably a workaround for this, not sure if I can get this for 2.6, let's see.

**Comment by jliljebl** [comment]
Fixed in repo.
