### ISSUE TITLE
Suggestions on improving Flowblade

### ISSUE THREAD

**Issue by houku** [jliljebl/flowblade#871]
Flowblade version 2.4.0: in Ubuntu studio has some stuff that annoy me, now, before i start, i want to clarify that when i used that software first, it seemed more like a neat color correction tool then anything, and now it looks to me almost like a premiere alternative, some stuff that annoy me tho with it (which idk if their intentional or not) are:
1) every time i muted the video, when i cut, it turns sounds back on, so i have to remute it, i dont mind it as much, but if will be a lot nicer if it would just keep muted,
2) i tried to make a outro transition (basically to make the screen black) with the crop and crop left, for some reason it doesnt work, i tried crop left but nothing, and yes, i did try to disable "invert" :p
the third one is not exacly a bug report, just something i would personally prefer to have, but i cant (or dont know how) costumize the short cuts, at the same time, i dont find it intuitive to press a number and memorise it so i can remember to and not have to press the tool icon to change to razor, i know theres a shortcut for it (shift+x) but it cuts all the tracks and its kind of annoying, especially because i dont want to accidently delete something important, now, before it will seem i have only complains, i want to clarify i had a good experience using it, coming from windows using stuff like premiere and davinci, that software is really intuitive for me, and while remembering the number to the cut button isnt the most intuitive thing, i personally can adapt to it easily, but not everyone can, if it will make it better about the software, i have to admit the preview is REALLY fast, a lot faster then davinci and premiere, it didnt crash what so ever (like kdenlive) and i LITTERALY used a bunch of effects and it played everything like nothing, when the 3 problems will be fixed, i would LOVE to use it as main editor, 1 thing i have to note tho, and its a really hard pill to take,

i love flowblade, probably the best option out of all linux video editors so far ^w^

**Comment by jliljebl** [comment]
> every time i muted the video, when i cut, it turns sounds back on, so i have to remute it, i dont mind it as much, but if will be a lot nicer if it would just keep muted,

This is coming for 2.8, we had *cut creates default clip* but I have allowed myself to be convinced by multiple commenters that we should do *cut creates clip clone* and that includes mute state too.

> tried to make a outro transition (basically to make the screen black) with the crop and crop left, for some reason it doesnt work, i tried crop left but nothing, and yes, i did try to disable "invert" :p
the third one is not exacly a bug report, just something i would personally prefer to have, but i cant (or dont know how

I just made an turorial video for Compositing in next version, hope this gives some ideas https://vimeo.com/427093600

> (or dont know how) costumize the short cuts, at the same time, i dont find it intuitive to press a number and memorise it so i can remember to and not have to press the tool icon to change to razor, i know theres a shortcut for it (shift+x) 

Configurable shortcuts are also planned for 2.8. Numbers will remain available for selecting tools, but maybe we could make it possible to add secondary user specified shortcuts for tools that are not active by default.

 Allowing users to turn off shortcuts is also something we need to support if we have configurnle shortcuts, so adding this comes quite easy after everything needed is in place, so I think we can get this sometime in the future.

**Comment by jliljebl** [comment]
Ok, for this Issue I've done:

1) Configurable keyboard shortcuts
2) Mute state is now cloned into new clip when clip is cut

Still missing "maybe ... add secondary user specified shortcuts for tools that are not active by default" and I'm adding that to my own lists for later evaluation. 

I'm closing this as *fixed* as it is difficult to repeatedly read multipart Issues and internalize what is asked for and also we have done majority of issues mentioned.
