### ISSUE TITLE
Documentation - best quality with media of different resolutions 

### ISSUE THREAD

**Issue by jose1711** [jliljebl/flowblade#872]
From https://jliljebl.github.io/flowblade/webhelp/basic_editing.html

> For best possible quality the input material, Project Profile and Rendering Profile should all have the same pixel dimensions and pixel aspect ratio. 

This however does not answer the question how to handle situation in which input material is using different resolutions - say it's a mix of a videos from two different cameras. What is the best way to tackle this?

**Comment by jliljebl** [comment]
Just put them on the timeline and Flowblade will scale video to match Project dimensions. The line in documentation just means that when video dimensions match Project Profile dimensions no scaling happens, and this is always the best thing from quality point of view.
