### ISSUE TITLE
Changed profile is not reflected in Titler

### ISSUE THREAD

**Issue by jose1711** [jliljebl/flowblade#873]
1) Flowblade version (Help->About):

2.4.0

2) MLT version (Help->Runtime Environment):

MLT version: 6.20.0
GTK version: 3.24.20

3) Your distribution (Ubuntu, Debian, Mint etc.):

Arch Linux

4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Run `flowblade`. Invoke `Tools - Titler`, render an image, use `Save Title Graphic` and save output to `.png`. Observe the image dimensions that match current profile (e. g. 1920 x 1080). Close `Titler` and change profile that is using different resolution (e. g. 4k). Open `Titler` again and observe that it's still using the original (previous) resolution.

**Comment by jliljebl** [comment]
Confirmed,  when we change project profile with "Project->Change Project Profile..." the Titler output remains in the old dimensions.

**Comment by jliljebl** [comment]
When Titler is open on project load we now keep the data but initialize Titler to new screen size.
