### ISSUE TITLE
flowblade update

### ISSUE THREAD

**Issue by houku** [jliljebl/flowblade#874]
Please include the following information.
Flowblade version 2.6
on endevourOS (arch)

before i start, yes, i know flowblade was litteraly released a short while ago, despite that, i had to update since i was installing from aur, and it got an update so i wanted to check it out, so heres some issues i have when i tested it:

crop still doesnt work
chroma key color select doesnt work (idk if its new or not)
the fade in and fade out doesnt work,
the opacity doesnt make the picture disappear
wipe doesnt move the pic out
dust doesnt work

i wont check all the effects, however, it seems like flowblade became now like a resturant with lots of food in it, yet theres only a few that actually work, and some of those i use now often, are unusable, despite that, ill try to stay optimisting and not hate on the project, it is still a new update and only ask to recheck the effects since i use them often, aside of that, the playback seems to have improve considering it was laggy on the 2.4 update on 4k resolution with a bunch of effects, and when i say "laggy", i dont mean unsuable, because it was kind of usable

**Comment by jliljebl** [comment]
2.6 is not out, I just changed the version strings before doing packages. i will look at the assortment of under specified issues here to see if I can find something that is actionable before release.

>crop still doesnt work

BTW Crop absolutely does work, are you failing to use compositors?

![crop2](https://user-images.githubusercontent.com/1823444/85917837-4a3e6700-b866-11ea-8bbe-e914b470f9aa.png)

>chroma key color select doesnt work (idk if its new or not)

Color select works as provided by GTK.

![color_select](https://user-images.githubusercontent.com/1823444/85917812-21b66d00-b866-11ea-9193-bdbcf50c7431.png)

I have to conclude that the reporting here is not reliable or Issues are with the user system.

As this text does not specify a single actionable issue as is sort of required by the the widely accepted mode of communication on Issue pages I'm closing this. Please refile with with single issues and please wait until 2.6 is available as distro official package.
