### ISSUE TITLE
Flowblade 2.6 on flathub?

### ISSUE THREAD

**Issue by welon68** [jliljebl/flowblade#878]
Whether Flowblade 2.6 will be available in the flathub repository?

**Comment by jliljebl** [comment]
Yeah, should be available, I pushed the patch and it successfully was build.

su 5. heinäkuuta 2020 klo 22.22 welon68 <notifications@github.com>
kirjoitti:

**Comment by welon68** [comment]
That's great. 
Thank You

**Comment by jliljebl** [comment]
Closing as fixed.
