### ISSUE TITLE
Proxy render does not launch

### ISSUE THREAD

**Issue by PixnWave** [jliljebl/flowblade#884]
Hello,
> `nice: « /app/share/flowblade/Flowblade/launch/flowbladeproxyheadless »: Permission non accordée
`
`Launch jobs dialog for unfinished jobs...
atomicfile.AtomicFileWriteError in ccrutils.abort_render(), could not open for writing:  /home/utilisateur/.var/app/io.github.jliljebl.Flowblade/data/flowblade/container_clips/c897492c71a229e2e83a98d595abeded
`
1) Flowblade 2.6.0 via flathub
2) MLT version 6.21.0
3) Ubuntu 18.04.4 LTS
4) 4K-> Proxy render start launch in job list but it never end

best regards

**Comment by jliljebl** [comment]
Ok, the Flatpak is not clearly not mixing well with application new rendering code. There will be a point release addressing these issues.

**Comment by cfenell** [comment]
Hi, I can confirm the same behaviour using the Archlinux packages.
   nice: ”/usr/lib/python3.8/site-packages/Flowblade/launch/flowbladeproxyheadless”: Åtkomst nekas 

I attach the complete output- hope this helps!
[flowblade_debug.txt](https://github.com/jliljebl/flowblade/files/5065193/flowblade_debug.txt)

**Comment by jliljebl** [comment]
We did two fixes and tested on Flatpak, fix will be in 2.6.1 Flatpak release. We can't use *nice* command with Flatpak and *shell=True* seems also does not work on Flatpak.
