### ISSUE TITLE
Hardware encoder

### ISSUE THREAD

**Issue by Kerrung** [jliljebl/flowblade#885]
1) Flowblade version: 2.6
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Arch Linux

**Comment by jliljebl** [comment]
Haven't looked at hardware encoding yet, I think it is in some cases possible to do hardware encoding on MLT but this has not been area of focus on Flowblade yet. We are obviously interested in getting this available via Flowblade.

**Comment by Kerrung** [comment]
> Haven't looked at hardware encoding yet, I think it is in some cases possible to do hardware encoding on MLT but this has not been area of focus on Flowblade yet. We are obviously interested in getting this available via Flowblade.

I know that Shotcut is MTL based too, but it already can use the hardware encoder.

**Comment by jliljebl** [comment]
Ok, this gives as a clear path on getting this into Flowblade.

**Comment by JochenMehlich** [comment]
is there an update if hardware encoding is implemented?
I'm using a AMD Radeon 5700xt.

**Comment by jliljebl** [comment]
I just tested and for the first time successfully rendered something with hardware encoding using MLT so this will get first try for next release.

**Comment by JochenMehlich** [comment]
Ok, that sounds great. Did you test it with a nvidia gpu or with an amd?
Because when it is cuda based, it will not work with amd gpus.

**Comment by jliljebl** [comment]
I have GeForce GTX 1650, so no news on AMD yet. I'll post info on developments when I get around to trying this out more. Next month probably spend on other issues but this will get attention after some other dev tasks are completed.

**Comment by JochenMehlich** [comment]
Thank you for the fast answer :D

**Comment by jliljebl** [comment]
I did some tests and 2.10 looks good hardware encoding, both NVENC and VA-API rendering seem to available for us.

**Comment by Kerrung** [comment]
> I did some tests and 2.10 looks good hardware encoding, both NVENC and VA-API rendering seem to available for us.

Thank you very much!

**Comment by JochenMehlich** [comment]
sounds very nice :D

any ideas when it will come? ;D

**Comment by jliljebl** [comment]
May-June -21, next release is coming in few weeks and this feature has a bit too much detail to push in at this late stage.

**Comment by ThatOneCalculator** [comment]
Any update? Still looking at May-June?

**Comment by fhaust** [comment]
I just looked into this for half an hour. This should be as simple as setting the right avformat to be passed on to mlt, right? In theory it should be even possible to pass the required options via the custom render args, but I tried and at some point the get lost :shrug:

**Comment by jliljebl** [comment]
I just pushed patches to support for both NVENC(nvidia) and VAAPI(AMD, Intel). If user's hardware supports either option a new rendering category - NVENC or VAAPI - will appear in the updated render encoding selection drop box.

Both have been tested and provide about 3-5x speedups, so things are looking up.

It would be useful if interested parties tested the curret repo code on their machines, see: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md#installing-using-development-repository-version

**Comment by jliljebl** [comment]
Will be doing more tests but closing this now as fixed, 2.10 release containing this coming in June.
