### ISSUE TITLE
FYI dependency error in Ubuntu 18.04

### ISSUE THREAD

**Issue by fortinux** [jliljebl/flowblade#886]
Please include the following information.
1) Flowblade version (Help->About): flowblade-2.6.0-1_all.deb
2) MLT version (Help->Runtime Environment): not installed
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.04
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
FYI: I can't install it if I don't install python-mlt first; which it's not installed by default in Ubuntu 18.04

Command line error (in portoghese): 
Os pacotes a seguir têm dependências desencontradas:
 flowblade : Depende: python3-mlt mas não é instalável

Thanks.
Fortinux

**Comment by jliljebl** [comment]
Hi,  python3-mlt is not available for Ubuntu 18.04 and Flowblade requires MLT 6.18 so installing Flowblade on Ubuntu 18.04 is probably not doable unsless you compile and install python3-mlt yourself.

The Python 3 transition has killed compatibility with older systems I'm afraid.
