### ISSUE TITLE
4K rendering seems slow

### ISSUE THREAD

**Issue by masterleo** [jliljebl/flowblade#887]
1) version 2.4.0

2) MLT version : 6.20.0
3) Your distribution: ubuntu 20.0

4) Edit a vidjeo in 4k, render this less than  5 minutes footage and then : 

After a night (11h) it still did not complete.

**Comment by jliljebl** [comment]
Something has gone wrong. A few questions:

1) Did you install from **.deb** package or **Flatpak** or OS repository?
2) How much memory your system has?
3) Did you check memory consumption with something like 'System Monitor' application during render?
4) There is a file in home folder */.cache/flowblade/log_batch_render*. Does that have any useful information?

**Comment by dvdlvr** [comment]
I just did a render of a 4K video on 2.4, MLT 6.17, Ubuntu 20.04. The source was 1m12s and it took about 1m20s.
So, on top of the questions asked by jliljebl above, please answer the following
1) What is your processor - type, speed, cores/threads
2) What are the settings on the performance tab in the Flowblade preferences

**Comment by jliljebl** [comment]
Merged with #924.
