### ISSUE TITLE
A preferences file for each instance of Flowblade

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#897]
**Enhancement**

Flowblade 2.6.0
MLT 6.21.0
GTK 3.24.18
Ubuntu Studio 20.04

This feature is helpfull for developpers.
The preferences file is in /home/xxxx/.config/flowblade/prefs. So when you have several instances of Flowblade, they share the preferences values. If you want to have preferences for each instance, you have to modify Flowblade as follows :

1. In app.py - main(), permute respaths and userfolders (see below 2., userfolders.py needs respaths)
  ```
  # Set paths.
    respaths.set_paths(root_path)

    # Create user folders if needed and determine if we're using xdg or dotfile user folders.
    userfolders.init()

```

2. In userfolders.py

`import  respaths`

 userfolders.py - init()
```
     flb_prefs_file_ext = respaths.ROOT_PATH.split("/")[-4]  # directory name of flowblade git clone 
    _xdg_prefs_file_exists = os.path.exists(_xdg_config_dir + "/prefs_" + flb_prefs_file_ext)
#    _xdg_prefs_file_exists = os.path.exists(_xdg_config_dir + "/prefs")

```

3. In editorpersistance.py

`import  respaths`

editorpersistance.py - load()
   ```
 root_pref_path = "_" + respaths.ROOT_PATH.split("/")[-4]  # directory name of flowblade git clone
    prefs_file_path = userfolders.get_config_dir() + PREFS_DOC + root_pref_path
#    prefs_file_path = userfolders.get_config_dir() + PREFS_DOC
```

editorpersistance.py - save()
    ```
```
root_pref_path = "_" + respaths.ROOT_PATH.split("/")[-4] # directory name of flowblade git clone 
    prefs_file_path = userfolders.get_config_dir()+ PREFS_DOC 
```

```

**Comment by jliljebl** [comment]
On first look I have to say that this does not appeal to me. I have never had much problems with prefs file vis-a-vis developing the application. I think once or twice it has been useful to manually delete the prefs file for some development related reason but I don't believe adding any complexity in this area is warranted for the sake of making the development easier.

I believe all additional complexity in such a fundamental area on application functionality would need to bring large benefits and I just don't see that here.
