### ISSUE TITLE
Add diagonal mirror to distort filters

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#904]
Please add diagonal mirrors to distort filters next to the existing Horizontal and Vertical mirrors.

Add two diagonal mirros:
- Diagonal to top left
- Diagnola to top right

By default, use the lower part of the diagonal (similar to vertical mirror) and offer invert option to use the upper part of the video.

1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 20.04

**Comment by jliljebl** [comment]
I agree on the usefulness but if this is not currently available from MLT or Frei0r it might take sometime to get improvement here.

**Comment by PanderMusubi** [comment]
What is the best place to request it? https://github.com/mltframework/mlt or https://github.com/dyne/frei0r or both?

**Comment by jliljebl** [comment]
Unfortunately neither is a good place to do this. 

MLT does not take feature requests at all, only bug reports and pull requests. 

Frei0r is almost unmaintained, we do get releases occasionally but there is no active development other then infrequent updates from developers like myself and certainly no one to respond to a pull request.

I will likely need to do this myself unless I've missed something and feature is already available, so this is not coming in the immediate future.

**Comment by jliljebl** [comment]
Ok, this was now in MLT so I added it into application. Feature will available in release 2.12.
