### ISSUE TITLE
Support icon for .flb files

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#905]
Please support the Flowblade icon for .flb files when viewed in Nautilus or other file explorers.

1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 20.04

**Comment by jliljebl** [comment]
Hmm, I thought the desktop file had some mime type thing for this, needs some investigation.
