### ISSUE TITLE
Support full screen for second window in two window mode

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#906]
Please, support full screen for second window in two window mode. Currently, only the main windows can be set into full screen mode.

1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 20.04

**Comment by jliljebl** [comment]
I agree that this would useful, adding in feature queue.

**Comment by jliljebl** [comment]
This is now in repo, will be in next release. F11 toggles fullscreen on second window if it has toplevel focus (was pressed with mouse last).
