### ISSUE TITLE
IndexError when attempting to re-link a "lost" rendered clip

### ISSUE THREAD

**Issue by rpdelaney** [jliljebl/flowblade#907]
Please include the following information.
* Flowblade version (Help->About): 2.6.0 
* MLT version (Help->Runtime Environment): 6.22.1
* Your distribution (Ubuntu, Debian, Mint etc.): arch
* If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easiest way to understand what is happening.:

1. Open flowblade, open project
2. Am met with "Media asset was missing!" error, path of missing asset: `/home/ryan/.local/share/flowblade/rendered_clips/dynasty_c4m2_wipe.xml`
3. Open media relinker tool, find the file in the filesystem, which is still there at the supposedly "missing" path
4. Save relinked version of project
5. Load relinked project, return to step 1

I saw this in the console:

```
  File "/usr/lib/python3.8/site-packages/Flowblade/cairoarea.py", line 80, in _draw_event
    self._draw_func(None, cr, (a.x, a.y, a.width, a.height)) # 'None' is event object that was used to pass through here.
  File "/usr/lib/python3.8/site-packages/Flowblade/tlinewidgets.py", line 1651, in _draw
    self.draw_sync_relations(cr)
  File "/usr/lib/python3.8/site-packages/Flowblade/tlinewidgets.py", line 2253, in draw_sync_relations
    parent_y = _get_track_y(current_sequence().first_video_index)
  File "/usr/lib/python3.8/site-packages/Flowblade/tlinewidgets.py", line 548, in _get_track_y
    tracks_height = tracks_height + current_sequence().tracks[i].height
IndexError: list index out of range
Launching Media Relinker
Loading Project, SAVEFILE_VERSION: 5
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
file does not exist
did not find a file
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/Flowblade/cairoarea.py", line 80, in _draw_event
    self._draw_func(None, cr, (a.x, a.y, a.width, a.height)) # 'None' is event object that was used to pass through here.
  File "/usr/lib/python3.8/site-packages/Flowblade/tlinewidgets.py", line 1651, in _draw
    self.draw_sync_relations(cr)
  File "/usr/lib/python3.8/site-packages/Flowblade/tlinewidgets.py", line 2253, in draw_sync_relations
    parent_y = _get_track_y(current_sequence().first_video_index)
  File "/usr/lib/python3.8/site-packages/Flowblade/tlinewidgets.py", line 548, in _get_track_y
    tracks_height = tracks_height + current_sequence().tracks[i].height
IndexError: list index out of range
```

**Comment by rpdelaney** [comment]
Correction. The file is actually gone. This may be related to having opened a new project and saved it elsewhere to disk. Regardless, this seems to make my original project unrecoverable.

**Comment by jliljebl** [comment]
Thanks, for the report. Clearing the rendered files will make projects un-openable and there is are warning displayed, but if at all possible it would certainly be preferable to be able to fix this somehow. I will see if it is possible to have improvements on this for 2.8.

**Comment by jliljebl** [comment]
"Save back-up Snapshot ..." has not received attention in a long time. I will test and improve on it but just destroying rendered data and moving project file cannot be made to preserve to data, Flowblade project files only has paths to disk data, no data is saved with project files.

Using Relink feature to fix missing rendered files will be tested and made to work if possible.

**Comment by rpdelaney** [comment]
What makes this design fatally flawed is that:

1. there is no way to back up project metadata without also backing up potentially enormous media files
1. `$XDG_CACHE_HOME` is defined as "**non-essential** (cached) data" in the freedesktop.org spec, i.e. cache is one small step up from tmpfs
1. The warning is not nearly threatening enough to make this bizarre, counter-intuitive and standards non-conformant behavior clear.

Now that my project is unrecoverable the question is settled anyway, but I cannot consider using flowblade in the future for anything.

**Comment by jliljebl** [comment]
> $XDG_CACHE_HOME is defined as "non-essential (cached) data" 

Rendered files are at data dir $XDG_DATA_HOME. *"$XDG_DATA_HOME defines the base directory relative to which user specific data files should be store"*

> The warning is not nearly threatening enough to make this bizarre, counter-intuitive and standards non-conformant behavior clear.

Perhaps a gun icon pointing at user will suffice. This is the first time I hear this complaint.
* user needs to check a box to even activate the button 
* there is red warning icon next to button
* standard confirmation dialog.

This is about as difficult as we can make this operation without becoming slightly ridiculous.

I will look if there are improvements to be had, but now I'm closing this issue.
