### ISSUE TITLE
Render audio sample frequency not saved for project

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#910]
1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 20.04
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
- create a project
- set (at least user defined) render audio sample frequency to e.g. 44.1 kHz
- save project
- close flowblade
- open flowblade with this project
- now the render audio sample frequency has been set to 48 kHz

**Comment by jliljebl** [comment]
Seems to be true, this is not saved. Should be easy enough to fix.

**Comment by jliljebl** [comment]
Fixed in repo.
