### ISSUE TITLE
Python Module collision with other Projects

### ISSUE THREAD

**Issue by ghostshadow** [jliljebl/flowblade#912]
Flowblade v2.6

I just had an issue with a module in the global python path that has a name, which conflicts one of the flowblade internal names (in my case it was `utils`). Flowblade loads the foreign module instead of its own, which of course will not work.

I have created an issue at the other project (the game 'singularity') regarding the utils module (I think no project should put their utils module as global). But this situation could happen with other projects, so the imports should best be made more explicit.

**Comment by jliljebl** [comment]
Changing *utils.py* name would be a massive undertaking. Anyone having this issue should fix their environment instead, this is going *wontfix*.

**Comment by ghostshadow** [comment]
actually i was not suggesting to change the name of the file, but instead making sure the import statements in the other files are more explicit. i.e. using absolute imports with the modules name as prefix or proper relative imports (starting with dot).
i know this would be a lot of refactoring, but would prevent surprising effects.
