### ISSUE TITLE
2.6 Slow/Fast Motion Render Hangs at "Render Starting..."

### ISSUE THREAD

**Issue by DroWnThePoor** [jliljebl/flowblade#913]
Please include the following information.
1) Flowblade version (Help->About): 2.6.0 Flatpak
2) MLT version (Help->Runtime Environment): 6.18.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.04
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

This is my first time using Fast-Motion since 2.2/2.4, but it now creates a listing under "Jobs" rather than the mini dedicated progress bar if I'm remembering correctly. I've tried simply doing export to tool, and first marking in/out before exporting to tool and both createa Motion Clip job that never starts/progresses.
It feels like I'm missing a step or something.

UPDATE/EDIT:
With nothing changing after several minutes I decided to close Flowblade without cancelling the render and the dialogue I am used to suddenly appeared with time elapsing, but nothing appears to be happening. The clip I'm trying to speed up is literally less than 10 seconds long to begin with and doesn't seem like anything is actually happening.
![image](https://user-images.githubusercontent.com/16339020/92297556-79302380-ef0e-11ea-8215-ae878b0172eb.png)

**Comment by mikeplus64** [comment]
I'm experiencing the same issue on Arch, using flowblade 2.6-1 from `[community]` there.

**Comment by DroWnThePoor** [comment]
@mikeplus64 Unfortunately I'm on Ubuntu, and using the Flatpak as that's the only version available on 18.04.

**Comment by CWalkden** [comment]
This is happening for me too.  Same versions as the OP.  Exactly the same symptoms.

**Comment by jliljebl** [comment]
Version 2.6.1 and Flatpak for it has been released and tested and it fixes this.

**Comment by Brt-L** [comment]
Still a problem for User Profiles with an underscore in the name.
Cause in flowblademotionheadless  line 42 ?
Better prevent then using underscores in User Profile names ...

Thanks for the great Flowblade work !
