### ISSUE TITLE
Pathological memory allocation during rendering

### ISSUE THREAD

**Issue by pde** [jliljebl/flowblade#914]
Please include the following information.
Flowblade 2.6-2 and melt 6.22.1.-3 on Debian sid:

I have a flowblade timeline I composed that was attempting to render a 21 minute output from 3.7GB of source material. Consistently across two machines, the rendering will get close to finishing with reasonable (<10GB) resource usage, and then attempt to allocate more than 32GB towards the end of rendering, causing an OOM crash. I observed this on two systems.

Eventually I figured out that I could export melt XML and render with shotcut, but that was a very unsatisfying solution.

If someone wants to debug, send me a google account address and I'll share a folder for the project.

**Comment by jliljebl** [comment]
Hi, I'm lead developer of the project and email is  janne.liljeblad@gmail.com  Is there some different 'google account address' other then that? I was unable to find any additional identifier.

Anyway, if you could share the folder with me, that would be great. Sorry for the bit of delay, I took an autumn break from the project but development is active again.

**Comment by pde** [comment]
Hi, just saw this! You should have an email and google drive share now.

**Comment by jliljebl** [comment]
Thanks, I got the files. I need to fix my code a bit to get this opened, seems that you have proxies made. This gives me good test data to make projects open with missing proxies. I though I fixed this but apparently not.

Once I get project opened I'll try reproduction. This will take a few weeks but there will definitely be developments here before next release.

**Comment by jliljebl** [comment]
Merged with #924. I'll still comment on this issue to communicate with reporter.

**Comment by jliljebl** [comment]
@pde I was able to load the project and render it but there was no issues, problem does not reproduce here. I'll kepp the files around for a bit for further testing then delete.
