### ISSUE TITLE
flatpak 2.6.1 does not open saves in the old version 2.6 and hangs

### ISSUE THREAD

**Issue by welon68** [jliljebl/flowblade#917]
:-(

os: linux Solus

**Comment by jliljebl** [comment]
Can you start flatpak from terminal with command:

flatpak run io.github.jliljebl.Flowblade

and post the terminal output here.

**Comment by welon68** [comment]
welon@welonpc ~ $ flatpak run io.github.jliljebl.Flowblade
FLOWBLADE MOVIE EDITOR 2.6.1
----------------------------
Launch script dir: /app/bin
Running from Flatpak installation...
modules path: /app/share/flowblade/Flowblade
MLT found, version: 6.18.0
numpy version: 1.17.4
Application version: 2.6.1
OS: GNOME 3.38 (Flatpak runtime)
Python 3.8.5 (default, Nov 10 2011, 15:00:00) 
[GCC 10.2.0]
GTK+ version: 3.24.23
XDG user data exists.
Locale: pl_PL
Found translations at /app/share/flowblade/Flowblade/locale, using those.
Force use English.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Loading shortcuts: Flowblade
Using Full Screen size for layout: 1920 x 1080
Small height: False
Small width: False
Detecting environment...
---
video_codecs:
  - a64multi
  - a64multi5
  - alias_pix
  - amv
  - apng
  - asv1
  - asv2
  - avrp
  - avui
  - ayuv
  - bmp
  - cinepak
  - cljr
  - dnxhd
  - dpx
  - dvvideo
  - ffv1
  - ffvhuff
  - fits
  - flashsv
  - flashsv2
  - flv
  - gif
  - h261
  - h263
  - h263p
  - huffyuv
  - jpeg2000
  - jpegls
  - ljpeg
  - magicyuv
  - mjpeg
  - mpeg1video
  - mpeg2video
  - mpeg4
  - msmpeg4v2
  - msmpeg4
  - msvideo1
  - pam
  - pbm
  - pcx
  - pgm
  - pgmyuv
  - png
  - ppm
  - prores
  - prores_aw
  - prores_ks
  - qtrle
  - r10k
  - r210
  - rawvideo
  - roqvideo
  - rv10
  - rv20
  - sgi
  - snow
  - sunrast
  - svq1
  - targa
  - tiff
  - utvideo
  - v210
  - v308
  - v408
  - v410
  - vc2
  - wrapped_avframe
  - wmv1
  - wmv2
  - xbm
  - xface
  - xwd
  - y41p
  - yuv4
  - zlib
  - zmbv
  - libvpx
  - libvpx-vp9
  - libx264
  - libx264rgb
  - h263_v4l2m2m
  - h264_v4l2m2m
  - h264_vaapi
  - hevc_v4l2m2m
  - hevc_vaapi
  - mjpeg_vaapi
  - mpeg2_vaapi
  - mpeg4_v4l2m2m
  - vp8_v4l2m2m
  - vp8_vaapi
  - vp9_vaapi
...
---
audio_codecs:
  - comfortnoise
  - s302m
  - aac
  - ac3
  - ac3_fixed
  - alac
  - aptx
  - aptx_hd
  - dca
  - eac3
  - flac
  - g723_1
  - mlp
  - mp2
  - mp2fixed
  - nellymoser
  - opus
  - real_144
  - sbc
  - sonic
  - sonicls
  - truehd
  - tta
  - vorbis
  - wavpack
  - wmav1
  - wmav2
  - pcm_alaw
  - pcm_dvd
  - pcm_f32be
  - pcm_f32le
  - pcm_f64be
  - pcm_f64le
  - pcm_mulaw
  - pcm_s8
  - pcm_s8_planar
  - pcm_s16be
  - pcm_s16be_planar
  - pcm_s16le
  - pcm_s16le_planar
  - pcm_s24be
  - pcm_s24daud
  - pcm_s24le
  - pcm_s24le_planar
  - pcm_s32be
  - pcm_s32le
  - pcm_s32le_planar
  - pcm_s64be
  - pcm_s64le
  - pcm_u8
  - pcm_u16be
  - pcm_u16le
  - pcm_u24be
  - pcm_u24le
  - pcm_u32be
  - pcm_u32le
  - pcm_vidc
  - roq_dpcm
  - adpcm_adx
  - g722
  - g726
  - g726le
  - adpcm_ima_qt
  - adpcm_ima_wav
  - adpcm_ms
  - adpcm_swf
  - adpcm_yamaha
  - libmp3lame
  - libopus
...
---
formats:
  - a64
  - ac3
  - adts
  - adx
  - aiff
  - amr
  - apng
  - aptx
  - aptx_hd
  - asf
  - ass
  - ast
  - asf_stream
  - au
  - avi
  - avm2
  - avs2
  - bit
  - caf
  - cavsvideo
  - codec2
  - codec2raw
  - crc
  - dash
  - data
  - daud
  - dirac
  - dnxhd
  - dts
  - dv
  - eac3
  - f4v
  - ffmetadata
  - fifo
  - fifo_test
  - filmstrip
  - fits
  - flac
  - flv
  - framecrc
  - framehash
  - framemd5
  - g722
  - g723_1
  - g726
  - g726le
  - gif
  - gsm
  - gxf
  - h261
  - h263
  - h264
  - hash
  - hds
  - hevc
  - hls
  - ico
  - ilbc
  - image2
  - image2pipe
  - ipod
  - ircam
  - ismv
  - ivf
  - jacosub
  - latm
  - lrc
  - m4v
  - md5
  - matroska
  - matroska
  - microdvd
  - mjpeg
  - mlp
  - mmf
  - mov
  - mp2
  - mp3
  - mp4
  - mpeg
  - vcd
  - mpeg1video
  - dvd
  - svcd
  - mpeg2video
  - vob
  - mpegts
  - mpjpeg
  - mxf
  - mxf_d10
  - mxf_opatom
  - null
  - nut
  - oga
  - ogg
  - ogv
  - oma
  - opus
  - alaw
  - mulaw
  - vidc
  - f64be
  - f64le
  - f32be
  - f32le
  - s32be
  - s32le
  - s24be
  - s24le
  - s16be
  - s16le
  - s8
  - u32be
  - u32le
  - u24be
  - u24le
  - u16be
  - u16le
  - u8
  - psp
  - rawvideo
  - rm
  - roq
  - rso
  - rtp
  - rtp_mpegts
  - rtsp
  - sap
  - sbc
  - scc
  - film_cpk
  - segment
  - stream_segment,ssegment
  - singlejpeg
  - smjpeg
  - smoothstreaming
  - sox
  - spx
  - spdif
  - srt
  - sup
  - swf
  - tee
  - 3g2
  - 3gp
  - mkvtimestamp_v2
  - truehd
  - tta
  - uncodedframecrc
  - vc1
  - vc1test
  - voc
  - w64
  - wav
  - webm
  - webm_dash_manifest
  - webm_chunk
  - webp
  - webvtt
  - wtv
  - wv
  - yuv4mpegpipe
  - alsa
  - fbdev
  - oss
  - sdl,sdl2
  - video4linux2,v4l2
  - xv
...
MLT detection succeeded, 168 formats, 92 video codecs and 69 audio codecs found.
565 MLT services found.
Loading render profiles...
Loading filters...
Brightness dropped, MLT version too high for this filter.
Brightness Keyframed dropped, MLT version too high for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Player initialized with profile:  HD 1080p 30 fps
Selected color NOT detected
BG color detected
Create SDL1 consumer...
Launching io.github.jliljebl.Flowblade dbus service
Autosave started...
Saving project...
No user folders actions needed.
Loading Project, SAVEFILE_VERSION: 5
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/app/share/flowblade/Flowblade/projectaction.py", line 130, in run
    project = persistance.load_project(self.filename)
  File "/app/share/flowblade/Flowblade/persistance.py", line 431, in load_project
    orig_path = media_file.path # looking for missing path changes it and we need save this info for user info dialog on missing asset
AttributeError: 'BinColorClip' object has no attribute 'path'
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED
window resized FAILED

**Comment by jliljebl** [comment]
Thanks, I'll push a fix a few days.

**Comment by jliljebl** [comment]
I was able to find and fix the issue immediately and I pushed a patch into Flathub, Hopefully it will update application soon. It would be great if you could comment here once application is updated on your system and confirm fix, don't know how quickly updates go.

**Comment by welon68** [comment]
when there is a new version on flathub I will install it immediately. I will give info. Thank You

**Comment by welon68** [comment]
flowblade works again ok
:-)

**Comment by jliljebl** [comment]
We now have fixed .deb available and can now close this. Thanks for the report, regressions are the worst.
