### ISSUE TITLE
Feature Request: Tooltip when hovering over a clip in the timeline

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#920]
Displaying a tooltip with the name of the media file and possibly with information about its length when hovering over a clip on the timeline.
For instance:
1) I add a lot of images
2) zoom out the timeline
3) I hover over any image
It would be nice if, on hover, a tooltip appeared with the file name.
![mB9XRgquATw](https://user-images.githubusercontent.com/26217756/97036905-2fa8a000-1571-11eb-8526-f8dc6a50ee67.jpg)

**Comment by jep-fa** [comment]
You can get this information with right click on a clip, item Clip info but you cannot slide over the clips. 
I was interested by this feature. I displayed this tooltip (name and length) on hovering but it’s awkward in routine work. In my opinion, it must be optional or visible only if the clip is selected..

**Comment by jliljebl** [comment]
Yes, this could get a bit distracting at times.

I think it is better to add a keyboard shortcut "Display info on clip under Cursor " or something like that. Could be useful in some workflows but probably not a high value feature.

**Comment by smolnp** [comment]
You're right, it would be great if you could take the time to enable this option with the option to disable it, for example in the Behavior menu like the Show Tooltips option.

**Comment by jliljebl** [comment]
I'll look at with last round of adding new small features this cycle, probably about early December.

**Comment by jliljebl** [comment]
I don't think this one is going forward. I'm being more selective on the features I'm adding now, and there is the *Zoom + Right Mouse* workflow for getting the info, I'm marking this *wontfix*.
