### ISSUE TITLE
Misspelling of Workflow in opening screen menu

### ISSUE THREAD

**Issue by gonzo69** [jliljebl/flowblade#921]
Please include the following information.
1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment):
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu
![Screenshot from 2020-10-25 11-51-34](https://user-images.githubusercontent.com/69282099/97112086-be740480-16b8-11eb-8ad1-d978d87e7e40.png)

4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

**Comment by gonzo69** [comment]
bottom menu option.

**Comment by jliljebl** [comment]
Thanks, I again didn't find it until I saw "bottom menu option", fixed now
