### ISSUE TITLE
FLOWBLADE 2.0 DOC MANUAL

### ISSUE THREAD

**Issue by MGMediaGa** [jliljebl/flowblade#922]
Please include the following information.
Hello All, 

I was just thinking that if you didn't have a good internet connection, it would be good to have a good offline manual for "FLOWBLADE ver. 2.0". I have included a .pdf, and .docx. Enjoy.

[FLOWBLADE DOC MAN.pdf](https://github.com/jliljebl/flowblade/files/5448798/FLOWBLADE.DOC.MAN.pdf)

[FLOWBLADE DOC MAN.docx](https://github.com/jliljebl/flowblade/files/5448801/FLOWBLADE.DOC.MAN.docx)

MGMediaGa

1) Flowblade version (Help->About):
2) MLT version (Help->Runtime Environment):
3) Your distribution (Ubuntu, Debian, Mint etc.):
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

**Comment by jliljebl** [comment]
Thanks, I added then in /docs folder so that if someone needs offline docs they are now available.
