### ISSUE TITLE
Memory leak when rendering with 60FPS

### ISSUE THREAD

**Issue by theCalcaholic** [jliljebl/flowblade#926]
Please include the following information.
1) Flowblade version: 2.4.0
2) MLT version: 6.20.0
3) Your distribution: Ubuntu 20.04
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easiest way to understand what is happening.:

I recently tried to render a project in the following profiles:

- 2.5K QHD 1440p 60 fps
- 2.5K QHD 1440p 30 fps
- HD 1080p 30 fps

The first one succeeds without any major issues. However, when I tried to render with any of the 30fps profiles, the flowblade rendering processes would eat away at my memory. By adding a 128GB swap file, I managed to get them up to >30GB RAM, before I killed the render process.

I'm not sure, what further information could be helpful. Here are my complete render settings:
![image](https://user-images.githubusercontent.com/6317548/98180599-aa72a300-1f01-11eb-8955-1ad6eefbff2e.png)

I can provide the whole project, if you think it's helpful. If so, just let me know.

**Comment by jliljebl** [comment]
thanks, yes, the whole project would be quite useful. This will become a main target once I have all the new stuff stabilized in maybe three weeks.

**Comment by jliljebl** [comment]
I'm merging this in #924 Render Issues sticky issue.
