### ISSUE TITLE
Feature proposal : Relink a directory when you relink a file

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#929]
Ubuntu studio 20.04
Flowblade 2.6.1

I replace a hard disk and I had to relink 313 files. 313 selections to do because you can only select file by file ! So I modified the media relinker. 

Now when I relink a file, Flowblade search in the directory of the relink file if other files have the same names (basename in python) as the names of the project files which cannot be found. Media Relink adds them in the list of files to relink. In my case, only 4 selections were enough.
Do you want this feature in a merge request ?

**Comment by jliljebl** [comment]
Yes, sounds very useful when large number of files need to be re-linked. 

Do pull request and I'll merge if there are no major problems.

**Comment by jliljebl** [comment]
Feature added by pull request #931.
