### ISSUE TITLE
"Free Bar" and "Tool Selection Widget (Bar)" are in conflict

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#930]
"Free Bar" and "Tool Selection Widget (Bar)" conflict. If you select both options, the "Free Bar" disappears.
![Screenshot_20201108_120439](https://user-images.githubusercontent.com/26217756/98583353-453df980-22d5-11eb-98cc-b26147327eb9.png)

**Comment by jliljebl** [comment]
Confirmed, thanks. Seems that we just need to make freebar middlebar aware that tool selector menu launch may not be there.

**Comment by jliljebl** [comment]
This is fixed now.
