### ISSUE TITLE
Bad values of volume level lines in the panel of keyframes

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#932]
Please include the following information.
Flowblade version 2.6.1

Right click on a clip, Edit, Volume keyframes

The lines 50 and 100 are out of the panel. The level volume is now between -70 and +20. So, in kftoolmode.py _draw_value_lines() and _draw_value_texts() the value100 and 50 must be replaced by +20 and for example -40.

When I click on a keyframe , the value tip hides it.  To see the keyframe when I click on it, in kftoolmode.py, _draw_value_text_box() I changed the position to 10 pixels.
        x = int(x) + 10
        y = int(y) - 10  

I try to have an hover tooltip on this panel to show the level value at the cursor position but I don't find in which module it is drawn. Can you give me this information, please.

**Comment by jliljebl** [comment]
This is what I'm getting from current master after doing *Right click on a clip, Edit, Volume keyframes*:
![Screenshot from 2020-11-15 13-35-40](https://user-images.githubusercontent.com/1823444/99183837-87d55b00-2747-11eb-957d-6fb6c5c62df7.png)
 
So I agree we could add  -70 and +20 on top and bottom but I'm not getting 100 and 50 lines here on master HEAD.

> I try to have an hover tooltip on this panel to show the level value at the cursor position but I don't find in which module it is drawn. 

*kftoolmode.TLineKeyFrameEditor._draw_value_text_box()*

**Comment by jep-fa** [comment]
Thanks for the tooltip.

> So I agree we could add -70 and +20 on top and bottom but I'm not getting 100 and 50 lines here on master  HEAD.

You can see  the level line 50 **out** **of** the panel in your screen capture. In my version with the vertically scroll timeline, I can see also the 100 level. It's because the max value is now 20.
![Capture d’écran_2020-11-15_16-57-06](https://user-images.githubusercontent.com/61981966/99190119-10aebf80-2765-11eb-89f1-cae8f54765fc.png)
If you change as I say, you can see the right lines.
![20to-70](https://user-images.githubusercontent.com/61981966/99190655-07732200-2768-11eb-8e56-a77c5224f5ba.png)
It's perhaps better to show the line -70 rather than -40.

**Comment by jliljebl** [comment]
Oh, you were right, thanks. I put a fix in and did some tests and changed the lines to be "0 db", -20 dB" and "-70dB", seemed to look cleanest.
