### ISSUE TITLE
Range delete doesn't move compositors

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#934]
Flowblade 2.6.1

1. Place clips on V1
2. Put à clip on V2 and add a compositor on this clip (blend for example)
3. Select a range
4. Click on the range delete button in the middlebar

The range is deleted, the clips after the range are moved to the left but the compositor stands at its place.

In the module edit.py-> range_delete_action() the compositors are not taken into account unlike in ripple_delete_action().

It's not a priority.

**Comment by jliljebl** [comment]
Ok, we should have data available to add this. There is obivously some thinking needed with compositors that overlap deleted range , I'm currently thinking those should stay put.

**Comment by jliljebl** [comment]
As the default mode is now full track compositing, I'm closing this as *wontfix*. Compositors still have some additional power compared to full track compositing (like tree compositing) and we will keep the feature available, but we will no longer spend additional development resources on them.
