### ISSUE TITLE
Missing Filter

### ISSUE THREAD

**Issue by musicdude1231** [jliljebl/flowblade#936]
Hello all,

I am using Flowblade 2.6.3-1 on Ubuntu 20.04. The MLT version is 6.20.0. When I right-click a video to add a filter, I see that the "Translate" filter that should be under "Transform" is missing. Is there a simple or not-so-simple fix to this?

![20201119_171142~2](https://user-images.githubusercontent.com/74477536/99911907-53fcb700-2cac-11eb-9830-f322b860c76e.jpg)

**Comment by jliljebl** [comment]
Use *Position Scale* instead, it has same functionality, a GUI editor available and had less bugs so we replaced *Translate* with *Position Scale*.

We very seldom remove anything, but this time we had a superior alternative available.
