### ISSUE TITLE
Green Halo around Fonts

### ISSUE THREAD

**Issue by dork3nergy** [jliljebl/flowblade#937]
Flowblade version : 2.61
MLT version: 6.22.1
Distribution : Arcolinux

I'm getting a green halo around fonts in the titler.  I've added this to my fonts.conf but it didn't change anything.

`<match target="font">
<edit name="rgba" mode="assign">
<const>none</const>
</edit>
</match>`

I don't get the same halo effect in gimp so I'm not sure where the problem is.

Cheers.

**Comment by dork3nergy** [comment]
Sorry, the above fix does actually work but, because I'm an idiot, I forgot I needed to recreate all my text images to make this work.

**Comment by jliljebl** [comment]
I haven't seen this and didn't even know about the *fonts.conf* but now I do and know that it may have effect on the app, which is good. Closing as there is not a fixable issue here.

**Comment by jliljebl** [comment]
I was finally able to reproduce this and fix it. This depends on system antialising default value for Cairo. Fix was to set anti-aliasing to cairo.Antialias.GOOD.
