### ISSUE TITLE
Version 2.6.3 still shows version number 2.6.1

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#940]
Please include the following information.
1) Flowblade version (Help->About): 2.6.1 - but I have downloaded the master.zip of 2.6.3
2) MLT version (Help->Runtime Environment): n/a
3) Your distribution (Ubuntu, Debian, Mint etc.): n/a
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: Start the program

Splash screen and Help / About still show version number 2.6.1 in the 2.6.3 version.

I have downloaded the master.zip and checked the values in the source files.
I found the following files that reference 2.6.1
setup.py
Flowblade/editorstate.py
Flowblade/dialogs.py

**Comment by jliljebl** [comment]
Yeah, that was just quick new push to offer a fixed version. I don't think I'll return on the 2.6 release anymore, the focus is now on getting 2.8 out without the quite bad problems we had with 2.6 release.
