### ISSUE TITLE
Blank gap between clips causes rendering to crash

### ISSUE THREAD

**Issue by petermetz** [jliljebl/flowblade#941]
Thank you for the awesome project and the work you put in!

Please include the following information.
1) Flowblade version (Help->About): `2.6.3` (latest on github as of an hour ago)
2) MLT version (Help->Runtime Environment): `6.20.0`
3) Your distribution (Ubuntu, Debian, Mint etc.): `Ubuntu Focal`
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
- Record 2 short videos with Kazam, WebM VP8 codec (don't know if the source video format matters or not)
- Create new project in flowblade
- Add the two short videos (few seconds each is enough)
- Put the videos on the timeline so that there's a blank gap between them
- Hit render
- Watch it crash, then try to play the partial video and observe that it is not a valid video file
- Join the 2 clips, eliminating the gap, hit render, everything works fine.

Attaching logs produced during the session where the crash is reproduced, but there's no stack trace in it unfortunately.
Also note: the crash itself is manifesting itself by the render progress window simply disappearing while it's in the middle of the rendering, there's no error popup or any kind of error message.

[flowblade.log](https://github.com/jliljebl/flowblade/files/5668138/flowblade.log)

Additional context: Before upgrading from `2.4.0` to `2.6.3` instead of the render crashing, it would successfully render, but drop the audio from the moment of the gap between the clips (so this is the issue I had on `2.4.0` which prompted me to upgrade to `2.6.3` and then observe the similar issue described above).

P.S. I'm a complete beginner in video editing so maybe no one else would ever think that leaving a gap between the clips on the timeline is even a valid use case, so feel free to close this as user error in that case, I'm okay with that.

**Comment by jliljebl** [comment]
Thanks for the report, confirmed. On quick test this seems to happen mostly on with *H.264* encoding option, e.g. *MPEG* and *Theora* do not crash here.

This is likely related to Known Issue *2. Audio may be corrupted when first clip is not at complete beginning with H.264/mp4* in https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/KNOWN_ISSUES.md,

> ...so maybe no one else would ever think that leaving a gap between the clips on the timeline is even a valid use case, so feel free to close this as user error in that case, I'm okay with that.

As proven by this report some users do try to do this (*and most may not be able to figure out the cause/solution*), so we need to try to offer some solution. 

Fixing the issue would (probably) need patches in MLT or FFMpeg, so I think we need to add an info dialog telling users this can happen.

**Comment by petermetz** [comment]
> so I think we need to add an info dialog telling users this can happen.

@jliljebl Thank you for the response! Yes, agreed. A little confirmation prompt when starting the render would've been sufficient in my case. Without it my way of discovering/fixing the issue was to trace the exact moment of sound cutting out in the rendered video and then take a look at the timeline at that time as well and noticing that there's a gap. 
The funny thing is that even at that point I thought to myself that it's probably not the gap's fault and was surprised (and happy) when it did end up fixing the issue. :-)

**Comment by jliljebl** [comment]
I was able to fix this with a workaround that replaces blanks in track V1 with white clips.

Still don't know the cause but everything works now.
