### ISSUE TITLE
French translation update

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#944]
Flowblade 2.6.1

I updated the french translation. It is still incomplete but better than the current translation. I questioned Loïc Vanderstichelen  who gave me his agreement to propose a new version.

The word "Tools" is used in two different senses so the translation fails. I suggest that:
- the Tools Menu should be named Plugins
- The Tools title in Menu Edition > Keyboard shortcuts should be named Edition modes

I think the create_pot script is obsolete : many python modules are missing. 

Some strings are not translated even if I add them in the flowblade.po. For example :
middlebar.py > def  _get_freebar_conf_panel()
"Check the groups of buttons visible or not in the toolbar; select one and change order"
"Up"
"Dowm"

Do you want a merge request ?

[fr_translation.zip](https://github.com/jliljebl/flowblade/files/5714826/fr_translation.zip)

**Comment by jliljebl** [comment]
I'll look at this more carefully when I do next session, probably on Sunday-Monday and comment more on then.

**Comment by jliljebl** [comment]
> the Tools Menu should be named Plugins

No, plugin is a short program that is created using a plugin API which Flowblade does not have. "Tools" is used here to mean a stand alone program that does some particular task and does not affect the main application data. I believe "Tools" to be the best word for referring to these, "Standalone Tools" is too long for application menu. 

> The word "Tools" is used in two different senses so the translation fails. I suggest that:
> The word "Tools" is used in two different senses, The Tools title in Menu Edition > Keyboard shortcuts should be named Edition modes

"Edition modes" is not the correct expression here, they are in fact tools and not modes. I'll use "Edit Tools" when appropriate from now on. Edition is also wrong noun here, it means:

>noun: edition; plural noun: editions

> 1. a particular form or version of a published text.
> 2. the total number of copies of a book, newspaper, or other published material issued at one time.

so it is not useful for referring to something used for editing. I believe "Tool" is correct for standalone tools, there has not been any confusion on the meaning here before and  "Edit Tools" for referring to tools used to edit timeline. Help docs already uses "Edit tools"

> I think the create_pot script is obsolete 

I had not ran the *upgrade_all* script in /locale after adding new translations, that updates all the translation .po files, I just did that and also changed "Tools" >  "Edit Tools" when referring to tools used for editing media on timeline.

You should now be able to do translation that is up-to-date with current master. Merge request would best way to update translation.

**Comment by jep-fa** [comment]
OK, thanks. Actually, in French the word "edition"must be translated by "edit" in English.

Edit Tools should be also in editorwindow.py line 1135
tool_selector_menu_item = Gtk.MenuItem(_("Tool Selection Widget"))

I still think the same word for two different meanings is confusing. The words assistants, complements, supplements, additions or toolkits are better in my opinion than Tools.

You can close this issue.

**Comment by smolnp** [comment]
> I think the create_pot script is obsolete : many python modules are missing.
I don't think it could be out of date. I have been using it for several years and have no problems with it.
> I believe "Tools" to be the best word for referring to these, "Standalone Tools" is too long for application menu.
It seems to me that this is more than just "Tools", for example "Tools Titler" is more like a set of several tools. Maybe "Editors" or something simila...
As for translations into other languages, personally I am also interested in these questions: #560.

**Comment by jliljebl** [comment]
> Edit Tools should be also in editorwindow.py line 1135
tool_selector_menu_item = Gtk.MenuItem(_("Tool Selection Widget"))

True that, changed it.

> The words assistants, complements, supplements, additions or toolkits are better in my opinion than Tools.

Now that we have given this attention I will look if there is a convention word for this kind of category app menu.

> As for translations into other languages, personally I am also interested in these questions: #560.

@smolnp Yes, that has dropped off my radar a bit. Too late for this cycle, after 2.6 regressions I'll keep a month long testing period and work on bug fixes and some new stuff a branches without further major feature work in master. I'll pick up on this in early 2.10 cycle and comment on more #560.

**Comment by jep-fa** [comment]
@smolnp 

> I don't think it could be out of date. I have been using it for several years and have no problems with it.

This is the list of the creat_po python modules

xgettext -o locale/Flowblade/flowblade.pot app.py projectaction.py editorwindow.py clipeffectseditor.py compositeeditor.py dialogs.py editevent.py editorpersistance.py guicomponents.py movemodes.py panels.py persistance.py projectdata.py render.py syncsplitevent.py translations.py mlttransitions.py propertyeditorbuilder.py keyframeeditor.py middlebar.py medialog.py projectinfogui.py tools/titler.py rendergui.py profilesmanager.py preferenceswindow.py tools/batchrendering.py proxyediting.py tlineaction.py extraeditors.py trackaction.py medialinker.py patternproducer.py tools/gmic.py tools/gmic.py tools/toolsencoding.py monitorevent.py compositorfades.py audiosync.py diskcachemanagement.py toolsintegration.py projectmediaimport.py shortcuts.py clipmenuaction.py dialogutils.py trimmodes.py menuactions.py exporting.py workflow.py kftoolmode.py tools/rotomask.py tools/containerprogramedit.py tools/simpleeditors.py jobs.py containeractions.py containerclip.py tlinerender.py editorlayout.py

and this the list of all the python modules of the current Flowblade

xgettext -o locale/Flowblade/flowblade.pot app.py appconsts.py atomicfile.py audiomonitoring.py audiosync.py audiowaveform.py audiowaveformrenderer.py boxmove.py cairoarea.py clipeffectseditor.py clipenddragmode.py clipmenuaction.py  compositeeditor.py  compositorfades.py compositormodes.py containeractions.py containerclip.py cutmode.py dialogs.py dialogutils.py diskcachemanagement.py dnd.py edit.py editevent.py editorpersistance.py editorstate.py editorwindow.py exporting.py extraeditors.py glassbuttons.py gui.py guicomponents.py guiutils.py jobs.py keyevents.py keyframeeditcanvas.py keyframeeditor.py kftoolmode.py lutfilter.py medialinker.py medialog.py menuactions.py middlebar.py miscdataobjects.py mltenv.py mltfilters.py mltplayer.py mltprofiles.py mltrefhold.py  mlttransitions.py modesetting.py monitorevent.py monitorwidget.py  movemodes.py  multimovemode.py multitrimmode.py panels.py patternproducer.py persistance.py positionbar.py preferenceswindow.py processutils.py profilesmanager.py  projectaction.py projectdata.py projectinfogui.py projectmediaimport.py propertyedit.py  propertyeditorbuilder.py propertyparse.py proxyediting.py render.py renderconsumer.py rendergui.py respaths.py resync.py sequence.py shortcuts.py snapping.py syncsplitevent.py  tlineaction.py tlinerender.py tlinerenderserver.py tlinewidgets.py toolsintegration.py  trackaction.py translations.py trimmodes.py undo.py updater.py userfolders.py utils.py  workflow.py tools/batchrendering.py tools/blenderheadless.py tools/blenderprojectinit.py  tools/blenderrendersetup.py tools/ccrutils.py tools/clapperless.py tools/containerprogramedit.py tools/exportardour.py tools/gmic.py tools/gmicheadless.py tools/gmicplayer.py tools/gmicscript.py tools/mltheadlessutils.py tools/mltxmlheadless.py tools/motionheadless.py tools/phantomcompositor.py tools/proxyheadless.py tools/rotomask.py tools/simpleeditors.py  tools/titler.py tools/toolguicomponents.py tools/toolsdialogs.py tools/toolsencoding.py 

Am I wrong with obsolete script ?

**Comment by jliljebl** [comment]
Not all modules have translations in them. E.g. *tools/mltheadlessutils.py* has no translated strings. 

Sometimes I do miss adding new module into *create_pot* list, which becomes obvious once you do CTRL+F  in *.po* file for string that still remains untranslated and can't find it.

Comment here if this happens.

**Comment by jliljebl** [comment]
@jep-fa We have had a single sticky Issue for translations related matters and I just opened a new one https://github.com/jliljebl/flowblade/issues/954 and closed the previous. Put further comments/questions/bug reports on translations there, thanks.
