### ISSUE TITLE
New design settings:Panel placement

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#945]
Flowblade 2.6.1
 
I tried the settings in View Menu > Panel placement.

I can place the monitor about in the center of the top row. It's an improvement.

I like the deletion of the stack in favor of a table of the effects in the Filter Panel.

**Filter select panel**
I don't understand why the Filter Select Panel is not in the Effect Panel : it's not ergonomic in my opinion, the two go together, side by side and I need to see them at the same time or neither of them. A setting for this possibility would make sense (default ?).

**Comment by jliljebl** [comment]
> I don't understand why the Filter Select Panel is not in the Effect Panel : it's not ergonomic in my opinion, the two go together

Horizontal space. Now that we allow panel on right side of monitor every pixel that makes filter editing panel min. size wider makes maximum monitor side on that layout smaller. On 1680px screen we could lose close to 2x of max. monitor size.

I will add a drop down menu for adding filters  that is in editing panel, but more complex solutions will need to wait.

**Comment by jep-fa** [comment]
OK. If we need space, we could use an horizontal scrolled window for the Effect Panel. Once we used  the Filter Select Panel, we scroll to make settings in the Filter Editor.
You can close this issue.
