### ISSUE TITLE
Filter panel icon disappeared 

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#946]
Flowblade 2.6.1

The icon ![image](https://user-images.githubusercontent.com/61981966/102606341-e5820c00-4126-11eb-9f5c-ac581b1d6a09.png)   showing at which clip the current Filer Panel is applied has disappeared.

**Comment by jliljebl** [comment]
Confirmed, this is not working right currently.

**Comment by jliljebl** [comment]
Fixed, thanks.
