### ISSUE TITLE
Add audio scrubbing support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jliljebl/flowblade#95]
```
Audio is silent when timeline is scrubbed.


```

Original issue reported on code.google.com by `janne.li...@gmail.com` on 19 Sep 2014 at 10:19

**Comment by jliljebl** [comment]
So i did mean to close this, reopening.

**Comment by jliljebl** [comment]
Feature added, will be in 2.2.

Hallelujah!!!!!
