### ISSUE TITLE
Translations >= 2.8

### ISSUE THREAD

**Issue by jliljebl** [jliljebl/flowblade#954]
This is the new sticky thread for translations issues. Please comment here on all translations related matters.

**Comment by jliljebl** [comment]
There has been some changes on existing translations:

"Up" Down" -> "Top", Bottom" https://github.com/jliljebl/flowblade/commit/0522d953b704eb72fe2a4f09cc7b927545f48188

"Pitchshifter" -> "Pitchshifter - AM" https://github.com/jliljebl/flowblade/commit/346467d53b8ae5058858904ed42efc7937cf7e9d

https://github.com/jliljebl/flowblade/commit/bc752424f496442ca43edc9f276a1524d2f69c77 Dropped semi-colons because from multiple checkbox labels because checkboxes were moved to the left e.g:
   "Use Project Profile:" -> "Use Project Profile"
   "Render using args:" -> "Render using args"

**Comment by jliljebl** [comment]
This one from previous thread still seems relevant: https://github.com/jliljebl/flowblade/issues/601#issuecomment-615128229

**Comment by smolnp** [comment]
I looked at how Audio Mixer looks in other languages and came to the conclusion that for correct display of the window, the easiest way is to remove the translation of the word "Pan" from the Audio Mixer.
![Screenshot_20210108_110821](https://user-images.githubusercontent.com/26217756/103991785-36c07100-51a4-11eb-98e9-f458a155c7f7.png)

**Comment by jliljebl** [comment]
Ok, I dropped the word 'Pan' altogether and replaced with an icon. I think it looks better too.

**Comment by jliljebl** [comment]
In "Volume" filter I changed param name to "Volume dB" for because the displayed numbers now in decibels.

**Comment by smolnp** [comment]
> Ok, I dropped the word 'Pan' altogether and replaced with an icon. I think it looks better too.

It looks cool! Thank you!

**Comment by smolnp** [comment]
No strings for translation
![Screenshot_20210117_233746](https://user-images.githubusercontent.com/26217756/104855411-b88b6980-591d-11eb-9127-6b4dc0b9ac45.png)

**Comment by jliljebl** [comment]
Ok, thanks, fixed. I changed the text to be "Set button group active state and position."

**Comment by jliljebl** [comment]
Closing this so that we don't get important new bug reports here.
