### ISSUE TITLE
GitHub Actions flatpak build workflow

### ISSUE THREAD

**Issue by eszlari** [jliljebl/flowblade#956]
I noticed PR https://github.com/jliljebl/flowblade/pull/951 and want to mention, that something like this could be implemented for flatpak too.

You could take inspiration from this PR: https://github.com/obsproject/obs-studio/pull/3804

If I find the time, I may open PR for it.

**Comment by jliljebl** [comment]
Thanks, seems like something could be useful. I'll look at this myself during next cycle and if I get PR I'll merge and test it out.

**Comment by jliljebl** [comment]
I've been doing local Flatpak builds quite a lot lately for many development purposes. I don't think any autobuilds provide enough additional value to justify taking the time to set them up, closing.
