### ISSUE TITLE
Media Relinker: Issues opening old files

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#958]
Flowblade version: Currently running 2.6.0 but this issue is probably version-independent.
MLT version: 6.18.0
OS: Fedora 33

My laptop has limited space on the SSD and so when I've finished working on an old project I tend to delete the stored assets with the assumption they can be re-rendered in the future.
Upon trying to open an old project today I discovered this is not the case.

A large number of rendered files were not found, which is not surprising; they've been deleted. However, Flowblade then asks me to relink those files, which is not possible; i.e. I currently cannot open my old file at all. I would like the option to ignore those files and just enter them as blank placeholders, and I would also like the option to re-render these placeholders at a later stage. Am I correct in assuming this is not currently possible, or am I just using the program incorrectly? This is an important feature required for archiving old work. Thanks

P.s. I should add that most of these files are likely just things like fades and dissolves.

![Screenshot from 2021-01-15 11-29-50](https://user-images.githubusercontent.com/25953969/104665272-1012b500-5725-11eb-8f67-b4d3392c7dbd.png)

**Comment by thennicke** [comment]
This is a very similar problem to issue #894. The user requires control when dealing with proxies, rendered assets etc., so as to reduce future problems with file save/file open. Thanks

**Comment by jliljebl** [comment]
Yes, this is related to Issue #894. To improve experience on both of these we are going to do something similar to Final Cut X Events Library which will make it much easier to move, back-up and restore projects. This will likely not make it to 2.10, but I'm strongly targeting this for 2.12. 

> P.s. I should add that most of these files are likely just things like fades and dissolves.

Here is something I can do for 2.10 because we already have code in place to re-render all  fades and dissolves. We just need add some GUI in Media Relinker to makes it possible to re-render fades for projects that cannot be loaded yet.

**Comment by thennicke** [comment]
I've just lost the project I've been working on for the past week due to an issue with the media relinker and the save feature.
I tried to change the name of the directory that my project was hosted in, which caused the relative file search to somehow fail for files that I had already deleted from the project. If I was able to click an "ignore" button for those files, I would have been fine.

Instead, I tried to satiate media relinker by feeding it some junk files, and for some reason this caused the project to be overwritten with a very early version from Tuesday. In the process I accidentally deleted the autosaves, and thereby lost my entire week's video editing work.

Let me know if you can think of a way I might be able to recover my work.

**Comment by jliljebl** [comment]
> reason this caused the project to be overwritten with a very early version from Tuesday.

Which version of Flowblade you have?

> Let me know if you can think of a way I might be able to recover my work.

What data you have now?

**Comment by jliljebl** [comment]
> reason this caused the project to be overwritten with a very early version from Tuesday.

You have very likely hit this: https://github.com/jliljebl/flowblade/issues/891 It is fixed now but has lead to data under some circumstances.

**Comment by micitabesh** [comment]
> If I was able to click an "ignore" button for those files, I would have been fine.
I agree, it would be nice to be able to create empty clips (placeholders), instead of the ones that I deleted and the project no longer wants to open because of them. Here I can either replace the placeholder with another clip or delete it on the timeline, today the project simply won't open unless I add another clip to Media Relinker.

**Comment by thennicke** [comment]
> > reason this caused the project to be overwritten with a very early version from Tuesday.
> 
> You have very likely hit this: #891 It is fixed now but has lead to data loss under some circumstances.

I have looked at bug #891 and I suspect you are correct -- because I was using 2.6.0. I will immediately upgrade to 2.6.1 or greater. Thank you for fixing this.

**Comment by thennicke** [comment]
> > reason this caused the project to be overwritten with a very early version from Tuesday.
> 
> Which version of Flowblade you have? EDIT: Sorry it was 2.6.0.
> 
> > Let me know if you can think of a way I might be able to recover my work.
> 
> What data you have now?

I have a version that is from last Tuesday, about an hour after I started the week's work. It has only got about 5 files added to the timeline, so it is almost like starting again from a blank slate.

Fortunately, I also have a recently rendered version of the full (28min) output video, so it might be possible for me to reverse engineer the .flb file from the mp4 output vid? Would still be around a week's worth of work though.

**Comment by jliljebl** [comment]
Unfortunately there probably is no way to get lost work back here. I always personally hand version project files running numbering which could why this escaped me.

**Comment by thennicke** [comment]
> Unfortunately there probably is no way to get lost work back here. I always personally hand version project files running numbering which could why this escaped me.

No problem, I'm just glad that the issue is now fixed. In future I will be more careful to save backups before trying to change the name of the folder that the .flb file is in.

**Comment by jep-fa** [comment]
I also had this misadventure and lost work. The  project was unable to open with only two destroyed files. As the  MediaRelinker waits a file with the same basename,I was stuck. I would like to be able to load the .flb file anyway by replacing the missing medias with blank clips in the timeline for example.
I'll be happy if you give me what are the options to program this.
The default behavior won't be change, a check button in the MediaRelinker window will enable this new feature.

**Comment by jliljebl** [comment]
jep-fa did a pull request and I added some GUI updates code and we have this now.
