### ISSUE TITLE
Play between Marks

### ISSUE THREAD

**Issue by leonerd** [jliljebl/flowblade#959]
It would be useful to add a "play marked section" feature that plays just the section between the In and Out marks, and then stops.

You can sortof recreate this by using "Move to In" and then hitting Play, but that doesn't stop at the Out mark. Often I want to preview exactly the selected range, before I insert it into the timeline. It would be useful to have this limited play button to do that.

**Comment by jliljebl** [comment]
I'll add this into feature queue, sounds like a useful feature. This is going to be a keyboard shortcut like "Control + Space", number of displayed player buttons needs to be kept as-is if believe unless we do a larger push and make them configurable allowing users a selection of many different player related actions.

**Comment by leonerd** [comment]
A keyboard shortcut would be just fine for this. I feel it's the sort of "poweruser" thing that you'd be wanting to hit repeatedly in short sequences anyway.

**Comment by jliljebl** [comment]
This is now in repo with "Control + Space" as playback start shortcut, will be 2.10 release.
