### ISSUE TITLE
Range Log always scrolls to top

### ISSUE THREAD

**Issue by leonerd** [jliljebl/flowblade#960]
If you have a lot of items in your range log, the list always scrolls back to the top after adding a new one. This is unhelpful because most often just after adding an item to the log you want to e.g. set its comment, or otherwise interact with it so you have to scroll it down to the bottom again to find it.

It would be helpful if it scrolled to the bottom at that point, ensuring your newly-added item is visible.

**Comment by jliljebl** [comment]
Confirmed and I agree that the list should not roll back up. I've always used like 5-10 of these so this has not come up.

**Comment by jliljebl** [comment]
Fixed now. I had the needed code in place but something had changed and it was required to exit the Gdk callback and do it in another one for position setting to have effect.
