### ISSUE TITLE
Allow to resize the Filter Selection Panel

### ISSUE THREAD

**Issue by micitabesh** [jliljebl/flowblade#963]
Please add a handle to resize the filter panel so that the names of all filters are displayed in full.
![Screenshot_20210112_124715](https://user-images.githubusercontent.com/59866948/104767362-0cab1800-577d-11eb-8fef-1d2af380d066.png)

**Comment by jliljebl** [comment]
Unfortunately with current panel positioning code it is not possible to add handle here. I will look at how to otherwise make sure that the panel is wide enough.
