### ISSUE TITLE
Range Log items sensitive to Proxy Media setting

### ISSUE THREAD

**Issue by leonerd** [jliljebl/flowblade#964]
If you create items in the Range Log when you have Proxy Media turned on, those items in the log now don't work if you turn off the Proxy.

Steps to reproduce:

1. Add some media files.
2. Enable and render proxy media.
3. Use the In/Out markers to create a selection in one of these files. Add it to the Range Log.
4. Switch off proxy media.
5. Try double-clicking on that item in the Range Log. Note that nothing happens - it does not select that range again.
6. Enable proxy media again.
7. Double-click the item in the Range Log. Now it becomes selected as expected.

**Comment by jliljebl** [comment]
Yeah, seems that I have just missed that Proxy Editing and Range Log functionalities indeed *are* interdependent and need to be made to work together.

**Comment by jliljebl** [comment]
I fixed the described issue and all others related to using range log with proxy mode.
