### ISSUE TITLE
 Add "Recrete icon" menu item in Media Item context menu

### ISSUE THREAD

**Issue by leonerd** [jliljebl/flowblade#966]
My current project contains about 200 PNG images as presentation slides, on top of which I am adding a "talking head" narration track.

If I update one of the PNG files on disk then flowblade does notice this when showing the output image in the monitor, or when rendering a movie file, but the "media bin" tab continues to show the original thumbnail.

Perhaps at startup it could compare thumbnails and (optionally?) refresh those if necessary? It's not a huge problem because actual rendered output is fine, but it does get a bit confusing looking at the wrong image in the bin. And I think just a startup-time check is fine; not necessary to continually check while the program is running. I think if you want to refresh the media then restarting the application is reasonable.

**Comment by jliljebl** [comment]
> Perhaps at startup it could compare thumbnails and (optionally?) refresh those if necessary? 

This is a:
   * too heavy operation for start-up/project load.
   * quite a big investment of development time

This is likely not going to happen.

I can add menu item in Media Items right click pop-up menu "Recrete icon" that does this for media items individually.

**Comment by leonerd** [comment]
> I can add menu item in Media Items right click pop-up menu "Recrete icon" that does this for media items individually.

That would be useful yes. Would avoid having to restart as well.
Bonus points if I can select multiple media files (or just "all of them") and bulk recreate the lot. I wouldn't mind if that takes a few moments to generate, because it's specifically on request.

**Comment by jliljebl** [comment]
> Bonus points if I can select multiple media files (or just "all of them") 

This is **Project->Recreate Media Icons...** in app menu.

**Comment by jliljebl** [comment]
This is now in repo.
