### ISSUE TITLE
Snapshotting behaviour of "Render to queue" 

### ISSUE THREAD

**Issue by leonerd** [jliljebl/flowblade#968]
This is initially more of a question, than an issue - but depending on the answer to it it's either a documentation-fix issue, or a feature request.

The question is: When I hit the "render to queue" button, how much of the project is captured in that queue entry? I understand things like the rendering parameters (resolution/framerate, etc...) are there - so I can enqueue multiple output formats for the same content. But what is less clear is the rest of the project - e.g. filter and compositor settings. Does the queue capture just the filename, and re-reads the project file off disk when it starts the rendering process, or does it capture a snapshot of the entire project data at "add" time? I wish to experiment with multiple different settings for some filters or compositors - Can I use the same named project file on disk and add multiple items to the queue with different output filenames, or must I save (temporary) copies of the project as a new `.flb` file on disk for each one?

I have read the relevant documentation about rendering at https://jliljebl.github.io/flowblade/webhelp/rendering.html but so far it remains unclear which is the case.

If it takes a snapshot of the entire thing - every filter, compositor, etc... - then could that be explained in the documentation?

If not - then could that be considered as a feature at some point? It would make these sorts of experimentations much easier to perform.

**Comment by jliljebl** [comment]
It saves a copy of the project at the time that it is added to queue, so what is captured is the whole thing, the same when you do "Save" or "Save As...".

I'll update the docs when I get around to it to remove any possible confusion on this, didn't occur to me that there could be much questions here.
