### ISSUE TITLE
Numbers typed into "Highpass filter" boxes don't actually apply

### ISSUE THREAD

**Issue by leonerd** [jliljebl/flowblade#969]
Dragging the slider or pressing the + / - buttons applies data properly, while updating the number shown in the text box.
Typing in a new number appears on the UI to work, but doesn't actually get applied to the data properly.

1. Add a "Highpass - Butterworth" audio filter
2. Type a number into the "Cutoff frequency" box; e.g. 150. Press Enter.
3. Navigate away from the filter then come back.
4. Observe that it has returned to its default of 500.

A workaround:

1. Type a number e.g. 150. Press enter.
2. Click the + then - buttons
3. The value changes momentarily to 151 then back to 150 again.
4. Now navigate away and return to the filter
5. Observe that this time, 150 was retained.

**Comment by leonerd** [comment]
I have just tried similar with the "Volume" audio filter, and that one behaves as expected (i.e. typing a number and pressing Enter does apply the data), so it seems to be dependent on which param of which filter. Some work, some do not.

**Comment by jliljebl** [comment]
Confirmed.

**Comment by jliljebl** [comment]
This is fixed now. This bug should only affect LADSPA filters as those needed (at least long time ago) some special treatment for stability purposes.
