### ISSUE TITLE
Clone only active filters

### ISSUE THREAD

**Issue by leonerd** [jliljebl/flowblade#970]
Feature request: A way to either a) have some sort of "group" or "global" filters that I could apply collectively to the entire sequence, or failing that b) copy/paste individual filters between clips.

Rationale: I have about 30 small clips pieced together into a 30minute movie. I need to apply some audio fixes to them all. While I can manually apply the same filter to each of these 30 clips, the process is long and tedious involving lots of typing (made worse by #969). It would be great if I could a "global filters" section, to contain filters that apply in addition to the individual clips; that way I could set it once not 30 times over.

Failing that, it would be nice to be able to select multiple individual filters on a clip for "copy" so they can be "paste"ed into another. I know I can copy all of them, but I don't want /all/ of them as that includes other things like alpha crop or chroma key, that are set differently per clip.

**Comment by jliljebl** [comment]
> Failing that, it would be nice to be able to select multiple individual filters on a clip for "copy" so they can be "paste"ed into another

This is what we will do, we can only clone *active* filters, this gives user the required additional control for your use case. 

I will be doing #949 (which is this but for tracks, not whole sequence) but not this, as features are overlapping and track filters offer more control.

So the main request here is going *wontfix* but we will be doing feature *Clone only active filters*.

**Comment by leonerd** [comment]
> Clone only active filters.

That sounds useful.

> I will be doing #949 (which is this but for tracks, not whole sequence) but not this, as features are overlapping and track filters offer more control.

Ooh yes, that would also serve my purpose just fine.

**Comment by jliljebl** [comment]
Changed the copy/paste filters functionality to only clone active filters. This gives user more control to e.g. clone only audio filters as was the use-case asked for here.
