### ISSUE TITLE
A "select" mode that does not change any data

### ISSUE THREAD

**Issue by leonerd** [jliljebl/flowblade#971]
All of the possible edit modes (Insert, Move, Trim, Roll, ...) will perform some change if you click/drag on the timeline.

Towards the end of my editing session I want to cycle through all of the clips to look over the filter settings, or maybe change them (see also #970). There is no "safe" editing mode that I can use to ensure I only select a clip without editing. Even something like Move mode will adjust things if I click too close to the start/end boundaries of a clip.

Currently to ensure safety, I zoom in far enough to be able to doubleclick just the middle of each clip, which requires lots of scrolling. As an additional safety measure I keep an eye on the total sequence length to ensure it's the same by the time I finish as when I started - but that only tells me if I screwed up, it doesn't prevent me from doing so.

It would be great to have a mode ("Select", perhaps shortcut zero, for "don't do anything") that cannot change anything by itself in the timeline and is used only for selecting clips to edit in the parameter boxes.

**Comment by jliljebl** [comment]
We still have some key shortcuts free so we could do:

  * *Alt + Up / Down Arrow* - select clip after next cut and open it in filter editor
  * If no clip/s selected, select clip after next cut
  * this will iterate all clips on all tracks

**Comment by smolnp** [comment]
> Even something like Move mode will adjust things if I click too close to the start/end boundaries of a clip.

In my opinion, there used to be a function to disable the context sensitive cursor for the Insert tool. This function could partially help if I understood the question correctly.

**Comment by jliljebl** [comment]
> In my opinion, there used to be a function to disable the context sensitive cursor for the Insert tool. 

Hell, I'm sure anymore but this could have have been ao. Anyway, that feature is not coming back, so we need something new for this use case.

**Comment by jliljebl** [comment]
Ok, we have this in repo as described above, feature will be in 2.10.
