### ISSUE TITLE
New "Volume" audio filters are initialised with two keyframes

### ISSUE THREAD

**Issue by leonerd** [jliljebl/flowblade#972]
Most filter types either don't have keyframe animation of parameters (e.g. Audio Highpass), or start with just one keyframe in them (e.g. Blur). A newly-created Volume audio filter gets initialised with two - setting 100% at both beginning and end of time.

If you don't notice this, you end up creating an audio fade that's set to your desired value at the start of time, but ramps up/down to 100% at the end of the timeline.

To reproduce:

1. Start a new project. Insert some video media as a clip
2. Add an "Audio" / "Volume" filter. Observe that the keyframe indicator already shows we're at 1/2.
3. Adjust the start keyframe's value to some other value - maybe 0%
4. Play the clip. Observe that over time this gradually fades from 0% to 100% at the end.

**Comment by leonerd** [comment]
Same thing happens with rightclicking on a clip and hitting the "Volume Keyframes" option. Dragging the initial point around creates a slope ending at 100% at clip end, as opposed to e.g. the "Brightness Keyframes" where dragging that initial point keeps the level constant until end.

**Comment by leonerd** [comment]
Random guess, but it -might- have to do with the "end gain" property of the MLT "volume" filter. If Flowblade sets only the "gain" and not "end gain" then maybe it's linearly interpolated until that?

https://www.mltframework.org/plugins/FilterVolume/

**Comment by leonerd** [comment]
Or more likely the "range_out" setting here maybe?

https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/Flowblade/res/filters/filters.xml#L198

**Comment by jliljebl** [comment]
I will look at this before release.

**Comment by jliljebl** [comment]
>   * Start a new project. Insert some video media as a clip
>   * Add an "Audio" / "Volume" filter. Observe that the keyframe indicator already shows we're at 1/2.

No, this is the old one and this happened because it was created when MLT didn't have the "level" property available and we had to  

https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/Flowblade/res/filters/filters.xml#L198

> Random guess, but it -might- have to do with the "end gain" property of the MLT "volume" filter.

The new one can show 2/2 after creation because thee is always keyframe a frame 0 of clip media nd is clip begins at 

> Or more likely the "range_out" setting here maybe?

No "range_out" is related to slider values.
