### ISSUE TITLE
Strip text for name in titler layer

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#977]
Please include the following information.
1) Flowblade version (Help->About): 2.6.3
2) MLT version (Help->Runtime Environment): 6.22.1
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 20.10 (Pop!_OS)
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: The name of a titler layer is based on the text inside that layer. If the text starts with new lines, there is no name shown for that titler layer. Please strip any whitespace at the beginning of the text in a layer when using it to name the layer.

**Comment by jliljebl** [comment]
Confirmed, also the bounding box no longer contains the text if there are empty lines in the beginning of text. On the other hand I see no use case for starting text with empty lines. I'll do something about this sometime but it could take a while.

**Comment by PanderMusubi** [comment]
The use case would be to position relative to identical x and y coordinates of another title with some leading new lines in the text. Understand this is low priority.

**Comment by jliljebl** [comment]
Ok, I can fix the layer text for next release but the GUI thing can take
more time.

su 24. tammikuuta 2021 klo 17.47 Pander <notifications@github.com>
kirjoitti:

**Comment by jep-fa** [comment]
We can add these program lines in titler.py > Class TextLayerListView() 
in > def fill_data_model(), replace line 1346

>             #row_data = [self.layer_icon, layer.text, visible_icon]

with

>             text = self.find_char_in_text(layer.text)
>             row_data = [self.layer_icon, text, visible_icon]

add a new def in this class

>     def find_char_in_text(self, text):
>         while text.find(" ") == 0 or text.find("\n") == 0:
>             text = text[1:]
>         line_end =text.find("\n")
>         if  line_end != -1:
>             text = text[:line_end]
>         return text

**Comment by jliljebl** [comment]
@jep-fa Ok thnaks, I can hand patch this some time later, but if you do a pull request that would be great.

**Comment by jliljebl** [comment]
Patch by jep-fa fixes this.
