### ISSUE TITLE
2.8: Interface rendering freeze when switching workspaces

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#980]
Flowblade 2.6.1
MLT 6.18.0
GTK 3.24.23
Running on Fedora 33 (Flatpak version)

I haven't yet found a way to reliably reproduce this bug, and it might be flatpak specific, but since I've upgraded to 2.6.1 from 2.6.0 a new bug has appeared for me, which is that the interface stops rendering properly after switching to other windows (e.g. a browser), working in those for a bit, and then returning to Flowblade. The top bar GTK menus still open, and if I click around on the timeline the video window still changes what it displays, but the cursor itself disappears and all other interface elements stop rendering/updating (they become greyed out, though clicking on them still appears to affect the project like normal).

I've had this bug occur about four times now, and I will see if I can find a way to reliably reproduce it (and take a screenshot if so). I can also try updating GTK (I think there's a new version out for my system; I just haven't run dnf update in a while).

For now, just flagging here that this issue exists for my system. Thanks

**Comment by thennicke** [comment]
Here is an example screenshot from a project I am currently working on. In this case I replicated the bug by switching workspaces to a GIMP window, working on something for about a minute, and then switching back to the workspace that Flowblade was in. Everything looks normal except that a lot of stuff is greyed out, and clicking around the interface visually does nothing, although it still changes what is displayed in the monitor window.
![Screenshot from 2021-01-23 22-04-01](https://user-images.githubusercontent.com/25953969/105576475-1230df80-5dc7-11eb-856c-a0babfcfac78.png)

**Comment by jliljebl** [comment]
I'm just starting work on next release Flatpak and will be updating many parts of it. I'll try to reproduce this as I test the new one and if found try to find a solution.

**Comment by thennicke** [comment]
This issue has become even worse for 2.8. Simply switching workspaces is enough to reliably freeze the interface now. Would be interested to hear if you can reproduce.

Flowblade 2.8 Flatpak running on Fedora 33.
MLT 6.24.0
GTK 3.24.25

**Comment by jliljebl** [comment]
I did see this once but now that I tried to reproduce again I couldn't. I'll keep open for the time being.

**Comment by thennicke** [comment]
> I did see this once but now that I tried to reproduce again I couldn't. I'll keep open for the time being.

Thanks. I know there was a change in workspace design with the latest Gnome release, so I'll note here if it still happens for me when I get around to updating my OS.

**Comment by jliljebl** [comment]
I did some testing on this with Flatpak 2.10.0.4, and did not see this anymore. Before latest release Flatpak had some issues with some themes causing GUI becoming invisible. Those were fixed by using just our custom theme. Hopefully that has fixed this Issue too. Marking this as fixed, if problem keeps showing up then comment here, and I'll reopen.
