### ISSUE TITLE
rotate + position  scale

### ISSUE THREAD

**Issue by PixnWave** [jliljebl/flowblade#981]
Please include the following information.
1) Flowblade version (Help->About): 2.6.1
2) MLT version (Help->Runtime Environment): 6.18.0
3) Your distribution (Ubuntu, Debian, Mint etc.): 18.04.05 LTS
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Good evening,
Congratulations for this wonderful software
I'm embarrassed, I can't scale the video to be in full screen after rendering.
I tried several scales without success ... 

![Capture d’écran de 2021-01-23 22-13-28](https://user-images.githubusercontent.com/27885587/105614342-0d6d2b00-5dc9-11eb-8a50-c1fd5efc1f49.png)

**Comment by jliljebl** [comment]
Not clear on the problem here. Seems that material contains some black bars, I would suggest maybe trying to stretch the edit box in the editor to make the image part bigger.

Anyway, this is not an actionable Issue so I'm closing this.
