### ISSUE TITLE
Rendering does not always respect threads setting

### ISSUE THREAD

**Issue by louispotok** [jliljebl/flowblade#983]
This morning I rendered a video using multiple threads, and it worked fine.

This evening, working on a different project, I tried rendering with multiple threads but never got a CPU usage over about 13% (of one core). When I clicked on "render using args", I did not see `threads` in the args. 

To work around this, I was able to successfully:
* export the project to MLT XML
* copy the args from the "render args" box and add `threads=5`
* run the following command: `melt  -consumer avformat:output.mp4 f=mp4 s=1920x1080 threads=5 {more render args} mlt_file.xml`

So it seems that flowblade is just not passing on the threads argument? But I'm pretty sure it was using multiple threads this morning. Wish I could provide more details on how to reproduce.

Please include the following information.
1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 20.04.1
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

**Comment by jliljebl** [comment]
Thanks for the report. I have some other data points on there being differences with Flowblade/melt rendering and will be looking at this thoroughly during next development cycle. I'm merging this with Render Issues.
