### ISSUE TITLE
A French user manual for Flowblade

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#985]
Flowblade 2.6.1
I wrote this manual for the french users.

[FLOWBLADE_manuel_V2102.2.pdf](https://github.com/jliljebl/flowblade/files/5932229/FLOWBLADE_manuel_V2102.2.pdf)

Unfortunately, I am not competent enough to translate it into English.

**Comment by jliljebl** [comment]
Holy hell, that's a large body of work there with images, icons and what have you, looks great. 

This is a much more through guide then the one that is made available by the project. Having done these myself I know that this has required a lot of work.

I'll upload it and add links to it webpage and application for 2.6. Ill run it through machine translation some in next cycle and see if I can turn this into English guide.

Again, thanks for the contribution. I was mostly off the project last week, but I'll upload it here now.

**Comment by jliljebl** [comment]
French language manual is now linked from application help docs with text "Manuel en français" which is hopefully correct in French, comment here if you want to change link text.

**Comment by jliljebl** [comment]
Both the application and web pages now link to this. Thank you, closing.
