### ISSUE TITLE
flowblade won't start in portrait mode

### ISSUE THREAD

**Issue by butrus** [jliljebl/flowblade#988]
Trying to start flowblade I get the following dialog:

"Too small screen for this application. Minimum screen dimensions fot ist application are 1152x768. Your screen dimensions are 1080x1920".

This is ridiculous. I would expect flowblade to start (and possibly rearrange the elements to fit the portrait mode).

But anyway, I don't see actually any reason why an application would limit display resolution it runs on. (On small displays, the user can enlarge the window above the screen resultion which would alow him to work around this problem. If the application refuses to start, the user cannot do anything. This is just stupid.)

Flowblade 2.6-2 / debian/devuan.

**Comment by jliljebl** [comment]
Explaining why this is going *wontfix* will be left as an exercise for the reader.
