### ISSUE TITLE
wrong/removed extension causes freezing

### ISSUE THREAD

**Issue by 4ov** [jliljebl/flowblade#989]
Please include the following information.
1) Flowblade version: 2.8
2) MLT version: 6.24.0
3) Your distribution: debian
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: 
1. turn image.png to image
2. try to load image
3. Flowblade stop responding.

**Comment by jliljebl** [comment]
> 1. turn image.png to image

My first suggestion is to not do this, garbage-in-garbage-out.

However, program crashing is always bad, so I'll look for some way to make app handle this more graciously.

**Comment by dotba** [comment]
Actually it happened in accident, i was renaming an image and the extension removed. 
I think a warning message of an unrecognized mimetype can save it from crashing.

**Comment by jliljebl** [comment]
> I think a warning message of an unrecognized mimetype can save it from crashing.

Yes, and refuse to load anything as media if it has no recognizable extension.

**Comment by jliljebl** [comment]
Fixed, we now no longer load media with missing/unrecognized extensions.
