### ISSUE TITLE
The developpement version doesn't work

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#990]
1) Flowblade version 2.8 from git clone https://github.com/jliljebl/flowblade.git
2) _mlt.so and mlt.py added

An error in editorlayout.py ?

Launch and trace

FLOWBLADE MOVIE EDITOR 2.8
--------------------------
Launch script dir: /home/jpf/flb_git/flowblade/flowblade-trunk
Running from filesystem...
MLT found, version: 6.21.0
numpy version: 1.17.4
Application version: 2.8.0
OS: Ubuntu 20.04.2 LTS
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
GTK+ version: 3.24.20
XDG user data exists.
Locale: fr_FR
Found translations at /home/jpf/flb_git/flowblade/flowblade-trunk/Flowblade/locale/, using those.
Force use  fr
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Gtk version is 3.24.20, Flowblade theme is available.
Using Full Screen size for layout: 1920 x 1080
Small height: False
Small width: False
no more csLADSPA plugins
Detecting environment...
.......
MLT detection succeeded, 173 formats, 106 video codecs and 79 audio codecs found.
883 MLT services found.
Loading render profiles...
Loading filters...
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Player initialized with profile:  HD 1080p 25 fps
Traceback (most recent call last):
  File "/home/jpf/flb_git/flowblade/flowblade-trunk/flowblade", line 93, in <module>
    app.main(modules_path)
  File "/home/jpf/flb_git/flowblade/flowblade-trunk/Flowblade/app.py", line 308, in main
    create_gui()
  File "/home/jpf/flb_git/flowblade/flowblade-trunk/Flowblade/app.py", line 488, in create_gui
    editor_window = editorwindow.EditorWindow()
  File "/home/jpf/flb_git/flowblade/flowblade-trunk/Flowblade/editorwindow.py", line 157, in __init__
    self._init_panels_and_frames()
  File "/home/jpf/flb_git/flowblade/flowblade-trunk/Flowblade/editorwindow.py", line 643, in _init_panels_and_frames
    top_project_panel, widget_is_notebook = editorlayout.create_position_widget(self, \
  File "/home/jpf/flb_git/flowblade/flowblade-trunk/Flowblade/editorlayout.py", line 328, in create_position_widget
    notebook = _create_notebook(position, editor_window)
  File "/home/jpf/flb_git/flowblade/flowblade-trunk/Flowblade/editorlayout.py", line 343, in _create_notebook
    tabs_pos = tabs_positions[position]
KeyError: 5

**Comment by jliljebl** [comment]
Ok, I'll look at this this week.

**Comment by jliljebl** [comment]
I just noticed "_mlt.so and mlt.py added". Where is this, it is not on master as I see it now? If you have these it tries to run them.

**Comment by jep-fa** [comment]
When you are in development version, you have to Set up bindings

    Copy mlt.py and _mlt.so from <ROOT_DIR>/mlt/src/swig/python into ../flowblade-trunk where your repository version Flowblade is installed.

as said in 

https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/creating_user_folder_bindings.md

**Comment by jliljebl** [comment]
I did **git log --full-history -- flowblade-trunk/mlt.py**
and got:
```bash
commit 6c6de44d41f5599e745fefa2817a35ffece9e67d
Author: Janne Liljeblad <janne.liljeblad@gmail.com>
Date:   Mon Sep 14 02:55:59 2015 +0300

    Remove mlt.py from repository

commit 3660eda56de6c931e3ffc35320ed3488059fdf29
Author: Janne Liljeblad <janne.liljeblad@gmail.com>
Date:   Sat Aug 22 21:35:45 2015 +0300
```

**git log --full-history -- flowblade-trunk/_mlt.so** gives nothing so these are not in repository now.

also **.gitignore** has
```bash
mlt.py

# C extensions
*.so
```

so *_mlt.so and mlt.py added* does not seem to be true.

**Comment by jliljebl** [comment]
> When you are in development version, you have to Set up bindings

Ok, you are running self build bindings currently, I thought these had somehow slipped in repository, has happened before.

**Comment by jliljebl** [comment]
> File "/home/jpf/flb_git/flowblade/flowblade-trunk/Flowblade/editorlayout.py", line 343, in _create_notebook
tabs_pos = tabs_positions[position]
KeyError: 5

Key 5 is *appconsts.PANEL_PLACEMENT_TOP_ROW_PROJECT_DEFAULT* lets see if I can get this to show up some how.

**Comment by jliljebl** [comment]
Got it. if appconsts.PANEL_PLACEMENT_TOP_ROW_PROJECT_DEFAULT has two panels it breaks now, does not correctly create a notebook because it has no default value. This one I certainly tested and it worked, maybe same data had already gone in my *prefs* during deveopment so missing default value didn't crash.

**Comment by jliljebl** [comment]
This has to be same sequence of data updates on disk so that when I tested it didn't crash. I'll push updates tomorrow.

**Comment by jliljebl** [comment]
Flatpak and .deb releases updated, thanks for the report.
