### ISSUE TITLE
2.8: Panel placement is buggy

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#991]
Flowblade version 2.8 (flatpak)
MLT version 6.24.0
GTK 3.24.25
Fedora 33

Filter Select Panel is now by default in bottom right. I don't like this change because it reduces the amount of visible side space for my timeline. So I tried to undo it through the panel placement menu by changing it to Top Row Project Panel Default. This simply removed the Project Panel from the screen as well. I then tried to change the Project Panel position to the option labelled Top Row Default Notebook, and this caused flowblade to crash. I am unable to find a way to get the filter select panel back to where it used to be in 2.6 without crashing the program. Any help would be greatly appreciated.

![Screenshot from 2021-02-18 20-06-24_ed](https://user-images.githubusercontent.com/25953969/108336383-15818480-7228-11eb-84e0-9d3f4d73e560.png)

**Comment by jliljebl** [comment]
This is Issue #990, fixed this morning. Install 2.8.0.2 from .deb or
Flatpak.

to 18. helmikuuta 2021 klo 11.31 thennicke <notifications@github.com>
kirjoitti:

**Comment by thennicke** [comment]
> This is Issue #990, fixed this morning. Install 2.8.0.2 from .deb or Flatpak.

Thanks. That version doesn't yet appear to be available when I "sudo flatpak update". I will check again in a few hours.

**Comment by thennicke** [comment]
Confirming that the new update has fixed the bugs. However it seems that it is still not possible to return the panel to where it was in the 2.6 release, which is annoying since I liked it as it was. I will adapt my workflow though.

**Comment by jliljebl** [comment]
This should be fixed now.
