### ISSUE TITLE
Sound is delayed by several frames

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#993]
Version 2.8 development
MLT 6.21.0
Ubuntu studio 20.04

When I read a sequence, the sound is staggered by about three or four frames.
I tested with three different medias (.mts, .mov, .mov) from three different devices. 
The project profile matches 

- the number of frames per second (25 or 23.98)
- the audio sampling rate (48 000 kHz)

of the medias.

Does anyone have the same problem?

**Comment by jliljebl** [comment]
At least on visual inspection I do not see this. I can try to think of more structured approach on detecting this.

We'll keep this open for the time being for more info.

**Comment by jep-fa** [comment]
You put a single clip on the timeline. Put the playback head two seconds before the start of the clip. Playback: The sound starts to sound when the playback head is at three or four frames after the start of the clip. 
It is also visible on the lips of a talking person.

**Comment by jliljebl** [comment]
I think the underlying issue  here is the Linux PulseAudio sound system which is known to have latencies of sometimes up to few tens of milliseconds. Latencies also vary from system to system. MLT does support JACK audio and we will need to look that again once we have the video playback updated.

**Comment by jep-fa** [comment]
Ok, it's personal despite the low latency kernel of Ubuntu Studio. You can close this issue.

**Comment by jliljebl** [comment]
This issue is something that can be improved on to make the application better but there is no immediate path make patches.
