### ISSUE TITLE
 flowblade : Depends: python3-mlt but it is not installable

### ISSUE THREAD

**Issue by freddieventura** [jliljebl/flowblade#997]
Please include the following information.
1) Flowblade version (Help->About):
2) MLT version (Help->Runtime Environment):
3) Your distribution (Ubuntu, Debian, Mint etc.):
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Debian Buster 64 Bits.

I cannot install the binaries cause of neededing this python3-mlt , but that is not available on my repos in Debian (at least the estable ones)
I have been seen your guides and they are quite complicated to follow in order to install a program.

If you update to a certain usage of libraries make sure than the regular user of Linux (which is not an average user to be honest) is able to at least install your program, otherwise we have tons of programs out there to do the same functionality.

I'm sorry but I wanted to try your program but I'm not going to spend an hour figuring out how.

Thanks for the resource anyways!!

**Comment by jliljebl** [comment]
For Debian Buster seems it is *python-mlt* not  *python3-mlt*.

You also can try installing from using *Flatpak* from *Flathub.*

There will be more info on creating dev environment for Flowblade later this cycle, if I remember I'll comment when that stuff gets updated.

**Comment by ovizii** [comment]
ell, I tried following your installation instructions but I also get: 

The following packages have unmet dependencies:
 flowblade : Depends: python3-mlt but it is not install-able
E: Unable to correct problems, you have held broken packages.


So are there any instructions for Debian Buster users? 
Even if I manually install python-mlt flowblade will still search for python3-mlt as far as I can see so any pointers?
