### ISSUE TITLE
G'MIC Rendering/Preview seems to do nothing

### ISSUE THREAD

**Issue by DroWnThePoor** [jliljebl/flowblade#998]
Please include the following information.
1) Flowblade version (Help->About): Flowblade 2.8 Flatpak
2) MLT version (Help->Runtime Environment): MLT 6.24.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 18.04
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

G'MIC tool doesn't render for Preview or to file.
This hasn't worked for me in a long time, but did at one point a while back.
I choose a small range from a video clip, select an effect(have tried many), and simply try to preview or to render.

Preview text comes up saying Rendering preview... and never changes. With no sort of process running.

Actual render makes it through "Writing clip frames", but stops on "Rendering frame 1/30" with nothing happening.

Perhaps this is because I'm using Flatpak, but I'm not sure.
I have package gmic installed via apt, but perhaps I need something else?

**Comment by jliljebl** [comment]
I'm having few weeks of break from the project but I'll post request for testing a fix here once I have a fix for this.

**Comment by jliljebl** [comment]
This issue only affected Flatpak and has been fixed new version 2.8.0.3 that was pushed into Flathub yesterday. Update manually if application does not automatically update. Thanks for the report.

**Comment by DroWnThePoor** [comment]
Thank you for taking the time to look into it.
Will this fix be available in an update to Flatpak soon?
Or is there a way I can apply it before then?
I'm not completely familiar with the commit process, but if you point me in the right direction I can probably figure it out.
