### ISSUE TITLE
Delete key does not work when caps lock is on

### ISSUE THREAD

**Issue by neltnerb** [jliljebl/flowblade#999]
Please include the following information.
1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 20.04
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

Select a clip in the editor. Click delete without the caps lock on.

Expected behavior: delete clip
Actual behavior: delete clip

Select a clip in the editor. Click delete with the caps lock on.

Expected behavior: delete clip
Actual behavior: ignored keypress

Not sure if it's a gnome/ubuntu thing or a flowblade thing but other applications do not have the same behavior so I am fairly sure there is not just some funny mapping issue with my keyboard. If you can't reproduce this trivially I wouldn't bother, I can work around it on my computer now that I know it's due to the caps lock.

**Comment by neltnerb** [comment]
Also, right click, edit -> delete works with caps lock on, it's just the keyboard delete key that does not do anything with caps lock on.

**Comment by jliljebl** [comment]
Ok, I will need to decide if this is the kind of Issue that requires a fix, *key* and *modifier+key* are different actions so it could be argued they should not produce same outcome. I'll decide one way or another before next release.

**Comment by jliljebl** [comment]
Yeah, with the way our codebase is handling keyboard shortcuts, and the fact that we have two shortcuts with delete:

*Delete - Splice Out*

*Delete + Control - Lift*

it is unfortunately quite difficult to offer a fix for this, and I'm closing this as *wontfix*.
